### ISSUE TITLE
Variant details - nearby classifications

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#10]
On Variant Details page we should show:

* variants on the same codon.
* same exon or +/- X AA away
* Same protein domain

-------------

Very useful for ACMG classifications involving hotspots etc.

We show classifications/clinvar on the variant - but we should also show for the same codon. ACMG has PM5 for this:

PM5 Novel missense change at an amino acid residue where a different missense change determined to be
pathogenic has been seen before
Example: Arg156His is pathogenic; now you observe Arg156Cys
Caveat: Beware of changes that impact splicing rather than at the amino acid/protein level.

Make it easy for med scientists to see - so on grid, and in variant details page. AGHA also want a search for this.

------------------------

Summarise ClinVar, Classifications

```
q_or = []
for t, e in v.varianttranscriptannotation_set.all().values_list("transcript_id", "exon"):
    q_or.append(Q(varianttranscriptannotation__transcript_id=t, varianttranscriptannotation__exon=e))
q = reduce(operator.or_, q_or)
qs = Variant.objects.filter(q)
qs.filter(clinvar__highest_pathogenicity__gte=4)
```

Then run the node count aggregates on it, to get a sum of clinvar and classified variants.

Have a section that shows variants at this locus, at this exon, at this domain etc etc

**Comment by davmlaw** [comment]
Still TODO:

* get detailsLink formatter to work on nearby variants page (doesn't even seem to be called??)
* Show James/Emma and ask about whether they want it on search results
* Proper classification grid??

**Comment by davmlaw** [comment]
@sksmi - deployed to test http://144.6.229.160 - please test away.

I've been wanting to do this for ages, and knocked out a quick draft while procrastinating other stuff. If it's broken or minor fix, let me know otherwise please put all ideas in a new issue "nearby variants v2" :)
  
New features are:

* Variant details has "Nearby" section
* Link to new page to view grids of nearby variants
* Search now shows a summary of Variants (eg search for "5:90445826")

+/- 50 was arbitrarily chosen.

Ideally, I'd like some of this info to auto-populate into classifications but am not sure how/what etc - thoughts in new issue?

**Comment by sksmi** [comment]
Very cool to be able to see variants in the same codon & really excited for nearby variants! Love this from a classification automation POV, but not sure how to use it as a curator as I struggle to interpret tables quickly and really rely on visualisation to run interpretations.  Usually I use UCSC and/or gnomAD to explore the locus. I'll often zoom in/out depending on the protein type & features (very difficult to summarise as I'll use tonnes of different data to decide on which region I should examine, but usually I'd like to start with +/- 50 then work from there) e.g.:

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/c60c696a-5e7b-460d-b982-0a0e783a8d2e)

A couple of suggestions for current iteration:
- Maybe focus only on the codon at this time, not sure we're ready for domain, exon summaries yet as don't really know how to interpret them.
- I'd probably keep it all on the variant page e.g. move the nearby variant grid to the nearby variants box as a 'show variants in codon' link with a little bit of text about what is shown in the grid (particularly for indels - e.g. are they shown if they overlap the region etc.).
- What is current intent of the nearby grid on http://144.6.229.160/variantopedia/nearby/242866580 & the counts summary in the nearby box? To show/summarise all nearby variants in codon, domain and exon? Bit confused as it's sitting under the codon header & the 23 variants correlate to the summary text next to codon on the variant page.
- I'm not sure that the codon ClinVa & DB counts are useful as lots of context is required to interpret. I'd probably take out the summary text and just leave the grid with links to ClinVar, internal db & gnomad pages.

In the long-term my personal pref would be to load the hotspot graph zoomed to +/- 50 around the locus with ClinVar, COSMIC, internal db & gnomAD counts (displayed similar to the gnomAD graph). Wondering if an interim solution would be to load VG data as a track into UCSC as that pretty much does the job at the moment.

**Comment by davmlaw** [comment]
Moved comments into new issues:

#117 View variants as a track in IGV or UCSC
#118 Nearby variants v2

>>  What is current intent of the nearby grid on http://144.6.229.160/variantopedia/nearby/242866580

This is a bug - because introns are labelled relative to the nearest codon - I will make a fix to not look for codons/exons/domains etc when in an intron

>> I'm not sure that the codon ClinVa & DB counts are useful as lots of context is required to interpret

I think it's important to know how many and what type of ClinVar classification are aound, and whether anyone in our database has them. The purpose is not to be able to do everything w/o interpretation, but to alert people to check something out... I'll add some help.

**Comment by davmlaw** [comment]
Now codon needs to be in exon

**Comment by sksmi** [comment]
Haven't tested coordinates yet, but they look ok at first glance. 
Two minor issues:
1) table currently includes variants with 0 het/hom counts, will you filter these out in the end (bit hard in test as not enough data)?

2) regions includes ref. 
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/c670a62f-b419-4414-9618-0fc4e3c8b4ad)

Draft test case for full QC: https://app.qase.io/case/VG/edit/70

**Comment by sksmi** [comment]
Few more ...

http://144.6.229.160/variantopedia/nearby/241616711
- codon coordinates incorrect
- range not displayed
- might be worth adding text to say that domain is only exonic variants (think that's right?)
- should the variant itself be included?

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/c60d2afc-2f36-4956-9523-87048a45ad12)


http://144.6.229.160/variantopedia/view_variant/241616741
- no variants showing in region, should be quite a few:

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/28216e40-25b9-45b2-acc1-6b459b648a4a)

**Comment by davmlaw** [comment]
>> codon coordinates incorrect

Ah yep whoops was using regex without proper termination

>> range not displayed

Whoops fixed +/- error

>> table currently includes variants with 0 het/hom counts

If we remove those, we also remove ClinVar classifications

>> domain is only exonic variants

I thought it was pretty common in molecular biology to use domain for "protein domain" - I've only ever called it domain everywhere else.

>> should the variant itself be included?

I don't think so, as it's "nearby"variants, and that info is available on variant page


TODO: Still need to fix codon regex issue and checkin

**Comment by sksmi** [comment]
PASS: GRCh37 - variant counts in nearby variants grid match counts on variant page. 
FAIL: GRCH38 - variant counts lower in nearby variants grid than on variant page. Region grid not displaying. e.g.  CA410147564

**Comment by sksmi** [comment]
Getting inconsistent results when loading the page, sometimes the grid displays, sometimes it doesn't. e.g. couldn't reproduce above then it re-appeared.  Guessing it's associated with:
 #2548 IndexError: string index out of range

**Comment by sksmi** [comment]
Future dev: 

- is it possible to show genomic coordinates for each interval? Makes it much easier to see what's being displayed 

e.g. trying to work out what's being assessed for the codon interval for this variant: 16:30764715 G>A
codon coords are: 16; 30764617, 30764618... intron ...30764715
codon variants displayed on nearby variants page include intronic variants.


- need to add text to indicate that if interval for codon or domain spans an intron, intronic variants are included in table. Alternatively could consider removing these variants although would argue that it's not important enough to prioritise, would suggest working in the interactive hotspot graph as more important than fixing grids).

http://frgeneseq02.imvs.sa.gov.au:92/variantopedia/nearby/2754267/14
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/f550515e-8b3b-4c5d-88cc-4db4b48040ae)

**Comment by davmlaw** [comment]
Yep I can add the coordinates

For the "index" out of range stuff - will fix that but if you only test GRch38 data that shouldn't happen, I think that only happens on old GRch37 data

**Comment by davmlaw** [comment]
>> need to add text to indicate that if interval for codon or domain spans an intron, intronic variants are included in table. Alternatively could consider removing these variants

I've added a page help to hopefully explain what's going on

**Comment by sksmi** [comment]
That's so fantastic. The help is great!
Happy to close and leave the rest for V2 if the index out of range is covered elsewhere.

**Comment by davmlaw** [comment]
Cool, the graphs will come... after the paper is done, we'll import MANE then have good transcripts for the hotspot graphs
