### ISSUE TITLE
Have visible deployment history

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#100]
The version page just says what git version is being currently run and the time that change was made to source control.

It does not track when it was deployed to the environment, or any details about the changes.

Have a management tool to record deployments (invoked by the upgrade tool).
Have commands possible of storing release notes (only alternative would be to grab commit comments out of github. Generally messier to read and parse, but doesn't require an extra level of storage.
( Could use git ancestory path git rev-list --ancestry-path 7b4a07a..ecf5891 , with the hashes being what was just deployed and what was deployed previously )

**Comment by EmmaTudini** [comment]
Testing:
- Logged into Shariant test as non-admin
- Git Hash
60523306b32b5f99e160e5f50e8f8aa22eb8466e
- Went to URL: https://test.shariant.org.au/version

Expected output: Link to branch upgraded with the release - link goes to github. View deployment history in table with dates and link to comparison of most current with historical version.

Actual output: Passed

**Comment by EmmaTudini** [comment]
Note: When logged in as admin, "Users with Weekly Update Emails Enabled" is also shown. Is this intended?

**Comment by TheMadBug** [comment]
I meant to put more comments in this issue (looks like I just put my general thoughts in and moved it to ready for testing), the listing of users with weekly emails enabled was done as part of this task, so admins can optionally alert users of new features.

**Comment by TheMadBug** [comment]
For a full list of features of the version page:

In addition to the old behaviour that showed you:
* The git modification date
* The git hash

Now shows you:
* The git branch
* The dates and hashes of the last 10 deployments, with links to GitHub to show you commit comments of what's changed between that version and the currently deployed version
* (For admins only) a list of users who have agreed to weekly emails, they can be manually emailed together or individually. This would allow us to notify prime users of an environment of changes.
