### ISSUE TITLE
view allele page - show errors?

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1003]
[This Allele](http://test.variantgrid.com/variantopedia/view_allele/172) - NC_000017.11:g.6398242_6408077dup - doesn't have ClinGenAllele

If you're admin, and you click 

This is because we didn't send it as it was too long. There's nothing about this on the Allele page - we should have some kind of a note about that.

If you do send it, [you get](https://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/allele?hgvsOrDescriptor=NC_000017.11%3Ag.6398242_6408077dup):

```
Type of the error: VariationTooLong

Explanation: VariationTooLong 
```

So it was the right thing to not send it, just need a  message about missing allele (as no error)

**Comment by davmlaw** [comment]
I just added a little error message here, so it's more obvious to check the liftover log

This is only visible as admin

**Comment by GracePendlebury** [comment]
Testing

Logged in as:
Grace.Pendlebury@qimrberghofer.edu.au (admin) & g.pendlebury1@outlook.com (non-admin)

Checked:
a28948 https://test.shariant.org.au/variantopedia/view_allele/28948
Admin:
<img width="1060" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejlqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0eabeb79c56d5801a54d6a53afd46248f1c8df3/image.png" alt="image.png" />

 vs non-admin:
<img width="1170" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEpqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba5c07983f14f26ae1f0a159f066546c4bcd6097/image.png" alt="image.png" />

Expected outcome:
Warning stating variant is too long to send to ClinGen for an CA ID will appear on allele page, and only for admin.

Actual outcome:
Passed
