### ISSUE TITLE
pyhgvs environments warn about nucleotide change from non-explicit to explicit

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#1012]
Given the input of NM_004343.3(CALR):c.1092_1143del52 in a pyhgvs environment, a warning message that the provided reference is all Ns and we had to substitute our own.

Testing this on variantgrid.com that's using biocommons does not suffer from this issue.

It is intended that all environments switch to biocommons for variant resolution so this should not be given much (if any) work, and has been created just as a record.

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUlaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88d271250367bc3802650b2f79d7e338930611ad/image.png" alt="image.png" />

**Comment by davmlaw** [comment]
This is now obsolete after having switched from PyHGVS to BioCommons HGVS
