### ISSUE TITLE
Add MONDO to free text phenotype matching

### ISSUE THREAD

**Issue by EmmaTudini** [SACGF/variantgrid#102]
@EmmaTudini commented on [Tue Oct 27 2020](https://github.com/SACGF/variantgrid_private/issues/2935)

MONDO is preferred by ClinGen for expert panels so would be good to add it to the free phenotype text matching (currently matches to OMIM and HPO). 

See below for licence:

You are free to:
Share — copy and redistribute the material in any medium or format
Adapt — remix, transform, and build upon the material
for any purpose, even commercially.
The licensor cannot revoke these freedoms as long as you follow the license terms.

Under the following terms:
Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

So when implemented, we will need to make sure that we provide a link to the license - https://creativecommons.org/licenses/by/3.0/ and give credit to MONDO

---

@sksmi commented on [Tue Oct 27 2020](https://github.com/SACGF/variantgrid_private/issues/2935#issuecomment-716871505)

Up vote from me.

**Comment by davmlaw** [comment]
See ```annotation.MonarchDiseaseOntology``` - we load the owl, but only use it for being able to store ClinGen disease validity.

Ideally, we'd store all of it, and link to HPO/OMIM then introduce it into phenotype matching

Phenotype matching could probably be sped up quite a lot by serializing it into gzipped JSON or something in a temporary file, it currently takes quite a while to read it from the DB and build the structures (hence the delay when trying to real time match)

**Comment by TheMadBug** [comment]
At some point if we add more features to this, might be time to break it out into its own service - plenty of fuzzy text matches out there. (though I'm not 100% convinced general English fuzziness is the problem when it comes to matching free text against these kinds of scentific terms).

Does mean that the service we end on setting up would send IDs back to the caller, and it would be up to the caller to already have those IDs in the db.

**Comment by davmlaw** [comment]
Well, I think it should be in the DB as it's best to store it in a structured way (eg you can only ever store it against ids that are there)

**Comment by TheMadBug** [comment]
Fuzzy searches (such as those built of Lucene like Solr or ElasticSearch) often make their own querable copy of data - like a metadata version of the data.
If we went down that route we'd feed it all the data from the database, and then it would give us back the ids. This is a common paradigm where you'd have an independant search database with a soft link to your real database.

**Comment by sksmi** [comment]
Haven't read details, but posting these tools as possibly relevant to discussion: 

https://github.com/dbmi-pitt/nobletools (Noble coder ICD-10 & free text to HPO ?MONDO)
https://gddp.research.cchmc.org/
https://github.com/WGLab/EHR-Phenolyzer
https://github.com/WGLab/Phen2Gene2

**Comment by sksmi** [comment]
https://www.kidney-international.org/article/S0085-2538(20)30012-0/fulltext

**Comment by TheMadBug** [comment]
As far as resolving existing condition text to MONDO terms, that's handled elsewhere now.
@davmlaw handing this issue over to you in case you want to update the patient phenotype page to include mondo terms.

(Though if you're going to restructure or rename the MONDO db tables e.g. to be Mondo rather than MonarchOntology etc give me a heads up so I can merge code sooner rather than later).

**Comment by davmlaw** [comment]
I'm not planning on doing that any time soon, but feel free to do it yourself - its annoying

**Comment by davmlaw** [comment]
We've rolled all Ontology into a single database structure now so this should be quite a lot easier to do

**Comment by davmlaw** [comment]
I also made gene_symbol go through HGNC so now we only match ontology which simplifies things a bit

* Added MONDO to phenotype node
* Added MONDO to patients phenotype

**Comment by davmlaw** [comment]
Few issues:

* Needs an autocomplete on patients page
* We should probably re-match patients on MONDO, as they're currently cached to not have it - so that if anyone has them they can be used for MOI node

**Comment by davmlaw** [comment]
tested on vg test
