### ISSUE TITLE
Somatic variant links

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#105]
Wendy asks:

Do you think it is possible to add (variant-specific?) links to cancer dbs other than cosmic such as the following (and maybe others):????

https://ckb.jax.org/
https://pmkb.weill.cornell.edu/
https://civicdb.org/home

**Comment by sksmi** [comment]
SKS Apr 2020: This is probably a better source as it pulls in all of the above: https://search.cancervariants.org/#RUNX1

Variant search example: BRAF V600E gives
https://search.cancervariants.org/#BRAF%20V600E
so think it would be more reliable to search via gene.

PMID: 32246132

@TheMadBug - possibly for addition to classification page?

**Comment by sksmi** [comment]
JA Jun 2020: So to summarise
https://search.cancervariants.org/#(gene symbol)
as an additional quick link
and only relevant if somatic or likely somatic?

**Comment by sksmi** [comment]
SKS Jun 2020: Sounds good, although relevant for both somatic & germline.

**Comment by sksmi** [comment]
Transferred from VG issue 2130.

**Comment by TheMadBug** [comment]
For the new QuickLinks, can you provide a list of how you expect the URLs to look for in search.
Does it make more sense to attempt to look at the variant, or would we just be searching on gene symbol?

**Comment by davmlaw** [comment]
@TheMadBug are you able to do this before Monday?

**Comment by TheMadBug** [comment]
Per conversation with @sksmi the links that were added in the end were
cBioPortal (warning: takes sometime to load), and
OncoKB

Links are still listed out in alphabetical order. We might want to think about making them by gene vs variant or by use case etc. Still if you work out where your favourite link is, it's easy to find again.

@davmlaw also sorry, only just comitted this to master now, assuming there'll be at least one patch deploy :/

**Comment by davmlaw** [comment]
>> assuming there'll be at least one patch deploy :/

This has been deployed to VG test now

Yes SA Path test hasn't been updated

It's likely if Karin agrees about gnomAD GRCh38 the release candidate will be late this week / next monday

**Comment by sksmi** [comment]
@TheMadBug tested on a couple of classifications, works well  (given the cbioportal speed limitations). Link order prob isn't too important- you get used to it pretty quickly, more difficult when it changes. So in the end, was it too much to put in the original 3 as well (guessing space is an issue)? 
https://ckb.jax.org/
https://pmkb.weill.cornell.edu/
https://civicdb.org/home

Anna was pretty keen to get those in as well if possible (but can reach via cbioportal if needed).

**Comment by TheMadBug** [comment]
Re those other links, I just needed some sample URLs from them so I know if you're after the gene level or variant level etc.
Prefer an even number of links but could survive with odd.

Think this will trigger an eventual re-work of how the side boxes work for the sake of people who don't have 4k screens like me. Something I've been trying to kick down the road as long as possible.

**Comment by sksmi** [comment]
Nb public data from CKB seems to be pretty limited. Requested by curators, but not sure how much it's used - so if something can't fit that would be the one to drop. 

CKB
https://ckb.jax.org/gene/show?geneId=861&tabType=GENE_VARIANTS

PMKB
Ideally: https://pmkb.weill.cornell.edu/variants/2451
More realistic? https://pmkb.weill.cornell.edu/search?utf8=%E2%9C%93&search=FLT3

CIVIC
https://civicdb.org/events/genes/43/summary/variants/155/summary#variant
https://docs.civicdb.org/en/latest/api.html

**Comment by sksmi** [comment]
@TheMadBug any chance you'd be able to take a look at this one?

**Comment by TheMadBug** [comment]
@sksmi sadly the only one of these that can be done with a quick link is the PMKB one, as the other two require a search/API call to obtain the CKB and CIVIC internal ids for genes or variants. Quick links can only handle substiution of values that are already part of the classification form.

The number and complexity of the links is exceeding what can happily just go on the side of the classification form.
We may want to think of a different approach, maybe a new window that acts like Genomizer, but obviously that's a bit more effort than adding another link.

**Comment by sksmi** [comment]
Thanks, think we can leave other links at this stage. Can re-visit in future if there's additional requests.
