### ISSUE TITLE
Search for allele

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1050]
Similar to our "v42" shortcut to jump to variant 42, introduce a42 to jump to allele 42

**Comment by TheMadBug** [comment]
I wouldn't mind changing this to a 2 letter prefix and underscore like we're slowing making standard across ClinVarExport (CE_XXX), Discordance Report (DR_XXX)

Considering vXXXX already existed, supporting aXXXX makes sense for now

<img width="1459" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66eb183076eb38a692aacd8f0defc86db01b10b5/CleanShot%202024-05-28%20at%2013.53.25%402x.jpg" alt="CleanShot 2024-05-28 at 13.53.25@2x.jpg" />

**Comment by davmlaw** [comment]
> 2 letter prefix and underscore

AL_ for Allele?

So the signal can call it, it can call it Al

**Comment by TheMadBug** [comment]
🥁 🎷

**Comment by GracePendlebury** [comment]
**Testing**

Logged in as:
Grace.Pendlebury@qimrberghofer.edu.au (admin) & g.pendlebury1@outlook.com (non-admin)

Performed:
Used allele number from a somatic only allele, germline only allele & combination allele, prefixed with “a”.

Expected outcome:
Both versions will work, across all allele.

Actual outcome:
Passed
I agree that AL_XXXXX would be nice long term for consistency, but doesn't appear anywhere I can recall in that format so very low priority. Also extra points for the jokes, made me chuckle.
