### ISSUE TITLE
GeneGrid - delete unmatched symbol

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#106]
DL Jul 2019: Enter gibberish eg "FDAFDAFAD" as a gene name.

It shows as "Could not match gene symbol". However there is no way to delete this from a gene list

We need to display a copy of the bad gene name in lists so the delete can appear etc.

**Comment by sksmi** [comment]
Transferred from VG issue 1797.

**Comment by sksmi** [comment]
First round testing - looks ok.  Formal testing in progress.

@davmlaw gene that (I assume) were unmatched when the gene list was created, but have since been matched with the upgrade are still highlighted (eg below) - not sure if this is good or bad, raising for discussion:
pro = shows that matching has changed, con = confusing, because the 'could not match gene symbol text' is no longer used, so users need to realise that gene IDs mean it has actually been matched despite the pink

Potential solutions: remove highlighting from matched genes, differentiate new match vs unmatched (e.g. use a different colour highlighting or bring back the 'could not match text').  

Very minor, no need to change if difficult - can be dealt with in training.

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/309d7890-682e-4a2a-b2f4-1e29261bdd06)

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/ba4f20ae-4b21-4090-810c-82fc9861591d)

**Comment by davmlaw** [comment]
Wasn't due to GeneGrid, but rather in the GeneList - gene symbol wasn't matched at the time but could be matched later.

I wrote a command:

```
python3.8 manage.py rematch_unmatched_gene_list_symbols
```

Will run it on environments every so often to match things after new symbols come out

**Comment by sksmi** [comment]
PASS:
- Unmatched gene deleted from list and updated in saved list. 
- Newly matched genes no longer highlighted. http://144.6.229.160/genes/gene_grid/gene-list-94
