### ISSUE TITLE
Classification export - CSV includes excluded records

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1064]
* Make sure there are some classifications with errors, so that liftover_error has "Excluded due to..." - these records shouldn't be shared
* Go to Classification export page
* Pick CSV, click export
* The excluded records are there, they shouldn't be

**Comment by TheMadBug** [comment]
The CSV actually includes "excluded" rows, but should place them at the bottom of the file with a column describing the resolution or liftover warning that caused them to be marked as "excluded"

**Comment by davmlaw** [comment]
Should this be an admin-only feature? Otherwise the stuff marked excluded could escape into the wild...

But if you think it's ok and it's by design then feel free to just close this

**Comment by TheMadBug** [comment]
To be fair, the things marked as excluded are probably right, but just need confirmation.
Excluding it from MVLs and VCFs were more important as systems that ingest that stuff don't typically have a (we're not 100% sure about this mapping) option, where CSVs are handled in bespoke fashion.
