### ISSUE TITLE
Classification export VCF - symbolic variants missing SVLEN

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1065]
* Submit and share a variant against a c.HGVS that is more than 1kb long, eg NM_000264.5(PTCH1):c.1004_3004dup
* Go to classification, export, select VCF, download
* The record is missing a SVLEN, so you don't know how long it is:

```
9	95458176	vg10714430	G	<DUP>
```

**Comment by davmlaw** [comment]
I made some modifications so that the VCF passed validation (with vcf-validator) so a quick check that expected fields are all there would be good as well

**Comment by EmmaTudini** [comment]
Testing in this google doc - https://docs.google.com/document/d/14hzg7TqNCFyeewuf2g2Nr9euqaVujOfWlbSHW_D63Ho/edit

**Comment by TheMadBug** [comment]
vcf-validator complains that ID and POS are switched around.
It would like (but not demand) the header "reference"
It also complains about the ID being non-numerical, but that might be due to the ID and POS.
I'll switch them around and see what happens.

**Comment by EmmaTudini** [comment]
VCF validator is wrong I think - from the specs
1. #CHROM
2. POS
3. ID
4. REF
5. ALT
6. QUAL
7. FILTER
8. INFO

**Comment by davmlaw** [comment]
I can't recreate the ID/POS switch - are you able to say what environment it is, include files or copy/paste errors?

I didn't change col order in my SVLEN change this issue is about, the file appears to have been heavily rewritten since then but I can't see how it would alter the order, the code currently in master is:

```
# Header
            [("#" + "\t".join(["CHROM", "POS", "ID", "REF", "ALT", "QUAL", "FILTER", "INFO"]))])  # NO SUPPORT FOR FORMAT, etc
# rows
            return "\t".join([chrom, str(pos), self.get_variant_id(), ref, alt, qual, filter_val, info_str])
```

**Comment by EmmaTudini** [comment]
@davmlaw The columns were switched sometime after May 22nd. Probably due to the re-work due to Emedgene

**Comment by davmlaw** [comment]
What environment? Can you attach a file or copy paste an example? The VCF export in Shariant test looks fine to me, and output from VCF validator is:

```
$ vcf-validator 'classifications_2024-06-17_GRCh38_vcf(1).vcf'
The header tag 'reference' not present. (Not required but highly recommended.)
```

**Comment by TheMadBug** [comment]
@davmlaw see my comment on June 14th where I run the validator.
I have since fixed the column order.
Appologies for not updating this issue to reflect that.

**Comment by davmlaw** [comment]
Ah, ok sorry I was confused about this issue and am very grumpy this morning...

Your last change on this file (in master) was 11 days ago, yet a bug was reported 3 days ago and is now fixed?

I feel that Emed gene should have had its own issue, given that the comments were on this issue, assigned to me in QA discussion column, it was due to my change and my responsibility to fix.

**Comment by EmmaTudini** [comment]
@davmlaw will leave @TheMadBug to respond RE the changes in master, etc.

RE process in general with issue assignment - I think we'd all benefit from reviewing the process we have for assignment of issues, documentation of code changes etc. We chatted about it briefly at our Shariant catchup this morning, and will put it on the agenda for the fortnightly meeting tomorrow morning.

Also I did raise a duplicate issue in VG private to put a link to my testing doc that has some private info - https://app.zenhub.com/workspaces/everything-space-5bb3158c4b5806bc2beae448/issues/gh/sacgf/variantgrid_private/3640
If you could look at that when you get the chance, that would be great

**Comment by TheMadBug** [comment]
RE the dates of that being mentioned and the fix, the fix was in the file vcf_export_utils.py which was changed on the 14th

**Comment by TheMadBug** [comment]
The bigger discussion aside, it appears to me this task (missing SLVEN) has been completed.
@EmmaTudini if you're happy with the testing re SLVEN, please move to pending Shariant release

**Comment by EmmaTudini** [comment]
@TheMadBug There are outstanding issues in the google doc link above, but I'm not sure if it's related to SVLEN or another issue?

**Comment by TheMadBug** [comment]
I've made another issue for including records missing 1 build, the rest of the doc does seem SVLEN related.

Can we close this issue and manage the remaining verification of SVLEN in the #sacgf/variantgrid_private/3640 ?

**Comment by EmmaTudini** [comment]
What was the issue you raised around records missing 1 build?

Happy to close as long as the testing doc that I included in #sacgf/variantgrid_private/3640 is looked at - there is an issue that needs fixing in there

**Comment by TheMadBug** [comment]
I raised #sacgf/variantgrid_private#3647 for exporting if missing 1 build.

We have this issue in public and a duplicate issue in private (with a link to the testing document).

Until we work out our better system, I wanted to close this task so the work in regards to the testing doc can be done in the issue that has the testing doc in it.

**Comment by EmmaTudini** [comment]
Ok makes sense - happy to close
