### ISSUE TITLE
check_deployment

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1071]
Write some functions that do checks and return JSON results (aiming to be able to work as management command, automated task or site)

Might be easier to just have 1 place which is "make sure things you've configured in your settings are going to work"

* Looks for annotation files (currently in "vep_check")
* checks whether certain libraries and command line tools are there and at the correct version
* Move code from various manual migrations
* Add this into a management command "check_deployment" and then add to standard upgrade scripts

**Comment by davmlaw** [comment]
@TheMadBug what do you think about moving the upgrade script / migrator into an app? I would say either a new "upgrade" app or potentially move it into "manual"

Advantages would be:

* Could call common code - eg my deployment checks for this task
* Could use eg ```/etc/variantgrid``` configuration to be able to turn off deploy notification on dev machines
* Only take the Django startup hit once
 
For instance, the following takes 22 secs on my machine:

```
python3 manage.py migrate;python3 manage.py collectstatic_js_reverse;python3 manage.py collectstatic -v 0 --noinput
```

While this takes less than 7 secs:

```
for argv in [["migrate"], ["collectstatic_js_reverse"], ["collectstatic", "-v", "0", "--noinput"]]:
    utility = ManagementUtility(["manage.py"] + argv)
    utility.execute()
```

**Comment by TheMadBug** [comment]
So the only problem with that is the upgrader also triggers a `git pull` and then runs the code post `git pull`.
But the existing `upgrade.sh` could easily call git pull, and then invoke an app, and as you say, that would save the "upgrader" from having to startup VariantGrid several times for one deploy.

**Comment by davmlaw** [comment]
Moving upgrader is independent of this work so moved to own issue https://github.com/SACGF/variantgrid/issues/1073

**Comment by davmlaw** [comment]
This is only tested by developers as part of the upgrade process, but should be tested on Shariant test / dev machines etc

I have added this to the upgrader/migration script but have NOT made it part of the "automate standard steps" yet

please run "k" option for a while, and if it only fails when it should fail, we'll make it part of "a"

**Comment by EmmaTudini** [comment]
@TheMadBug Can I leave this to you to test?

**Comment by TheMadBug** [comment]
Yup already have and it helped identify that the demo environment was missing bcftools (which it now has - even if bcftools isn't enabled it's good to know it's there and ready).
