### ISSUE TITLE
BCFTools liftover failing due to ModifiedImportedVariants

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1079]
I recently moved some of this code around, I think it's failing as process VCF has been skipped (0 entries?)

```
upload.models.models.UploadStep.DoesNotExist: UploadStep matching query does not exist.

import_vcf_tasks.py
    upload_step = upload_pipeline.uploadstep_set.get(name=ModifiedImportedVariants.LINKED_SUB_STEP_NAME)

```

**Comment by davmlaw** [comment]
Testing:

Need to wait for all the ClinVar VCF annotation to finish, but once done, this is ~20k:

http://test.variantgrid.com/snpdb/watch_manual_variant_entry/87

So visit allele, and then liftover and confirm bcftools liftover works

**Comment by EmmaTudini** [comment]
Re-opening for Shariant testing - test when looking at BCFtool liftover
