### ISSUE TITLE
het_count and hom_count should only apply for germline samples

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#108]
DL Feb 2020: Multiple samples can be uploaded for the same patient. Germline GATK, Mixed GATK and Mixed FreeBayes

This will cause dupes in het_count and hom_count

Make some kind of configuration - settings based?
Can we tell via Helix? What about SampleSheet?

DL Mar 2020: Could also separate it out - also store somatic counts as well (then need to pull out of variant table)

“all” and “germline” or “somatic” databases. Unique patients database - use “sample name” as a unique key - to only do it once. Not guaranteed to work

**Comment by sksmi** [comment]
SKS Mar 2020: To complicate, germline & somatic aren't sample dependent - we have plenty of 'somatic' samples where the majority of filtered variants are germline, obviously different if the vcf was germline subtracted (is anyone doing that?). Perhaps AF cutoffs are a reasonable approach? There won't be too many somatics with a VAF 30 - 60 (+ homs), if you put a warning on there it should be ok.

Re. multiple specimens for same individual, I don't think there's a way to determine from lab as they don't receive (reliable) unique patient IDs (MRN is as close as you'll get and that's hospital dependent plus all the typo issues) DOB + names might work, but issue for obvious reasons. We have a similar problem with RUNX1 as it looks like the same individuals have been re-sequenced unknowingly by different labs so even though we have unique patient ids the counts will still be wrong. Only reliable approach would be to run a relationship test. Is that a feasible option?

**Comment by sksmi** [comment]
Transferred from VG issue 2325.

**Comment by davmlaw** [comment]
This is a new requirement not a bug

**Comment by davmlaw** [comment]
This was done and made it into VG3

https://github.com/SACGF/variantgrid/issues/279

We can also do it for sequencing runs etc and add/remove manually
