### ISSUE TITLE
Annotation page red TODO/warning etc doesn't take into account ANNOTATION_GENE_ANNOTATION_VERSION_ENABLED setting

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1089]
Go to the annotation page in Shariant demo

We have disabled gene annotation (as only used in anaylsis and annotation on gene pages) but it shows to run:

```
python3 manage.py gene_annotation --gene-annotation-release=1
```

The errors/TODO here shouldn't be reported if  ```settings.ANNOTATION_GENE_ANNOTATION_VERSION_ENABLED``` is True

**Comment by davmlaw** [comment]
This is what it looks like on Shariant test:

<img width="1032" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXg2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aca47954386fcfe2f23f24d57f52d07eacdc8db1/Screenshot%20from%202024-06-20%2017-01-24.png" alt="Screenshot from 2024-06-20 17-01-24.png" />

So to test:

* go to annotation page
* There should not be red box complaining about gene annotation

**Comment by EmmaTudini** [comment]
@davmlaw I can't see gene annotation using my admin login. Went to annotations and then searched for gene annotation, and all I could find was "gene annotation release" and "dbNSF gene annotation"
<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVNGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ddd5c8d519e221848ad9dbe180bfabd99836bb08/Screenshot%202024-06-24%20at%201.31.08%20pm.png" alt="Screenshot 2024-06-24 at 1.31.08 pm.png" />

**Comment by davmlaw** [comment]
That's good, that's what the change is - to not have a red box complaining about gene annotation when it is disabled (like in Shariant)

**Comment by EmmaTudini** [comment]
@davmlaw So gene annotation shouldn't appear at all then? I thought it would just not show the red box, rather than remove the heading completely?

**Comment by davmlaw** [comment]
Should we show features that are disabled?

If a feature is enabled we show:

```
Feature:

XXXX objects loaded
```

If not working, we show:

```
Feature:

Not loaded - here are installation instructions
```

If it's disabled, we don't show it. We could potentially show:

```
Feature:

This has been disabled via setting XXX
```

**Comment by EmmaTudini** [comment]
If it's not supposed to show, then I'm happy - moving to pending release
