### ISSUE TITLE
Intergenic variant details

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#109]
DL Nov 2019: 
Currently, if no variant annotation transcript we show:
"Variant is intergenic, so no transcript or gene information is available. "

But there are some intergenic annotations - ie gnomad, external data etc etc. We should show if intergenic and divide up sections into needs transcript or not and hide them if not needed.

See also VG issue 2116 Transcript select - annotations w/o transcripts

**Comment by sksmi** [comment]
Transferred from VG issue 2115.

**Comment by davmlaw** [comment]
An example integenic variant that has gnomAD data is NC_000011.10:g.34758731G>A

**Comment by davmlaw** [comment]
Confirmed it showed limited stuff and warning on page:

https://variantgrid.com/variantopedia/view_variant/250698650
