### ISSUE TITLE
VEP minor release changes (git hash) cause VEPVersionMismatchError

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1090]
When moving to a new system, we often re-install VEP via pulling down from Git and they appear to have changed the git commit in releases (for minor updates etc)

We check the git hash as part of VariantAnnotationVersion and if it changes, we get:

```
Traceback (most recent call last): File "/opt/variantgrid/annotation/tasks/annotate_variants.py", line 74, in annotate_variants dump_and_annotate_variants(annotation_run)
File "/opt/variantgrid/annotation/tasks/annotate_variants.py", line 105, in dump_and_annotate_variants vep_check_command_line_version_match(annotation_run.variant_annotation_version)
File "/opt/variantgrid/annotation/vep_annotation.py", line 388, in vep_check_command_line_version_match _vep_check_version_match(variant_annotation_version, vep_version_kwargs, "VEP command line")
File "/opt/variantgrid/annotation/vep_annotation.py", line 371, in _vep_check_version_match raise VEPVersionMismatchError(msg) annotation.vep_annotation.VEPVersionMismatchError: Annotation/VEP out of sync! Version 'v9. (21 February 2024) VEP: 110 / RefSeq/GRCh38' and VEP command line differ, KEY: 'ensembl_io' annotation: '110.b1a0d57', vcf: '110.0edbb93'
```

I don't think we have ever cared about this (enough to dump all existing annotation and re-annotate) - so the work around has been to update the existing VariantAnnotationVersion to match the new VEP deployment.

So - what to do about this?

* Just remove "ensembl" and "ensembl_io" from VariantAnnotationVersion - so this won't happen again?
* We could just ignore these fields in the get_or_create and then maybe update it with what's in the VCF, maybe storing in an audit log the fact that it was bumped?
* Have a concept of a "minor version" or something that keeps track of this - meaning we keep track but don't have to create a new version?

**How I usually fix it:**

```
 $ python3 manage.py vep_version --genome-build=GRCh37

{'vep': 110, 'ensembl': '110.73b02d8', 'ensembl_funcgen': '110.24e6da6', 'ensembl_variation': '110.d34d25e', 'ensembl_io': '110.0edbb93', 'thousand_genomes': 'phase3', 'cosmic': 99, 'hgmd': '20204', 'assembly': 'GRCh37.p13', 'dbsnp': 154, 'gencode': 'GENCODE 19', 'genebuild': '2011-04', 'gnomad': '2.1.1', 'refseq': '2020-10-26 17:03:42 - GCF_000001405.25_GRCh37.p13_genomic.gff', 'regbuild': '1.0', 'sift': 'sift5.2.2', 'genome_build': <GenomeBuild: GRCh37>, 'annotation_consortium': 'R', 'columns_version': 3, 'distance': 5000, 'dbnsfp': '4.5a'}
```

The numbers for "ensembl" and "ensemble_io" are from the VEP code so are the same for each build

```
from annotation.models import VariantAnnotationVersion, GenomeBuild

for genome_build in [GenomeBuild.grch37(), GenomeBuild.grch38()]:
    vav = VariantAnnotationVersion.latest(genome_build)
    # Copied from JSON output from management command above
    vav.ensembl = '110.73b02d8'
    vav.ensembl_io = '110.0edbb93'
    vav.save()
```

**Comment by davmlaw** [comment]
Hit by this again. Probably easiest thing to do is strip the hash off the end then we still get a major but not minor version check

**Comment by davmlaw** [comment]
Went with stripping out the hash (leaving just the major version) ie '110.73b02d8' -> '110'

Testing - go to the annotation, version page. A new version should NOT be created and all existing annotation works fine

**Comment by EmmaTudini** [comment]
@davmlaw as non-admin went to https://test.shariant.org.au/annotation/annotation_versions
- VEP remains as 110
- Ensembl variation listed as 110.d34d25e - is that ok?
- <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8d938047c871bc84e5739729664246c5178647f/Screenshot%202024-07-09%20at%2011.55.54%20am.png" alt="Screenshot 2024-07-09 at 11.55.54 am.png" />

**Comment by davmlaw** [comment]
Yeah, I don't know if that will change and cause us issues too, but it can't hurt to strip it the same time we're doing the other ones

**Comment by davmlaw** [comment]
Did same thing for ensembl_variation

**Comment by EmmaTudini** [comment]
Testing
- As non-admin went to annotation page >versions
Expected output: Ensembl variation should no longer contain hash at the end
Actual output: Passed
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8110e9b438743d8cb0cb719fb2956ae015b9e957/Screenshot%202024-07-13%20at%2012.10.09%20pm.png" alt="Screenshot 2024-07-13 at 12.10.09 pm.png" />

**Comment by TheMadBug** [comment]
Can confirm in prod we now have VEP 110
