### ISSUE TITLE
BCFTools +Liftover - test, collect, display reject reasons

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1091]
See [this issue](https://github.com/freeseek/score/issues/10#issuecomment-2159306538)

New release - testing: https://software.broadinstitute.org/software/score/

If it works, we should store then display the liftover failure reject reasons

**Comment by davmlaw** [comment]
Will need to install updated version of bcftools +liftover plugin, this should be detected by the deployment_check tool

We read and store the reason now, eg:

```
{ "message": "BCFTools +liftover rejected variant: UnmappedAnchors" }
```

**Comment by davmlaw** [comment]
Deleted old liftover, re-ran, verified it came up with unmapped anchor message

http://test.variantgrid.com/snpdb/liftover/view_liftover_run/58

**Comment by EmmaTudini** [comment]
@davmlaw Will any of these changes affect Shariant?

**Comment by davmlaw** [comment]
Shariant currently has BCF tools liftover disabled for the next deploy

When it's enabled, you should probably test it, added to "Shariant - BCFTools liftover testing"
