### ISSUE TITLE
Store HGVS resolution method on imported allele info

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1099]
Raised from 

https://github.com/SACGF/variantgrid_private/issues/3653

In this issue:

https://github.com/SACGF/variantgrid_private/issues/3654

We store the hgvs matcher and the method (whether internal or clingen fallback) on resolved variant info

We should do the same on Imported Allele info when it comes in (will this always be the same as resolved variant info for non lifted over build?)

**Comment by davmlaw** [comment]
If you look at HGVS Matcher lines 345, 367 - the method is returning lots of different strings, eg:

"LRG_274t1:c.2416dupA" -> 'BioCommons hgvs v0.1.dev1531+g201a2bc as 'NM_000527.4:c.2416dup' (from LRG_RefSeqGene)'

This is good as human readable but it is bad for creating a HGVSConverterVersion you can search on

Should perhaps clean this up, and split into what's used to populate HGVSConverterVersion, and the details for human consumption

Will also need to do historical migration from message

Working in branch feature/issue_1099_imported_allele_info_hgvs_resolution

**Comment by EmmaTudini** [comment]
Test
- As non-admin went to allele 32361
- Selected imported as link
Expected output: Extra additions should not appear
Actual output: Passed
