### ISSUE TITLE
Analysis permissions

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#11]
*  Analysis works on view_analysis never checking change_analysis - ie no read only mode
*  When you don’t have permission for a patient for that project it shouldn't use it in the node

**Comment by sksmi** [comment]
Passed w/ caveat. See https://app.qase.io/run/VG/dashboard/14

Issue: Analysis settings changes couldn't be saved. Tried updating analysis name, description & annotation version. No save button. Force reload worked but didn't save changes.

**Comment by davmlaw** [comment]
Whoops - typo on analysis settings page, enabled button again

**Comment by sksmi** [comment]
Re-tested https://app.qase.io/run/VG/dashboard/14
All looks good. Minor issue where csv download from node throws error (but still downloads): 	
Error making request to server. status: 403 statusText: Forbidden

**Comment by davmlaw** [comment]
403 is from setting panel size which is mysteriously trigger from CSV download. You can also cause the 403 by resizing the analysis/grid panel widths in the middle. Will fix both

**Comment by davmlaw** [comment]
Fixed, can you please add 2 test cases (as a read only user):

* Attempt to resize panel
* Attempt to add a variant tag
* try to delete a variant tag (a user with write permissions needs to make one)

**Comment by sksmi** [comment]
Re-tested. Passed. No issue with csv download. 
Note throws error on gene list node:  django.core.exceptions.PermissionDenied: You don't have permission to access gene_list 1988

**Comment by davmlaw** [comment]
Raised permission issue as #140
