### ISSUE TITLE
Variant coordinate parsing error 2kb del

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#112]
Error parsing variant coordinate. See: https://variantgrid.com/classification/classification/1575

Variant identified in external paper, would like to classify as part of review. 
Searched for variant: NM_032638.5:c.-45-155_871+527del

Maps ok to CAR, but reports variant coordinate error on creation of classification form. All looks ok to me. 
Note that variant is 2kb deletion, so assuming this is the cause. 
No action required as will use classification form as is, but raising issue FYI.

**Comment by davmlaw** [comment]
Whoops that's due to abbreviating the variant coordinate to ```3:128204042 TCT...GAA>T```

There are a few classifications in RUNX1 that are affected: 1658, 1659, 1678 so we need to make a data migration

**Comment by EmmaTudini** [comment]
@davmlaw Could be a completely separate issue but variants are also abbreviated when exporting as a vcf from Shariant - see: https://app.zenhub.com/workspaces/everything-space-5bb3158c4b5806bc2beae448/issues/sacgf/variantgrid_private/2875

**Comment by davmlaw** [comment]
Have made a classification for "NM_032638.5:c.-45-155_871+527del" in test so that we can make sure that legacy data is migrated once the fix comes in:

http://144.6.229.160/classification/classification/461

**Comment by sksmi** [comment]
Checked existing classification & made a new classification. Fixed, no error reported.
