### ISSUE TITLE
Upload processing issue for sample MODY_013

### ISSUE THREAD

**Issue by PeerArts** [SACGF/variantgrid#1140]
Hi Dave, 

A while ago, I asked Frank and Sashi to upload the .vcf for a MODY sample to VG.com. 
I've been looking for the data to analyse, mbut I just noticed that it got stuck in VG.com at the "importing stage". 
https://variantgrid.com/snpdb/view_vcf/1460

Is that something you can help with? Or should we delete and re-upload? 

Thanks, 

Peer

**Comment by davmlaw** [comment]
Hi, I can fix this, looking into it now

This is due to the annotation not finishing. A structural variant annotation run failed with:

```null value in column "predictions_num_benign"```

Will see what I need to do to fix

**Comment by davmlaw** [comment]
Hi, I restarted the annotation and it worked. The file failed quite a while ago, and I've upgraded the code since, which seems to have fixed it
