### ISSUE TITLE
Test server slow

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#119]
http://144.6.229.160/analysis/1716/

Only 1 classification in db - taken something like 10 mins to load so far. No error I can see.

**Comment by davmlaw** [comment]
Keeping all test server performance issues in 1 place.

* The test server uses a non-SSD disk so it's going to be 5-10x slower than vg.com or SA Path
* As reported in https://github.com/SACGF/variantgrid_private/issues/2895  - the database is making some really bad decisions still need to look into it

**Comment by davmlaw** [comment]
The strange thing is the test database is really big still:

VG test - 14M variants = 288G 
RUNX1 - 8.6M variants = 58G

This appears to be because this table wasn't cascade deleted properly?

```
snpdb=# select count(*) from annotation_varianttranscriptannotation_version_7;
   count   
-----------
 338600401
```

**Comment by davmlaw** [comment]
Running vacuum analyse full on annotation_varianttranscriptannotation_version_7.

Still need to:

* Delete any remaining partitions that shouldn't be there
* Delete any old variant record collection data.
* delete variant_id < 241615481 in other tables (zygosity count?)

**Comment by davmlaw** [comment]
Cleaned up a lot of crap I think this is faster now - running a final ```vacuum full analyze ``` on the server overnight which should clear up the space (but will make the server not really work for maybe an hour)

Should be good to go Wednesday morning. If fast enough (remember it won't be as fast as prod due to machine), please close issue.

**Comment by sksmi** [comment]
Passed. Tested using merge: https://app.qase.io/run/VG/dashboard/3# 

Benchmarking: 
- Self-merge 2x 598 variants ~2.5 min.
- Standard merge: 598 + 699 = 899 unique variants. ~1.5min.

Resolved D-3 based on results: https://app.qase.io/defect/VG/view/3
