### ISSUE TITLE
Unable to annotate variant

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#120]
Think this is fixed in test, but highlighting FYI.

Manually created variant X:154128237 G>C in both VG test & prod.
Both env. correctly mapped variant to coordinate.

Test: http://144.6.229.160/variantopedia/view_variant/248261930
Looks good.

Prod: https://variantgrid.com/variantopedia/view_variant/241931627
Couldn't find VariantAnnotation for X:154128237 G>C, VariantAnnotationVersion v7. (17 July 2020) VEP: 100/Ensembl/GRCh37

**Comment by davmlaw** [comment]
This was due to vg.com running out of disk space - see errors on annotation page or slack channel reporting out of disk.

I was in a talk so only just got out to fix it
