### ISSUE TITLE
Damage node - OR option on filters

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#121]
Selecting the 'min damage prediction' (or 'at least one damaging prediction' in older versions) results in filtering of some stop-gain variants.

Env: variantgrid.com
Example variant: CA374986424
Example analysis: https://variantgrid.com/analysis/2075/ compare left damage node to right. There is 1 damage prediction, but impact is HIGH. 

Expected behaviour:  Impact min OR min damage prediction  (not AND).

**Comment by davmlaw** [comment]
Every other node filter works with AND unless it explicitly has an OR option. This is a change request under the guise of "expected behavior"

**Comment by sksmi** [comment]
Problem is that if you add damage predictions or CADD score you lose some of the stop-gains which seems non-intuitive to me esp. given the splice variants are explicitly handled. Easy enough to build a manual filter as long as you're aware, just high risk if you're not. Did a quick stock take on analyses, seems no one is using the scores for filtering except me so moot point.

**Comment by davmlaw** [comment]
Rolled into #216 - SpliceAI Built-in Filter
