### ISSUE TITLE
SQL tab - rename to debugging tab

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#122]
Convert user preference, change name etc.

Can then start showing all kinds of other useful information to help debug any issues

**Comment by davmlaw** [comment]
Renamed preference and tab. Also added a dump of node values

**Comment by sksmi** [comment]
Tab displays (tested multiple nodes). Preference renamed. Show columns working as expected.
No formal test, but no obvious issues.

**Comment by sksmi** [comment]
Closing don't think there's anything else I can test here.
