### ISSUE TITLE
More forgiving HGVS search matching

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#124]
BadTranscript: The transcript 'PALB2' does not exist in the RefSeq database.

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/1690/](https://rollbar.com/jimmy.andrews/VariantGrid/items/1690/)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/variantopedia/search.py", line 349, in search_within
    build_results = get_results_func(self.search_string,
  File "/mnt/variantgrid/variantopedia/search.py", line 474, in search_hgvs
    variant_tuple = hgvs_matcher.get_variant_tuple(hgvs_string)
  File "/mnt/variantgrid/genes/hgvs.py", line 223, in get_variant_tuple
    variant_tuple = pyhgvs.parse_hgvs_name(lookup_hgvs_name, self.genome_build.genome_fasta.fasta,
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 1394, in parse_hgvs_name
    transcript = get_transcript(hgvs.gene)
  File "/mnt/variantgrid/genes/hgvs.py", line 217, in get_pyhgvs_transcript
    return TranscriptVersion.get_refgene(self.genome_build, transcript_name,
  File "/mnt/variantgrid/genes/models.py", line 592, in get_refgene
    TranscriptVersion.raise_bad_or_missing_transcript(genome_build, transcript_id, version)
  File "/mnt/variantgrid/genes/models.py", line 558, in raise_bad_or_missing_transcript
    raise BadTranscript(f"The transcript '{accession}' does not exist in the {annotation_consortium} database.")
BadTranscript: The transcript 'PALB2' does not exist in the RefSeq database.Traceback (most recent call last):
  File "/mnt/variantgrid/variantopedia/search.py", line 469, in search_hgvs
    variant_tuple = hgvs_matcher.get_variant_tuple(hgvs_string)
  File "/mnt/variantgrid/genes/hgvs.py", line 223, in get_variant_tuple
    variant_tuple = pyhgvs.parse_hgvs_name(lookup_hgvs_name, self.genome_build.genome_fasta.fasta,
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 1382, in parse_hgvs_name
    hgvs = HGVSName(hgvs_name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 758, in __init__
    self.parse(name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 772, in parse
    self.parse_allele(allele)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 859, in parse_allele
    raise NotImplementedError("unknown kind: %s" % allele)
NotImplementedError: unknown kind: PALB2 c.3113G>A
```

**Comment by davmlaw** [comment]
We get a search like "PALB2 c.3113G>A" once a week - we could support it

**Comment by davmlaw** [comment]
More wacky HGVS searches maybe we can do stuff about:

NM_015120.4:c.4166 
NM_016222.3:c.C1015T
NM_000059:c.426‐12426‐8del

**Comment by sksmi** [comment]
Half the time they're my variants, either typos or copied from some resource usually without looking at them first. I quite often use VG as a variant check when I'm in a hurry. :)

**Comment by davmlaw** [comment]
I like the idea of logging then examining HGVS errors to try and be more forgiving, but perhaps we should disable rollbar reporting for these, it's just more stuff to wade through to work out whether it's an error.

**Comment by TheMadBug** [comment]
Agreed, Rollbar isn't really the place for this. Could have an admin or command line to spit out all the bad ones rather than popping up everytime a record is mentioned.

**Comment by davmlaw** [comment]
Got a search for:

3:128200782G>A c.1023C>T

**Comment by davmlaw** [comment]
GATA2(NM_032638.5):c.1082G>C

**Comment by davmlaw** [comment]
Have been able to fix: GATA2(NM_032638.5):c.1082G>C but not GATA2:c.1082G>C - that needs a way to calculate the canonical transcript

**Comment by davmlaw** [comment]
(NM_004991.4:c.2577+4A>T Gene symbol

**Comment by davmlaw** [comment]
Emma says people have searched for:

* p.(Arg212Cys)
* c.634
* NM_000492.3(CFTR) : c.1549
* CFTR p.arg75

No idea what they expected us to do with the first two but I guess the other 2 could take us to a locus

**Comment by TheMadBug** [comment]
If searching on p.hgvs or partial c.hgvs, we could always search for classifications that include those. It wont be particuluarily efficient, but it would only kick in when a certain pattern is matched. (I'd happily implement that bit when time permits), will leave locus searching to you.

**Comment by davmlaw** [comment]
If you wanted to find classifications via "c.634" - I think it might be best to have an autocomplete of the Classification HGVSs?

**Comment by TheMadBug** [comment]
Actually I retract my previous suggestion of searching classifications with partial c.hgvs/p.hgvs anyway. As in the case of environments that take imports p.hgvs is not always available - so there might be some classifications that should have a certain p.hgvs but instead have it blank.

If a user was then to search on the p.hgvs and not find any results that might fasly think we have no classifications for that protein.

Autocomplete for c.hgvs is best solution, but not an immediate priority.

**Comment by davmlaw** [comment]
Need to lower case the dup/inv etc

NM_032638:c.1126_1133DUP fails - NM_032638:c.1126_1133dup works

**Comment by davmlaw** [comment]
Someone searched for NM_001193307.1):c.170T>C - died with:



```
Traceback (most recent call last):
  File "/mnt/variantgrid/variantopedia/search.py", line 349, in search_within
    build_results = get_results_func(self.search_string,
  File "/mnt/variantgrid/variantopedia/search.py", line 469, in search_hgvs
    variant_tuple = hgvs_matcher.get_variant_tuple(hgvs_string)
  File "/mnt/variantgrid/genes/hgvs.py", line 223, in get_variant_tuple
    variant_tuple = pyhgvs.parse_hgvs_name(lookup_hgvs_name, self.genome_build.genome_fasta.fasta,
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 1392, in parse_hgvs_name
    transcript = get_transcript(hgvs.transcript)
  File "/mnt/variantgrid/genes/hgvs.py", line 217, in get_pyhgvs_transcript
    return TranscriptVersion.get_refgene(self.genome_build, transcript_name,
  File "/mnt/variantgrid/genes/models.py", line 568, in get_refgene
    transcript_id, version = TranscriptVersion.get_transcript_id_and_version(transcript_name)
  File "/mnt/variantgrid/genes/models.py", line 535, in get_transcript_id_and_version
    version = int(parts[1])
ValueError: invalid literal for int() with base 10: '1)'
```

**Comment by davmlaw** [comment]
**Gene/transcript order switched**

Example: GATA2(NM_032638.5):c.1082G>C 

 - just reverses them (this has been fixed since March 11 2021)

**Bad brackets:**

Example: "NM_001193307.1):c.170T>C"

If the number of "(" not equal to ")" or more than 1 of each - strips the brackets and tries again. Not this won't work if you screw brackets up around the gene symbol

**Bad case**

Example: NM_032638:c.1126_1133DUP

Converts "ins", "del", "dup", "inv" to lower case, eg will search for NM_032638:c.1126_1133dup works

**Gene symbol and no transcript**

Examples: PALB2 c.3113G>A, DDX41:c.121C>T

* Searches for all transcripts associated with symbol
* Adds eg "Warning: HGVS requires transcript, given symbol: 'PALB2'"
* Groups results together if they produce the same search result
* Tries to merge messages nicely

As part of the above, I made some general changes to make the results better:

* Search result sorting algorithm to bring existing results forward, and lower priority of AbstractMetaVariant - ie "create manual variant" etc and also make HGVS use annotation consortium (so eg NM_XXX will show up before ENST if that's what our system is using)
* HGVS throws an error if it resolves outside of the transcript boundaries - this is part of HGVS standard, and it didn't do it before. Reason is to not return eg short transcripts that couldn't be at that position

**Comment by davmlaw** [comment]
Needs to go through Shariant testing process

**Comment by davmlaw** [comment]
Moved search HGVS locus to issue #437

**Comment by EmmaTudini** [comment]
Initial testing in Shariant test:
- Logged in as non-admin user assigned to VCGS Unit 1

1. Searched for BRCA2:c.1A>G 
- Searching for gene and chgvs takes around 9 seconds. This seems a little long but not sure what could be done to fix this?

First result - 
HGVS (RefSeq, GRCh38)	
Warning: HGVS requires transcript, given symbol: 'BRCA2'
Results for: NM_000059.4, ENST00000380152.8, ENST00000544455.5, ENST00000614259.1, ENST00000670614.1, ENST00000671466.1

13:32316461 A>G Classifications: 1

Output: *Failed* - shows 1 classification. Not sure where this has come from but there is more than 1 classification. Thought that it could be due to it only recognising GRCh38 imported classifications but there are no GRCh38 imported classifications at all. 

Also happened for GRCh37 result - shows only only one classification when there are at least 4.

**Comment by TheMadBug** [comment]
test comment

**Comment by EmmaTudini** [comment]
Also, results show - HGVS (RefSeq, GRCh38)	
Warning: HGVS requires transcript, given symbol: 'BRCA2'
Results for: NM_000059.4, ENST00000380152.8, ENST00000544455.5, ENST00000614259.1, ENST00000670614.1, ENST00000671466.1

13:32316461 A>G Classifications: 1

But then show ENST transcripts? This could have already existed as an issue before.

**Comment by davmlaw** [comment]
> there is more than 1 classification

Raised counts issue https://github.com/SACGF/variantgrid/issues/456 - was due to miscounting in variant summaries (not due to this HGVS change)

> then show ENST transcripts

Is the issue you're highlighting that it says "RefSeq" but shows "ENST" transcripts? That's because we:

* collapse the results to unique variants (ie RefSeq and Ensembl transcripts listed point to same variant) 
* Flag the search result as being RefSeq if it contains a refseq transcript, so it's moved up in the search results

I guess it's a bit confusing as it isn't all refseq. The correct thing to do is probably flag it as both but still allow the same annotation consortium boost

**Comment by davmlaw** [comment]
OK, change was to show both annotation consortia in the case of merged results across both. Search results from preferred build still appear in front

**Comment by EmmaTudini** [comment]
Testing: 
- Logged into Shariant test as non-admin
- Searched for BRCA2:c.1A>G

Expected output: Results should show correct classification count and preferably be the same in both genome builds (test for issue #456). Ensembl should be shown alongside refseq if search result includes results for ensembl transcripts.

Actual output: **Failed** - 10 classifications shown against one result 
HGVS (ENSEMBL, REFSEQ, GRCh37)	
Warning: HGVS requires transcript, given symbol: 'BRCA2'
Results for: NM_000059.4, ENST00000380152.3, ENST00000544455.1
13:32890598 A>G Classifications: 10

- There are 10 classifications in the database but only 8 are shared. 
- Also it's a little confusing to show 10 classifications for one genome build and not the other. Should probably be showing the number regardless of the build. 
- Ensembl is now shown with Refseq if the result includes ensembl transcripts.

@davmlaw Chatted to James about this.. as we need to go to prod in the next couple of days, we decided to remove the classification count for now. I'll raise another issue with some possible fixes.

**Comment by TheMadBug** [comment]
I have had a quick look at the code in get_variant_q that counts the classifications, and it looks like it takes the user access into account - so not sure what's causing the issue. I'll do a bit of investigation just to make sure it's not bad data in test confusing the issue.

**Comment by TheMadBug** [comment]
Okay after a bit more of a look @davmlaw I **think** I found the issue
```
q_classification = Classification.get_variant_q(user, genome_build,
                                                    clinical_significance_list=clinical_significance_list)
```
returns all the variants that the user can see at least 1 classification in.
BUT if some of those variants have classifications that the user can't see, they'll still be counted.

So when it comes to the search results for an allele, if the user can see at least 1 classification, it'll count all the classifications for that allele.

**Comment by TheMadBug** [comment]
I have made a setting to turn off classification count in search results (defaults to being shown, only turned off in Shariant where the share levels are of more importance)

**Comment by EmmaTudini** [comment]
Additional testing:
- Logged in as non-admin to Shariant test
- Searched for variant that is shared (classifications for multiple transcripts with different chgvs) - NM_002887.3(RARS1):c.1367C>T
Search terms - 1. NM_002887.3(RARS1):c.1367C>T - should go straight to allele page
2. ENST00000520013.5(RARS1):c.*868C>T - should go straight to allele page
3. RARS1(NM_002887.3):c.1367C>T - should go to search results page with warning and links to allele
4. NM_002887.3):c.1367C>T - should go to search results page with warning and links to allele
5. (NM_002887.3:c.1367C>T - should go to search results page with warning and links to allele

- Also searched for NM_000059.3(BRCA2):c.5197_5198DEL, NM_023083.4(CAPN10):c.997+136_998-148DUP, NM_000251.2(MSH2):c.942+1DUPC and NM_000251.2(MSH2):c.942+1dupC (wrong base)

Actual output: 
**Failed** - for point 5 above - inserting an open bracket before the transcript is not fixed.
Note: searching for a dup with an incorrect base doesn't correct like it does for dels, etc (see outstanding issue: https://github.com/SACGF/variantgrid_shariant/issues/7)
- Classification numbers have all been removed.

- Searched for variant that is unshared but belongs to the lab - NM_001004334.3(GPR179):c.4653C>G, GPR179:c.4653C>G
Expected output: Should be taken directly to result for first search term. Should show search results page with options for second.
Actual output: Passed

Not shared - NM_015378.4(VPS13D):c.1342A>G, NM_015378.4:c.1342A>G, NM_015378.4(VPS13D):c.1342A>T, NM_015378.4(VPS13D):c.1342T>G, VPS13D:c.1342A>G, VPS13D:c.1342A>T
Expected output: Should get "no results"
Actual output: Passed

**Comment by EmmaTudini** [comment]
More testing:
- Logged in as above
- Variant being searched -	
NM_001010938.1(TNK2):c.1733-19C>T and NM_001010938.2(TNK2):c.1616-19C>T (change in version changed the chgvs)
- Searched for - TNK2:c.1733-19C>T and TNK2:c.1616-19C>T

Expected output: Should show refseq results for both.

Actual output: **Failed** - It seems like it only searches on  the most recent transcript version, which means that the chgvs for version 1 of the transcript only comes up as a search result coincidentally because it matches an ENSEMBL transcript. Maybe this should be raised as another issue to be fixed next deploy?

**Comment by EmmaTudini** [comment]
More testing (outside of boundaries)
- Searched for  NM_001004334.3(GPR179):c.7990C>T (10 bases outside boundary) and NM_001004334.4(GPR179):c.7990C>T (longer transcript so inside boundary)

Expected output: First should fail with warning, second should go straight to classification page.

Actual output: Passed
Note: This also works for gene symbol only search but only brings up most recent transcript version (which could be an issue for edge cases as stated above)

**Comment by davmlaw** [comment]
Fixed (NM_002887.3:c.1367C>T
Fixed: TNK2:c.1733-19C>T - shows all now

NM_001010938.2:c.4020del being outside transcript boundaries - I explicitly don't check anything but SNPs as there are potentially normalization problems

**Comment by davmlaw** [comment]
Thinking about this some more, the check needs to be done in mRNA space, ie using the c. coords - as it's possible that you could "normalize off the transcript" in the genome and it be valid.

So in indels, just need to check start/end against transcript start/end

**Comment by davmlaw** [comment]
While here, "armc9" is kicking off an error, whatever regex we're using could be a bit tighter

```
#3294 InvalidHGVSName: Invalid HGVS allele "armc9": expected kind "c.", "p.", "g.", etc
```

**Comment by davmlaw** [comment]
Moved outside of transcript range etc to issue #487

**Comment by EmmaTudini** [comment]
Test outside of transcript range in https://app.zenhub.com/workspaces/everything-space-5bb3158c4b5806bc2beae448/issues/sacgf/variantgrid/487

**Comment by TheMadBug** [comment]
Outstanding problems covered by other tasks
