### ISSUE TITLE
Panel App update from web panel counts don't match

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#130]
326 panels listed in https://panelapp.genomicsengland.co.uk/panels/ 
VG panel app: Imported: 2 days ago. Details: 175 panel app panels.

For details see:
https://app.qase.io/run/VG/dashboard/13#

**Comment by davmlaw** [comment]
Please report this bug to PanelApp - there is nothing we can do - there are 175 elements in the results array on this API link (where we get it):

https://panelapp.genomicsengland.co.uk/WebServices/list_panels/

**Comment by sksmi** [comment]
Haha, nice try :) , but well beyond my skill set. No idea how to talk APIs.
Stuck at first q - what's the diff btwn https://panelapp.genomicsengland.co.uk/api/v1/panels/ & your link above? ...

**Comment by davmlaw** [comment]
OK, they must have changed their API

I checked and that path also works on PanelApp Oz

**Comment by sksmi** [comment]
**TBD** 
Data up to date, (limited) testing indicates VG data matches PanelApp website. Update button seems to work (#Panels updated on annotation page). Gene symbol panelapp info (imported in real-time?) doesn't match panels (imported on demand). 

Confusing for users (e.g. see bottom images below - VG.com (PanelApp outdated), VG.test (PanelApp updated yesterday))

__________________________________________________________
Genomics England:  326 panels, matches website (hasn't changed for a while though)
Recent change: TRIM8 present in both VG.test & VG.com pre-update.

Oz: 255 panels - matches VG test, fewer in VG.com as expected
Checked recent changes - CRYM, TEK, MAP2K1. All present (in VG.com too though!)


Genomics England pre-VG.test API call (9:57 Melb time)l:
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/33329fbf-1ba5-4265-990b-104693a9f6ff)

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/533db98f-57bd-48a2-91b1-7aec47823c71)

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/3afe2486-9302-40d1-84c6-9010ac850e05)

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/ac67ffdb-f1ff-4c07-bf96-85b110abf33f)
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/8daca238-e187-497d-9d1f-b235fb625fd3)

**Comment by davmlaw** [comment]
>> Confusing for users (e.g. see bottom images below - VG.com (PanelApp outdated), VG.test (PanelApp updated yesterday))

Can you please describe in words what the issue is? Thanks

If this is due to a gene list being out of date - there is a setting ```settings.PANEL_APP_CACHE_DAYS=30``` which we can change. It's a tradeoff between how often PanelApp changes and speed/performance (as well as say, chance of PanelApp being down and blocking people from working)

30 days is probably too long.

**Comment by sksmi** [comment]
Gene symbol info (imported in real-time?) doesn't match available panels (imported periodically).

i.e.  A new panel 'miscellaneous metabolic disorders' has been recently added to Oz panel app. In VG.com (where Oz PanelApp hasn't been updated for a couple of months) this gene list isn't available (as expected), however, when viewing the gene symbol the panel details have been imported (cool, but now users can't access the panel and think there's a bug in the PanelApp import).

![image](https://user-images.githubusercontent.com/8601717/108643621-6e3e6f00-74ff-11eb-80cc-ef59dc665966.png)

**Comment by davmlaw** [comment]
Changed PanelApp cache from 30 days to 14.

Flagged as meeting so we can ask KK what appropriate time is.

**Comment by sksmi** [comment]
14 is probably passable, but would it be an issue to use a 1 day cache? Quite a lot of panel app changes coming through daily so high potential for panel lists to be out of sync with gene annotation.

**Comment by davmlaw** [comment]
Set to 1 day cache.

The tradeoff is speed, ie if it takes 2 mins to retrieve the data from panel app, then saving the node will have a 2 minute overhead if you save it more than 1 day since the last time it was saved.

For diagnostics - they probably don't revisit stuff much so no big deal.

Ideally we'd run a service at night that updates all the panels etc but that can be future work
