### ISSUE TITLE
Classification form shows all sequence for large indels

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#131]
FYI large deletion shows up as follows on classification form: 
http://144.6.229.160/classification/classification/462

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/04136f1d-723f-4912-b055-c8e6012527e2)

Wondering if this will break the form if it's too large.

**Comment by davmlaw** [comment]
This was due to fixing #112 - if we abbreviate the sequence it causes an inconsistent coordinate/HGVS error.

**Comment by TheMadBug** [comment]
I probably need to add some auto truncating on the display of the form, as large values in any field with spaces or not - can make the form a bit wonky.
As in taking up too much verticle space on the form when in read only mode - and pushing out the Help box that re-displays all the text.

Will see if I can squeeze it in when time allows as it's been requested for Shariant as well.

**Comment by davmlaw** [comment]
This has been fixed due to the new formatting of symbolic variants

Eg NM_025114.4(CEP290):c.125_1025del used to have a 900 base REF, now it looks like:

```Variant coordinate: 12:88520131-88534787 <DEL>```

**Comment by TheMadBug** [comment]
Can confirm this is the behaviour now and alreay deployed. Closing as complete. 3 years later and we've done it!
