### ISSUE TITLE
All variants source node shows ref 

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#132]
http://144.6.229.160/analysis/1720/

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/6ad6806b-8584-4ea1-8a91-418f05ae7be2)

Is this intended?

**Comment by davmlaw** [comment]
nope - will fix

**Comment by davmlaw** [comment]
While here, also want to add:

* global var zyg count
* gene autocomplete

**Comment by davmlaw** [comment]
Just need to work out a way to set initial value to 1 (so it only shows internal db variants) - if I set in NodeView initial kwargs it's not saving the value set in form properly
