### ISSUE TITLE
Filter node + & - buttons missing

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#133]
http://144.6.229.160/analysis/1731/

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/5d5c7e1d-31e4-405a-ab8b-1ec5b6789dcd)

@TheMadBug  bootstrapping issue?

**Comment by TheMadBug** [comment]
The element for the `+` button by "Any" and the `-` button by the row are there, but just with the inline css `style="display:none"` causing them not to appear.
There are no JavaScript errors or missing files, going to say Bootstrap is probably innocent on this one.
Just some logic that is meant to make the buttons appear isn't working properly, over to @davmlaw on this one.

**Comment by davmlaw** [comment]
Whoops bug introduced during analysis read only change

**Comment by sksmi** [comment]
Passed. http://144.6.229.160/analysis/1741/
