### ISSUE TITLE
User Survey

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#134]
Proposing a user survey to determine: 
- Who is using VG, how often, in which environment?  
- What are users trying to achieve with VG? Does VG meet these needs?  
- What on-going development is required by users for a) maintenance of status quo, b) to encourage additional use/users?

Draft survey can be viewed here: 
https://surveys.adelaide.edu.au/redcap/surveys/?s=JCE4YFD4AT

@davmlaw thoughts?

**Comment by davmlaw** [comment]
Seems good, but IMO no point asking questions we can answer exactly via monitoring - eg how often people do things

Don't know if I want to do the work but if we used a Django poll app (which we actually have experience in) you could eg randomly show these to users after their first X uses, and it would work for all environments not just SA Path

**Comment by davmlaw** [comment]
The other thing is we've already spent a lot of time improving documentation in v3, what are we going to learn?

**Comment by TheMadBug** [comment]
We would learn improvements were good.
They could say v2 is clunky and doesn't do what they want
Then they could say v3 is smooth and does do what they want. (or they could say something else).

Then we start this whole process on an upwards trajectory, important to get a baseline.

**Comment by davmlaw** [comment]
I guess I'm just trying to say surveys have a cost in wages and user fatigue, and we should think really hard about when and what questions to ask (ie never anything we already know the answer to, or that we will not alter our behavior based on results)

**Comment by sksmi** [comment]
@davmlaw  was hoping to discuss today as I'm still keen and would like to circulate this week in prep for next wks steering committee (SAP & HSS users only). Think automated user monitoring would be ideal, but I would have thought it's quite a bit of work to get it happening.  I think it's hard to know if useful or not until we get responses - if nothing comes of it wouldn't repeat, if lots of useful feedback could go for an annual approach. Agree re. survey fatigue so have kept it short. Thoughts?

**Comment by davmlaw** [comment]
My main concern is mixing up results from VG2 and VG3 - maybe we could state that you only answer for the most recent one you use or something.

For documentation - the question I'm most interested in is whether people prefer the in-page documentation or the help guides, or they want something else (eg tutorials etc)

**Comment by davmlaw** [comment]
Perhaps what kind of documentation should we improve first:

* Tooltips (mouse hover text)
* In-page documentation
* Read the docs (docs link in top menu)
* Tutorials
* Videos

**Comment by davmlaw** [comment]
Also, it would be good to distinguish between "this sucks" and "this is slow" - perhaps a question about performance and where it needs to improve?

For instance I spent a bit of time making "samples with this variant" on variant details much faster with VG3 (it only looks 1x per VCF instead of pre sample - so probably 12-20x as fast) - because I saw how often people visited that page

**Comment by sksmi** [comment]
Bril. Thx - I'm taking that as an ok to go ahead. Have added the above - think we're pretty close, not sure about the prioritising new features question (not really sure which features are on the list). @davmlaw also feel free to log in to redcap and go crazy, you have full admin rights.
