### ISSUE TITLE
Gene Symbol page - remove top tagged variants grid

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#138]
This can be replaced now we can see all tags in the standard grid.

However, I'd like to have the "tag counts that filter grid"  from the variant tags page (make it a template tag or somethig?)

You can still see the individual analyses etc and the tag user and dates etc on the variant details page.

**Comment by davmlaw** [comment]
While here, on gene list grid, don't show category if nothing there

**Comment by davmlaw** [comment]
Sarah points out that we should also remove the tags column as it'll always be blank outside of an anaylsis

**Comment by davmlaw** [comment]
This is partly redundant with #33 - Gene page - merge variant grids, allow tagging

**Comment by davmlaw** [comment]
* VariantTags grid - shows variant in build it was classified in
* Variant details page - doesn’t show tags same allele
* Remove obsolete variant tags grids on view_gene_symbol

**Comment by sksmi** [comment]
Removed tags grid: PASS
Tag counts / filter for gene symbol variants grid: ?? (don't know what this means)
Works across genome builds: PASS (not tested: variant that can't be lifted over)
Removed tags column as it'll always be blank outside of an analysis: PASS

@davmlaw moving to SAP test, can you clarify the filter statement above?

**Comment by sksmi** [comment]
**PASS**

Ah the the gene variants grid - previously tested, works well. **PASS**
Quick check in SAP test. **PASS**
