### ISSUE TITLE
Analysis grid tags / classifications don't take into account sharing / withdrawn

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#139]
At the moment classifications (purple square 1st column) and global tags are shown without any Guardian user security.

Had a report of someone being confused they couldn't see the classification after it said there was one due to sharing

**Comment by davmlaw** [comment]
James said:

The columns "Internal Classification (max)" and "Internal Classification" thar relate to the below SQL don't exclude withdrawn classifications.

(This does not affect vg environments that don't use analysis)

They also don't take into account the share level - though for environments that use analysis that might be for the best.

```
SELECT_INTERNALLY_CLASSIFIED_SQL = """
select string_agg(coalesce(classification_classification.clinical_significance, 'U'), '|')
from classification_classification
where classification_classification.variant_id in (
    select snpdb_variantallele.variant_id
    from snpdb_variantallele
    where
    allele_id in (
        select allele_id from snpdb_variantallele where variant_id = snpdb_variant.id
    )
)
"""

SELECT_MAX_INTERNAL_CLASSIFICATION = """
select max(coalesce(classification_classification.clinical_significance, '0'))
from classification_classification
where classification_classification.variant_id in (
    select snpdb_variantallele.variant_id
    from snpdb_variantallele
    where
    allele_id in (
        select allele_id from snpdb_variantallele where variant_id = snpdb_variant.id
    )
)
"""
```

Due to the low impact of adding "withdrawn=False" to the SQL, might want to consider this for a hot fix
But due to the low amount of withdrawn data, might want to just wait for VG 3.1 for this to be deployed.

**Comment by davmlaw** [comment]
May be best to do via #234 -  Node counts could use querysets instead of SQL

**Comment by sksmi** [comment]
false positive affecting very few variants, negligible clinical impact - don't think hotfix is necessary.

**Comment by davmlaw** [comment]
This has been fixed via #234 - using node counts queryset

**Comment by davmlaw** [comment]
I started on this but it was more complicated than I thought. The most difficult part is when showing cohort zygosity fields, you can get them from multiple cohort genotypes and we pack them together with "||"

Probably best to retrieve the columns separately and deal with it in Python

Here's attempt to do via annotate - though this makes a group by which fails due to our manually adding columns (which also needed to go into group by)


```
def annotate_extra_columns(qs: QuerySet, user, genome_build, exclude_analysis=None) -> QuerySet:
    classification_qs = Classification.get_classifications_qs(user)
    classifications_ids = list(classification_qs.values_list("pk", flat=True))
    q_classification = Q(classification__in=classifications_ids)
    q_classification &= Classification.get_variant_q_from_classification_qs(classification_qs,
                                                                            genome_build)

    q_tags = None
    if exclude_analysis:
        q_tags = ~Q(variantallele__allele__varianttag__analysis_id=exclude_analysis)

    internally_classified = StringAgg("variantallele__allele__classification__clinical_significance",
                                      '|', output_field=TextField(), filter=q_classification)
    max_internal_classification = Max("variantallele__allele__classification__clinical_significance",
                                      filter=q_classification)
    tags_global = StringAgg("variantallele__allele__varianttag__tag_id", '|',
                            filter=q_tags, output_field=TextField())

    anno_kwargs = {
        "internally_classified": internally_classified,
        "max_internal_classification": max_internal_classification,
        "tags_global": tags_global,
    }
```

**Comment by davmlaw** [comment]
I think we can do it like this:

```
In [82]: tag_qs = VariantTag.filter_for_user(user)

In [83]: tags_subquery = Subquery(tag_qs.filter(allele__variantallele__variant_id=OuterRef("id")).values("allele").annotate(tags=Stri
    ...: ngAgg("tag_id", delimiter='|')).values_list("tags")[:1])

In [84]: qs.annotate(my_tags=tags_subquery).values()
Out[84]: <TransformerQuerySet [{'id': 1590576, 'locus_id': 1469536, 'alt_id': 526, 'my_tags': 'FakeTag|MyTag|blah2'}, {'id': 2849829, 'locus_id': 2627487, 'alt_id': 108, 'my_tags': None}, {'id': 2849830, 'locus_id': 2627487, 'alt_id': 526, 'my_tags': None}]>
```

**Comment by davmlaw** [comment]
Working in branch "analysis_grid_view_permissions" - still need to check that things work ok - ie check that it's using 
permissions correctly (analysis not request.user?)

Also need to check new SQL split code how it affects ordering

Clean up old code

Can raise an issue about converting whole grid to use querysets instead of SQL (just need to put cohort code into queryset)

**Comment by davmlaw** [comment]
I changed VariantGrid to use analysis.user for permissions vs request.user (which we use for row counts on the grid)
