### ISSUE TITLE
VEP skips some annotation due to obscure contigs

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#14]
If VEP doesn't recognise a contig, or like an AL, it skips it.

For instance, search for "NT_113878.1:g.272_274delTTT" in GRCh37 then create it.

This will run through the annotation and create an annotation dump file ```<vep_annotated_vcf_gz>_warnings.txt``` with:

```
WARNING: Chromosome HSCHR1_RANDOM_CTG5 not found in annotation sources or synonyms on line 1
```

Some other errors have the line / variant_id:

```
WARNING: VCF line on line 3351 looks incomplete, skipping:
2	202146658	.	T	<DEL>	.	.	variant_id=15193564
```

**TODO**

* We should load the warnings file into the DB, and have the option of showing it if it exists
* After variant annotation is completed, we should look for any variants that were asked to be annotated, but weren't. Store "unannotated count" so we can easily check up on things
* Add error flag and message to VariantAnnotation so that it's obvious something failed
* Created errored VariantAnnotation for all in import that failed.
* On variant details page, be able to jump to import warning
* After VCF is imported, check if it contained any error annotations, then store and make a warning on VCF page (like normalization)
* If it's easy, handle the particular errors with more detail, eg by contig or by variant_id as per example warnings above

**Comment by davmlaw** [comment]
Before you do this, ```annotation.annotation_versions.get_unannotated_count_min_max``` is really slow, because:

```
qs = qs.order_by("pk")[:annotation_batch_max]
```

needs to do a massive sort. Perhaps use increasing numbers to jump forward in the Variant table to find the unannotated ones?

**Comment by davmlaw** [comment]
Still todo:

* Search for variant annotation has error during sample stats - then raise a VCF annotation warning?
* Show error on variant details page

**Comment by davmlaw** [comment]
I've uploaded a VCF with the bad contig here:

Shows warning on these pages:

http://144.6.229.160/upload/view_upload_pipeline/1113
http://144.6.229.160/snpdb/view_vcf/573

Can see the particular variants here:

http://144.6.229.160/upload/view_upload_pipeline/warnings_and_errors/1113

And the variant page:

http://144.6.229.160/variantopedia/view_variant/248261924

**Comment by sksmi** [comment]
Tested the above. Works nicely. 

Ran a second test that failed: 
- Made a dodgy2.vcf by changing chr name to HSCHR1_RANDOM_CTG5
- Annotation warnings don't show.
- https://app.qase.io/run/VG/dashboard/16

**Comment by davmlaw** [comment]
The [VCF spec](https://samtools.github.io/hts-specs/VCFv4.3.pdf) requires that "All  entries  for  a  specific CHROM must form a contiguous block within the VCF file." while dodgy2.vcf has HSCHR1_RANDOM_CTG5 in the middle of variants from chrom 3

We should handle these invalid VCFs better, so I've raised an issue about it - https://github.com/SACGF/variantgrid/issues/127

**Comment by sksmi** [comment]
Deleted test case referenced above, replaced with new test case: https://app.qase.io/run/VG/dashboard/18

See also issue  #2947 Unannotated variant warnings
