### ISSUE TITLE
ClinGen Allele search results shows 2x hg37

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#142]
http://144.6.229.160/variantopedia/search?search=CA6989449

Searched for CA6989449
Should show hg37 & hg38 in list, but shows 2x hg37 (see below)

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/16c19d89-b350-4a28-b6da-f16342d680d7)

**Comment by davmlaw** [comment]
This is returning the GRCh38 as 37

If you have both builds enabled it returns:

```
ClinGen Allele ID (GRCh37)	13:51974171 G>A ClinVar: 1
ClinGen Allele ID (GRCh37)	13:52548307 G>A ClinVar: 1
ClinGen Allele ID (GRCh38)	13:51974171 G>A ClinVar: 1
ClinGen Allele ID (GRCh38)	13:52548307 G>A ClinVar: 1
```

**Comment by TheMadBug** [comment]
We can make all users in an environment have access to both builds - still pick a favourite - but not give them functionality to disable any.
(Dave is heavily opposed to this and I'm heavily for it).

I believe that no user will actually want to hide data for a given build, but will want to see it marked with what build it's for (something we have to code for anyway).
Hiding data based on genome build is going to cause confusion, especially when many variantgrid.com users colloborate.

(Requires 1 line code change to a settings file)
`USER_SETTINGS_SHOW_BUILDS=False`
Already in use in Shariant.

**Comment by davmlaw** [comment]
I think this is separate to that, as eg the coordinate is labelled for the wrong build

**Comment by davmlaw** [comment]
Was due to unrestricted FK join returning too many records causing dupes

I also made a change here that if ```settings.PREFER_ALLELE_LINKS=True``` (ie in Shariant) then it goes to the Allele page rather than the variant

**Comment by EmmaTudini** [comment]
Testing:
- Logged into Shariant test as non-admin
- Searched for CA6989449 as GRCh37 build and then again in GRCh38 build

Expected output: Should be taken directly to the allele page (not show the search as above).

Actual output: Passed

**Comment by sksmi** [comment]
Fixed. Not tested formally, but have used CAR search extensively. Will land on variant page for default build. 
No problems to date, closing.
