### ISSUE TITLE
NodeCache doesn't take into account global analysis changes

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#147]
Changing analysis settings (locked/unlocked, columns, sort by) can make the grid and editors change, but this is not captured in the node editors / grid as that is cached.

Easiest fix is:

* Add analysis.version which is bumped whenever something big changes
* Use analysis_version in all urls for node that could change because of it

**Comment by sksmi** [comment]
@davmlaw any advice on how to test this one?

**Comment by davmlaw** [comment]
Load an analysis, and click on a node so that it's cached.

In analysis settings, change one of these fields:

* custom_columns_collection
* default_sort_by_column

Save it.

Click back on a node, and make sure that you can see the changed fields have an effect (ie it's not just using the cached version which is now obsolete due to changes)

**Comment by sksmi** [comment]
Deployed. Not tested.
