### ISSUE TITLE
GeneListNode - PanelApp

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#149]
Use (multi) auto-complete to create gene lists for the filter.

I guess we'll take a snapshot at the time so the filter is consistent (and don't want to have to do API call every save)

**Comment by davmlaw** [comment]
Still need to handle being out of date.

Tiny change to node name (say x panel app panels)

**Comment by davmlaw** [comment]
Apologies here for making saving a new panel app panel take ages, it's doing API calls... will raise issue to do properly but no time now

To test "out of date" functionality - goals here are keep analyses consistent historically (eg locked analysis from 2 years ago still returns same results)

* Save gene list node w/panel app panels etc

Test if what node uses is different from latest panel:

* Via admin, change PanelAppPanelLocalCacheGeneList.version to be something different (was set via PanelAppPanel.current_version)
* View the gene list node (unfortunately may be cached - attach/detatch parent to reset cache) - should show a warning about panel not being checked
* User saving node should check/update things to latest version

Test if panel app panel hasn't been checked for 30 days:

* Via admin, change PanelAppPanel.modified so that it's more than 30 days in the past
* View the gene list node (unfortunately may be cached - attach/detatch parent to reset cache) - should show a warning about panel being out of date
* User fix is to save and/or have an admin hit the "update from web" on panel app panels on admin page

**Comment by sksmi** [comment]
VG.test GRCh37

- out of date warning **PASS**
used autism v 0.129 in gene list, modified to v 0.102, cleared cache. Warning displayed on node. 

- panel check > 30d ** HELP NEEDED**
can't find modified date - should it be here: http://144.6.229.160/admin/genes/panelapppanel/593/change/?_changelist_filters=p%3D3

**Comment by davmlaw** [comment]
Sorry it's ```genes.PanelAppPanelLocalCacheGeneList.modified``` not ```PanelAppPanel.modified```

Ie here:

http://144.6.229.160/admin/genes/panelapppanellocalcachegenelist/

I'll make those names more useful too

**Comment by sksmi** [comment]
Still lost, am I supposed to change the modified date or the version #? Modified date not accessible through admin as far as I can see...

**Comment by davmlaw** [comment]
Ah yeah you can't edit those by default in the admin.

I have set all of them to be last modified in early Jan so they should all be expired.

**Comment by sksmi** [comment]
Still not sure if I'm testing this one correctly - @davmlaw might leave it to you to close. 

VG test panels last updated 2+ months ago. Also tried to modify iron metabolism disorders (0.22 to 0.21). No warnings visible. 

http://144.6.229.160/analysis/2111/
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/f25ebe19-0779-4c5e-9a32-710ca6e2c6d6)
