### ISSUE TITLE
Gene filter field unusable

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#152]
Field too small to enter data.
http://144.6.229.160/genes/genes

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/8577d793-64b0-47e4-bb54-3fa4922b5698)

**Comment by davmlaw** [comment]
Made initial width wider.

FYI before the fix comes in, you can drag the bottom right of those grids to resize them

**Comment by sksmi** [comment]
Fixed on gene annotations page.

Now also an issue on gene symbol page. @davmlaw is it possible to fix there as well? 

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/82cd7407-3eea-4435-b124-286b202fdc5c)

**Comment by sksmi** [comment]
**PASS**
