### ISSUE TITLE
Update GRCh38 Refseq annotation release

### ISSUE THREAD

**Issue by EmmaTudini** [SACGF/variantgrid#153]
A new annotation version for GRCh38 was released at the end of last month - see 109.20201120. ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/annotation_releases

**Comment by davmlaw** [comment]
```
wget ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/annotation_releases/109.20201120/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gff.gz --output-document=GCF_000001405.39_GRCh38.p13_genomic.109.20201120.gff.gz
gff3ToGenePred -processAllGeneChildren -geneNameAttr=Name -rnaNameAttr=transcript_id GCF_000001405.39_GRCh38.p13_genomic.109.20201120.gff.gz GCF_000001405.39_GRCh38.p13_genomic.109.20201120.genePred

python3.8 ${VG_DIR}/manage.py import_gene_annotation --genome-build=GRCh38 --replace --annotation-consortium=RefSeq \
  --gff GCF_000001405.39_GRCh38.p13_genomic.109.20201120.gff.gz \
  --genePred GCF_000001405.39_GRCh38.p13_genomic.109.20201120.genePred
```

Deployed to:

* Shariant
* Shariant test
* VG test

Made a note to do w/SA Path test

All other environments will get it gene install scripts if/when they switch to GRCh38.

**Comment by davmlaw** [comment]
Confirmed this has been performed on Shariant prod, 20201120 is on variant annotation page (GRCh38, transcript versions, toggle import sources)
