### ISSUE TITLE
Confusion caused by window re-sizing in the analysis workspace

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#156]
If the window divider is moved too far to the left it becomes difficult to see that the divider exists. Causes some confusion with users who think the analysis is blank. I think this mostly happens when moving between computers/screens, or opening someone else's analysis (hopefully you remember if you moved it yourself!). 

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/b88b539e-3062-4251-914c-3fbe25763d7f)

**Comment by davmlaw** [comment]
Set min width to 200

**Comment by sksmi** [comment]
Tested - can't move grid window completely to left of screen.
