### ISSUE TITLE
Mutational signatures graph broken

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#157]
![mutational_signatures.png](https://images.zenhubusercontent.com/5bb45cdce135e46293defe80/7f99896d-f73c-4ae8-a593-3daf570687e8)

Graph at the top has nothing in it.

Examples include variantgrid.com and RUNX1

**Comment by davmlaw** [comment]
This was caused by having a variable called "bootstrap"

**Comment by sksmi** [comment]
Only 1 sample to test. Has been working for awhile. 
https://variantgrid.com/analysis/view_mutational_signature/2/
