### ISSUE TITLE
Trios list on sample page includes all trios from vcf

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#158]
If multiple trios have been created from a vcf all possible trios will be shown on a sample page regardless of whether that sample is included in the trio. e.g.

https://variantgrid.com/snpdb/view_sample/8007

Might be more intuitive to only list cohorts/trios that use the sample?

**Comment by davmlaw** [comment]
Yeah that's a bug

**Comment by davmlaw** [comment]
While there I found 2 other bugs:

* Same issue for pedigrees (showing if made from same VCF even if sample not in it)
* VCF/Cohort page showed Trios but not pedigrees made from cohort

**Comment by sksmi** [comment]
Tested in VG.com
