### ISSUE TITLE
Classify from variant tag

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#16]
SA Path user mentioned that junior people often flag a variant as needs review, or requires classification, then others will come along and do the classification.

Having a link to do a classification from the tags grid, would save them a lot of time.

We have the node, so I guess we can ask if it has a single sample, and if so set that in the classification

**Comment by davmlaw** [comment]
I think this is pretty straight forward with current features - reconfirm as perhaps they don't know about the "requiresClassification" tag functionality?

* From tags page, click on variant then classify (you need to re-select the sample, though)
* From inside the analysis, just classify it as "classificationRequired"

**Comment by davmlaw** [comment]
There are 2 paths to create a classification via web:

* "create for variant” page ```classification.views.views.create_classification_for_variant``` which does a POST to ```create_classification```
* “tagnode” - ```tagnode_editor.html``` and ```analysis.views.views_json.create_classification_from_variant_tag```

The “create from variant” is much more full-featured (eg shows autopopulation) - so perhaps it would be best to run them all through that - and then delete the duplicated code.

The changes to make to the "create for variant" page are:

* Mention we’re classifying from tag (and the node, etc). Link to analysis etc.
* Filter samples from tag, ie tag.node.get_subclass().get_samples()
* After creating the classification via POST - make an AnalysisClassificaiton object

**Comment by davmlaw** [comment]
todo:

* Make sure you've deleted all the legacy code we no longer require

testing:

* create requires classification in "all variants" node (so no sample actually exists)
* Create when you only have read access to a classification (should give warning about it)
* Make sure that you can still see what was classified from this analysis

**Comment by sksmi** [comment]
@davmlaw  - not sure if I'm blind, but can't see the link/button for this Can you add an image so I know what I'm looking for?

**Comment by sksmi** [comment]
All good - got it, it's in the tags grid - had for some reason thought it would be next to the IGV icon on all variants.

**Comment by sksmi** [comment]
Blocked.
https://app.qase.io/run/VG/dashboard/29


Passed, but 'blocked' as some non-intuitive behaviour. See details in blocked steps & below.

Wondering whether requiresclassification tag should be replaced by a 'classified' tag instead of removed? Or just left as is if that's too hard? Removing the tag means you can't use the tag grid to see important variants and lose the info that the variant has actually already been classified for this analysis - obviously this can be worked out by adding a new node filtering to classified variants, then checking all classified variants to see if there's a form related to this sample, but that seems painful.

Confusing behaviour if you don't reload browser page after classifying. Wondering if better to open create classification page in same window rather than new tab to force user to re-load analysis workspace, otherwise the message doesn't make sense (see blocked step for details). Or is there a way to force reload the classification tab info after a classification is created (assuming no/difficult)?

**Comment by davmlaw** [comment]
You can see variants that were classified in the analysis in the "classified" tab of the tags node, but that will only show ones that were created via the "classify from tag" process. You can also see them on the grid in the purple box (red=ClinVar classification, purple = internal)

But to be able to keep using it like other tags, a "classified" tag sounds like a good idea. Maybe make it special so you can't add it by hand?

Will check out other stuff later...

**Comment by sksmi** [comment]
Oooh cool feature I didn't know! Although might need a warning for that as lots of times variants are classified via variant page - have made a note to add in training docs. Filtering to internal classified is useful, but don't think it's specific enough as there can be lots of variants classified in some cases which is different from 'this is the variant we're going to report for this sample', also need to be careful w/ incidental findings.

**Comment by davmlaw** [comment]
@sksmi

I think just having the button disappear would be a good solution

Opening in the same window would throw out the flow, ie if the user tags 3 variants as "requires classification" then clicks on the 1st one. Then they have to re-open the analysis, open tags, click classifications tab.

And  thinking about whether a "classified" tag is a good idea, as:

**a) False negatives **

Eg exisitng classifications and doing it this way:

>> lots of times variants are classified via variant page 

**b) False positives**

What if someone creates a classification then withdraws it? What if someone tags a variant they haven't classified (should we restrict people from manually adding that tag?)

**c) We have existing ways we can rely on seeing whether it's been classified**

There are existing ways to see a classification:

* Purple box on the grid
* In analysis tags
* Listed on gene/variant pages

**Comment by davmlaw** [comment]
Clicking "New Classification" hides the button. So at least you can remember where you are and not easily re-click from the same page.

You can of course reload the pages, then do some work in another tab, not reload and it'll be out of date - but that's an extremely difficult problem without re-polling every page all the time - so in that case, if you click "New classification" on a tag which was deleted, it'll take you to a page where you'll be told it was deleted (better than a crash)

**Comment by sksmi** [comment]
Looks good & covers most scenarios. 

Testing passed, closing as no comments of note. https://app.qase.io/run/VG/dashboard/29
