### ISSUE TITLE
PDB link broken on classification page

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#160]
https://variantgrid.com/classification/classification/1735
https://www.rcsb.org/pdb/protein/P82914
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/9b4f492f-7260-4686-8403-645e9c83967c)

**Comment by TheMadBug** [comment]
@sksmi to confirm for P82914 would
https://www.rcsb.org/uniprot/P82914 be appropriate

and for P82914 would
https://www.rcsb.org/uniprot/P82914 be appropriate?

(You have to wait a second or two on those pages for the data to load)

**Comment by sksmi** [comment]
@TheMadBug Yes, think that's the new page. Another example for BRCA1 is https://www.rcsb.org/uniprot/P38398

Option also to remove the link - the new format isn't as great for what we're doing -  hard to see the sequence & access the models. Really only applicable to research & they can access via uniprot. 

Still need a link to a good protein viewer linking genomic sequence to domain e.g. protein paint or similar - ideally this would be the VG hotspot graph, but lots of work to implement & maintain so not sure if feasible.

**Comment by TheMadBug** [comment]
For now I'm just fixing the link, happy to point it to something better (internally or externally) when it comes along.

**Comment by sksmi** [comment]
Tested on a couple of gene. All good.

**Comment by EmmaTudini** [comment]
@sksmi would it be ok if we reopened this so that I have it around for my next round of testing?

**Comment by sksmi** [comment]
@EmmaTudini  done - all yours.

**Comment by EmmaTudini** [comment]
Testing:
- Logged in as non-admin 
- Went to classification test_1611789761 (has Uniprot ID assigned)
- Clicked on PDB link

Expected output: Would be taken to PDB page for Uniprot ID

Actual output: Passed
