### ISSUE TITLE
Sequencing run not complete is non obvious

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#161]
When the sample sheet changes and/or QC fail etc, whatever is stopping the run from being released needs to be more obvious

**Comment by sksmi** [comment]
Discussed 11 Jan.

**Comment by davmlaw** [comment]
Note: This is an existing issue (ie won't be made worse by upgrade)

Due to ```seqauto.grids.sequencing_data_grids.SequencingRunListGrid```

filtering incomplete as:

```
        if not user_grid_config.show_incomplete_data:
            queryset = queryset.filter(data_state=DataState.COMPLETE)
            queryset = queryset.filter(sequencingruncurrentsamplesheet__sample_sheet__illuminaflowcellqc__data_state=DataState.COMPLETE)

            read_sample_sheet_ids = SampleSheet.objects.filter(sequencingsample__fastq__data_state=DataState.COMPLETE).values_list("pk", flat=True).distinct()
            queryset = queryset.filter(sequencingruncurrentsamplesheet__sample_sheet__in=read_sample_sheet_ids)
```

Possible solution is if any of those things fail, the overall sequencing run fails?

And for each of those, make sure it's obvious on first page of view sequencing run what to do?

**Comment by davmlaw** [comment]
Removed the "show incomplete data" - just always show everything is safer I think.

Added a "ready" field which gets set as red on the sequencing run grid

Visiting the sequencing run page shows the errors you need to fix

**Comment by davmlaw** [comment]
Waiting for SA Path test to finish running annotation so I can upgrade and test this

**Comment by sksmi** [comment]
Ready column shown. False highlighted. Messaging shown on sample page.
