### ISSUE TITLE
Population filter - 'gnomAD hom alt max' filters out variants absent from gnomAD

### ISSUE THREAD

**Issue by PeerArts** [SACGF/variantgrid#164]
The gnomAD Hom alt max filter is great, but it should also show variants that are absent from gnomAD (null). In the de novo part of this analysis (https://variantgrid.com/analysis/2182/), I have separated the filtering with and without the gnomAD Hom alt as max 1. In the d-tour for the de novo analysis (right), many of the variants are absent from gnomAD, but these are filtered out as part of the gnomAD Hom alt (max 1) filter -> while in reality, they are gnomAD Hom Alt max 0. 
Only the 7 variants that are reported in gnomAD, are seen in the left part of the analysis. 

This really limits/breaks analyses because variants that are absent from gnomAD are missed. 

![image](https://user-images.githubusercontent.com/34562740/102323921-0d5f5b80-3fd1-11eb-9c29-a91919f38847.png)

**Comment by PeerArts** [comment]
Just found that we missed a diagnosis because if this issue last month. Not sure how long this bug exists.

**Comment by davmlaw** [comment]
@PeerArts apologies for this bad bug - I've made the fix to variantgrid.com

To work out the differences, the population node counts are for the old values (gnomad hom alt NULL removed) until they're saved/reconnected. Though the grids will now show gnomad hom alt NULL)

Wherever there was a population node with gnomAD hom alt max set, I've added a population node without the hom alt filter, and a filter below it showing only where gnomad hom alt is NULL. You can compare the counts in this node vs the old counts to see the number of variants affected.

You may want to select/clone all of the children of the original population nodes, then attach to this filter, then you can compare the final outputs.

Here are links to the affected analyses:

https://variantgrid.com/analysis/1462/36712
https://variantgrid.com/analysis/2140/36714
https://variantgrid.com/analysis/1587/36718
https://variantgrid.com/analysis/1442/36722
https://variantgrid.com/analysis/1554/36724
https://variantgrid.com/analysis/1557/36726
https://variantgrid.com/analysis/2028/36734
https://variantgrid.com/analysis/2074/36738
https://variantgrid.com/analysis/2039/36740
https://variantgrid.com/analysis/1881/36748
https://variantgrid.com/analysis/1459/36750
https://variantgrid.com/analysis/1621/36754
https://variantgrid.com/analysis/1123/36756
https://variantgrid.com/analysis/1875/36760
https://variantgrid.com/analysis/1197/36762
https://variantgrid.com/analysis/1356/36766
https://variantgrid.com/analysis/1976/36768
https://variantgrid.com/analysis/1877/36770
https://variantgrid.com/analysis/1087/36774
https://variantgrid.com/analysis/2182/36778
https://variantgrid.com/analysis/1457/36780
https://variantgrid.com/analysis/1552/36786
https://variantgrid.com/analysis/1883/36790
https://variantgrid.com/analysis/985/36792
https://variantgrid.com/analysis/1469/36794
https://variantgrid.com/analysis/2077/36796
https://variantgrid.com/analysis/1549/36798
https://variantgrid.com/analysis/1995/36800
https://variantgrid.com/analysis/1555/36802
https://variantgrid.com/analysis/1461/36804

**Comment by davmlaw** [comment]
Code run on production:

```
from analysis.models.nodes.node_utils import update_nodes
from analysis.models import Analysis, PopulationNode, FilterNode, FilterNodeItem


pop_node_qs = PopulationNode.objects.filter(gnomad_hom_alt_max__isnull=False)

for analysis in Analysis.objects.filter(pk__in=pop_node_qs.values_list("analysis_id", flat=True)):
    for pop_node in list(pop_node_qs.filter(analysis=analysis)):
        parent = pop_node.get_single_parent()
        pop_node2 = pop_node.save_clone()
        pop_node2.gnomad_hom_alt_max = None
        pop_node2.x += 75
        pop_node2.save()
        
        filter_node = FilterNode.objects.create(analysis=pop_node2.analysis, x=pop_node2.x, y=pop_node.y + 75, auto_node_name=False, name="gnomAD hom alt NULL")
        filter_node.filternodeitem_set.create(sort_order=1, operation='nu', field='variantannotation__gnomad_hom_alt')

        pop_node2.add_parent(parent)
        pop_node2.save()
        filter_node.add_parent(pop_node2)
        filter_node.save()

    #print(f"Analysis: {analysis.pk}")
    update_nodes(filter_node.analysis_id, run_async=False)
    print(f"https://variantgrid.com/analysis/{analysis.pk}/{filter_node.pk}")
```


Here are the original counts:

```
pop_node_qs = PopulationNode.objects.filter(gnomad_hom_alt_max__isnull=False)
for pop_node in PopulationNode.objects.filter(gnomad_hom_alt_max__isnull=False).order_by("analysis"): 
    print(f"{pop_node.analysis.pk}/{pop_node.pk}: {pop_node.count}") 
```
985/21978: 1
1087/30438: 192
1087/19592: 1039
1123/20208: 49012
1197/21557: 2294
1356/24317: 52
1356/24335: 67462
1442/26267: 4
1442/26273: 26
1457/26541: 3054
1459/26593: 2204
1461/26630: 2208
1462/26638: 18308
1469/26770: 18308
1549/28022: 23
1552/28110: 6
1552/28122: 2799
1552/28104: 10
1554/28170: 6786
1555/28177: 6693
1557/28191: 6730
1587/28571: 55
1587/28570: 49
1621/28972: 26
1621/28998: 391
1875/32097: 5
1875/32098: 3141
1877/32137: 3564
1881/32220: 36
1881/32222: 1480
1881/32223: 19
1881/32221: 2
1883/32296: 36
1883/32298: 2491
1976/33554: 2562
1995/33783: 6907
2028/34281: 0
2028/34280: 2596
2028/34278: 67
2028/34279: 0
2039/34453: 1622
2074/34846: 2033
2074/34845: 47
2077/34903: 36
2140/35760: 2663
2182/36471: 13
2182/36470: 172
```

**Comment by sksmi** [comment]
@davmlaw when did the gnomAD Hom alt go in - can't remember - just wondering if/how I missed it in testing? Also wouldn't call it a bug, as technically it works in the same way as the damage & manual filters, just not intuitive behaviour. Arguably it's up to users to understand how the filters work as there's a bunch of caveats although that's difficult without documentation. Will include x-check with documentation in test cases & make sure we fill any gaps.

**Comment by PeerArts** [comment]
Thanks for fixing this Dave! 
@sksmi, Sorry, I couldn't find the 'not intuitive behaviour' tag ;-)..

**Comment by davmlaw** [comment]
I think it's a bug, a bad false negative bug that removes what you're looking for when usung that filter.

Having nulls not do what you expect is a really common thing, I've already looked at the rest of the pop filters  but will audit the rest of the code looking for similar issues

**Comment by a1618617** [comment]
Thanks for the list of affected analyses @davmlaw, have gone through them for our project. 
Only two families were affected by this "bug", but luckily both families are part of a recent batch that hasn't been reported yet. @PeerArts outcomes below fyi, will let Luis know of the analyses affecting his projects. Cheers all

https://variantgrid.com/analysis/1462/36712 > deleted, duplicate dataset (delete Leila's dragen dataset)
https://variantgrid.com/analysis/2140/36714 > independent analysis wo homalt filter (https://variantgrid.com/analysis/2147/)
https://variantgrid.com/analysis/1587/36718 > dual analysis using SeqR
https://variantgrid.com/analysis/1442/36722 > deleted, dual analysis using SeqR (delete Leila's dragen dataset)
https://variantgrid.com/analysis/1554/36724 > Lipedema, notify Luis
https://variantgrid.com/analysis/1557/36726 > Lipedema, notify Luis
https://variantgrid.com/analysis/2028/36734 > analysis updated, candidate missed
https://variantgrid.com/analysis/2074/36738 > independent analysis wo homalt filter (https://variantgrid.com/analysis/2149/)
https://variantgrid.com/analysis/2039/36740 > analysis updated, no result changes
https://variantgrid.com/analysis/1881/36748 >  analysis updated, no result changes
https://variantgrid.com/analysis/1459/36750 >  analysis updated, no result changes
https://variantgrid.com/analysis/1621/36754 > dual analysis using SeqR
https://variantgrid.com/analysis/1123/36756 > Lipedema, notify Luis
https://variantgrid.com/analysis/1875/36760 > dual analysis using SeqR
https://variantgrid.com/analysis/1197/36762 > dual analysis using SeqR
https://variantgrid.com/analysis/1356/36766 > PED002, Peer to review 
https://variantgrid.com/analysis/1976/36768 > analysis updated, no result changes
https://variantgrid.com/analysis/1877/36770 > dual analysis using SeqR 
https://variantgrid.com/analysis/1087/36774 > analysis updated, no result changes
https://variantgrid.com/analysis/2182/36778 > analysis updated, no result changes
https://variantgrid.com/analysis/1457/36780 > analysis updated, no result changes
https://variantgrid.com/analysis/1552/36786 > independent analysis wo homalt filter (https://variantgrid.com/analysis/1328/)
https://variantgrid.com/analysis/1883/36790 > analysis updated, no result changes
https://variantgrid.com/analysis/985/36792 > AFHCS, Peer to review
https://variantgrid.com/analysis/1469/36794 > N/A
https://variantgrid.com/analysis/2077/36796 > independent analysis wo homalt filter (https://variantgrid.com/analysis/2151/)
https://variantgrid.com/analysis/1549/36798 > independent analysis wo homalt filter (https://variantgrid.com/analysis/1440/)
https://variantgrid.com/analysis/1995/36800 > dual analysis using SeqR 
https://variantgrid.com/analysis/1555/36802 > Lipedema, notify Luis
https://variantgrid.com/analysis/1461/36804 > analysis updated, no result changes

**Comment by sksmi** [comment]
Failed testing - no filtering if AF = 100%, otherwise looks good.
See pop filter testing: https://app.qase.io/run/VG/dashboard/24 for details.

**Comment by davmlaw** [comment]
Oooh, good catch.

I didn't modify "skip gnomad filtering if 100% AF" after adding gnomad hom alt max

**Comment by davmlaw** [comment]
Fix deployed on vg test

**Comment by sksmi** [comment]
Retested. Passed.
