### ISSUE TITLE
Gnomad gene constraint

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#169]
Have this in DB already, make a template tag and add to gene symbol page

Also link out to gnomAD gene page, ie https://gnomad.broadinstitute.org/gene/ENSG00000179348

**Comment by davmlaw** [comment]
For variant page - As gnomAD only gives Ensembl IDs - for RefSeq you match via gene symbol

For testing gene page - A symbol that has multiple transcript associated with it is "AQP1"

**Comment by sksmi** [comment]
**PASS**

Tested a couple of edge cases: 

NDUFA7: (GRCh37: ENSG00000167774,ENSG00000267855)
Expected 2x LOF o/e, got 1, constraint NA for ENSG00000167774

HSPA14 (GRCh37: ENSG00000187522, ENSG00000284024)
Expected 2x LOF o/e, got 1, ENSG00000284024 - gene not found in gnomAD

RP11-1055B8.7 - expected 1x LOF. Matches.

GOLGA8M - expected 2x LOF, got 1,  constraint NA for ENSG00000261480.1
