### ISSUE TITLE
Site messages not formatting correctly using --shutdown

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#171]
* Site messages aren't using the string template functionality anymore
* They always have the timestamp appended at the end which doesn't work with shutdown message

**Comment by TheMadBug** [comment]
The timestamp is appended, but using the <time> tag where JavaScript should convert it to a ticking time.

The problem appears to be that when you set the value in the future, it will still say "ago" as opposed to "from now".
Having a quick look into it.

**Comment by TheMadBug** [comment]
`python3.8 manage.py site_messages --shutdown 7`
![image](https://user-images.githubusercontent.com/2100255/103614458-920e1b80-4f78-11eb-84eb-d8138c2b6454.png)

the time ago library needs to be configured to even allow future dates `allowFuture: false` was the default.
Fixed that and also made shutdown messages of log level warning so you get an eye catching warning icon.

**Comment by davmlaw** [comment]
verified fixed on vg test
