### ISSUE TITLE
Docs - analysis nodes

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#173]
Now that we link to this page from node editors, it could be a lot better:

https://variantgrid.readthedocs.io/en/latest/analysis/nodes.html

**Comment by davmlaw** [comment]
https://variantgrid.readthedocs.io/en/latest/analysis/nodes.html

Change:

https://github.com/SACGF/variantgrid_docs/commit/c459fbf595ffd12614d3367b4a7d7f1c567d85a6

I updated the effect node (so it has splicing) and the population node editor (was outdated as we don't have ExaC etc)

**Comment by davmlaw** [comment]
@sksmi - if you want to review or add anything else (if not feel free to close and we can just review all docs at the end)

**Comment by sksmi** [comment]
Happy to review at end.
