### ISSUE TITLE
DB Workers - infinite celery.chord_unlock

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#175]
The DB workers sometimes keep recieving celery.chord_unlock and this eventually fills up the /var/log/variantgrid/db_workers.log and causes issues with no free space.

Apparently this is a known issue with the RabbitMQ backend. We decided to go with that one because Redis sometimes re-sends tasks that run for a very long time (eg VEP annotation)

Suggestions from googling say use a max_retries:

```
chord(...).apply_async(max_retries=300, interval=1)
```

Only chord for db workers is in ```schedule_pipeline_stage_steps```:

```
    if pipeline_stage == VCFPipelineStage.FINISH:
        chord_task = chord(parallel_tasks, pipeline_success_task.si(upload_pipeline_id))
        chord_task.apply_async()
```

Celery issue may be: https://github.com/celery/celery/issues/6029

**Comment by sksmi** [comment]
Bumped up, per TAU discussion.

**Comment by davmlaw** [comment]
This got particularly bad after a day of heavy use, was 299 tasks - and DB workers ended up reporitng "no workers found" and basically not responding

**Comment by davmlaw** [comment]
Changed only db_workers chord for a chain in ```upload.tasks.vcf.import_vcf_step_task.schedule_pipeline_stage_steps```

Deployed to VG3upgrade, will see in a few days after use whether this has gotten rid of the issue

**Comment by davmlaw** [comment]
Moved backend to Redis, and upgraded celery to 5

Trying on vg test will check if it re-occurs.

**Comment by davmlaw** [comment]
Haven't seen this for a long time
