### ISSUE TITLE
View gene - make transcripts in a table showing genome build

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#177]
Sarah asks to update the transcript table format to match the gene symbol table format on the gene page?

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/26ffb609-1491-4448-865d-7a5ed7673082)

**Comment by EmmaTudini** [comment]
Tested - https://app.qase.io/run/SHARIANT/dashboard/9
Note: Note: If an unknown gene ID exists, it will be shown in the transcript version table for a specific genome build but will not be shown as existing in that genome build on the view gene page.

See:
https://test.shariant.org.au/genes/view_gene/55130
https://test.shariant.org.au/genes/view_transcript_version/NM_001290020/1
