### ISSUE TITLE
Trio zygosity filters help table 

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#18]
SA Path started on a table which looks like a pretty good way to display this information:

![trio_table.png](https://images.zenhubusercontent.com/5bb45cdce135e46293defe80/72115488-7b3f-4004-bcef-f177b79b10e6)

**Comment by davmlaw** [comment]
OK, the details for the current settings of a TrioNode appear in the "doc" tab now. Need to pull them out into a table and add to help

**Comment by sksmi** [comment]
Test case: https://app.qase.io/case/VG/edit/85

@davmlaw A couple of questions about expected behaviour. Should.. 

- the parental affected status alter the zygosity filters? 
- XLR non-strict require Father:? ?
- c.het change with strict/non strict?

**Comment by sksmi** [comment]
Have added some quick notes on source nodes to readthedocs.
https://variantgrid.readthedocs.io/en/latest/analysis/nodes.html

**Comment by davmlaw** [comment]
yeah whoops forgot to clarify all the required zygosity bits

**Comment by davmlaw** [comment]
It appears Sarah has done this

**Comment by sksmi** [comment]
Still need to add & verify inheritance modes when parent(s) affected.

**Comment by sksmi** [comment]
Discussed XLR with KK last week. Debated whether it should be applied for females & when only 1 parent is het. Also requested by PA in #321. 

For future discussion only, variants currently captured in other arms of new trio workflow.

**Comment by davmlaw** [comment]
Help docs written for VG3 upgrade so lowering from high priority

In a few months will ask KK about affected parents, X-females and any other trio analyses needed and can modify for 3.1

**Comment by davmlaw** [comment]
Old documentation issue. Will handle other work is linked issues and raise if new work comes in
