### ISSUE TITLE
GeneListNode - PanelApp async API requests

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#190]
At the moment saving GeneListNode with PanelApp data takes ages as it does the API calls in the form.

Move to doing this async if possible as it's annoying

**Comment by sksmi** [comment]
ok to close? Not exactly sure how to test,  Panel App lists working well. <2mins to load 2x large ID panel app.

**Comment by davmlaw** [comment]
Previously, it did the panel app API calls when you saved the node, so if it took 2 mins, it would sit for 2 mins saving the form, so it looked like the node wasn't saving.

Now, it should submit straight away, then do the work as the node is loading.

So if the "<2mins to load 2x large ID panel app." is all happening while the node's loading (ie not during form save time) then yes, can close
