### ISSUE TITLE
Liftover - link to manually create on allele page

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#191]
Using settings: ```VARIANT_MANUAL_CREATE and VARIANT_MANUAL_CREATE_BY_NON_ADMIN```

Would be nice to be able to kick off a liftover manually from allele page for testing

**Comment by TheMadBug** [comment]
Somewhat backpeddling from a different position of mine, I would also like to add rollbar reporting that happens overnight that:
* Reports to rollbar any allele that hasn't been lifted over.
* Reports any classification that doesn't have both a 37 and 38 representation.
But have it only complain about each record once.

**Comment by davmlaw** [comment]
@TheMadBug if you still want to do your above comment, can you please raise it as a different issue?

**Comment by TheMadBug** [comment]
Raised as https://github.com/SACGF/variantgrid_private/issues/2996
Can ignore my comment within this issue now

**Comment by EmmaTudini** [comment]
@davmlaw Is this in Shariant test and if so, how do I test it?

**Comment by davmlaw** [comment]
To test go to allele page of a variant that is only in 1 genome build, eg: https://test.shariant.org.au/variantopedia/view_allele/4187

There is a button to create the variant in the build that's not lifted over.

In Shariant, almost everything has been lifted over to both builds, so you'll probably need to create a new variant for just 1 build through search (I like to copy/paste an existing HGVS then change last base to probably get a new valid one), then visit variant page, then click on Allele link

**Comment by EmmaTudini** [comment]
Ok thanks. To confirm - this is only for alleles where liftover hasn't been attempted for some reason? So https://test.shariant.org.au/variantopedia/view_allele/2204 shouldn't have a button for "create variant".

**Comment by davmlaw** [comment]
Most of the time clicking it on a failed liftover will just fail again. When we fix things so liftover will work, we'll run those through again (we did on Prod) so there won't be a need for users to re-run failed ones ever I think

**Comment by EmmaTudini** [comment]
Yes but regardless should the "create variant" button be on the allele page for 2204 (because it isn't at the moment)?

**Comment by davmlaw** [comment]
No.

The reason it isn't included is because it failed liftover before, and I don't think there's any reason to give users an opportunity to try again
