### ISSUE TITLE
Tags should automatically liftover between genome builds

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#194]

**Comment by davmlaw** [comment]
* Variant tags - top grid now works across builds
* Shows on variant details page for different builds

TODO:

* Creating a tag automatically creates liftovers
* Bottom grid on variant tags page

**Comment by sksmi** [comment]
FAIL

Tagged 2 non-lifted variants:
1x GRCh37: CA247284629
1x GRCh38: CA207045431

Variant automatically lifted over - PASS
Shown on gene symbol page - both builds - PASS
Shown on analysis - tags page - both builds - FAIL:

- bottom grid on analysis tags GRCh37 page shows GRCh38 variants (compare A1CF variant top & bottom grids, first image). 
- gene present on variant page, but missing from tagged variants page CA632868504 (second image)

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/2bf5e6e0-7f50-4c3c-9860-6136ede19de7)
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/42d088d4-e0b2-433a-bb8d-3bb1d9921d63)

Tagged 2x variants where liftover known to fail:
1x GRCh37: couldn't find a variant
1x GRCh38: CA752811242

Variant automatically lifted over - no. PASS
Shown on gene symbol page - both builds - Present on GRCh38, not GRCh37. PASS
Shown on analysis - tags page - both builds - Present on GRCh38, not GRCh37. PASS 

PASS, might be good to add a note that tags won't display if liftover fails (~2% variants)

**Comment by davmlaw** [comment]
Whoops didn't finish my TODO list from above...  will fix

**Comment by sksmi** [comment]
**PASS**

Variant now correctly annotated in grid. Closing.
