### ISSUE TITLE
Proposal to change order of classification form boxes

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#198]
Issue: I keep missing warnings because the warning box is not displayed on the page (or is at the very bottom of the page) due to the large size of the help box e.g.
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/1b761c34-0a5e-4449-bd57-cd50c188f821)

Possible solution: Switch the order of the boxes? If the help box is at the bottom it's likely you'll see at least some of the text, also missing the help box is not as critical as missing the messages or status box.

**Comment by EmmaTudini** [comment]
@sksmi I disagree - for Shariant purposes the help box is very useful. It contains both notes imported from a lab as well as a lab specific description of the ACMG criteria (e.g. some labs use modified versions of ACMG codes and we record that modification in the help box).

If anything, maybe the message box could go above the link box on the right hand side?

**Comment by davmlaw** [comment]
If there's no errors, the messages box doesn't show - so it would only ever push down the help when there's a message

In that case - isn't the message more important than the help. I agree with Sarah that the warnings should be box 2  so they're always at the top.

**Comment by EmmaTudini** [comment]
@davmlaw what is displayed in messages? No condition, no zygosity, cannot match a variant? What else?

**Comment by TheMadBug** [comment]
Missing mandatory fields (SA Path has configured a bunch more fields to be mandatory compared to Shariant) and remember we turned of the no zygosity rules for a lot of labs.
c.hgvs parsing errors (note that cannot match variant is NOT a validation message but a flag. A c.hgvs that we can't even process is a validation message).
Fields which have illegal values, e.g. if we got a value of "BLJDSF" for the Zygosity drop down - though I don't think that happens in Shariant with our mappings anyway.

So for the most part in Shariant, the only things that will have messages are records taht are "Missing Condition" and those records can't be shared, so it'll only ever be someone from the lab looking at them - in which case it's important that they see the validation errors.

**Comment by EmmaTudini** [comment]
From the Shariant perspective, messages still aren’t that important as you are auto taken to a filtered classification form in Shariant and all fields with errors have a pretty obvious “!” symbol. So the messages are just repeating what you already see on the form. 

Saying that, if it’s a massive issue for other environments, then messages can be moved up as long as it remains rare that Shariant users will see it. I’d prefer that the status box didn’t move as that’s a fixed box and I’m still of the opinion that the help box is the most important one out of the three for Shariant purposes (other than the help box, there is no other place for labs to view a lab specific description of an ACMG criteria). 

Perhaps a better long term solution would be to work on scrolling of the classification form page or a help box that has a set height and can then be expanded.

**Comment by TheMadBug** [comment]
I still would say it's not a problem for Shariant at all, as with one accidental exception that's to be fixed, the only records that aren't shared are the ones that have messages, and therfore the messages are important. As in the only people who will ever be looking at a classification form with messages are from the lab that submitted it as it wont be shared.

For the most part the help box now has a semi-fixed height (see https://github.com/SACGF/variantgrid_private/issues/2689) but fixed heights will always just push the problem back a little bit as some people will have smalelr screens.
Users have gotten very used to the ability to be able to scroll anywhere on the page - so making the help box smaller but scrollable interferes with that

**Comment by TheMadBug** [comment]
There still is the issue of the boxes go a little bit offscreen before wrapping to the next column, I'll attempt to fix that as part of this.

**Comment by EmmaTudini** [comment]
@TheMadBug Ok well what about if the box is fixed up until a certain height but can then be expanded and collapsed if the text is over that height? 

In my opinion, it would be worthwhile to implement a long term fix rather than these smaller fixes that suit the current needs.

**Comment by TheMadBug** [comment]
Will also remove "Examples" from the text box for fields that are read only - as that's only useful when providing data entry.

**Comment by sksmi** [comment]
Checked on a couple of classifications. Works well. Thanks, much clearer.
@EmmaTudini ok to close?

**Comment by EmmaTudini** [comment]
Testing:
- Logged into Shariant test as non-admin
- Went to classification page for test_1613954728 (no warning)
- Went to classification page for hg19_XR_001746343_1_TMEM38B_n_230_7A_G (two warnings)

Expected output: If no warning, messages box would not be displayed. If warning, messages box would be above help box.

Actual output: Passed
