### ISSUE TITLE
Have option for multiple bams / VCFs for sample

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#2]
*Originally reported by* **David Lawrence (Bitbucket: [davmlaw](https://bitbucket.org/davmlaw), GitHub: [davmlaw](https://github.com/davmlaw))**

----------------------------------------

Tick box - show VCF, show Hap, show recal reads

----------------------------------------
- Bitbucket: https://bitbucket.org/sacgf/variantgrid/issue/873

**Comment by davmlaw** [comment]
SA Path plan on moving to CRAM files

Perhaps instead of having sample bams we should have sample files, and then a type - that way could have BAM/BED/CRAM etc

**Comment by davmlaw** [comment]
I think just allow arbitrary types, then have user settings for each type to decide what to display.

That way, once SA Path switch over to crams, can just do a lab/global settings and switch everyone over with no new code to validate

**Comment by davmlaw** [comment]
Still TODO:

* A way to bulk set for a VCF (like we used to have, probably needs a new tab)
* Raise a new issue to do SA Path specific changes

**Comment by davmlaw** [comment]
Testing - error:

When you enter a new bam in sample page, files tab, the page submits (rather than using Ajax Form) so you end up with just that form (blank rest of page)

**Comment by davmlaw** [comment]
Had JS error affecting the document.ready calling ajax form

Also fixed up the django messages appearing, styling and form looking good after a post (deletes hang around - https://code.djangoproject.com/ticket/11476)
