### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_variant_tuple'

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#200]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2202/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2202/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/variantgrid/variantopedia/views.py", line 332, in view_allele
    link_allele_to_existing_variants(allele, AlleleConversionTool.CLINGEN_ALLELE_REGISTRY)
  File "/opt/variantgrid/snpdb/clingen_allele.py", line 340, in link_allele_to_existing_variants
    variant_tuple = allele.clingen_allele.get_variant_tuple(genome_build)
AttributeError: 'NoneType' object has no attribute 'get_variant_tuple'
```

**Comment by TheMadBug** [comment]
https://test.shariant.org.au/variantopedia/view_allele/2397 is an example that causes problems.
`variant_tuple = allele.clingen_allele.get_variant_tuple(genome_build)` is the line that fails.

Not sure if the solution is just to defensively check that the clingen_allele is present, or if anything else needs to be done.

**Comment by davmlaw** [comment]
Yes, need to do a defensive check - if you have no clingen_allele there's no point calling that function - so either do it outside the build loop or skip the function call from view_allele

The point of that call in view_allele is to see if you can link not already linked variants to the Allele.

This will only happen if variants were created separately (ie not via liftover) - it uses the clingen allele data to see what the coordinates should be. We can't do a quick check via NCBI liftover as that requires an API call

**Comment by EmmaTudini** [comment]
@davmlaw so to me, it sounds like the variants shouldn’t be exported?

**Comment by EmmaTudini** [comment]
Testing:
- Logged into Shariant test as non-admin user assigned to VCGS unit 1 (emmatudini@gmail.com)
- Went to: https://test.shariant.org.au/variantopedia/view_allele_from_variant/9287?refer=mvl&seen=2021-01-27"" target=""_blank
https://test.shariant.org.au/variantopedia/view_allele_from_variant/9290?refer=mvl&seen=2021-01-27"" target=""_blank
https://test.shariant.org.au/variantopedia/view_allele_from_variant/9292?refer=mvl&seen=2021-01-27"" target=""_blank
(all resulted in rollbar error when issue was raised)

Expected output: No rollbar errors. Allele page would be displayed.

Actual output: passed

**Comment by davmlaw** [comment]
Shariant Prod updated with this code, closing
