### ISSUE TITLE
Rapid generation of unnamed analyses

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#202]
Not a bug as far as I'm aware, but interesting use case: 
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/f10fa0d2-2a90-4046-a4ee-02b96d3028b4)

**Comment by davmlaw** [comment]
Opened analysis, analysis settings, template run tab.

Opened template it was created from:

https://variantgrid.com/analysis/1611/

The name template is harcoded as "None" - think this is luser error

**Comment by sksmi** [comment]
yeah that was the first template we made - think we crashed vg bca it lacked a name so you added the none option.  Cool will close, guessing  lots of these samples are from the mega vcf - will see how it goes.
