### ISSUE TITLE
Annotation page - what needs to be done

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#203]
With the original page, if something wasn't loaded, the component that needed to be installed had the instructions shown.

Now, it's much harder to see what needs to be done.

Maybe tThe components that aren't loaded should be red - or have a message, or have those instructions auto-toggled?

**Comment by davmlaw** [comment]
Thought I'd need this for SA path upgrade

**Comment by sksmi** [comment]
@davmlaw not sure what to test here - will leave for you to review & close. 

All the toggles/links work and the information appears appropriate.
Numbers for datasets look approximately correct. 
Ran an update of Aus Panel App - loading and imported messaging look good.

**Comment by davmlaw** [comment]
Yeah admin-only... good enough!
