### ISSUE TITLE
NodeCount node_version/label already exists

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#204]
Occurs at analysis_node.py line 678:

```
        node_version = NodeVersion.get(self)
        for label, count in label_counts.items():
            NodeCount.objects.create(node_version=node_version,
                                     label=label,
                                     count=count)
```

Some kind of race condition....

![image.png](https://images.zenhubusercontent.com/5bb45cdce135e46293defe80/9737c251-2cb4-483a-b268-399c70194a8e)

**Comment by davmlaw** [comment]
In dupe issue SKS says she saw it when:

* When I copied a row of nodes in templates
* When I copied a node in an analysis
* When I added an additional filter condition to an existing manual filter

**Comment by davmlaw** [comment]
It would be easy enough to do a get_or_create and ignore this but want to know why it's happening....

I spent a few minutes cloning nodes to try and reproduce this and found you can reproduce it 100% of the time:

* Clone a node (works fine)
* Clone the new cloned node (errors)

**Comment by davmlaw** [comment]
OK, the problem was we tried to save an SQL query by copying NodeCount when you cloned a node, then when it came time to load the node, NodeCount was already there.

This was doubly bad as it did the query anyway, then died trying to store it (so we didn't even save the SQL query)

When loading node counts, we check and see if we can retrieve them from cache in ```_get_cached_label_count``` - so, the change is:

* When cloning a node, store the node/version of what you cloned in "cloned_from"
* In ```_get_cached_label_count``` - if you have "cloned_from" set - return the counts from that
* cloned_from is cleared upon either the original or the clone changing

**Comment by sksmi** [comment]
**PASS**

**Comment by sksmi** [comment]
IntegrityError: duplicate key value violates unique constraint

Still occurring when trying to load sample node grid. Saw in this analysis, but now fixed. Will post if I see it again. http://frgeneseq02.imvs.sa.gov.au:92/analysis/9086/

**Comment by davmlaw** [comment]
SKS reports this is still happening:

![](https://camo.githubusercontent.com/94f9d89e16bd69f69c77922864ada4103bab4c1966efe1ec9f86396398735187/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3562633534363530383666336136373864343937633062652f66353436323532372d356462342d346337662d383038322d663265623166656533613235)

**Comment by davmlaw** [comment]
This is the same issue as #227 VennNode error with empty grandparents

OK can recreate the cache being kicked off multiple times by:

* Create a venn node
* Create a merge node beneath venn node
* Trigger reload - causing venn/merge to start loading
* Before venn has started, connect/disconnect something else to merge

This causes ```get_analysis_update_tasks``` to run twice (because we're just setting analysis_update_uuid not requiring it to be blank ie using it as a lock) and running multiple celery jobs causes:

* NodeCount error
* deadlock detected - DETAIL:  Process 50724 waits for AccessShareLock on relation 561171 of database 16384; blocked by process 50698. Process 50698 waits for AccessExclusiveLock on relation 561153 of database 16384; blocked by process 50724.
* {vennode_cache.variant_collection.get_status_display()}") Type: , Value: A: (31648 (v3)), B: (31653 (v1)): INTERSECTION had status: Created

Even if we were able to get locks at the node level, that's not good enough, as we need to build a dependency graph.....

So I think the scheduling needs to go through ```scheduling_single_worker``` queue

Scheduling job should:

* Generate a UUID (as per analysis_update_uuid)
* Create records with in a table that enforces unique together node/version and also has analysis_update_uuid, celery task
* Bulk create them (with ignore conflict = True)
* Re-fetch out whatever you created with your analysis_update_uuid (this means you got a lock on it)
* Create graph and execute the jobs

**Comment by davmlaw** [comment]
ok hopefully that's the last of these annoying errors, please test adding/reconnecting nodes like crazy while they're loading....

**Comment by davmlaw** [comment]
Seems much more stable, however Using usual trick, can still end up with this:

```
Internal Error: Traceback (most recent call last): File "/data/variantgrid/analysis/tasks/node_update_tasks.py", line 45, in update_node_task node.load()
File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 727, in load status, count = self.node_counts()
File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 709, in node_counts retrieved_label_counts = get_node_counts_and_labels_dict(self)
File "/data/variantgrid/analysis/models/nodes/node_counts.py", line 111, in get_node_counts_and_labels_dict qs = node.get_queryset(inner_query_distinct=True)
File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 408, in get_queryset qs = self._get_unfiltered_queryset(**extra_annotation_kwargs)
File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 396, in _get_unfiltered_queryset a_kwargs = self.get_annotation_kwargs()
File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 289, in get_annotation_kwargs for parent in self.get_non_empty_parents():
File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 240, in get_non_empty_parents raise NodeParentNotReadyException(f"Parent {p} is not ready!") analysis.exceptions.NodeParentNotReadyException: Parent is not ready! 
```

**Comment by sksmi** [comment]
Downgrade?

**Comment by sksmi** [comment]
Closing, not seen in updated environments.
