### ISSUE TITLE
Incorrect variants displayed in tagged variants grid on gene symbol page

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#211]
e.g. PIK3R1
http://144.6.229.160/genes/view_gene_symbol/PIK3R1
seems to be showing top grid from tagged variants page (http://144.6.229.160/analysis/analyses_variant_tags/), rather than filtering it per gene. 

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/d7479a2a-e8b5-4f6f-a1d4-02867595f557)

Thinking this grid can be removed now that tagged variants are shown in the variants grid underneath (while you're there, is it also possible to remove the tags column from the variants grid as it will always be empty?)

**Comment by davmlaw** [comment]
Plan is to remove this, see #138 - Gene Symbol page - remove top tagged variants grid

**Comment by sksmi** [comment]
Is that planned pre-upgrade (I'm assuming it's a quick delete)?

**Comment by davmlaw** [comment]
Just added it then. I agree it needs to go

**Comment by davmlaw** [comment]
Will fix in other issue
