### ISSUE TITLE
User timezones

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#214]
![timezone.png](https://images.zenhubusercontent.com/5bb45cdce135e46293defe80/90c3c86a-83bc-489c-b4cb-607f77fad10b)

At the moment we display most dates using server time.

The Django way to do it is store user timezone then do this every view:

```
timezone.activate('aus/EST')
```

Though there is probably some middleware to do this automatically given a way to look it up?

We could make it a user setting, which could be configured per lab (would catch 95% of people) then travellers could change it in user settings

Other option is to use a template tag ```{% timestamp date %}``` which does things in Javascript - works for the user’s timezone without extra data entry, puts it in a proper time tag, gives you a hover over tip with full details.

**Comment by TheMadBug** [comment]
Damn it, you made me miss the era of arcades with that graphic!

**Comment by davmlaw** [comment]
This has been handled in other issue:

https://github.com/SACGF/variantgrid_private/issues/3391
