### ISSUE TITLE
VG not showing gnomADV3.1 count

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#220]
**Describe the bug**
gnomAD freq of 11:72139110 CTA>C is 0.8.
In VG: "no gnomAD entry' 

**To Reproduce**
Variant:  http://144.6.229.160/variantopedia/view_variant/247104198
gnomAD: https://gnomad.broadinstitute.org/variant/11-72139110-CTA-C?dataset=gnomad_r3

**Other**
Wondering if due to gnomAD VG3.1 patch? Have previously noted gnomAD error message re. VEP annotation, msg still present on website:

 _Warning: We have identified an issue in gnomAD v3.1 where some variants are missing VEP annotations. As a result, some variants in the table below may be missing consequences. We are working on a resolution for this issue._

e.g. https://gnomad.broadinstitute.org/region/12-132148870-132148910?dataset=gnomad_r3

**Comment by sksmi** [comment]
Also: http://144.6.229.160/variantopedia/view_variant/248138677

**Comment by davmlaw** [comment]
We are using gnomAD2 the issue to upgrade to 3 is here:

https://github.com/SACGF/variantgrid_private/issues/2042
