### ISSUE TITLE
gnomAD link broken on analysis grid

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#223]
This was probably due to ref/alt changing

Make sure it goes to the right version (ie gnomad2/3 etc)

**Comment by davmlaw** [comment]
There is also a link to gnomAD on the variant details page

TODO: 

Didn't deal with genome version on analysis grid

**Comment by sksmi** [comment]
**PASS**

Tested GRCh37 1x variant:
- analysis node
- variant page (top & bottom links)

Tested GRCh38 1x variant: 
- analysis node
- variant page 


@davmlaw note that the link on the bottom of the GRCh37 page doesn't include the suffix ?dataset=gnomad_r2_1

**Comment by davmlaw** [comment]
That's the default but just in case it changes, added dataset for 37 as well
