### ISSUE TITLE
Minor HGVS nomenclature inconsistencies

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#224]
Not a bug, but recording for discussion. 

There are a number of formatting differences between variant sources that result in minor HGVS inconsistencies. Examples illustrated below (GRCh38). Variant validator is the first source I've seen that seems to produce the correct HGVS (have only tested briefly).

CA3969272
CA4962912
CA7294278
CA1139767829

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/32edb8b8-4d08-46ea-b9ea-3a435b06ef15)

Low priority issue - nomenclature issues like this are currently manually checked & fixed by curators.

**Comment by davmlaw** [comment]
For the del/dup issue - 

For bases at the end of a dup, it is only a recommendation not part of the spec:

https://varnomen.hgvs.org/recommendations/DNA/variant/duplication/

```
NOTE: the recommendation is not to describe the variant as c.20_23dupTAGA, i.e. describe the duplicated nucleotide sequence. This description is longer, it contains redundant information and chances to make an error increases (e.g. c.20_23dupTGGA).
```

And while they claim it's redundant, it's only redundant if you include the genome build and patch version used, which HGVS doesn't do.

**Comment by sksmi** [comment]
'Correct' result is shown in variant validator lines. Not enough time to review full guidelines at the moment, but can do if/when issue is in progress.

**Comment by davmlaw** [comment]
Even if it's not a spec violation but just personal preference / consistency I think it's worth being able to set them per system (but needs to be config sometimes as eg Shariant/VariantGrid probably disagree)

There is also another issue similar to this - Normalize imported p. - https://github.com/SACGF/variantgrid_private/issues/2703

**Comment by davmlaw** [comment]
We get nothing for these 2 in our PyHGVS library, should be error for first and good for second:

NM_007294.3:c.5094_5096insACG - 5326 and 5328 are not consecutive positions.
NM_007294.3:c.5095_5096insACG - OK

**Comment by davmlaw** [comment]
This is now obsolete after having switched from PyHGVS to BioCommons HGVS
