### ISSUE TITLE
'All columns' doesn't contain all columns

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#225]
All columns set might need an update/rename at some stage - the default all columns looks like this:

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/b0946fc9-b949-427f-95cc-0d4a2bfb5df9)

**Comment by davmlaw** [comment]
Yeah, I was almost going to add columns then realised I'd have to pick an order and gave up.

Plan for SA Path is for Karin to make her columns then set them for everyone. So this can wait a bit

**Comment by davmlaw** [comment]
tested on variantgrid.com
