### ISSUE TITLE
Genome build not specified on analysis templates grid

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#228]
http://144.6.229.160/analysis/analysis_templates/

Would be useful to see genome builds for templates. 

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/45d6f4f1-f017-4b17-9822-50c32eaddfda)

**Comment by davmlaw** [comment]
You can create a template in 37 and run it with 38 data.

After populating the data, it runs a check to make sure that all nodes are all on the same build and dies if there's any problem.

This would happen if you eg hardcoded a sample in there (that wasn't a template variable) but in general you should try and make them build independent. I guess I should add this explainer to the docs / help guide etc

**Comment by sksmi** [comment]
Closing. Looks like you've already done it - just that I haven't read the docs & saw that build was locked down in the template so assumed it was build-specific.  Made some updates to readthedocs analysis templates.
