### ISSUE TITLE
Condition matching

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#238]
http://144.6.229.160/classification/condition_matchings
Can we add help to condition matching or hide the page until help is available? Not sure this is required for VG at this stage and without documentation will be confusing for users.

**Comment by TheMadBug** [comment]
Yes, it shouldn't have been enabled in the first place.
I'll disable it for non-Shariant environments.

**Comment by TheMadBug** [comment]
Should have been disabled for non-Shariant environments for a few deploys by now hopefully.
