### ISSUE TITLE
Capturing genes in child relationships of ontology terms

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#241]
Example: would like to assess patient with X syndrome.  Would like to filter to all genes known to be associated with X syndrome. However, current phenotype matching only matches selected subset of X genes.  Is there a way to capture all genes related to a phenotype? 

**example**
Enter noonan syndrome as patient phenotype. Current ontology matching produces:  OMIM:163950 NOONAN SYNDROME 1 (PTPN11, BRAF, MAP2K1) which is correct for NS1, but is only a subset of all noonan syndrome. 

MONDO mapping is better:  MONDO_0018997 (Noonan syndrome) (RIT1, LZTR1, RAF1, NRAS, SOS2, BRAF, KRAS, SOS1)
http://144.6.229.160/ontology/term/MONDO_0018997  

However, even MONDO term misses well known genes, e.g. misses terms from MONDO_0008104 Noonan Syndrome 1 even though this is a child of MONDO_0018997 (Noonan syndrome).

**other resources**
ClinGen has a good summary of Noonan assoc. genes for cross-reference: https://search.clinicalgenome.org/kb/conditions/MONDO:0018997

**Comment by EmmaTudini** [comment]
I'd suggest GenCC for a better cross reference. Has all of ClinGen and a bunch of other contributors. See: https://search.thegencc.org/

**Comment by sksmi** [comment]
great resource! tx.

**Comment by TheMadBug** [comment]
For the example given GenCC does fill in the gaps

MONDO_0018997
![image.png](https://images.zenhubusercontent.com/5b9734f72df36e0aa911d89d/1f9dec68-14de-4ba7-ad9d-ebdb6fb3f795)
Specifically PTPN1 is there now.

Dave is currently uploading the ontology on vg.test so the data should be reflected there in the next few hours.

**Comment by davmlaw** [comment]
@TheMadBug - What needs to be done on this?

**Comment by TheMadBug** [comment]
@davmlaw (apologies for late month old reply).
Nothing needs to be done on this, except keeping the annotations up to date.
Instructions on how to load the gencc database are on the annotations page, and otherwise this is automatically used as a source of gene to disease relationships.
