### ISSUE TITLE
Difficult to search for gene in gene dropdown

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#243]
For gene symbol searches in the dropdown fields (e.g. patients page, gene annotation grid) it's not clear how the search is working. 

**to reproduce**
Search in field using gene symbol
Dropdown shows ENSG/RefSeq IDs, not sure what gene these are related to.
Try searching with IDs, no result found

Search is actually working fine based on gene symbol. Is it possible to add the gene symbol to the text shown in the dropdown? 

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/0aa95ff9-441e-4f6f-aa5f-4e8cffeba5a5)

**Comment by davmlaw** [comment]
Also fixed issue:

* Gene dropdown in edit patient (remove dashes, use gene symbol not gene)
* Remove prefix in tooltip

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/323b6f7e-8215-48a2-a2f2-1e4306a2c9ec)

**Comment by sksmi** [comment]
*FAIL**

Tested:
Gene dropdown patient grid /patients/patients **PASS**
- Gene search & associated filter works.

Gene dropdown patient page /patients/view_patient/1292 **PASS*
- Gene search & addition to phenotype box works (can't check assoc. ENSG ID)
- Tooltip prefix removed


Gene dropdown gene annotation grid /genes/genes **FAIL**
- Gene search still in gene ID, not gene symbol fomat

**Comment by davmlaw** [comment]
Replaced gene w/gene symbol form on gene annotaiton page

**Comment by sksmi** [comment]
**PASS**

Re-tested on all 3 dropdowns. Gene displayed & selected correctly. Closing.
