### ISSUE TITLE
RVIS is outdated

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#244]
**minor**

**Is your feature request related to a problem? Please describe.**
RVIS is now quite outdated and has been replaced by gnomAD lof. Current RVIS data doesn't match historical data. Looks correct when comparing to source file, but am unsure of reason for difference.

**Describe the solution you'd like**
Removal of RVIS data from database. 

**Describe alternatives you've considered**
Leave data in - not a great option as extra columns to maintain and test, potential for curators to use outdated RVIS instead of gnomAD.

**Comment by davmlaw** [comment]
The original source of data was the supplimentary file "journal.pgen.1003709.s002.xlsx" described as "The Residual Variation Intolerance Score (RVIS) and corresponding RVIS percentile for the full set of 16,956 CCDS assessed genes." from this paper:

https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1003709

This paper is from 2013 and skimming the paper it appears the data is from the NHLBI Exome Sequencing Project (ESP) with 6503 whole exome sequences

What I downloaded was RVIS from ExaC (60k individuals) which explains the difference.

**Comment by davmlaw** [comment]
Removed RVIS

**Comment by sksmi** [comment]
Checked:
- RVIS column removed from custom columns option
- Analyses previously using RVIS column now lack RVIS column, but still run: http://144.6.229.160/analysis/1920/

@TheMadBug are there any potential repercussions for classifications? If not, I think this can be closed.

**Comment by TheMadBug** [comment]
Can't find any trace of RVIS in classiifcaitons.
Closing.
