### ISSUE TITLE
Uncaught TypeError: errorMessage.startsWith is not a function

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#246]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2305/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2305/)

```

TypeError: errorMessage.startsWith is not a function
  File "(unknown)", line 8, in on_error_function
  File "http://144.6.229.160/static/js/grid.7bc293d4ab2e.js", line 586, in Object.success
  File "http://144.6.229.160/static/js/lib/jquery-3.3.1/jquery-3.3.1.min.a09e13ee94d5.js", line 2, in u
  File "http://144.6.229.160/static/js/lib/jquery-3.3.1/jquery-3.3.1.min.a09e13ee94d5.js", line 2, in Object.fireWith [as resolveWith]
  File "http://144.6.229.160/static/js/lib/jquery-3.3.1/jquery-3.3.1.min.a09e13ee94d5.js", line 2, in k
  File "http://144.6.229.160/static/js/lib/jquery-3.3.1/jquery-3.3.1.min.a09e13ee94d5.js", line 2, in XMLHttpRequest.<anonymous>
```

**Comment by davmlaw** [comment]
Can recreate via:

* Get some nodes working
* Change analysis settings annotation version to something that will cause an error, save
* Click on a node

**Comment by davmlaw** [comment]
If you change analysis settings annotation version, we now reload the analysis - this was the right thing to do and removes the issue about being out of sync.

**Comment by sksmi** [comment]
Assuming this fix was part of the deploy? Still seeing error: http://144.6.229.160/analysis/1736/
- opened analysis
- clicked on a node > error

**Comment by davmlaw** [comment]
It shouldn't happen going forward (as we reload nodes if analysis annotation verstion changes), but for existing errors you'll have to force reload nodes manually to get rid of ability to get this error

**Comment by sksmi** [comment]
Tested on http://144.6.229.160/analysis/1786/
Force reload prevented error. Closing, will re-open if error seen again.

**Comment by sksmi** [comment]
Think this is still happening in a new analysis: http://frgeneseq02.imvs.sa.gov.au:90/analysis/5248/
(not 100% if I made it pre/post deploy, but pretty sure I've force reloaded).  No action required yet, doing lots of testing so if an issue will pop up again.

**Comment by sksmi** [comment]
Definitely still an issue. Cloned & force reloaded analysis above. Still happening.
http://frgeneseq02.imvs.sa.gov.au:90/analysis/5251/

**Comment by davmlaw** [comment]
Yeah can recreate by cloning a filternode and then clicking on it (while it's not attached to parents)

**Comment by davmlaw** [comment]
@sksmi fixed and upgraded VG test and SA Path test

**Comment by sksmi** [comment]
Error removed with force reload. Closing, will reopen if continues to occur.
