### ISSUE TITLE
User gene list not displayed in grid after re-selecting gene list

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#248]
**Description**
Gene list not displayed in grid after switching between lists in same category. 

Minor - solved with page refresh & unlikely use case, not sure this is a bug.

**To Reproduce**
Load user gene list sirt2 - list loads
Load  user gene list test - list loads
Load user gene list sirt2 - list removed
Load user gene list sirt2 - list not added
Refresh page - both lists displayed
Only seems to occur with user gene lists.

**Expected behaviour**
Re-selecting a user gene list that is already displayed in the grid has no impact i.e. list not removed from grid. This aligns with the behaviour of other categories of gene lists.

**Comment by davmlaw** [comment]
In the reproduction steps - are you saving the node at any point?

>> Re-selecting a user gene list that is already displayed in the grid has no impact i.e. list not removed from grid. This aligns with the behaviour of other categories of gene lists. 

This is built into the library we use - all multi-select autocompletes remove an already selected item if you select it again. Eg just tried it out with panel app panels on the gene list node.
