### ISSUE TITLE
ValueError: Cannot find HGNC for MARS1

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#251]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2227/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2227/)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/genes/views.py", line 119, in _get_omim_and_hpo_for_gene_symbol
    'for omim in OntologySnake.terms_for_gene_symbol...OMIM, max_depth=0).leafs():  # direct links only'
  File "/mnt/variantgrid/ontology/models/models_ontology.py", line 424, in terms_for_gene_symbol
    gene_ontology = OntologyTerm.get_gene_symbol(gene_symbol)
  File "/mnt/variantgrid/ontology/models/models_ontology.py", line 210, in get_gene_symbol
    raise ValueError(f"Cannot find HGNC for {gene_symbol}")
ValueError: Cannot find HGNC for AF196779.12
```

**Comment by davmlaw** [comment]
Search for eg "AF196779.12", go to gene symbol page and this happens.

It's not a bug - ok to not be found but should check or be quiet about it rather than report via rollbar

**Comment by TheMadBug** [comment]
The thing is if you go to the MARS1 gene symbol page, in the HGNC section it knows that it's HGNC:6898
Actually if you search for HGNC:6898 it knows it's the value for MARS - but doesn't have the MARS1 alias there.

If I do the same in Shariant Test it has MARS1 listed as an alias
https://test.shariant.org.au/ontology/term/HGNC_6898

The code of
```
        hgnc_matcher = HGNCMatcher.instance()
        if hgnc := hgnc_matcher.match_hgnc(gene_symbol):
            if hgnc_term := OntologyTerm.objects.filter(ontology_service=OntologyService.HGNC, index=hgnc.id).first():
```
probably needs to be enhanced to also look at the HGNC table. Timing of which symbols were requested probably caused this to work in one environment and not the other.

And I should improve OntologyImport sync_hgnc to handle aliases.

**Comment by davmlaw** [comment]
Or I call ```sync_hgnc``` every time HGNC gets updated?

**Comment by TheMadBug** [comment]
sync_hgnc attempts to bulk part of what get_gene_symbol lazily does (just for a bit of increased efficiency).

But it doesn't have proper support for settings aliases... yet.
So it will be good practise to run `sync_hgnc` when HGNC gets updated, but also need to code that alias support in.

**Comment by TheMadBug** [comment]
MARS1 has existed in Shariant and Shariant Test since at least Feb.
