### ISSUE TITLE
AnalysisNode not auto-loading grid once ready

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#252]
Save a node, and don't click off it. It'll never auto-load the grid/editor when ready, but just sit there.

If you click off then back again, it'll load instantly.

**Comment by sksmi** [comment]
@davmlaw upvoting, have to refresh almost every time to see the analysis grid.

**Comment by davmlaw** [comment]
This was due to a string/int equality check on whether to load the node or not - so it never loaded

**Comment by sksmi** [comment]
**PASS**

Env. SAP Test. So much better, loading quickly. Closing, but will keep watch for reoccurrence.
