### ISSUE TITLE
 AttributeError: 'NoneType' 

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#260]
Bunch of errors viewing variant (clicked on ClinVar link) http://frgeneseq02.imvs.sa.gov.au:90/variantopedia/view_variant/650047 
Had updated annotation in http://frgeneseq02.imvs.sa.gov.au:90/analysis/5135/ a couple of minutes previously.

#2334 AttributeError: 'NoneType' object has no attribute 'gene_annotation_release'
#2335 AttributeError: 'NoneType' object has no attribute 'replace'
[#2056 Annotation pipeline run 1098]
#2057 OSError: [Errno 30] Read-only file system: '/tau/references/VariantGrid/annotation_dump'

Logging as not sure of importance.

**Comment by davmlaw** [comment]
Find an analysis where we're missing variant_annotation_version, eg:

http://frgeneseq02.imvs.sa.gov.au:90/analysis/978/

Add  a pheno node, add hpo then click save:

```
File /data/variantgrid/analysis/models/nodes/analysis_node.py line 746 in save args locals
self.name = self.get_node_name()
File /data/variantgrid/analysis/models/nodes/filters/phenotype_node.py line 170 in get_node_name args locals
num_genes = self.get_gene_qs().count()
File /data/variantgrid/analysis/models/nodes/filters/phenotype_node.py line 89 in get_gene_qs args locals
return self.analysis.gene_annotation_release.genes_for_symbols(gene_symbols_qs)
```

**Comment by davmlaw** [comment]
I think these have been fixed, can't recreate them anyhow
