### ISSUE TITLE
Accordion title missing for Pathology Test

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#261]
Env. VG test (not SAP test)

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/9e5bbfe3-7452-4d26-8a0b-8a0db3816b3a)

**Comment by davmlaw** [comment]
Pathology tests shouldn't have been enabled in VG test

**Comment by sksmi** [comment]
Fixed. Closing.
