### ISSUE TITLE
Incorrect SpliceAI score displayed for variant

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#269]
http://144.6.229.160/variantopedia/view_variant/259636852

Score in VG is for AL645608 not SAMD11. Probably complicated by gene changes (see second image for a re-run with gencode v36 - image truncated, but only SAMD11 transcripts returned, all same output). Not sure of importance as difficult to assess how often a locus will generate different scores for transcripts/genes without looking at the SpliceAI files. 

https://spliceailookup.broadinstitute.org/#variant=1%3A930130%3AC%3AG&hg=38&distance=50&mask=1&precomputed=1

Using Illumina Pre-computed scores:
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/e19255a9-f577-4ad6-84d8-de97ec8c9c0b)

Fresh run on gencode V36:
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/88698c97-37d6-4e5b-8896-21cd9dbd9a48)

**Comment by davmlaw** [comment]
spliceai_scores.raw.snv.hg38.vcf.gz:

```
1	930130	.	C	A	.	.	SpliceAI=A|AL645608.1|0.00|0.00|0.02|0.11|-20|1|-20|1
1	930130	.	C	A	.	.	SpliceAI=A|SAMD11|0.01|0.00|0.00|0.00|25|44|2|25
1	930130	.	C	G	.	.	SpliceAI=G|AL645608.1|0.00|0.00|0.04|0.11|-20|1|-20|1
1	930130	.	C	G	.	.	SpliceAI=G|SAMD11|0.68|0.02|0.00|0.00|1|25|1|44
1	930130	.	C	T	.	.	SpliceAI=T|AL645608.1|0.00|0.00|0.04|0.11|-20|1|-20|1
1	930130	.	C	T	.	.	SpliceAI=T|SAMD11|0.00|0.00|0.00|0.00|25|-47|44|25
```

Our VEP annotation has the following for all transcripts - last column is "SpliceAI_pred_SYMBOL=SpliceAI gene symbol"

```
|-20|1|-20|1|0.00|0.00|0.04|0.11|AL645608.1|
```

So basically it's not choosing the right one based on gene. Will look into how the VEP plugin works. Our command line is:

```
-plugin SpliceAI,snv=/data/annotation/VEP/annotation_data/GRCh38/spliceai_scores.raw.snv.hg38.vcf.gz,indel=/data/annotation/VEP/annotation_data/GRCh38/spliceai_scores.raw.indel.hg38.vcf.gz
```

**Comment by davmlaw** [comment]
Raised issue with VEP plugins here: https://github.com/Ensembl/VEP_plugins/issues/393

Unfortunately not much else I can do other than rewrite Perl plugin

**Comment by davmlaw** [comment]
As a quick fix, can add the gene SpliceAI is using - and perhaps a link to the SpliceAI site so can at least know why it's wrong, see  #273

**Comment by davmlaw** [comment]
VEP fixed this:

> our new release 104 is out. The SpliceAI plugin now contains the comparison by gene symbol and only attaches the scores if the symbols match.

**Comment by sksmi** [comment]
Agreed at dev meeting that this can wait for VG4.

**Comment by davmlaw** [comment]
Stopgap measure is in, issue will be fixed next VEP version upgrade
