### ISSUE TITLE
VCF Allele Frequency

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#271]
We currently split multi-alleles and normalize VCFs with VT, then calculate the AF by adding up depths for all loci.

If a multi-allele is split and one is normalized to a different locus, then the two alleles are no longer linked and calculated together.

I think the variant caller is probably doing is deliberately not normalizing things because it wants to keep haplotypes together on the same locus, even if the representation isn't right?

So - I think a good compromise is that if a VCF comes in with an AF, I just use that. If it doesn't have one, I calculate my own

So I'll just rely on the VCF to define correct AF

Need to store whether it was us that calculated AF or was in the VCF (legacy will be our calcs)

**Comment by davmlaw** [comment]
Had to do a migration on VCF, so while there added fields:

```
allele_frequency_field = models.TextField(null=True)
allele_frequency_source = models.CharField(max_length=1, choices=AlleleFrequencySource.choices, default=AlleleFrequencySource.CALCULATED)
```

Still need to hook them in etc

**Comment by davmlaw** [comment]
Do a double-check first that running a FreeBayes VCF through VT splits the AF up properly between multi-alts

**Comment by davmlaw** [comment]
Also need to store "./." - new FreeBayes writes them out as this. There's a example VCF on vg.com from Frank

**Comment by davmlaw** [comment]
Frank asks to also display the FT tag. Our Vardict VCF files  have that tag. They look like this:

```
##FORMAT=<ID=FT,Number=.,Type=String,Description="Sample-level filter">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  6_9_4400004_EOT_DNApanel
chr21   34792684        .       AG      A       83      HmplymLowFreqIndel      .     GT:DP:VD:AD:AF:RD:ALD:FT        0/1:1156:5:1150,5:0.0043:113,1037:0,5:HmplymLowFreqIndel
chr21   34792744        .       T       C       270     PASS    .       GT:DP:VD:AD:AF:RD:ALD:FT        0/1:733:333:396,333:0.4543:9,387:9,324:PASS
chr21   43094393        .       A       AT      151     Q25;HmplymLowFreqIndel  .     GT:DP:VD:AD:AF:RD:ALD:FT        0/1:889:26:796,26:0.0292:695,101:23,3:Q25;HmplymLowFreqIndel
```

**Comment by davmlaw** [comment]
Working on vcf_allele_frequency branch

TODO:
* Allele frequency - check if VCF has “AF” if so, set allele_frequency_source and vcf.allele_frequency_field
* Modify code that grabs infos  finished_locu so that it reads values 
* Deal with sample level filters (uses same as normal filters) - Frank has test VarDict VCF in slack

Once done, upgrade VG test and inform W and Sarah

**Comment by davmlaw** [comment]
Asked Frank to replace escaped double quotes with single quotes in the FILTER lines?
I get from the pyVCF library:

```
SyntaxError: One of the FILTER lines is malformed: ##FILTER=<ID=LowFreqBias,Description="Set if true: INFO/AF < 0.02 && ((INFO/TYPE != \"Complex\" && NM >= 2.5) || SN < 4)">
```

I wondered whether this is against the spec - VCF validator passes the file, reading the VCF spec - http://samtools.github.io/hts-specs/VCFv4.2.pdf - says for INFO fields that “Double-quote character can be escapedwith backslash \ “ however it does not mention escaping in the FILTER section right below it.

**Comment by davmlaw** [comment]
Changes are:

* If VCF has "AF" - we use that instead of calculating it ourselves
* view vcf page, "VCF Info" tab - shows whether we read it or calculated it ourselves
* We now read every VCF record, even if there's no zygosity calls against any samples

I also did the VarDict sample filters stuff, but have left some of that work as doing the AF testing / validation is more important

**Comment by sksmi** [comment]
@davmlaw can you confirm that the text below indicates data has been read from vcf? I'm assuming that the AF calc details are displayed if you've re-calculated. 
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/b0c3d69e-6cf6-4d76-85e7-fe2e70639716)

**Comment by davmlaw** [comment]
Yep, that's read from the AF format field, the ones that have no AF field or legacy ones look like:

![AF_calculation](https://user-images.githubusercontent.com/763201/112244863-cbb11180-8c9f-11eb-8c3b-4989a7f5f4ba.png)

**Comment by sksmi** [comment]
Confirming that imported AF functioning. e.g. http://144.6.229.160/analysis/2008/
However, new vardict vcfs  have AF 0-1 rather than 0-100, which is incompatible with AF filter 

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/9010fed3-3dcb-4d0d-895e-178b3c1f9214)

**Comment by davmlaw** [comment]
@sksmi opinions on fix?

I think we should move to all AF being from 0-1, but that requires informing users of the change (we are alreadying shifting to 0-1 for gnomAD vs VG2)

The alternative would be having a user preference I guess, but it could be confusing.

It would take too much time to re-calculate everything, so I think just attach something to the VCF saying whether it was calculated as a percent or not, then if it's a percent and you're displaying as 0-1 then divide by 100

**Comment by sksmi** [comment]
I've sent a slack message requesting user feedback, will post an update in the next hour or so if there's any comments. 

My personal pref. is % because I process it a lot better than decimals, but 0-1 is fine.

**Comment by davmlaw** [comment]
A preference would be pretty easy - and it would allow people to not have to change current habits

**Comment by sksmi** [comment]
Might be easy, but likely confusing. I'd vote we go with one or the other for the time-being (not just because I don't want to add extra testing :) ). I've definitely been caught out on the gnomad AF a few times now because I can never remember whether it's % or not - pretty bad when you're out by 100x.

**Comment by sksmi** [comment]
No major comments from the user team. Should be fine to go ahead with change to frequency (0-1).

**Comment by davmlaw** [comment]
Ok, everything should look like it's 0-1 now, legacy data is labelled as percent and does conversions behind the scenes

Some things to test:

* Loading old AF filters and making sure they're converted correctly
* AF filters for sample/trio/cohort (legacy and new AF from VCF)
* Grids always show as 0-1, export as CSV and VCF
* View samples for varinat on variant details page

Note: have not migrated legacy Classifications - this will be done in #320 - after consulting w/Shariant crew

**Comment by sksmi** [comment]
Has this been fully deployed? Not quite there yet..

:90/variantopedia/view_variant/31339689

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/9a9054fe-07ef-4b53-81aa-c58deb24ea8a)

**Comment by davmlaw** [comment]
Whoops... I use "-1" as my "NO DATA" value, instead I converted it from percent to unit which then made it show

Fixed so it'll go back to being "." again

**Comment by sksmi** [comment]
@davmlaw is it possible to add an extra decimal place to the AF filters? e.g. Would be really useful for to filter for AF > 0.8% (quite a big diff from >1%) Not critical, only if an easy fix.

**Comment by davmlaw** [comment]
Since the widgets have to display in pixels and take mouse input, there is an effective minimum sensitivity to them.

This leads to some strange behavior if you set it too low, eg you sometimes skip some values, eg you can set it to 0.07 and 0.08 but it jumps from 0.08 to 0.1 (can't select 0.9). It also makes it extremely fiddly to set it on a whole number, eg try to set it to 0.04 and you set it to 0.042

I'd argue that the difference between 0.08 and 0.1 is not meaningful - even with depth of 10k reads - we're talking 80/10,000 reads vs 100/10,000 reads has a FET of 0.1547 (ie not significant)

**Comment by sksmi** [comment]
Widget sensitivity could be an argument to move back to  % at some stage, but not important now. 

Agree that there's no sig sampling diff between 0.008 & 0.01 but somatic guys would like to track low AF variants between samples, e.g. when a  variant is found in one sample and traced back in samples over time so sig diff isn't important. Can easily be done using a AD cutoff instead of AF though so not a required feature. 

**Minor bug:** 

AF text is still in % on node:

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/18681c6d-12ad-482b-af0d-ae678e6bb78f)

**Comment by davmlaw** [comment]
Removed % from node text

**Comment by sksmi** [comment]
PASS.


PASS: Help updated (annotation/view_annotation_descriptions)
PASS: Loading old AF filters and making sure they're converted correctly
PASS: AF filters for sample/trio/cohort (legacy and new AF from VCF)
PASS: Grids always show as 0-1, export as CSV and VCF
PASS: Variant details page - samples grid, AF graphs
