### ISSUE TITLE
SpliceAI gene choice

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#273]
While waiting for issue #269 - wrong SpliceAI - we could at least import the gene symbol so we know why it's wrong

This is already in the VEP output, just need to create a column / data etc and pull it out and display it on the variant details page and grid

**Comment by davmlaw** [comment]
I've added the SpliceAI gene symbol. It'll appear with new annotation (and eg all of SA Path after upgrade) but am not going to re-run all annotation to get it. Also not adding the column to any custom columns (though people can if they want)

To test, after server is upgraded, insert a new variant, eg 

NC_000001.11:g.930130C>A

It should show in SpliceAI section

**Comment by sksmi** [comment]
SpliceAI Gene Symbol'n field present on variant page for variants with SpliceAI data. 
Gene symbol present on variant (tested 2 variants).
