### ISSUE TITLE
VEP pick - (variant annotation trascript choice)

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#274]
Sarah says:  I think we need to look at VEP pick order for refseq - currently choosing the wrong transcripts for a bunch of really important genes (e.g. NR for BRCA1, SCN1A etc), can't see us being able to use as is, sometimes we're lucky and the variant will come through the filters, other times we'll never see it e.g. we lose 6/10 of our BRCA1, 4/5 SCN1A pathogenic variants. Overall we're missing approx 10% of known pathogenic variants in filtering - I'm still working out if that's a transcript choice issue, too stringent filtering or just because we'll never catch them, but of the 10 I've looked at so far 8 have been due to transcript choice.

My initial thought is to put MANE at top of VEP pick order  - but no idea of how to test this prior to re-annotating the entire db or what happens if there's MANE clinical plus option as well. I'm assuming you need to re-annotate with the switch to v103 anyway so this won't cause a delay - either way think it's worth a group discussion as critical & impacts all output/testing/validation.

---------------

VEP v103 has ```--mane, --mane_select ``` also there are other options ```--appris --tsl --canonical``` - so we could potentially get these and re-create the VEP pick algorithm but with some tweaks

Another option would be to hardcode transcript choice for some genes, though that would mean you'd eg pick synonymous for that transcript over a stop in another.

**Comment by sksmi** [comment]
MANE 0.92 says they cover all known disease causing genes and 16K+ genes in total, so I would expect it to be the safe option.. just wondering how to validate the choice as it's so critical.

As an example, investigated impact of filters on SCN1A & BRCA1 pathogenic variants (from Shariant or ClinGen)  - essentially 10/15 pathogenic variants removed because of wrong transcript choice. These genes were specifically chosen for investigation as it was immediately clear that an NR transcript was the wrong choice, but there are also a number of other examples where transcript choice will likely impact filtering (see links below). Even without knowing overall proportion of genes affected, it's fairly clear that this isn't feasible for clinical applications. 

http://144.6.229.160/variantopedia/view_variant/247055190
http://144.6.229.160/variantopedia/view_variant/248056203 
http://144.6.229.160/variantopedia/view_variant/247785577 
http://144.6.229.160/variantopedia/view_variant/247108116 

[https://app.zenhub.com/files/299486514/79d88b81-0fdc-403a-881c-1df74293227e/download](https://app.zenhub.com/files/299486514/79d88b81-0fdc-403a-881c-1df74293227e/download)

**Comment by davmlaw** [comment]
There are 2 concepts here - canonical and representative.

**Canonical** - flagged by someone (eg Ensembl/RefSeq/MANE) as the transcript to use FOR A GENE. SA Path have their own definition of canonical, which is mostly MANE, but we'd use that.

**Representative** - chosen from all overlapping transcripts for a variant

The key point is, "canonical" is not enough to determine which one is representative. For instance all of your examples above overlap multiple genes, so there are multiple canonical transcripts.

**Comment by davmlaw** [comment]
@sksmi  OK, well the good news is that running VEP 103 seems to resolve the issue. With exactly the same arguments, the variants in your list changed:

**VEP v100 PICK**

SCN1A NR_148667.2:n.6182T>C, impact: MODIFIER, revel: 
SCN1A NR_148667.2:n.5953_5956del, impact: MODIFIER, revel: 
SCN1A NR_148667.2:n.5203C>T, impact: MODIFIER, revel: 
SCN1A NR_148667.2:n.3904-2A>G, impact: HIGH, revel: 
SCN1A NR_148667.2:n.1063C>T, impact: MODIFIER, revel: 
BRCA1 NR_027676.2:n.4866C>G, impact: MODIFIER, revel: 
BRCA1 NR_027676.2:n.4661+1del, impact: HIGH, revel: 
BRCA1 NR_027676.2:n.3933_3936del, impact: MODIFIER, revel: 
BRCA1 NR_027676.2:n.3043_3047del, impact: MODIFIER, revel: 
BRCA1 NR_027676.2:n.2248del, impact: MODIFIER, revel: 
BRCA1 NR_027676.2:n.1798C>T, impact: MODIFIER, revel: 
BRCA1 NR_027676.2:n.724+1G>T, impact: HIGH, revel: 
BRCA1 NR_027676.2:n.393-11T>G, impact: MODIFIER, revel: 
BRCA1 NR_027676.2:n.392+21A>G, impact: MODIFIER, revel: 
BRCA1 NR_027676.2:n.317T>C, impact: MODIFIER, revel: 

**VEP 103 PICK**

SCN1A NM_001165963.4:c.5765T>C, impact: MODERATE, revel: 0.966
SCN1A NM_001165963.4:c.5536_5539del, impact: HIGH, revel: 
SCN1A NM_001165963.4:c.4786C>T, impact: MODERATE, revel: 0.967
SCN1A NM_001165963.4:c.3551-2A>G, impact: HIGH, revel: 
SCN1A NM_001165963.4:c.677C>T, impact: MODERATE, revel: 0.917
BRCA1 NM_007294.4:c.4689C>G, impact: HIGH, revel: 
BRCA1 NM_007294.4:c.4484+1del, impact: HIGH, revel: 
BRCA1 NM_007294.4:c.3756_3759del, impact: HIGH, revel: 
BRCA1 NM_007294.4:c.2866_2870del, impact: HIGH, revel: 
BRCA1 NM_007294.4:c.2071del, impact: HIGH, revel: 
BRCA1 NM_007294.4:c.1621C>T, impact: HIGH, revel: 
BRCA1 NM_007294.4:c.547+1G>T, impact: HIGH, revel: 
BRCA1 NM_007294.4:c.213-11T>G, impact: MODIFIER, revel: 
BRCA1 NM_007294.4:c.211A>G, impact: MODERATE, revel: 0.866
BRCA1 NM_007294.4:c.115T>C, impact: MODERATE, revel: 0.934

Looking through the changelog, the only thing different from 100 to 103 was 103 added MANE, and [pick](https://asia.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick) uses MANE though it's the last option

The strange thing is, I can't get MANE_SELECT to come through at all

You can also change how pick works with ```--pick_order``` - ie you could put MANE first, I tried that and it didn't make a difference with the above list (exactly the same)

So.... my thoughts are I should install VEP 103 on the test VM and re-run everything.

A few questions:

* OK for me to upgrade the test VM to use VEP 103? I have no idea if it fixes transcript selection issues for Ensembl, but probably does. We could also then upgrade VG.com / RUNX1 to 103 if it's way better
* Should I also collect eg "tsl, appris, ccds" etc - might make it easier to work out why something was picked as representative
* When I restore the old SA Path prod and upgrade it, I'll use VEP 103 on that - that may take a while, though, as the VM only has a few cores.

**Comment by davmlaw** [comment]
Downloading homo_sapiens_vep_103_GRCh37.tar.gz and homo_sapiens_vep_103_GRCh38.tar.gz on test VM to /data/annotation/VEP/vep_cache but it's really slow. Looks like it'll take 24hrs... can't find any other mirrors

**Comment by davmlaw** [comment]
Re-running annotations on vg test

http://144.6.229.160/annotation/variant_annotation_runs

**Comment by davmlaw** [comment]
Upgrading to VEP 103 solves the transcript choice for BRCA1 and SCN1A, but multiple-overlapping genes issue wasn't solved (as there are multiple genes, each with their own canonical)

> http://144.6.229.160/variantopedia/view_variant/247055190
> http://144.6.229.160/variantopedia/view_variant/248056203
> http://144.6.229.160/variantopedia/view_variant/247785577
> http://144.6.229.160/variantopedia/view_variant/247108116

I've listed the variants and transcripts in ClinGen expert panels (regarding that as our source of truth)

https://docs.google.com/spreadsheets/d/1VcsTa21JptDAXVb_Ci8KYDWjFxL9rFMAcnWhuyoNlbo/edit?usp=sharing

VEP 103 didn't always choose the same as ClinGen, but I was able to improve it by altering the pick order.

The only one "custom pick 103" didn't match ClinGen expert was "NM_002880.3(RAF1):c.1587G>A" - Ensembl has a transcritpt ENST00000251849.9:c.1587G>A  that matches the codon - but it's synonymous - which is why that wasn't chosen

```
# Default
--pick-order canonical appris tsl biotype ccds rank length mane

# custom pick 103
--pick-order mane,biotype,rank  # Note: I think I will also include "length" at the end as a tie breaker

```

**Ensembl documentation**

```--pick```

This is the option we anticipate will be of use. VEP chooses one block of annotation per variant, using an ordered set of criteria. This order may be customised using --pick_order.

* canonical status of transcript
* APPRIS isoform annotation
* transcript support level
* biotype of transcript ("protein_coding" preferred)
* CCDS status of transcript
* consequence rank according to this table
* translated, transcript or feature length (longer preferred)
* MANE transcript status

**Comment by davmlaw** [comment]
TODO:

* Add and store MANE fields (only works in Ensembl) - and indicate on transcript choice along with canonical / representation
* SA Path - run VEP 103 RefSeq using my modified pick, will validate there
* Need to decide whether to upgrade VG.com / RUNX1 with VEP 103 and new pick - I vote yes, and I think if I started it at 6pm it may be done by the next day as vg.com has plenty of cores

**Comment by sksmi** [comment]
Ran a quick test on transcript choice using gold classifications (Shariant & ClinGen LP/P & LB/B) + random selection of coriell snps (these are assumed to be benign).

In summary, there's pretty good agreement between my test filters & truth set across all transcripts so this may not be the best way to test (or transcript choice just doesn't have much impact which I doubt). Will think about a better approach.

__________________________________________
Dataset:
2350 deleterious
4350 tolerated

Assuming:
- LP/P gold classifications are true positive for all transcripts for that variant (no way of assigning to a single transcript)
- XM_ transcripts removed 
- any variant that passes basic filter = candidate/positive test (i.e. will be found in analysis node) where the basic filter set is gnomad popmax AF < 0.1  AND (rf  > 0.4  OR revel > 0.6 OR  impact = high)

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/88286cd6-d659-49e8-ad23-66e26da2377b)

Opt1: 
1. biotype = protein coding
2. impact
3. mane transcript 
4. canonical
5. if > 1 randomly selected 1 transcript


Opt2 order:
1. mane
2. canonical
3. ccds
4. biotype
5. impact
6. if >1 randomly selected 1 transcript

```
opt1 = vep_merge %>%
  group_by(variant, source) %>%
  filter(biotype.score == max(biotype.score)) %>%
  filter(impact.score == max(impact.score)) %>%
  filter(mane.score == max(mane.score)) %>%
  filter(mane.ref.score == max(mane.ref.score)) %>%
  filter(can.score == max(can.score)) %>%
  filter(ccds.score == max(ccds.score)) %>%
  mutate(count = n()) %>%
  sample_n(1) %>%
  ungroup
  
    
opt2 = vep_merge %>%
  group_by(variant, source) %>%
  filter(mane.score == max(mane.score)) %>%
  filter(mane.ref.score == max(mane.ref.score)) %>%
  filter(can.score == max(can.score)) %>%
  filter(ccds.score == max(ccds.score)) %>%
  filter(biotype.score == max(biotype.score)) %>%
  filter(impact.score == max(impact.score))%>%
  mutate(count = n()) %>%
  sample_n(1)%>%
  ungroup
```
n.b. mane ref score = manually imputed mane transcript.

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/e567b0df-2e28-46a8-afb2-d878f9ab3c1a)

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/2c8db2dd-34db-4e60-a6cc-9af51e3a8133)

**Comment by sksmi** [comment]
Repeat of the above with basic filter set:  IMPACT HIGH or MOD 
(population freq, REVEL & rf scores are not transcript specific so have been removed to increase sensitivity)

Conclusion is still that transcript choice has marginal overall impact, although opt1&2 perform better than random selection.  
____________________________

1. Number of transcripts/variant:

conclusion - MADD has a phenomenal number of refseq transcripts! 
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/c1b4ccc4-216d-4137-8083-f960c96c249f)

2. Impact of transcript selection criteria on transcript choice (independent of variant classification):
Opt1 & Op2 = 97% overlap in transcript choice
Opt3 (random selection of 1 transcript/variant) = 40% overlap in transcript choice with opt1 or 2 (approx. no bootstrapping)

3. Impact of transcript selection on variant detection.
Still minimal overall impact. 

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/492c7798-e25a-4081-bf64-9ffa0e539747)

**Comment by davmlaw** [comment]
I need to start VG3 upgrade annotations running, so am going with Sarah's slack suggestion (from meeting today):

* biotype (protein coding)
* consequence rank 
* MANE
* CCDS
* length (don't know if/how this works for refseq)

**Comment by davmlaw** [comment]
Problems with that are:

1) MANE doesn't support GRCh37
2) If there's no MANE, it'll basically randomly choose (ie no concern for canonical transcript at all)

So I think we should go for:

```
--pick-order biotype rank mane canonical ccds length
```

Or at the very least, switch out mane for canonical for GRCh37

Let me know ASAP so I can kill the annotation jobs if you want to change it (as they take forever to run and then test)

**Comment by sksmi** [comment]
In general I'd go ccds over canonical as a reasonable # of the canonicals are non-coding, I wouldn't worry about changing it though given you've started - I doubt it will have any impact in practice as we'll pick these up through biotype and rank anyway.  

Are we still doing the first testing on the mini-dataset?

**Comment by davmlaw** [comment]
Yeah, I'm currently running the above pick order on vg3 upgrade (1 week old prod upgraded to latest code) but it takes forever for the VMs to run annotation (seem to be spending 3/4 cores on system - which is probably disk I/O through VirtualBox sharing?)

I guess under the assumption that we'll use that annotation, but yeah we should test it first to confirm.

So, I'll kill the current annotation jobs, clone the DB and VM, then bring up another environment where we can do the mini dataset (then restart annotation again)

**Comment by sksmi** [comment]
sounds good, can you confirm that vep pick MANE selection works on refseq GRCh38? Or is the plan to manually flag and filter?

**Comment by davmlaw** [comment]
Dave to prioritise work on #271 - FreeBayes VCF import / Allele Frequency.
Once this is done, upgrade VG test + inform Sarah/W so they can do testing using VEP 103 Ensembl and see if it’s ok.
A VM (recent clone of prod called “VG3 upgrade”) is running annotations with VEP 103 + pick order of biotype,rank (severity),mane,canonical,ccds,length. This is estimated to def finish by Wednesday (could potentially finish earlier if I can figure out how to give more resources to VM) Once done - Dave to verify RefSeq is using MANE correctly w/PICK
By Wednesday, Sarah/W to run analyses and report on what % are detected on
VEP 103 w/Ensembl - VG Test
VEP 103 w/RefSeq - SA Path test
A/W to send Dave copy of their canonical transcripts
Dave to compare canonical transcripts vs what VEP 103 w/RefSeq chose for VCFs, summarise concordance and list differences

**Comment by sksmi** [comment]
@davmlaw Quick vep pick check in :92. 

Assessed 188 variants. All MANE selected with the exception of: 

- NM_001271208.2:c.9465del	(3 equal HIGH impact transcripts, didn't choose mane NM_001164508.2)
- NM_001369787.1:c.178G>A (MANE: NM_033360.4)
- NM_001130702.2:c.263A>G (MANE: NM_001122955.4)	
- NM_019032.6:c.767_786del (MANE: NM_019032.6)

Overlapping gene selection looks much better too.

Not sure vep pick is behaving exactly as we'd expect, but the clinical impact appears to be minimal with the caveat that full testing is required once data fully annotated.

**Comment by sksmi** [comment]
Tested with current classifications and tags. No issues identified. 
Waiting for SAP #99 - test data to fully finalise.

**Comment by davmlaw** [comment]
VG3 went into validation with:

```
ANNOTATION_VEP_PICK_ORDER = "biotype,rank,mane,canonical,ccds,length"
ANNOTATION_VEP_DISTANCE = 2000
```
