### ISSUE TITLE
VCF - be able to disable variant zygosity count

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#279]
Admins can configure VCFSourceSettings to do special cases on VCF based on what type it is.

Expose our current settings, which eg sets "variants type" (ie FreeBayes to mixed somatic)

Also be able to configure whether it should count for Global variant zygosity count - SA Path want to disable that for FreeBayes

**Comment by davmlaw** [comment]
Basically: upload a FreeBayes VCF and it should no longer alter the variant zygosity counts.

On the view VCF page, VCF info tab, there's now "Variant Zygosity Count" which shows what the VCF has counts for (will only be global until we make more)

Note: does not affect legacy data

**Comment by sksmi** [comment]
FAIL. 

1 Made an analysis using an existing sample (image 1 below) http://frgeneseq02.imvs.sa.gov.au:90/analysis/5326/
2. Downloaded the vcf containing the sample and re-uploaded
3. Refreshed the analysis in 1 above (image 2)- counts unchanged. PASS
4. Force reloaded analysis 5326 - counts updated. FAIL.

(1) Analysis 5326 pre-upload using old sample data:
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/da9a1404-2ea3-4dba-a1fa-2080ac3431b6)

(2) Same analysis #5326 post-upload with page refresh, no force reload:
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/202107f0-d3d1-4b10-8850-ccaf1429f2a5)

(3) Same analysis #5236 post-upload with force reload: 
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/f998e8b4-6d6f-4512-874d-217d1c81e9a3)

**Comment by davmlaw** [comment]
Sorry, forgot to make a config change to SA Path. Should work now

I made it count freebayes by default (as eg on other servers it may be the only copy) but the admin has to turn it off.

**Comment by sksmi** [comment]
PASS.

Tested with new sample: http://frgeneseq02.imvs.sa.gov.au:90/analysis/5331/
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/011d08ae-6db7-4252-b61d-64083b3f2282)
