### ISSUE TITLE
Improve Rollbar reporting with Thread Local request

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#285]
A small percentage of our Rollbar errors don't have any information about who the current user was or what page they were on when the error was triggered.

This happens if we specifically catch the error, report it, and then continue on with some processing.
If we don't catch the error it bubbles all the way back to the start of the request where the information about the URL and current user are present.

If we setup some middleware that stores the Request in a threadlocal, and then have report_exc_info check for that and pass the request onto rollbar, that should solve these cases.

**Comment by TheMadBug** [comment]
Not really anything to test here, will just be a matter of Dave and I looking through rollbar reports after this is deployed to hopefully see more detail in some circumstances.

**Comment by EmmaTudini** [comment]
Moving to pending release
