### ISSUE TITLE
Splice donor site designated as missense? Bug or HGVS

### ISSUE THREAD

**Issue by a1618617** [SACGF/variantgrid#291]
Hi guys,

https://variantgrid.com/variantopedia/view_variant/251398211

Just wondering why the HGVS nomenclature for this variant was missense when its located in the -1 position.
https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr5%3A37036569%2D37036609&hgsid=1054575551_bqMXepxyeCscO8T5iC746A88CmXH

Don't know if its a bug or this is how it should be written.

**Comment by sksmi** [comment]
Not sure if I'm missing something here, but 5:37036589 is exonic by my calcs. Still predicted splice effect though. 
https://variantvalidator.org/service/validate/

![image](https://user-images.githubusercontent.com/8601717/110870269-3bc6ab80-8320-11eb-8cf5-1f62b05772c9.png)

**Comment by davmlaw** [comment]
>> HGVS nomenclature

HGVS is "NM_133433.4:c.5971G>A" - do you mean the molecular consequence was assigned to "missense variant & splice region variant"

Or are you talking about the protein? "NP_597677.2:p.Asp1991Asn"

The change is GGT  => AGT, looked up on Amino acid codes and it's ASP => ASN so protein seems right

>> located in the -1 position.

In your screenshot, it appears that the variant is on the 1st base of the codon, still in the exon

**Comment by a1618617** [comment]
Sorry, had a low IQ moment. Got the wrong G position. Close Issue
