### ISSUE TITLE
GeneListNode PanelApp filters don't work on systems without pathology tests enabled

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#294]
I tested this on my dev machine and SA Path test (which have pathology tests enabled), but not on VG test (which has path tests disabled)

This is because accordion order is path tests = 3, panel app = 4, but if path tests are disabled, panel app thinks it's 3

Either need to make a data migration, (also remember to add comment to code to mention not to add new filters after path tests) or hide the path tests accordion

**Comment by davmlaw** [comment]
Thuong reported this issue against this node: https://variantgrid.com/analysis/790/422293/

**Comment by davmlaw** [comment]
Hotfixed to vg.com:

```
git fetch
git cherry-pick f86851cbf66844cddd504501db3340d1b16c2915
```

**Comment by sksmi** [comment]
Works in vg.com env on quicktest.
