### ISSUE TITLE
Mystery nodes

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#303]
No idea if this is an issue or not, but swear I didn't add the filter to parents nodes: 
http://144.6.229.160/analysis/1973/

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/395dded0-4f2e-456d-a548-00ac96204a01)

**Comment by sksmi** [comment]
sorry accidentally just deleted this analysis..

**Comment by davmlaw** [comment]
That was me, I was trying to grab the SQL from just that 1 variant so I could run it in the DB
