### ISSUE TITLE
VarDict sample level filters

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#305]
Frank asks to read + display the FT tag from Vardict VCF files  have that tag. They look like this:

```
##FORMAT=<ID=FT,Number=.,Type=String,Description="Sample-level filter">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  6_9_4400004_EOT_DNApanel
chr21   34792684        .       AG      A       83      HmplymLowFreqIndel      .     GT:DP:VD:AD:AF:RD:ALD:FT        0/1:1156:5:1150,5:0.0043:113,1037:0,5:HmplymLowFreqIndel
chr21   34792744        .       T       C       270     PASS    .       GT:DP:VD:AD:AF:RD:ALD:FT        0/1:733:333:396,333:0.4543:9,387:9,324:PASS
chr21   43094393        .       A       AT      151     Q25;HmplymLowFreqIndel  .     GT:DP:VD:AD:AF:RD:ALD:FT        0/1:889:26:796,26:0.0292:695,101:23,3:Q25;HmplymLowFreqIndel
```

I have already added:

```
VCF.sample_filters_field
CohortGenotype.samples_filters
```

And read these during VCF import. Still need to do:

* Make analysis variant grid sample columns show/hide based on what the input samples have (eg don’t show GQ if not used)
* Add sample filters to grid

Ideally, add the ability to perform filtering on sample filters as well as normal filters, not exactly sure how that should work

**Comment by davmlaw** [comment]
I get an error  from the pyVCF library:

```
SyntaxError: One of the FILTER lines is malformed: ##FILTER=<ID=LowFreqBias,Description="Set if true: INFO/AF < 0.02 && ((INFO/TYPE != \"Complex\" && NM >= 2.5) || SN < 4)">
```

Have asked Frank to replace escaped double quotes with single quotes in the FILTER lines.

I wondered whether this is against the spec - VCF validator passes the file, reading the VCF spec - http://samtools.github.io/hts-specs/VCFv4.2.pdf - says for INFO fields that “Double-quote character can be escapedwith backslash \ “ however it does not mention escaping in the FILTER section right below it.

**Comment by davmlaw** [comment]
GQ, PL and FT now only show in the grid if one of the source VCFs has the data.

To test, upload a VarDict VCF (from Frank)

View on grid, ensure that FT column is populated correctly

**Comment by sksmi** [comment]
FAIL (minor)

Tested: 

- PASS Uploaded to SAP :92.  
- PASS zygosity, AD, AF,DP, FT imported. GQ, PL not shown.  
- PASS cohortgenotype_2000__filters shown (match FT column exactly - do  these change in multi-sample vcfs?)
- FAIL Sample filters don't work see :92/analysis/8910/  - not in rollbar.


![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/1b9a9b33-fa3a-49f9-a179-4ad513bd826a)

**Comment by davmlaw** [comment]
Unrelated to original change but needs to be fixed so sample filters work.

http://frgeneseq02.imvs.sa.gov.au:92/analysis/8910/ has been deleted but can recreate:

* Create a sample node with a var dict sample, with no other modifications (no AF, no min AD etc) - won't work otherwise
* Click "Select filters", click one and save.

**Comment by sksmi** [comment]
**PASS**
