### ISSUE TITLE
View Case page displays VariantClassification table twice, causing datatables to fail

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#310]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2455/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2455/)

```

(unknown)
  File "(unknown)", line 3, in [anonymous]
```

**Comment by davmlaw** [comment]
A page this happened on was http://frgeneseq02.imvs.sa.gov.au:90/pathtests/view_case/2208 (or same url with :92)

**Comment by sksmi** [comment]
Can access case pages without error.
