### ISSUE TITLE
UploadPipeline 4101 failed. Filename: VCF Error: invalid input syntax for type integer: "U"

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#315]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2466/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2466/)

```
UploadPipeline 4102 failed. Filename: VCF Error: invalid input syntax for type integer: "U"
CONTEXT:  COPY snpdb_cohortgenotype_collection_1959, line 1, column unk_count: "U"

```

**Comment by sksmi** [comment]
Not sure how to test this one - can you provide some more detail?

**Comment by davmlaw** [comment]
Basically import a VCF with no genotype - I did that with the Somalier sites VCF, also wrote a unit test, so can close this one.
