### ISSUE TITLE
KeyError: 'chrom'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#317]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2473/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2473/)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/classification/models/classification.py", line 1864, in _generate_c_hgvs_extra
    c_hgvs = hgvs_matcher.variant_to_c_hgvs_extra(variant, transcript_id)
  File "/mnt/variantgrid/genes/hgvs.py", line 349, in variant_to_c_hgvs_extra
    return self.variant_to_hgvs_extra(variant, transcript_name)
  File "/mnt/variantgrid/genes/hgvs.py", line 313, in variant_to_hgvs_extra
    transcript = self.get_pyhgvs_transcript(transcript_name)
  File "/mnt/variantgrid/genes/hgvs.py", line 227, in get_pyhgvs_transcript
    return TranscriptVersion.get_refgene(self.genome_build, transcript_name,
  File "/mnt/variantgrid/genes/models.py", line 663, in get_refgene
    return make_transcript(transcript_version.data)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/utils.py", line 79, in make_transcript
    transcript_json['chrom'],
KeyError: 'chrom'
```

**Comment by davmlaw** [comment]
If you search for "ENST00000386347.1" (on test - works in my environment)

It dies trying to show differences:

```
        if self.data and transcript.data:
            my_chrom = self.data["chrom"]
            other_chrom = transcript.data["chrom"]
            if my_chrom != other_chrom:
                differences["contig"] = (my_chrom, other_chrom)
```

**Comment by sksmi** [comment]
Bumped up, not sure if required.

**Comment by davmlaw** [comment]
I think this is just bad annotation data and will be fixed importing more up to date annotations.

But I made it so that the transcript versions page shows a warning when data is missing, not crashes out.

**Comment by sksmi** [comment]
**PASS**

Warning displayed: "We don't have any data for this transcript version on file."

@davmlaw a search for non-existent transcript version returns no results. Wondering whether it should return the transcript page if transcript page exists. 

e.g. searching for NM_000038.7
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/b1d6f033-8f1a-4f1e-b488-f6c1076b14a9)

Should it return: 
Transcript version not in database. For further details on available transcript versions see the transcript page: /genes/view_transcript/NM_000038

**Comment by sksmi** [comment]
**PASS**
