### ISSUE TITLE
Zygosity displayed differently on variant page versus cohort analysis grid. Why?!

### ISSUE THREAD

**Issue by a1618617** [SACGF/variantgrid#325]
Hi team,

This variant is displaying differences in zygosity from the "variant page" versus "analysis". 
variant: https://variantgrid.com/variantopedia/view_variant/180404776
cohort analysis: https://variantgrid.com/analysis/2547/

Example screenshot - ClinEx105 is HOM_ALT and ClinEx107 is HET
![image](https://user-images.githubusercontent.com/16040469/113955669-5b87bb80-985b-11eb-885a-2ac124f29fd9.png)

Example screenshot - ClinEx105 is HET and ClinEx107 is HOM_ALT
![image](https://user-images.githubusercontent.com/16040469/113955852-a6a1ce80-985b-11eb-89c7-34a5b1a286ee.png)

The zygosity listed in the variant page is correct, but wrong in the cohort analysis.
Any help would be appreciated. Thanks

**Comment by davmlaw** [comment]
Will have to continue looking after lunch, but initial look is:

samples_zygosity = "OOEEO" 

```
Sample               SampleID	cohort_genotype_packed_field_index	Cohort zyg	Actual Zyg
34_GAS_PED003E_GA_0632	8057	0	HOM ALT	HOM ALT
ClinEx107_90202879_S7	7106	1	HOM ALT	HET
ClinEx108_90202880_S8	7107	2	HET	HET
ClinEx105_90202877_S5	7104	3	HET	HOM ALT
ClinEx106_90202878_S6	7105	4	HOM ALT	HOM ALT
```

If you sort the fields by sampleID the zygosity matches the actual - so... it appears this is due to the sort order being out of sync with the "sample id order"

It's possible we're not taking into account sort order properly here. 

I think this only affects cohorts where someone has altered the sort order

**Comment by davmlaw** [comment]
Fixed on vg.com by manually running code fix (see below) - written data migration to fix other environments if affected next upgrade

The cohorts affected were:

Cohort PED004 (5 samples)
Cohort AML4_S4_L001_R1_001 (paired)_Variantes_S_F.vcf sub cohort (4 samples)
Cohort UPN_33755 (20 samples)
Cohort PED148 trio (3 samples)
Cohort UPN_39621 (22 samples)
Cohort PED004 proband trio (3 samples)
Cohort DDX41_Malignancy (49 samples)
Cohort PED003 (5 samples)
Cohort DDX41_ML_SA (32 samples)

Verified by checking https://variantgrid.com/analysis/2547/42712/

Code was:

```
from django.db.models.aggregates import Max 
from django.db.models.expressions import F, Value
from snpdb.models import Cohort, CohortSample

for cohort in Cohort.objects.filter(vcf__isnull=True):
    # Fix incorrectly remaining a sub cohort
    if cohort.parent_cohort:
        my_samples = cohort.get_samples()
        parent_samples = cohort.parent_cohort.get_samples()
        if my_samples.exclude(pk__in=parent_samples).exists():
            logging.info("Cohort %s (%d) set to not a sub cohort", cohort, cohort.pk)
            cohort.parent_cohort = None  # No longer a sub cohort
            cohort.save()

    # Fix issue #325 - sample order mixups
    out_of_order = False
    for i, cs in enumerate(cohort.cohortsample_set.order_by("sample")):
        if i != cs.cohort_genotype_packed_field_index:
            out_of_order = True
            break

    if out_of_order:
        if cohort.parent_cohort is None:  # These are the only ones that were affected
            logging.info(f"Cohort {cohort} has wrong pack order - fixing")
        qs = cohort.cohortsample_set.all()
        data = qs.aggregate(highest_value=Max("cohort_genotype_packed_field_index"))
        if highest_packed_index := data["highest_value"]:
            # packed fields are unique per cohort so need to move them sufficiently high to be able to rearrange
            out_of_range = F("cohort_genotype_packed_field_index") + Value(highest_packed_index + 1)
            cohort.cohortsample_set.all().update(cohort_genotype_packed_field_index=out_of_range)

            # Cohort genotype packed fields are in sample order
            cohort_samples = []
            for i, cs in enumerate(cohort.cohortsample_set.order_by("sample")):
                cs.cohort_genotype_packed_field_index = i
                cohort_samples.append(cs)

            if cohort_samples:
                # Do a bulk update so it doesn't trigger a save then call this func again
                CohortSample.objects.bulk_update(cohort_samples, ["cohort_genotype_packed_field_index"])
```

**Comment by sksmi** [comment]
Good catch!
@davmlaw What the best approach to test for sorting issues & where is it required? This probably isn't sufficiently covered in current test cases which only minimally address sorting in parent node v child node.

**Comment by davmlaw** [comment]
The bug would have occured when:

* Cohorts were sorted by hand
* Cohorts were built by hand, and samples were added not in sample order

The most common way to make a trio/cohort is to click on a list of samples on the VCF page then "create trio" or "create cohort" - these will be in sorted order. Whenever I made a test trio I guess I had also created them in sorted order

I wrote 3 unit tests that re-created the issues in cohort and now pass after the fix

But yeah, if you could add 2 test cases for Cohort (testing sorting them etc and verifying zygosity calls etc match):

* Test sub-cohort - this is where a cohort is a subset of a VCF - we don't need to recalculate things here just only take the samples we need
* A cohort built from samples from different VCFs - this requires re-processing the data

**Comment by sksmi** [comment]
**PASS** 

Now included test case - will be tested more formally next week.
Manually tested with 5 variants in sub-cohort & mixed cohort.
