### ISSUE TITLE
Analysis template - intersections node changes to enrichment kit

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#329]
The intersections node automatically switches to an EnrichmentKit bed file if available.

This overrides our HGVS coordinate in an analysis template

* Make sure it doesn't switch if set to anything other than enrichment kit
* Make sure it does switch with different kits if set to Enrichment Kit

**Comment by davmlaw** [comment]
Started on this but it's too risky to do this change now.

The fastest way to filter a sample is to use a pre-processed VCFBedIntersection but this only works if all of the samples are from the same VCF.

Currently, the enrichment kit filter only works if we have a VCFBedIntersection - so doesn't work eg below a venn/merge of samples from different VCFs - just says "Can't determine enrichment_kit from input samples"

If we make this subclass "AncestorSampleMixin" - then we can have a sample select when there are multiple ones to choose from. We can use the VCFBedIntersection if available, and if not, then fall back on using enrichment kit genomic_intervals_collection (modify to use / write cache in that case)

**Comment by sksmi** [comment]
Enrichment kit also overrides any selection in genomic coordinates if the parent sample node is re-saved. 

e.g. if you change allele depth in the sample node, the filter will switch from custom range to enrichment kit 
:92/analysis/9130/

**Comment by sksmi** [comment]
Would vote for disabling auto-import enrichment kit for the time-being. 
1) is a quick temp solution to this issue
2) we don't use enrichment kit filtering in any of the set analyses, and the bed is easily available if anyone wants to manually apply it
3) enrichment kit filtering isn't currently working: 

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/ac5c23cb-69b4-40b2-83c0-79ad024bee3b)

**Comment by davmlaw** [comment]
>> we don't use enrichment kit filtering in any of the set analyses

We do in VG2, though possibly not for the latest kits as I didn't set them up. But for old kits, we did

**Comment by sksmi** [comment]
Even though the intervals node is part of the V2 standard analysis, as far as I'm aware it's never been used to filter any variants so we don't need to worry too much about back compatibility.

**Comment by davmlaw** [comment]
Disabled auto switch

**Comment by sksmi** [comment]
**PASS**
