### ISSUE TITLE
Custom columns - sharing / permissions

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#333]
At the moment CustomColumnsCollection don't use standard guardian permissions.

* Inherit from guardian mixins so it behaves standard way
* management command w/migration
* If you don’t have permission you can view it read only
* Clone button (on grid)
* Clone button (on page)
* Make a tab so you can change permissions etc

**Comment by sksmi** [comment]
Moved up in queue as required (but not critical) for validation.

**Comment by sksmi** [comment]
**PASS**

Test Case VG #188
https://app.qase.io/run/VG/dashboard/31
