### ISSUE TITLE
Allele Frequency unit / percent display

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#335]
We now store all frequencies as a unit, but display them inconsistently:

Variant details - percent
Classification form - unit + percent
Analysis Grid + Nodes: unit (full really long floating point values)

I don't mind which we use, but we need to be consistent. Ie if we go for percent we need to write a formatter for the grid.

Another option would be to have it as a setting (ie can change per deploy). I think a user preference would get too confusing.

**Comment by davmlaw** [comment]
Karin says to go with percentage everywhere

**Comment by davmlaw** [comment]
Converted gnomad/tomed/1kg etc - still need to do Allele frequency filters and sample AF (do on backend)

**Comment by sksmi** [comment]
**PASS**

Checked fields displayed as percentage, with % sign:
- Variant page population frequencies
- Variant page sample AF
- Analysis grid frequencies
- Classification form frequencies (displayed as frequency & percentage)
