### ISSUE TITLE
Analysis Allele Frequency filter operations were backwards

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#338]
The any/all had their operations switched, ie

ALL = was filtering OR - should have been AND (ie the ALL have to be true)
ANY = was filtering AND - should have been OR (ie ANY can be true)

The sample nodes etc always defaulted to ANY - so was wrongly applying an AND - so that if you did multiple filters that overlapped to full coverage (ie 0-60 and 40-100) it returned no results. So this was effectively broken for > 1 filter

The Allele Frequency Node allowed you to switch between any/all so I suspect people were mixing them up?

I've fixed the bug now, but find out if people swapped them, then need to do a data migration on legacy data.

**Comment by davmlaw** [comment]
Well, the good news is, there were 2503 allele frequency filters, and only 1 was set to "all" and that only had 1 entry.

There were 1209 AlleleFrequencyNodes and none had multiple entries, seems they only use it to pull out eg <=3%  frequency

**Comment by sksmi** [comment]
**PASS**

PASS: Manual quick check 1
ANY (1-5, 95-100)
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/09ea3964-0a9d-42d1-b564-3ab35112bedf)

PASS: Manual quick check 2
ALL (1-5, 95-100)
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/015b24f0-5d08-44b7-a858-4c9eef24921d)

PASS: Manual quick check 3
ANY (1-5, 3-6)
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/0a44e231-bca6-45c3-b8ba-cad50c2338ca)


PASS: Manual quick check 4
ALL (1-5, 3-6)
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/e133a671-764b-4ff3-a7b3-0e509ea77e92)
