### ISSUE TITLE
Somalier relate - loading data for deleted samples

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#350]
At the end, when loading the CSV into the system, it can die if the sample has been deleted.

This currently happens on vg test. In this case, we should just not insert the record (or do bulk insert with ignore conflict)

**Comment by davmlaw** [comment]
This is going to cause problems.

We should have a sample delete signal that clears these to save space as well

**Comment by davmlaw** [comment]
Scope of change:

* If a sample is deleted during somalier all samples run, it used to crash due to database intergrity issues - now it just skips that record (as no sample to store against)
* When a VCF is deleted, the somalier files it used (data/*.somalier - 200k each and media_root related/ancestry) are now deleted - saving disk space

**Comment by sksmi** [comment]
Deleted a sample and a vcf. No errors created, somalier still displayed for other samples. 
@davmlaw  Does somalier need to be running during delete to crash the db?

**Comment by davmlaw** [comment]
It doesn't crash the DB, just the Somalier all samples job because of a DB record is missing due to the deletion.

I was able to recreate this 100% of the time on my machine before then it fixed it 100% so pretty sure that part is fixed (that part was just a catch error and ignore).
