### ISSUE TITLE
Sample Grid - determining VCF caller

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#352]
The width of the Name box in the Details Tab of the Data menu is too short, making it difficult to see the end of the vcf name which has the Variant Caller details. It would be useful if we could see the entire vcf file name in the box. Thanks :-) 

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2710/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2710/)

```
User Feedback : Width of Name box
```

**Comment by davmlaw** [comment]
It is short, but perhaps what they really want to do is see and sort/filter by the variant caller.

At the moment we have "VCF source" on the object, but ideally would move the seqauto variant caller code (used to distinguish vardict/gatk etc VCFs) to every VCF

Then add this column and add a sort/filter to it.

**Comment by sksmi** [comment]
**PASS**
