### ISSUE TITLE
User Feedback : Zygosity in sample node

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#353]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2711/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2711/)

```
User Feedback : Zygosity in sample node
```

**Comment by davmlaw** [comment]
Dupe of https://github.com/SACGF/variantgrid_sapath/issues/149
