### ISSUE TITLE
User Feedback : Protein length

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#355]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2716/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2716/)

```
User Feedback : Protein length
```

**Comment by davmlaw** [comment]
Just added it back to variant details page, on transcript select. Won't bother with being able to do via SQL as we don't usually need to compare transcripts against each other there

**Comment by sksmi** [comment]
**PASS**

Manual check for APC: 
https://www.ncbi.nlm.nih.gov/gene/324
:92/variantopedia/view_variant/22133221
341824 - 2843 PASS
341826 - 2853 PASS
341831 - 2752 PASS
20983 -2825 PASS
20982 - 2843 PASS
341827 - 2818 PASS
341833 - 2717 PASS
341835 - 2560 PASS
341825 - 2861 PASS
29 - 2843 PASS
341832 -2742 PASS
341828 - 2815 PASS
341829 - 2802 PASS
341830 - 2784 PASS
341834 - 2683 PASS


PASS: ATP8B1 :92/variantopedia/view_variant/32182608
PASS: FANCA :92/variantopedia/view_variant/32182607
