### ISSUE TITLE
VG Feedback quick issues v1

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#363]
* VCF date - set to read only

**Anaylsis**

* Add genome build indicator to analysis workspace
* ClinVar Drug Respose' typo -> 'ClinVar Drug Response'
* Trio node sample link
* CohortNode - of No samples samples.
* 1 new classifications since last save -> 1 new classification since last save
* Checkbox alignment is a bit confusing, always think I’m selecting to the right not the left
* Node count 'ClinVar' is actually 'ClinVar Max LP/P' - think this is significant enough to consider changing node text
* Will be a lot of templates very soon in research (might also need to think about managing this better in general). Can we add a search option to the template grid?

**Gene Symbol page**

* Can uniprot be a live link? Can refseq link (e.g. https://www.ncbi.nlm.nih.gov/gene/861) be avail directly from gene symbol page?
* Panel App "no evidence" (try CRPPA)

**Custom columns**

* Difficult to distinguish 'Custom Columns' page heading from column set name .e.g 'Default columns'. Can we use different font sizes or drop the 'Custom Columns' header? Also hard to see clone button, can we give it a bit of space.

**Comment by davmlaw** [comment]
2. Custom columns - I changed the style of the name, but not when it's read only - will make it obvious it's an entered name by making it a read only input field

**Comment by EmmaTudini** [comment]
Shariant testing
- Logged in to Shariant test as non-admin user
- Searched for RMRP

Expected output: Able to link from gene symbol page to refseq and ensembl gene pages. All links are consistent and displayed consistently across gene symbol pages.

Actual output: **Failed** - this is pretty minor. Think the best fix would be to only show a link for the refseq gene number or ENSG (and to not include "refseq gene" or "ensembl gene" in the link.
- Link for ensembl genes sometimes includes the text "ensembl gene" and sometimes does not. See examples below: 1. Link includes "ensembl gene"
![Screen Shot 2021-05-24 at 6.22.43 pm.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/52664a22-e815-4373-b239-97eaf869870d)
2. Link does not include "ensembl gene"
![Screen Shot 2021-05-24 at 6.22.26 pm.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/499e7b24-142e-4aa0-81ea-26851a03f46b)

**Comment by davmlaw** [comment]
> Link for ensembl genes sometimes includes the text "ensembl gene" and sometimes does not.

I didn't change that while working on this issue. The same behavior is in Shariant prod

**Comment by EmmaTudini** [comment]
Maybe made a little more obvious now that the hover over is an underline of the whole thing rather than a highlight of the box. Should I raise a new issue to fix this?

**Comment by sksmi** [comment]
@EmmaTudini closing issue. Can you raise a new one re. ensembl link if you'd like it followed up?
