### ISSUE TITLE
VG Feedback quick issues v2

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#364]
**Sequencing**

* It's difficult to find sequencing runs if you don't have the full name - added autocomplete "jump to" - not sure what benefit experiment filter adds over enrichment kit
* Can't tell if exec summary is missing. Add text 'Executive Summary data not available' or something similar?

**VCF / Sample page**
* Add sample name to top of page? Hard to know what type of data you’re looking at sometimes.
* Add link to variant page in 'Variants Tagged in Analyses'
* You can view but not modify this data  -> make message more obvious

**Trio**
* Quite hard to find trio. Sort table in reverse order so at least the latest trio is at the top. 

**Path test**
* Allow download of pathology test gene list from test page. 

**Analysis**
* Stop analysis grid window from opening 100% to right (aka same as fix for LHS).
* CohortNode - name is wrong - doesn't take into account accordion panel

**Gene**
* Difficult to see what VG has defined as a gene. Is it possible to add gene genomic coordinates to page (not doing gene grid in this change)

**GeneSymbol page**
* Allow filtering to 'tagged' e.g. show variants with any tag
* Hotspot graph - need to say het/hom variant counts
* Instead of hiding sections, grids, hotspot graphs etc, show section, but with explanatory text  e.g. when no OMIM/HPO: 'No HPO or OMIM terms associated with this gene symbol'.  - only did for OMIM/HPO section
* If not on page 1 of the Gene Variants grid, filtering variants to tag doesn't display any variants (fix: reset page clicking filter to tag)

**GeneGrid**

* Can gene ID be the leftmost column? More intuitive when the key(s) are the first columns.
* The genes grid download is also in a ?random order - possible to order by ID or gene symbol? _Assumed you meant "gene list genes grid"_

**Comment by davmlaw** [comment]
**Sequencing**

* It's difficult to find sequencing runs if you don't have the full name. Is it possible to allow more advanced filtering on sequencing  and/or switch from filtering on enrichment kit to filtering on experiment?
* Can't tell if exec summary is missing. Add text 'Executive Summary data not available' or something similar?

**VCF / Sample page**
* Add sample name to top of page? Hard to know what type of data you’re looking at sometimes.
* Add link to variant page in 'Variants Tagged in Analyses'
* You can view but not modify this data  -> make message more obvious

**Trio**
* Quite hard to find trio. Sort table in reverse order so at least the latest trio is at the top. 

**Path test**
* Allow download of pathology test gene list from test page. 

**Analysis**
*  Add ! for samples restricted to GOI (to differentiate between GOI & locking which look similar at the moment)
* Stop analysis grid window from opening 100% to right (aka same as fix for LHS).
* CohortNode - name is wrong - doesn't take into account accordion panel

**Comment by EmmaTudini** [comment]
Shariant testing
Note: Modifications to gene symbol page does not affect Shariant users so was not tested. 
- Logged in to Shariant test as non-admin user
-Git Hash
39f9499b8814e79180204df50b67a4b4a148aaaa
- Went to: https://test.shariant.org.au/genes/view_gene/672

Expected output: Gene version table would now also display genomic coordinates.

Actual output: Passed
Note: @davmlaw Where do the genomic locations come from? Currently they do not line up with the Refseq website. See: https://www.ncbi.nlm.nih.gov/gene/672 for BRCA1. Is that to be expected?

Also, would it be possible to show the genomic locations below the gene symbol on the view gene page? To me, it looks a bit cluttered with it beside the gene symbol currently

**Comment by davmlaw** [comment]
Removing "any tag" button from variant tagging page (as that only shows tags anyway)

**Comment by davmlaw** [comment]
> Currently they do not line up with the Refseq website. See: https://www.ncbi.nlm.nih.gov/gene/672 for BRCA1. Is that to be expected?

It depends on how you define "gene" and "coordinate"

There are 2 points on a coordinate and you can describe it in 4 ways (hooray!) - either 0 or 1 based and open or closed intervals (include the end or not). We're displaying the data as it is, while it looks like RefSeq is giving 1 based coordinates - will change it as the convention is to show 1 based to humans and 0 based to machines.

I define gene as "the distance between the most 5' and 3' transcript coordinates" (NM_007294.3 ends at 43125483), but it looks like RefSeq are using the start and end of the canonical transcript

We don't have canonical transcripts yet, so I can't make it match RefSeq until then, please let me know if you want it disabled in Shariant.

**Comment by sksmi** [comment]
**PASS**

Quick check only. Additional testing covered in regression. 
Thx, this is so lovely!! 

Minor comment, can we adjust: 
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/f1ab11ed-3d5f-4adc-8333-50b37bdce3ab)

**Comment by davmlaw** [comment]
Moved sequencing auto-complete to #392
