### ISSUE TITLE
Nearby variants load async in page

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#368]
SKS feedback:

The variant details page for variants in ultra large exons (e.g. 18:44951948 G>A) take an extremely long time to load due to nearby variants calcs. Suggested: load nearby variants separate to rest of page.

**Comment by TheMadBug** [comment]
FYI, I've made a component to very easily inject ajax content in a declarative sense
e.g.
```
<div data-toggle="ajax" href="{% url 'view_gene_symbol_classifications' gene_symbol.symbol genome_build.name %}">Loading...</div>
```
Currently the HTML has to be rendered in the initial page load, but I can make it so if a data-toggle is dynamically added the ajax is still oaded.

**Comment by davmlaw** [comment]
Thanks that made it easy

**Comment by sksmi** [comment]
**PASS**

tested TTN, very fast loading 
http://frgeneseq02.imvs.sa.gov.au:92/variantopedia/view_variant/32407022
