### ISSUE TITLE
Samples Tab for Grid Zygositities

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#37]
*Originally reported by* **David Lawrence (Bitbucket: [davmlaw](https://bitbucket.org/davmlaw), GitHub: [davmlaw](https://github.com/davmlaw))**

----------------------------------------

In nodes with samples - ie Cohort / Pedigree / Sample - have a tab that shows the samples.

This should also show you how the zygosities will be displayed on the grid.

Would also be possible to maybe make a border for the ZYG columns (in formatter) so that tagged columns would work as well.

How the samples are shown should be an analysis option, but settable in this tab as well.

* Option to turn off AD/PL columns, and have them just be shown on mouse over over?
* color columns by samples as well.

Handling zygosity ordering in SACGF/variantgrid_private#787

----------------------------------------
- Bitbucket: https://bitbucket.org/sacgf/variantgrid/issue/224

**Comment by davmlaw** [comment]
Closing as 6 years old and unlikely to do this. You can view the samples in the entire analysis now so not really necessary
