### ISSUE TITLE
Analyses list grid fields

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#370]
SKS asks to change fields / order of columns on Analysis list grid. Current fields:

```
"id", "name", "modified", "genome_build__name", "analysis_type", "description", "user__username", "analysislock__locked"
```

Available fields on Analysis model:

```
'created',  'modified',  'version',  'description', 'custom_columns_collection',  'annotation_version']
```

**Comment by davmlaw** [comment]
Bump for adding the separate ID/name field you can sort on - when trying to find a certain one by ID (not by name) it was quite annoying not to be able to

**Comment by davmlaw** [comment]
Separated out ID/name, added "created" column.

Did for both analyses and templates.

Please send back if you wanted any other columns changed while we're here

**Comment by sksmi** [comment]
Assuming changes haven't been deployed yet. Can you re-assign me when they're through?

**Comment by davmlaw** [comment]
Yeah sorry, had originally assinged to you as you had "requires design review" or something in the feedback issue - but just decided to charge ahead and do my change then see if you wanted to bump back other changes.

You can't see in GitHub but in ZenHub it's in "Code Complete" - which is where I put things that are finished but not yet deployed

**Comment by sksmi** [comment]
This one's really exciting! Thx!!
