### ISSUE TITLE
Sorting gnomAD and impact columns

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#371]
From VG feedback:

> If you sort on gnomad AF it will give you null > high to low. Really want null - low - high e.g. treat as 0 (but not sure that null should be 0 ..needs some thought/testing).

https://docs.djangoproject.com/en/3.1/ref/models/expressions/#using-f-to-sort-null-values

Can do:

```.desc(nulls_last=True))```

> Can we reorder the IMPACT factors so they sort by IMPACT level (think they're currently alphabetical)

Might be easiest to just change the choice fields so their order matches impact - and update via data migration case statement

**Comment by davmlaw** [comment]
Having issues getting this done on variantgrid.com due to disk space, even after making updates smaller


```
python3.8 manage.py fix_impact_change_choice --small_updates
Updating v7. (17 July 2020) VEP: 100/Ensembl/GRCh37 VariantAnnotation L -> 2
Updating v7. (17 July 2020) VEP: 100/Ensembl/GRCh37 VariantAnnotation M -> 3
Updating v7. (17 July 2020) VEP: 100/Ensembl/GRCh37 VariantAnnotation H -> 4
Updating v7. (17 July 2020) VEP: 100/Ensembl/GRCh37 VariantTranscriptAnnotation... O -> 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DiskFull: could not extend file "base/16384/156785.94": No space left on device
HINT:  Check free disk space.
```

**Comment by sksmi** [comment]
Think this change has removed any Impact = MODIFER* from all analyses & templates.

e.g. :92/analysis/9589/
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/c94765f9-00ae-476a-87de-ddeb6c21a592)

Have updated the templates and links which seems to solve the issue going forward, but will need to re-validate any cases that were assessed during this period. ~30 cases affected.

**Comment by davmlaw** [comment]
Thanks for fixing. 

Please let them know it would have led to false positives not negatives. 

Will fix so doesn't affect vg.com after restore

Will come back to this after kids are asleep

**Comment by sksmi** [comment]
Think it's just needs a manual check that we didn't miss anything in validation, I can have a look shouldn't take too long - basically if we used the complex filter the HIGH/MOD variants didn't come through. Caught it in time for yesterday's case so should be fine.

**Comment by davmlaw** [comment]
Actually not that sure how it works if blank, may have led to false negs actually will check in 2 hrs

**Comment by sksmi** [comment]
**PASS**

gnomad & impact sorting in analysis works, variant details page matches analysis workspace grid. 
Super exciting!! 

For future dev/discussion: not sure modifier\* should be in the manual filter. 
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/eaeb2879-40db-498e-a6b4-65983b4d46ee)

Happy to close.

**Comment by davmlaw** [comment]
Added MODIFIED* to issue FilterNode - columns improvements #2326
