### ISSUE TITLE
FilterNode case insensitive search

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#372]
VG Feedback:

* Filtering is currently caps dependent. Probably less risk if caps-independent e.g. conflict = Conflict etc.

While here also add node help text to clarify that null values aren’t included in filter. e.g. 'Null values are excluded from filter unless explicitly defined by user.'

**Comment by sksmi** [comment]
**PASS**

Tested: 
consequence contains FRAMESHIFT/frameshift = 56
gene symbol equal GNB2/gnb2 = 1
gene family description contains Phosphatase/phosphatase = 175

Text displayed.
