### ISSUE TITLE
Manual Variant Entry - 403 forbidden when settings.UPLOAD_ENABLED=False

### ISSUE THREAD

**Issue by a1618617** [SACGF/variantgrid#379]
Hi guys,

Just wondering but is manual variant entry disabled for the time?

I was tryna enter this variant 7:42079899 T>C, but it came up with a Forbidden error message.

**Comment by davmlaw** [comment]
I have disabled uploading because we have run out of disk space.

I am going to apply for an increased quota very shortly

**Comment by davmlaw** [comment]
Need to fix - Manual variants page should not allow you to enter anything if ```settings.UPLOAD_ENABLED=False```

**Comment by davmlaw** [comment]
Can't really test in prod easily, tested on my dev machine...
