### ISSUE TITLE
Site messages need to be more prominent

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#380]
A few times I've put up messages like "Please do not use the system" or "The database is being backed up, you can view but please do not create data as it will be lost" and people ignore it.

Warnings should be in a yellow box, and errors in a red box or something instead of just changing the logos

**Comment by davmlaw** [comment]
They also don't appear on analyses

**Comment by davmlaw** [comment]
Added yellow/red borders for warnings/errors

**Comment by sksmi** [comment]
**PASS**

Test case generated: VG-91 
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/f6ee54ff-dc66-43ef-9929-b14b07170def)

**Comment by davmlaw** [comment]
Should have added a blink tag
