### ISSUE TITLE
Node cloning issue

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#384]
When we clone a node, we re-use the cache from the original node, but this can sometimes fail:

* Clone node A
* Open new cloned node B so it's cached
* Bump the version of A (original)
* Re-open the clone B, then click next page on the grid

Fails saying: Grid failed to load due to: Node 7320 not found

Fixes needed
* Need to handle this failure in cloned node, and fall back is to request the grid from the actual node
* The message is wrong it's the node/version not found

**Comment by davmlaw** [comment]
Before we used to switch what grid was loaded in the grid config, now we always go for the actual node/version but then perform a redirect if it's ok. This adds a 302 but it's quick (<100ms for sure) and most grids take eg seconds to load so still worth keeping this cache I think.

Long term plan is to take a hash of the node config then don't need special case for clones

**Comment by sksmi** [comment]
Testing in: 92/analysis/9666/

Issue with loading the cloned node (B). Node counts don't load in B (5+min). Clicking off/on node doesn't help nor does a basic page refresh. Cloning A again (B2) worked fine.  B1 corrected when I updated the analysis description in analysis settings. 

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/ae5728a8-e52b-478d-ad86-f3b82005bdee)

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/cd93f4ab-f9a6-4f9e-a22b-8fadf18c6ab3)



Side note - have noticed recently (past week or two) that sometimes when I click on a node I need to click quite a few times before it is selected.  Not logging as separate issue as not major enough and possibly just my computer, but wanted to note. 


(testing in progress)

**Comment by sksmi** [comment]
Reproduced in second row of nodes - first clone worked fine, next clones failed (cloned L > R)
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/954704c3-dd4b-480e-ab52-0ba08331c4d2)

**Comment by davmlaw** [comment]
Can't reproduce issue, tried a few dozen times
