### ISSUE TITLE
Stop people from uploading junk

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#387]
While moving the servers I found a few gigs of .bam files that people had uploaded.

We should make sure that we prevent / delete these so people can't fill up our disks with useless files

**Comment by sksmi** [comment]
sorry that was probably me at least a couple of times .. sometimes just dragged and dropped wrong file. Thought it never got saved. Oops..

**Comment by davmlaw** [comment]
Saw a few more files uploaded, I think we can basically just throw away:

.bam, .bai (bam index), .tbi (VCF index)

That'll do for now but make it easy to add more

**Comment by davmlaw** [comment]
Tested variantgrid.com - Tried bam/bai/gff.gz/ico etc, all rejected correctly

Still able to upload VCFs and tags
