### ISSUE TITLE
Tagging improvements

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#39]
* Show gene symbol again, make links to genes
* Make tags for a variant all on 1 row

Split out stuff I don't need to do now into #137 (tagging 2) and #138 - Gene Symbol page - remove top tagged variants grid

**Comment by sksmi** [comment]
@davmlaw  not sure what I need to test here.

**Comment by davmlaw** [comment]
>> Show gene symbol again, make links to genes

The variant tags grid was missing the gene symbol. I put it back, and it now links to gene symbol page

>> Make tags for a variant all on 1 row

On the [analysis] -> [variant tags] page, the previous functionality (bottom row) showed 1 variant tag per row. So if there were multiple tags for a variant, it showed multiple rows.

There is a new grid on the page, where tags are grouped per variant. So if a variant is tagged multiple times

>> link to variant page from tagged variants grid.

Clicking the left-most column on the grids takes you to the appropriate variant page (this had been done for ages)

**Comment by sksmi** [comment]
Assuming you're talking about the tags grid on the tagged variants page? 
http://144.6.229.160/analysis/analyses_variant_tags/

**Comment by davmlaw** [comment]
The top grid is "variants with tags" - which shows all the tags for a variant on 1 row.

Remember you were the one who said:  "Up-voting placing all tags on 1 row."!

The reason there are 2 grids is so:

* tags are linked per variant in the top grid
* You can see all the information about the individual tags in the lower grid (user, analysis, date etc) - you can't easily show this in the top grid, and can't sort it

**Comment by davmlaw** [comment]
TODO: Add headers on variant tags page

**Comment by sksmi** [comment]
Much clearer, works well. Closing as issue above addressed. 
Remaining issue with genome build coords at #194
