### ISSUE TITLE
Can't access some legacy VCFs due to UploadedFile size failing with FileNotFoundError

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#396]
Can't access some VCFs because view_vcf.html is failing in 

```
vcf.uploadedvcf.uploaded_file.uploaded_file.size

FileNotFoundError: [Errno 2] No such file or directory: '/data/variantgrid/data/uploads/combined_PoPCyMJ.vcf'
```

https://rollbar.com/jimmy.andrews/VariantGrid/items/2804/?utm_campaign=occurrence_message&utm_medium=slack&utm_source=rollbar-notification

This is because our UploadedFile should support both web uploads (Django FileField etc) and from a filesystem path:

```
vcf = VCF.objects.get(pk=1343)

In [16]: vcf.uploadedvcf.uploaded_file.get_filename()                                                                                                             
Out[16]: '/tau/data/clinical/aligned/one_truSight/160926_NB501009_0053_AHMTJ3BGXY_GATK/combined.vcf'

vcf.uploadedvcf.uploaded_file.uploaded_file.size # Throws exception
```

We should implement a size property that handles the path case as the Django uploaded file is not there

**Comment by davmlaw** [comment]
Previously, some legacy VCF pages failed, ie:

http://frgeneseq02.imvs.sa.gov.au:92/snpdb/view_vcf/1343 would die with "#2804 FileNotFoundError: [Errno 2] No such file or directory: '/data/variantgrid/data/uploads/combined_PoPCyMJ.vcf'"

This was due to trying to read the size of an uploaded file that didn't exist (as we loaded it off TAU disks)

Now, the VCF page works:

http://frgeneseq02.imvs.sa.gov.au:90/snpdb/view_vcf/1343

**Comment by TheMadBug** [comment]
(Sorry got confused when it said I closed it, but rollbar actions are me)
