### ISSUE TITLE
Analysis tags import - bugfixes

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#397]
* Support analysis_id and node_id being empty (we never store these anyway)
* Skip non-standard variants (ie alt=*) - make some warnings for these but don't insert into DB

At the moment, I worked around this manually by populating node_id/analysis_id with eg "-1" and deleting records with alt=*

**Comment by davmlaw** [comment]
Also got error:

```
Variant matching query does not exist.
Traceback (most recent call last):
  File "/mnt/variantgrid/upload/tasks/vcf/import_vcf_step_task.py", line 69, in run
    items_processed = self.process_items(upload_step)
  File "/mnt/variantgrid/upload/tasks/import_variant_tags_task.py", line 100, in process_items
    variant = Variant.get_from_tuple(variant_tuple, genome_build)
  File "/mnt/variantgrid/snpdb/models/models_variant.py", line 359, in get_from_tuple
    return Variant.objects.get(locus__contig__genomebuildcontig__genome_build=genome_build,
```

**Comment by davmlaw** [comment]
Reloading a pipeline also gives:

```
duplicate key value violates unique constraint "upload_uploadedvcf_upload_pipeline_id_key"
DETAIL:  Key (upload_pipeline_id)=(1652) already exists.
```

Need to clean things properly for reload

**Comment by davmlaw** [comment]
For re-running VCF imports - VariantTagsImportTaskFactory.get_data_classes needs to return [UploadedVCF] to properly handle re-running VCF pipeline

The trouble is, VariantTagsCreateVCFTask then creates new objects, I think we should check whether UploadedVariantTags already exists and if so, delete the existing VariantTagsImport object, and create a new one?

**Comment by davmlaw** [comment]
Scope of changes: Variant tag CSV imports

If you want to user test this, try importing a tags CSV where:

* node_id, analysis_id and name as empty
* A variant will be normalized - ie insert same reference base on the start of both REF/ALT (must actually be the reference base) - ie "3:51385335 GT>GGGAGGAG" (GRCh37)
* Go to import page, then re-import - make sure that it works, and doesn't make 2 copies

There is an issue "tags import 2" or something to do the things we need to do here - see what the original username was, what tags came in from an import, and being able to delete all tags from an import etc

**Comment by sksmi** [comment]
@davmlaw not sure how I can test this? Is there an option to upload tags through the user/admin interface that I'm missing (not that I think there nec should be - could be a messy disaster)?

**Comment by davmlaw** [comment]
* Go to tags page, on the 1-tag per row grid, click download CSV
* Drag and drop that CSV onto upload page

**Comment by davmlaw** [comment]
While it could lead to a messy disaster... I can tell which tags were imported via an upload, and can delete them all pretty easily.

But yeah, would do in test or somewhere you don't care about

**Comment by davmlaw** [comment]
Have been using this periodically as part of https://github.com/SACGF/variantgrid_sapath/issues/81 with no issue
