### ISSUE TITLE
Search for VCF doesn't work

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#398]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2599/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2599/)

NotImplementedError: unknown kind: GMPFocus_20_001_200626_NB501009_0391_AHFHLJBGXG.gatk.hg38.vcf.gz

```
Traceback (most recent call last):
  File "/data/variantgrid/variantopedia/search.py", line 357, in search_within
    build_results = get_results_func(self.search_string,
  File "/data/variantgrid/variantopedia/search.py", line 500, in search_hgvs
    variant_tuple = hgvs_matcher.get_variant_tuple(hgvs_string)
  File "/data/variantgrid/genes/hgvs.py", line 390, in get_variant_tuple
    variant_tuple = pyhgvs.parse_hgvs_name(lookup_hgvs_name, self.genome_build.genome_fasta.fasta,
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 1382, in parse_hgvs_name
    hgvs = HGVSName(hgvs_name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 758, in __init__
    self.parse(name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 772, in parse
    self.parse_allele(allele)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 859, in parse_allele
    raise NotImplementedError("unknown kind: %s" % allele)
NotImplementedError: unknown kind: Haem_21_003_210409_M02027_0122_000000000_JKL85.vardict.hg38.vcf.gzTraceback (most recent call last):
  File "/data/variantgrid/variantopedia/search.py", line 490, in search_hgvs
    if fixed_hgvs := HGVSMatcher.fix_swapped_gene_transcript(hgvs_string):
  File "/data/variantgrid/genes/hgvs.py", line 533, in fix_swapped_gene_transcript
    hgvs = HGVSName(hgvs_name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 758, in __init__
    self.parse(name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 772, in parse
    self.parse_allele(allele)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 859, in parse_allele
    raise NotImplementedError("unknown kind: %s" % allele)
NotImplementedError: unknown kind: Haem_21_003_210409_M02027_0122_000000000_JKL85.vardict.hg38.vcf.gz
```

**Comment by davmlaw** [comment]
Scope of change:

* Previously, sample name search was only performed if the search string contained letters. So eg "10291" would not search for a sample name. Now, we search for sample names on any search string
* Previously, we didn't look for VCF names. Now we search for a VCF of exactly the search string

**Comment by sksmi** [comment]
@davmlaw which searches does this impact? 
- global search
- /snpdb/data

anything else?

**Comment by davmlaw** [comment]
Only the top right hand search box - the snpd/data search is an auto-complete that works differently.

**Comment by sksmi** [comment]
**PASS**

**Comment by sksmi** [comment]
Works in test :90 but not in SAP:92 - deployment setting?

**Comment by sksmi** [comment]
Note still throws rollbar error in test:90
[rollbar 2908 NotImplementedError: unknown kind:GMPFocus_20_001_200626_NB501009_0391_AHFHLJBGXG.gatk.hg38.vcf.gz
](https://rollbar.com/jimmy.andrews/VariantGrid/items/2908/?utm_campaign=occurrence_message&utm_medium=slack&utm_source=rollbar-notification)

error in SAPbeta:92
[rollbar 2599 NotImplementedError: unknown kind: GMPFocus_20_001_200626_NB501009_0391_AHFHLJBGXG.gatk.hg38.vcf.gz](https://rollbar.com/jimmy.andrews/VariantGrid/items/2599/?utm_campaign=occurrence_message&utm_medium=slack&utm_source=rollbar-notification)

**Comment by davmlaw** [comment]
> Works in test :90 but not in SAP:92 - deployment setting? 

Works for me. Can you list the search string you used that failed? 

> Note still throws rollbar error in test:90

We need to be lax about accepting HGVSs as people type in random things they expect to work that are totally non-standard, and it's worth us knowing about them so we can try and fix/accept them one day.

Those VCFs have "G." in them so we run them through HGVS - eg the search string "22G.g8g" would do the same thing

I've made it hide errors unless the HGVS string is "better". It used to do this with InvalidHGVSName but now it also works for NotImplementedError (which is thrown if HGVS fails in a slightly different way)

If you think this error will drown out Rollbar and don't want to mute it, then we can patch this very small change:

https://github.com/SACGF/variantgrid/commit/288c951bc757a34397f5ca1b940a160108b42616

**Comment by sksmi** [comment]
GMPFocus_20_001_200626_NB501009_0391_AHFHLJBGXG.gatk.hg38.vcf.gz
http://frgeneseq02.imvs.sa.gov.au:92/variantopedia/search?search=GMPFocus_20_001_200626_NB501009_0391_AHFHLJBGXG.gatk.hg38.vcf.gz

**Comment by davmlaw** [comment]
So it does find the VCF based on the name...

Can you be explicit about what you mean by it not working?

* If it's showing an error message, that's fixed in patch as per above
* If it's because it only shows results rather than going to them, it's because search was changed to only auto-jump to 1 results when its in your desired build. I think you're using GRCh37 while the VCF is 38. That's not due to this change, and could probably go under: https://github.com/SACGF/variantgrid_com/issues/53

**Comment by davmlaw** [comment]
@sksmi - if issue is error message, need to decide whether to be in hotfix:

https://github.com/SACGF/variantgrid/commit/288c951bc757a34397f5ca1b940a160108b42616

**Comment by davmlaw** [comment]
** SAP Testing **

* Searched for "GMPFocus_20_001_200626_NB501009_0391_AHFHLJBGXG.gatk.hg38.vcf.gz" in both 37/38 - no errors shown or thrown. Jumped to VCF in 38 ok

**Comment by davmlaw** [comment]
Last seen 34 days ago
