### ISSUE TITLE
Analysis panel resizing

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#401]
This analysis - https://variantgrid.com/analysis/1093/ - crashed with a JS recursion depth exceeded (panel layout) 

It was:

```
In [11]: a.analysis_panel_fraction
Out[11]: 0.15056022408963585
```

Changed to 0.2 and it loaded ok.. 

Resizing the panel doesn't store anymore, gives

```
 / UI Layout Callback Error
The center onresize_end callback is not a valid function.
```

**Comment by davmlaw** [comment]
May need to do a data migration to bump old analyses above the minimum

**Comment by davmlaw** [comment]
There were 2 bugs here:

* Saving the analysis panel width was broken due to removing a variable causing a callback to silently fail (well, it may have caused the warning but no error)
* Loading a very narrow analysis panel with minSize on the east panel (grid/editor) caused the recusion error - found no way to fix this, so no way to limit how small users make it, however I do make sure it loads the min 200 width initially when loading the analysis

**Comment by davmlaw** [comment]
Testing:

* Make the analysis as small as it can go - reload analysis - used to die with recursion error, now fixed
* Move analysis panel size - then reload - make sure it saved position (approx)
* Move analysis panel so node editor/grid is as small as possible. Reload and make sure it comes back as min 200 pixels

**Comment by sksmi** [comment]
**ISSUE**

Not critical. 

Tested: :90/analysis/9522/


PASS: Divider remains in position when analysis opened and closed. 
PASS: Divider can't be moved completely to the left.
FAIL: Javascript error still there if analysis reopened with divider completely to the left.  Can't remove error so analysis becomes inaccessible. 
[Rollbar 2915 Uncaught RangeError: Maximum call stack size exceeded](https://rollbar.com/jimmy.andrews/VariantGrid/items/2915/?utm_campaign=occurrence_message&utm_medium=slack&utm_source=rollbar-notification)
FAIL: Divider can be moved completely to the right. (arguably out of scope)
PASS: Analysis can be reopened with divider completely to the right.

**Comment by davmlaw** [comment]
> FAIL: Javascript error still there if analysis reopened with divider completely to the left.

Are you able to give more info on how exactly you recreated this, and can you link to an analysis that still fails?

> FAIL: Divider can be moved completely to the right. (arguably out of scope)

Yeah I couldn't fix that, so had to reset it upon loading

**Comment by sksmi** [comment]
@davmlaw 

> FAIL: Javascript error still there if analysis reopened with divider completely to the left.
> 
> Are you able to give more info on how exactly you recreated this (via the admin? Via an analysis that was still open before the reload?), and can you link to an analysis that still fails?

Link to analysis above url not posted due to repo. Couldn't recreate again and if I open analysis above it's fine. 

Not sure what I did differently - can't seem to recreate the Maximum call stack size exceeded error today - was happening on every analysis tested last week. Tired switching between screen sizes still didn't recreate.

Happy to close and re-open when it occurs again.

**Comment by sksmi** [comment]
Just managed to recreate it with this analysis: http://frgeneseq02.imvs.sa.gov.au:90/analysis/9540/
Only thing I did was open the analysis from 90/analysis/analyses/list/.

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/cc17152f-09a8-40a2-bc75-8a154fb83cbc)

**Comment by davmlaw** [comment]
Hasn't been seen in environments with the fix since Sarah reported it 19 days ago.

Perhaps it was an issue with cache or something. Closing, will re-open if it happens again
