### ISSUE TITLE
Analysis grid - gene symbol column, create gene child filter icon now invisible

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#407]
This used the "GeneListNode" class to add background to an icon, is now invisible.

This was removed due to the "detach during drag" changes.

**Comment by sksmi** [comment]
**PASS** 
90/analysis/9538/

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/2acb2d04-00e6-4d95-925e-571587962150)
