### ISSUE TITLE
Can't add "sample gene list" to analysis variables

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#410]
This means you can't recreate the GOI template anymore

**Comment by sksmi** [comment]
Think this one will need to be addressed for current deploy. Are you able to investigate and provide an impact assessment on the change? e.g. how risky, which features/pages potentially affected? Preference would be to get the change into test env :90 today if agreed by the team so I have the weekend to make sure it's ok.

**Comment by sksmi** [comment]
Not sure if this is related to the above/fixed at same time, but if you save a GOI restricted sample node the GOI is removed. Can test with this sample: :92/snpdb/view_sample/20133

**Comment by davmlaw** [comment]
Yeah it doesn't show as I removed "sample_gene_list" from the SampleNodeForm on On 10/05/2021 08:38 PM with comment "#347 - SampleNode w/SampleGeneList behaves same as gene list node wrt coverage"

I am not sure what I was doing here, I added "has_gene_coverage" then hid that AND "sample_gene_list" from the form

**Comment by davmlaw** [comment]
OK, fixed - keeping track as this one is likely to be hotfixed on top of current deployment after validation is done then re-tested:

https://github.com/SACGF/variantgrid/commit/4daccfed4ce6ae2d4eca42dbb76342e05007e992

There was also an issue (that you'd only ever see with sample node / sample gene list) where if there were multiple variables in a node, it was shown twice in the "Template Run" tab of analysis settings.

**Comment by sksmi** [comment]
**PASS** 

Gene list setting saved in template:
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/cecb940d-bab5-43ea-bf0d-ca39b3f85b98)

Tested template: 90/analysis/9555/
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/5e6ebdf2-32e6-4d47-a7fc-fdd87be7d8e8)
