### ISSUE TITLE
Same contig liftover (eg MT) 

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#416]
At the moment, we run MT variants through ```create_liftover_pipelines``` while we could use the same contig shortcut (just create a VariantAllele in the other build with ```conversion_tool=SAME_CONTIG```)

**Comment by davmlaw** [comment]
Need to use a MT variant that doesn't exist or you haven't created an allele for (does that if you visit the allele or variant page for MT)

**Comment by EmmaTudini** [comment]
@davmlaw What needs to be tested?

**Comment by davmlaw** [comment]
Test liftover on MT variants

* Take an existing MT variant, modify the coordinate/allele then search for it, if it doesn't exist create it, you know it's new
* Visit the variant or allele page, which should trigger liftover
* Liftover should be almost instant as it just links the same variant against both builds (as they have the same MT contig in 37/38) it should say the liftover method was "same contig liftover" instead of ClinGen / NCBI

**Comment by davmlaw** [comment]
Also should probably test classification - find a new MT that doesn't exist from search, instead of creating it, import a fake classification with that coordinate

**Comment by EmmaTudini** [comment]
As far as I was aware, MT variants were still turned off in Shariant cause we were deciding on an evidence key. So going to leave testing for this for another time.

**Comment by EmmaTudini** [comment]
@TheMadBug Has anything changed for this?

**Comment by davmlaw** [comment]
If we don't use this for Shariant - can we just close it?

It was tested on the other environments, otherwise will just sit for ages.

I do think we should prioritise the new EKeys that allow us to support non coding, mito etc etc

**Comment by TheMadBug** [comment]
Closing for now - reopen if we need to.
