### ISSUE TITLE
Be able to set different thresholds for minimum coverage based on enrichment kit. 

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#421]
**FEATURE REQUEST**

Be able to set different thresholds for minimum coverage based on enrichment kit. 

e.g. for exome min depth = 20. Doesn't make sense for haem panel which has a much higher threshold. 

Low priority.

**Comment by davmlaw** [comment]
Added field to enrichment kit. If not set, or sample doesn't have one, then fall back on using global default from settings

**Comment by davmlaw** [comment]
Actually thinking about it should rename sample.get_minimum_coverage to desired coverage so we can distinguish between the two ideas

**Comment by davmlaw** [comment]
Not testable on vg test, will do during 3.1 SA Path validation
