### ISSUE TITLE
reCAPTCHA for public registration

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#438]
There's some kind of bot that keeps registering users.

We should add a reCAPTCHA to stop it.

Also need to install the mail server on AWS so that people can actually register

**Comment by TheMadBug** [comment]
re mail server, you can use the AWS one, but you have to go via sandbox mode first.
Then apply to have sandbox removed.
AWS will also send outgoing emails on behalf of another email address, and you must receive an email address from AWS and then authorise AWS to send emails on that behalf.
It's... a bit of a process, but the email server is well trusted by the end of it, uses proper authentication, can now be Sydney based.
If you want to get things moving, prob no issue setting up your own email server and migrating later.

**Comment by davmlaw** [comment]
Instructions on PiPy refer to out of date version of library, need to actually do implementation:

https://stackoverflow.com/questions/22665211/is-there-any-solutions-to-add-captcha-to-django-allauth

**Comment by davmlaw** [comment]
OK, got a CAPTCHA on it now. However postfix gives:

```
Network is unreachable
```

Apparently AWS ban outgoing mail by default, and you have to ask to turn it on.

https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/?nc1=h_ls

The other options is not require emails (CAPTCHA should hopefully prevent issues?):

https://django-registration.readthedocs.io/en/3.1/one-step-workflow.html

**Comment by davmlaw** [comment]
OK just went with allowing open registration (protected by ReCaptcha3)
