### ISSUE TITLE
Add contig to transcript version, option to filter analyses by contig

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#451]
**Currently working in branch:** analysis_node_get_contigs

Even without using partitions, you can get a large speedup in analysis queries by filtering by contig.

For 3 genes (STAG2, MPL, ZRSR2) on 2 chroms (1/X)

Old query - 8.2s
New query - 2.2s

Just need to add a filter to locus:

```
# Add to join
inner join "snpdb_locus" on
	("snpdb_variant"."locus_id" = "snpdb_locus"."id" and snpdb_locus.contig_id in (1, 23))
# Adding to where clause seems to work equally well
WHERE "snpdb_locus".contig_id in (1, 23)
```

Just adding them in there, where they are not really helping doesn't seem to hurt, eg HSS2008 sample - no other filters:

Old query - 806k rows in 7.682s
Adding all contigs for build - 806k rows in 7.7s

So maybe just always include it.

This is needed if/when we end up partitioning the variant table by contig, which should make it even faster.

**Comment by davmlaw** [comment]
* Add contig to GeneVersion, so we can pull it out with an (inner) SQL query
* AnalysisNodes implement get_contigs() - defaults to all in genome build
* Implement get_contigs via retrieving from geneversions (for nodes that have genes in baseclass)
* In calculate sample stats - count contigs in sample - a lot of panels might be missing contigs - be able to handle not having this as will need to calculate on existing data slowly over time
* Benchmark 
* Add contig filter to final query, benchmark and compare

**Comment by davmlaw** [comment]
Before we do anything - need to check whether all transcripts from GeneVersion are always within a single contig, might have to deal with patches etc and thus pull from TranscriptVersion instead. Check performance of that

**Comment by davmlaw** [comment]
One of the interesting things is the performance only comes when you explicitly list the contig IDs, not from an inner query, ie need to call list as per:

```
            contigs = Contig.objects.filter(transcriptversion__genome_build=self.analysis.genome_build,
                                            transcriptversion__gene_version__gene__in=genes_ids_qs).distinct()
            # Small enough number of contigs it's ok to store in Q as list
            q_gl &= Q(locus__contig__in=list(contigs))
```

**Comment by davmlaw** [comment]
Would be good to be able to turn this on / off easily. It may not be worth doing contig filtering if you know it's going to be all of them etc.

Of course the real question is how will it perform once we have partitions - would be good to be able to do that, needs to be inheritance partitions as the auto ones can't have a FK in Django

While here it would be good to start recording what % of time is spent loading nodes and getting queries etc, vs actually executing the SQL

**Comment by davmlaw** [comment]
OK, I think this makes things faster, but still need to test on real data, eg those massive WGS samples etc on prod.

So I've made an analysis setting ```node_queryset_filter_contigs``` that you can set to turn this on/off (off by default)

Can also benchmark an analysis looking at individual node times:

```
from collections import defaultdict
from analysis.models import Analysis, AnalysisNode
analysis = Analysis.objects.get(pk=507)
nodes = analysis.analysisnode_set.select_subclasses()
node_times = defaultdict(list)
for node in nodes.order_by(“-load_seconds”):
    node_times[node.get_node_class_label()].append(node.load_seconds)
```

Still TODO: Run a few benchmarks and see if there's an advantage to look in eg only contigs 1-24 vs all of the full ones for a genome build (randoms etc) - we could then store that when a sample is loaded, so that we can reduce what we look at.

**Comment by davmlaw** [comment]
The DB schema migration that set null=False on TranscriptVersion.contig failed on shariant test as there were some legacy transcript versions that had no "chrom" in data

Having chrom is part of the test as to whether our local copy can be used for variant matching, so these will never be considered for matching. Verified by submitting a few imports against them, they went straight to ClinGen and worked/failed depending entirely on clingen (ie didn't do local HGVS conversion at all) 

They also crash out if you try and view the transcript or transcript version page. 

The import source of them confirms they are from very ancient imports:

```
[‘File: ref_GRCh37.p5_top_level.gff3.gz’,
 ‘File: ref_GRCh38.p2_top_level.gff3.gz’,
 ‘File: Unknown’]
 ```
‘File: ref_GRCh37.p5_top_level.gff3.gz’, also has some good chroms in there
but the only good 38 is ‘File: ref_GRCh38_top_level.gff3.gz’,

So, we will:

* Manually delete them on Shariant test
* Perform re-matching as verification
* If that's all ok, then we can do a data migration to delete anything lacking a chrom from all systems

**Comment by TheMadBug** [comment]
Should also be noted the source from the non File: Unknown file are trivial

```

In [13]: TranscriptVersion.objects.filter(import_source__url='File: ref_GRCh38.p2_top_level.gff3.gz').count()                                                                                     
Out[13]: 1

In [14]: TranscriptVersion.objects.filter(import_source__url='File: ref_GRCh37.p5_top_level.gff3.gz').count()                                                                                     
Out[14]: 7

In [15]: TranscriptVersion.objects.filter(import_source__url='File: ref_GRCh37.p5_top_level.gff3.gz', data__chrom__isnull=True).count()                                                           
Out[15]: 2

In [16]: TranscriptVersion.objects.filter(import_source__url='File: Unknown', data__chrom__isnull=True).count()                                                                                   
Out[16]: 21121

In [17]: TranscriptVersion.objects.filter(import_source__url='File: Unknown', data__chrom__isnull=False).count()                                                                                  
Out[17]: 0
```

**Comment by davmlaw** [comment]
OK, I think this should do the trick - also does a check in case they had been linked anywhere that needed them:

```
from genes.models import TranscriptVersion

bad_tvs = TranscriptVersion.objects.filter(data__chrom__isnull=True)
if num_bad_tvs := bad_tvs.count():
    print(f"Deleting {num_bad_tvs} legacy TranscriptVersion records missing 'chrom' entries")
    _, deleted = bad_tvs.delete()
    deleted.pop("genes.TranscriptVersion", None)  # Expected
    if deleted:
        raise ValueError(f"Unexpected CASCADE deletion from removing bad TranscriptVersion records: {deleted=}")
```

**Comment by davmlaw** [comment]
Modified migration has been run on shariant test

**Comment by davmlaw** [comment]
Doesn't break anything but it doesn't seem to make much difference - so will just leave it turned off. Was only really expecting a massive gain once we partitioned things by contigs

https://variantgrid.com/analysis/240/
w/o contigs - 1.66 min, 1.39 min, 1.42 mins
With contigs - 1.51 min, 1.45 min, 1.45 mins, 1.46

One thing I did notice though is GRC38 data loads much faster (probably as we have way less variants)

**Comment by davmlaw** [comment]
This did break things if set as get_parent_contigs didn't work in nodes with parents.

Updated server, tested ok
