### ISSUE TITLE
Variant interesting summary - counts variants not classifications

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#456]
* Go to classifications page, copy paste a HGVS entry that has >=2 classifications, eg: "NM_000492.3(CFTR):c.350G>A"
* Change it so that it doesn't have transcript, ie "CFTR:c.350G>A", paste into search box

The search runs ```_variant_interesting_summary``` and shows a count for classifications, but only ever shows a max of 1.

This code was designed to count variants in a domain, so counts variants, needs to eg count classifications

**Comment by TheMadBug** [comment]
(Duplicating my comment from the issue raised against search).
What I believe this is doing is finding any variant that has at least 1 classification the user is allowed to see.
Then reporting the number of classifications, regardless of if the user has ability to see them.

**Comment by davmlaw** [comment]
vt test - shows 2 classifications when I have permission for 2
