### ISSUE TITLE
Reference Variants linked together into 1 Allele

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#465]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3224/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3224/)

```
Traceback (most recent call last):
  File "/opt/variantgrid/classification/models/classification.py", line 2147, in _generate_c_hgvs_extra
    c_hgvs = hgvs_matcher.variant_to_c_hgvs_extra(variant, transcript_id)
  File "/opt/variantgrid/genes/hgvs.py", line 533, in variant_to_c_hgvs_extra
    return self.variant_to_hgvs_extra(variant, transcript_name)
  File "/opt/variantgrid/genes/hgvs.py", line 510, in variant_to_hgvs_extra
    raise self.TranscriptContigMismatchError(contig_msg)
TranscriptContigMismatchError: Variant contig=21 - NC_000021.8 (48129895) (chrom=21) while Transcript NM_205768.3 contig=1 - NC_000001.10 (249250621) (chrom=NC_000001.10)
```

**Comment by davmlaw** [comment]
Looks like all of these have variant set to "21:38852938 A>="

Need to work out why

**Comment by davmlaw** [comment]
The classifications were imported and set to the variant OK

However, the variants were all linked to the same allele - and thus I think when it was lifted over, they all got the same variant in GRCh38

So, need to work out how reference variants are assigned to allele - must be something going wrong

**Comment by davmlaw** [comment]
TODO: Need to make some kind of migration that puts these right. Can find via:

```
variant_alleles = list(Variant.objects.filter(alt__seq=Variant.REFERENCE_ALT, variantallele__isnull=False).order_by("variantallele__allele", "variantallele__genome_build").values_list("pk", "variantallele__genome_build", "variantallele__allele"))
last_allele = None
last_build = None
for v, gb, a in variant_alleles:
    if a == last_allele and gb == last_build:
        print(v, gb, a)
    last_allele = a
    last_build = gb
```

There is 1 affected allele in SAP - Allele 18047 with 2 legacy classifications

So this will need to be HF'd to SAP (for when Shariant reference classifications come down) and the the migration run (probably manually).

**Comment by TheMadBug** [comment]
FYI, Shariant prod had this output
```
2974286 GRCh38 6283
3799209 GRCh38 6283
```
Not to concerned about test as can wipe the classifications and re-import them all.
Agree that we'll need to coordinate a patch into SA Path for handling Shariant downloads.

**Comment by EmmaTudini** [comment]
@TheMadBug @davmlaw Just to confirm, is the allele above the only one affected in Shariant? ALMS1 has always been a mess so luckily it never made it into exports

**Comment by TheMadBug** [comment]
Can confirm only two affected variants in Shariant prod - which has ALMS1 as you've already found
https://shariant.org.au/variantopedia/view_variant/2974286
https://shariant.org.au/variantopedia/view_variant/3799209

**Comment by davmlaw** [comment]
Another reference issue I found is that somewhere we're converting '.' to "=' but not everywhere, ie have some variants:

```
In [11]: Variant.objects.filter(locus__contig__refseq_accession='NC_000001.11', locus__position=244053917, locus__ref__seq='G')                                   
Out[11]: <QuerySet [<Variant: 1:244053917 G>A>, <Variant: 1:244053917 G>.>]>
```

which causes an error because then it looks up the '='

```
  File "/home/dlawrence/localwork/variantgrid/upload/vcf/bulk_minimal_vcf_processor.py", line 53, in finish
    self.batch_process_check(0)  # Insert anything that is there
  File "/home/dlawrence/localwork/variantgrid/upload/vcf/bulk_minimal_vcf_processor.py", line 48, in batch_process_check
    variant_ids = self.variant_pk_lookup.get_variant_ids(self.variant_hashes)
  File "/home/dlawrence/localwork/variantgrid/snpdb/variant_pk_lookup.py", line 57, in get_variant_ids
    raise ValueError(f"Variant hash {variant_hash} had no PK in DB!")
ValueError: Variant hash (95, 244053917, 77049, 59792) had no PK in DB!
```

**Comment by davmlaw** [comment]
This issue occurs when populate_clingen_alleles_for_variants is called with multiple reference variants (probably only happens during a classification import)

So I'd expect it to be quite rare.

When the migration runs, it should print out a list of affected variant IDs, then call management command classification_ensure_alleles_and_liftover

It's worth collecting these variant IDs and then making sure they've been properly assigned an Allele.

If you view the allele you now shouldn't get TranscriptContigMismatchError anymore

**Comment by EmmaTudini** [comment]
Pretty sure this is working but going to leave in review so that I can check after prod deploy.

**Comment by EmmaTudini** [comment]
Had a look at ALMS1 variants in Shariant that had been lifted over and they all seem to link to the correct Clingen ID now. Genomic coordinates from above no longer exist in prod.

**Comment by EmmaTudini** [comment]
Think this issue is ok to close?

**Comment by TheMadBug** [comment]
This will be HF to SA Path, I'll move it to the SA Path test status column

**Comment by davmlaw** [comment]
Can't really test this, but code was very simple
