### ISSUE TITLE
User Feedback : Single record report - coordinates still hg19

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#466]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3236/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3236/)

```
User Feedback : Single record report - coordinates still hg19
```

**Comment by TheMadBug** [comment]
FYI, this would require a code patch (albiet a very small one) as well as a change to the report vue template (also very small).

Currently the template is provided with the values of all the evidence keys, but the normalised 38 c.hgvs is kept against the classification record - which is not passed to the report.
See classification_export_report.py

**Comment by TheMadBug** [comment]
Server code change implemented as part of commit
1251087cdb31c95bf025f638d4c916620caf964a
The change is issolated to `classification_export_view` so wont have any affect on code outside of the report.

When this is applies, the report template also needs to change to convert references from
`this.c_hgvs`
to
`this.c_hgvs_grch38`

which will then use the calculated 38 representation rather than the evidence key.

**Comment by davmlaw** [comment]
The user reported: " In the report section the coordinates are still showing as hg19/GRCh37. This should be updated to hg38."

This is g.HGVS not c.HGVS, so I think the change is to modify the report line:

```
<format :evidence="gene_symbol"></format>: hg19 (GRCh37) <format :evidence="g_hgvs"></format>
```

And change the hardcoded hg19 (GRCh37) to hg38 (GRCh38) - will assign to TAU bioinformatics

**Comment by davmlaw** [comment]
@TheMadBug ok to undo the Pyhton code change? HGVS should be the same in both builds and you'd never eg want to use the wrong build in your reports

**Comment by davmlaw** [comment]
Even better may be to actually use the genome build evidence key, just in case they classify GRCh37 ones

**Comment by TheMadBug** [comment]
Depends if 37 reports should be reported in 38 regardless of how they were originally worked out.
But I have no special insight as to which c.hgvs is required, and no other VG installation uses it yet.

**Comment by davmlaw** [comment]
The g_hgvs will always be in the genome build the classification was made in, which matches genome_build evidence key

**Comment by davmlaw** [comment]
Song tested and deployed 15/12/2021:

I checked on several classifications and it all works. So I updated VG3 too.
