### ISSUE TITLE
Reference Variant inserted with alt='.'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#467]
Another reference issue I found is that somewhere we're converting '.' to "=' but not everywhere, ie have some variants:

```
In [11]: Variant.objects.filter(locus__contig__refseq_accession='NC_000001.11', locus__position=244053917, locus__ref__seq='G')                                   
Out[11]: <QuerySet [<Variant: 1:244053917 G>A>, <Variant: 1:244053917 G>.>]>
```

which causes an error because then it looks up the '='

```
  File "/home/dlawrence/localwork/variantgrid/upload/vcf/bulk_minimal_vcf_processor.py", line 53, in finish
    self.batch_process_check(0)  # Insert anything that is there
  File "/home/dlawrence/localwork/variantgrid/upload/vcf/bulk_minimal_vcf_processor.py", line 48, in batch_process_check
    variant_ids = self.variant_pk_lookup.get_variant_ids(self.variant_hashes)
  File "/home/dlawrence/localwork/variantgrid/snpdb/variant_pk_lookup.py", line 57, in get_variant_ids
    raise ValueError(f"Variant hash {variant_hash} had no PK in DB!")
ValueError: Variant hash (95, 244053917, 77049, 59792) had no PK in DB!
```

**Comment by davmlaw** [comment]
I think this was created from liftover VCFs

**Comment by davmlaw** [comment]
OK, having issue with data migration failing due to:

```
ClinVar.objects.filter(variant__alt__seq='.').count()
```

Need to move these to seq='='

**Comment by davmlaw** [comment]
Ran migration:
```
  Applying snpdb.0045_one_off_reference_variant_fixes...Deleting Alleles for GenomeBuild object (GRCh37) variants - may want to check these have Alleles later:
3066206, 3066179, 3066165, 3066155, 3066153, 3066143, 3066121, 3049859, 2959053, 2475760
Deleting Alleles for GenomeBuild object (GRCh38) variants - may want to check these have Alleles later:
3064911, 3064856, 3064855, 1521937
Updating variant on 231 ClinVar records (reference variant with alt='.')
 OK
```

Then data migration option "ensure alleles and liftover"

The GRCh38 annotations need to run, then afterwards will check that everything is ok

**Comment by davmlaw** [comment]
Ah, I think I needed to restart the services before doing ensure alleles and liftover - will restart and re-do after annotation is run

**Comment by EmmaTudini** [comment]
@davmlaw What should be tested here? @TheMadBug Does anything need to be added to the list for deploy?

**Comment by TheMadBug** [comment]
Any issues here would have been caught by re-matching all records.
The migration script is also run automatically as part of the upgrade tool - so no extra steps here.

**Comment by EmmaTudini** [comment]
@TheMadBug @davmlaw Any way for me to test that this worked in prod?

**Comment by TheMadBug** [comment]
Looking for instances of ref=alt in prod and I can only fine one where that happens in the liftover
https://shariant.org.au/variantopedia/view_allele/2964

I don't think any records in prod were affected, think this one is safe to close
