### ISSUE TITLE
HGVS - invisible unicode symbols in strings

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#469]
We get: c.HGVS - Error attempting to parse variant coordinate

Searching for it on ClinGenAllele Registry gives:

HgvsParsingError - Explanation: One of the characters c,g,p,m,n,r was expected, but the character '�' was found 

I looked in the shell:

```
$ echo "NM_000495.3:​c.3A>C" | od -c
0000000   N   M   _   0   0   0   4   9   5   .   3   : 342 200 213   c
```

We should detect these and give a much better error than we currently do

**Comment by davmlaw** [comment]
Another example copy/pasted from ZenHub is NR_033294.1(SNORD118):​n.*5C>G

**Comment by davmlaw** [comment]
**Testing**

Copy/paste below into search box - If you move the cursor between the colon and n/c you can see there's an extra non-printable character in there.:

* NM_000495.3:​c.3A>C
* NR_033294.1(SNORD118):​n.*5C>G

Make sure that they get a warning about being cleaned (including non-printable characters) and actually resolve the HGVS properly.



Checked and this was only coming up in search, not sent to us in Classifications, so will just fix search at the moment

```
import re
import string
from classification.models import Classification


def clean_string(input_string: str) -> str:
    """ Removes non-printable characters, strips whitespace """
    return re.sub(f'[^{re.escape(string.printable)}]', '', input_string.strip())


for cs in Classification.objects.all():
    if old_hgvs := cs.get_c_hgvs(cs.get_genome_build()):
        cleaned = clean_string(old_hgvs)
        if cleaned != old_hgvs:
            print(f"{cs} cleaned {old_hgvs} => {cleaned}")
```

**Comment by davmlaw** [comment]
Is in a few s test classifications (entered by hand) but not in prod - fixing by hand

**Comment by EmmaTudini** [comment]
Testing:
- Logged in as non-admin assigned to VCGS (emmatudini@gmail.com)
- Searched for NM_000495.3:​c.3A>C (ref base not correct) and NM_000495.3:​c.3G>C (confirmed that non-printable character was in both) 

Expected output: Should be told about non-printable character being cleaned. No error in search.

Actual output: **Failed** - search works but not told about chgvs being cleaned. Not too fussed about not being told though

**Comment by davmlaw** [comment]
Someone searched for invisible unicode strings in gene names, so I stripped all invisible characters from search in #477

I don't think anyone cares is invisible strings are stripped from their search - they didn't know they were there to start with so better to just silently do what they wanted to do I reckon
