### ISSUE TITLE
Classification - store HGVS matching method

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#470]
Now we have different methods - we should store in a classification how the HGVS matching was done

Store in Variant matching flag - each classification has one already and storing in flags would allow us to keep track of history

Change is in Classification.set_variant - say what version etc of PyHGVS / ClinGen request date

Should do a data migration that sets all flag comments (currently set to 'Variant Matched) to "matched with PyHGVS vXX"

This will be wrong in Shariant test as some have now used ClingenAllele registry, but will be right in prod where it matters

**Comment by davmlaw** [comment]
**LRG_199t1:c.357+1G>A**

> Matching on GRCh37 LRG_199t1:c.357+1G>A resolved to X:32841411 C->T
> 
> HGVS matched by 'pyhgvs v0.11.1 as 'NM_004006.2:c.357+1G>A' (from LRG_RefSeqGene)'
> 

**NM_004006.2:c.357+1G>A**

> 
> Matching on GRCh37 NM_004006.2:c.357+1G>A resolved to X:32841411 C->T
> 
> HGVS matched by 'pyhgvs v0.11.1'

**NM_015120.4(ALMS1):c.4156dupA**

> Matching on GRCh37 NM_015120.4(ALMS1):c.4156dupA resolved to 2:73677806 T->TA
> 
> HGVS matched by 'ClinGen Allele Registry'

**Comment by EmmaTudini** [comment]
@TheMadBug Will it be necessary to migrate if we re-match everything in prod? Also have seen that this works many times in test so passing it

**Comment by TheMadBug** [comment]
The act of re-matching everything will indeed populate this information.

**Comment by TheMadBug** [comment]
Flag are now full of this information
