### ISSUE TITLE
Search - move code back into individual models

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#473]
The search.py has internal knowledge of how records are structured, it would be neater to move this code back into the models so they are responsible for themselves.

James suggested we raise a search signal, which models could choose to listen to. Need to test signal overheads, and work out whether we want to eg dispatch to all and let them do their own regex match

**Comment by davmlaw** [comment]
Searching for:

MT:1000G>T - variant coordinate
1:169519049 T>C - variant coordinate
chr1:169519049 - Locus
CFTR:c.350G>A - HGVS gene 

Currently dies with:

```
  File "/home/dlawrence/localwork/variantgrid/ontology/models/models_ontology.py", line 304, in get_or_stub
    prefix = OntologyService(prefix)
  File "/usr/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.8/enum.py", line 663, in __new__
    raise ve_exc
ValueError: 'CFTR' is not a valid OntologyService
```

**Comment by TheMadBug** [comment]
I've changed the signal usage from send to send_robust (so they'll all get called, even if 1 throws an exception).
And to report search exceptions to roller but otherwise keep going.

Also made it specifically so that the ontology_search wouldn't complain if everything that had a semicolon in it wasn't a valid ontology.

**Comment by davmlaw** [comment]
@TheMadBug - can we close this?

**Comment by TheMadBug** [comment]
Possibly, I still want to break search more - (I started a branch ages ago to move variant search out but never got time to finish it).

Going forward just make sure we do new searches in the same way as ontology_search.py and classification_search.py, and migrate the existing search whenever time permits. I suppose no great need to have an issue open for a low priority refactor.

**Comment by TheMadBug** [comment]
Search has been broken into smaller parts for many months now. Closing.
