### ISSUE TITLE
Data tables could do with a way to move quickly through pages

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#474]
Eg jump to page, -/+ 5 or 10 pages

Would be fine making this optional, or only visible if there are a large amount of pages (jump 10% through them etc)

Motivation was wanting to sort by date and look at a period 6 months ago.

**Comment by TheMadBug** [comment]
Since I was playing around with DataTables anyway, e.g. can now have this HTML with no need for tags
```
 <table id="event-datatable" class="event-table sticky-header" data-datatable-responsive="true" data-datatable-url="{% url 'event_log_datatable' %}" data-datatable-data="datatableFilter"></table>
```

Found some code that lets DataTables have a user enterable page number. Have a play and see if it helps your use case.

**Comment by TheMadBug** [comment]
This has been in prod for a while
