### ISSUE TITLE
HGVS variant to c.HGVS error when bad/missing transcript

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#478]
The old ones in rollbar are fixed, the new ones are due to the transcript ID being wrong, eg:

Given "NM_00128225.2" but the real transcript is "NM_001282225.2"

This is due to filter_best_transcripts_by_accession not returning anything.

If there are no attempted methods we should return BadTranscript - I took that out as it was taking way too long when doing a HGVS search with a gene symbol as it was having to do dozens of requests. Maybe cache results or make it optional to do the lookup.

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3261/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3261/)

```
Traceback (most recent call last):
  File "/opt/variantgrid/classification/models/classification.py", line 2147, in _generate_c_hgvs_extra
    c_hgvs = hgvs_matcher.variant_to_c_hgvs_extra(variant, transcript_id)
  File "/opt/variantgrid/genes/hgvs.py", line 764, in variant_to_c_hgvs_extra
    return self._variant_to_hgvs_extra(variant, transcript_name)
  File "/opt/variantgrid/genes/hgvs.py", line 660, in _variant_to_hgvs_extra
    hgvs_name, hgvs_method = self._variant_to_hgvs(variant, transcript_name)
  File "/opt/variantgrid/genes/hgvs.py", line 741, in _variant_to_hgvs
    raise ValueError(f"Could not convert {variant} to HGVS - tried: {attempts}")
ValueError: Could not convert 22:50721875 G>GC to HGVS - tried: 
```

**Comment by davmlaw** [comment]
The fix here is to correctly identify when the transcript is missing or bad, ie:

```
BadTranscript: Transcript 'NM_00128225.2' does not exist in the GRCh38 RefSeq database.
```

**Comment by EmmaTudini** [comment]
Testing:
- Imported NM_0005466.6(TP53):c.38delC (should be NM_000546.6) as GRCh37

Expected output: Should fail variant matching with error
Actual output: Passed

**Comment by EmmaTudini** [comment]
Moving to pending release and raised a new issue - https://app.zenhub.com/workspaces/everything-space-5bb3158c4b5806bc2beae448/issues/sacgf/variantgrid_private/3173 (couldn't transfer to variantgrid repo for some reason)
