### ISSUE TITLE
TranscriptVersions - filter_best_transcripts_by_accession only uses transcripts I have, even for ClinGen

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#481]
I ask for NM_000314.4 (GRCh37)

This has an alignment gap. The next transcript up for 37 is v8, so because I'm going through the transcripts I have, I skip v5, v6, v7 using ClinGen (v5 would have worked)

**Comment by EmmaTudini** [comment]
Think this is now tested in general variant testing using diff file - see https://app.zenhub.com/workspaces/everything-space-5bb3158c4b5806bc2beae448/issues/sacgf/shariant-admin/124
@davmlaw Is there anything else that I should check?

**Comment by TheMadBug** [comment]
This is def covered by the diff, I don't think there's anything else to test if we're happy with current transcript choices.
