### ISSUE TITLE
ClinGen Allele Registry for HGVS can return no data for unknown alleles

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#484]
If you query ClinGen with a HGVS that it hasn't seen before, it returns no useful data.

I think this is because we're using the GET hgvs query, if we switch to POST then it'll create a new one

**Comment by EmmaTudini** [comment]
@davmlaw Were you planning on implementing this before going to Shariant prod?

**Comment by davmlaw** [comment]
Yep. I think it works now

**Comment by EmmaTudini** [comment]
Great! Thank you!

**Comment by davmlaw** [comment]
I tried to re-match the ones that had previously failed with no clingen allele ID, but now the fail with no GRCh37 coordinates in build.

I went and registered one of these: NM_014516.3(CNOT3):c.943del and even after registering, it had no GRCh37 coordinates (only 36 and 38). I guess this makes sense as everyone uses 37 so 38 exclusive stuff wouldn't have been registered as fast

**Comment by EmmaTudini** [comment]
@davmlaw Since Clingen allele registry fails sometimes, I think we need to be very careful around which transcripts are assigned as having an alignment gap. It was ok having some fail previously via Clingen allele registry as we went to NCBI remap as a backup for liftover. Most variants now being matched using clingen allele registry due to an alignment gap, weren't causing problems previously.

**Comment by EmmaTudini** [comment]
@davmlaw For NM_014516.3(CNOT3):c.943del - I searched for it in test and came up with an allele page with no classifications and failed merge log? See: https://test.shariant.org.au/variantopedia/view_allele/6374
![Screen Shot 2021-09-27 at 9 45 26 am](https://user-images.githubusercontent.com/43164432/134828402-433795bc-8ff3-42e8-84e9-032b3ce3e176.png)

**Comment by EmmaTudini** [comment]
Testing:
- Imported NM_014516.3:c.944del in GRCh38 (no identifier in clingen allele registry)

Expected output: Should generate a clingen allele ID. If no GRCh37 genome build, should use NCBI remap.

Actual output: Passed
