### ISSUE TITLE
HGVS outside of transcript range

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#487]
We should error when a HGVS coordinate is out of range.

I tried doing this with genomic coordinates but figured that would lead to issues with indels possibly being normalized off the transcript.

I've disabled cDNA level checks in ```_pyhgvs_get_variant_tuple``` as I didn't take into account negative (5'UTR) coordinates.

I've added TranscriptVersion fivep_utr_length and threep_utrl_length (to go with coding_length and length) so we should be able to calculate this now.

Some test data:

```
NM_001005484.1 - length 918, has no 5'UTR
NM_001005484.1:c.0A>C - out of range
NM_001005484.1:c.1A>C - ok
NM_001005484.1:c.919G>C - out of range off end
NM_001010938.1:c.4020del - OK
NM_001010938.2:c.4020del - out of range
```

**Comment by davmlaw** [comment]
Need to fix non coding:

NR_002217.1:n.1406T>C currently fails but works on [ClinGen](http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/allele?hgvsOrDescriptor=NR_002217.1%3An.1406T%3EC)

**Comment by davmlaw** [comment]
Then once fixed, re-validate then re-match evidence containing "NR_"

**Comment by EmmaTudini** [comment]
Testing:
- Logged in as non-admin assigned to VCGS Unit 1
- Imported NM_004360.5:c.4686del (in string of As at end of transcript)
Expected output: Should import without error and right align
Actual output: Passed

Finally found an example where it could right align off the transcript!
- Imported NM_014381.3:c.7597dup (final base of transcript but there's another C off the transcript that it should be right aligned to). Also imported 	
GRCh37 NM_014381.3:c.7598dup and GRCh37 NM_014381.3(MLH3):c.*3308dupC - already off transcript but same variant as above

Expected output: Not sure really... @davmlaw to comment
What did happen was that the first variant that was in the transcript was right aligned to a base outside of the transcript but then the other variants that were already off the transcript generated errors. All of the variants above resolve to the same allele so it might be a bit risky erroring on the final two and not the first. Not sure what should be done?

**Comment by EmmaTudini** [comment]
Raise new issue
