### ISSUE TITLE
HGVS - reference validation now fails

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#491]
Searching or submitting classification for these now fails validating that = not in GATC - issue with validating our internal representation

NM_005629.3(SLC6A8):c.1403A=
NM_018090.5:c.462=

**Comment by EmmaTudini** [comment]
@davmlaw Not quite sure what the intended output is here. NM_005629.3(SLC6A8):c.1403A= can be imported, matched and searched for but NM_018090.5:c.462= fails import and searching (error about not having a base)

**Comment by davmlaw** [comment]
Fix was to allow creation of a reference HGVS, didn't work due to a bug.

The error about not having a base is due to our enforcing that we specify the reference in our HGVSs - so that's the right behavior the example I listed was wrong and forgot about that rule

**Comment by TheMadBug** [comment]
NM_018090.5:c.462= in prod complains about
HGVS: Invalid HGVS name "NM_018090.5:c.462=": alt=NN contains non-standard (A,C,G,T) bases: NN (GRCh38)

Is this expected?

**Comment by davmlaw** [comment]
Yeah I think we should just take the reference base here, if we want to stop people from doing that can always give a warning / flag etc but should resolve it

**Comment by EmmaTudini** [comment]
@davmlaw What has changed since your last comment?

**Comment by davmlaw** [comment]
Fails due to https://github.com/SACGF/variantgrid_private/issues/2142

**Comment by davmlaw** [comment]
This was due to the HGVS library not handling reference variants without reference bases supplied:

Raised as bug https://github.com/counsyl/hgvs/issues/61

I have fixed it in our version of HGVS library, so upgrade via:

```
sudo python3 -m pip install --upgrade git+https://github.com/SACGF/hgvs#egg=pyhgvs
```

**Comment by davmlaw** [comment]
James upgraded Shariant test - tested submitting "NM_018090.5:c.462=" works fine just raises a matching warning whne it inserts the gene symbol and reference base

Search also works (not sure if it was broken before)
