### ISSUE TITLE
ClinGen allele registry supplied non-normalized indel coordinates / bases at 1 point in time

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#492]
In S test we have flags:

```
NM_001080522.2(CC2D2A):c.4465_4468delGACA (imported)
NM_001080522.2(CC2D2A):c.4465_4468delCAGA (resolved)
```

```
from snpdb.models import Variant, GenomeBuild
from genes.hgvs import HGVSMatcher

v = Variant.get_from_string("4:15597431 TCAGA>T", GenomeBuild.grch38())

matcher = HGVSMatcher(GenomeBuild.grch38())
matcher.variant_to_c_hgvs(v, "NM_001080522.2")
```

On my dev: 'NM_001080522.2(CC2D2A):c.4465_4468delGACA'
On the s test: 'NM_001080522.2(CC2D2A):c.4465_4468delCAGA'

The API has changed how it responds - seems to use normalization now:

```
from snpdb.models import ClinGenAllele
ca = ClinGenAllele.objects.get(pk=206276) 
```

Has different results!

```
# Test - API called at 2020-06-19
In [39]: ca.transcript_alleles_by_transcript_accession["NM_001080522.2"]["coordinates"]                                                                                 
Out[39]: [{'end': 4711, 'start': 4707, 'allele': '', 'referenceAllele': 'CAGA'}]
```

```
# Dev - API called at 2021-09-21
In [20]: ca.transcript_alleles_by_transcript_accession["NM_001080522.2"]["coordinates"]                                                                                 
Out[20]: [{'end': 4713, 'start': 4709, 'allele': '', 'referenceAllele': 'GACA'}]
```

I think we'll have to re-retrieve data from ClinGen - at least the old indels

**Comment by davmlaw** [comment]
Added a helper method ```variant.is_indel``` and added "file_type" to hgvs_put so can now query via:

```
from snpdb.clingen_allele import ClinGenAlleleRegistryAPI
from snpdb.models import ClinGenAllele

clingen_api = ClinGenAlleleRegistryAPI()
records = ClinGenAllele.objects.all()[:100]
records = [str(ca) for ca in ClinGenAllele.objects.all()[:100]]
clingen_response = clingen_api.hgvs_put(records, file_type="id")
```

Write a management command that replaces clingen alleles, either all, indels or before a certain date

**Comment by davmlaw** [comment]
Added manual migration upgrade step

Once it's done, run:

```
python3.8 manage.py fix_legacy_classification_alignment_gap_hgvs_matching
```

(running on sharinat test now)

This should always be the last step in an upgrade after all the other stuff

**Comment by davmlaw** [comment]
I emailed 2 bug reports to ClinGen Allele Registry (brl-allele-reg@bcm.edu)

**non-coding HGVS for protein coding transcript**

> For this allele:
> 
> http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/by_canonicalid?canonicalid=CA2988667
> 
> There's a HGVS given as:
> 
> NM_015697.7:n.320G>C NP_056512.5:p.Ser107Thr
> 
> Why does it have a "n." instead of a "c."?
> 
> RefSeq says it has a CDS and you give a protein change
> 
> https://www.ncbi.nlm.nih.gov/nuccore/NM_015697.7
> 


**transcriptAllele coordinate referenceAllele off by 1?**

> Hi, if you submit this HGVS:
> 
> NM_001276345.1:c.659_661delAGA
> 
> http://reg.clinicalgenome.org/allele/CA006429
> 
> as JSON contains a transcriptAllele entry:
> 
> ```
> {
>       "coordinates": [
>         {
>           "allele": "",
>           "end": 753,
>           "referenceAllele": "GAA",
>           "start": 750
>         }
>       ],
>       "gene": "http://reg.genome.network/gene/GN011949",
>       "geneNCBI_id": 7139,
>       "geneSymbol": "TNNT2",
>       "hgvs": [
>         "NM_001276345.1:c.659_661del"
>       ],
>       "proteinEffect": {
>         "hgvs": "NP_001263274.1:p.Lys220del",
>         "hgvsWellDefined": "NP_001263274.1:p.Lys220del"
>       },
>       "referenceSequence": "http://reg.genome.network/refseq/RS020876"
>     }
> ```
> 
> The RefSeq page https://www.ncbi.nlm.nih.gov/nuccore/NM_001276345.1 gives: CDS 93..989
> 
> If CDS starts at 93 that means there is a 92bp 5' UTR - so c.659_661 should be 1-based transcript coordinates of 92 + 659 to 92+661 = 751 to 753
> 
> Or, 0 based half closed interval of 750:753 - eg in Python I get the reference sequence of:
> 
> ```
> In [5]: nm_001276345_1_sequence[750:753]                                                                                                        
> Out[5]: 'AGA'
> ```
> 
> This matches what I submitted as the ref of my HGVS
> 
> 
> Issue 1 - referenceAllele is wrong, I think off by 1:
> 
> "referenceAllele": "GAA" - This is not the reference sequence. 
> 
> If I supply this as the ref eg I submit NM_001276345.1:c.659_661delGAA it errors:
> 
> http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/allele?hgvsOrDescriptor=NM_001276345.1%3Ac.659_661delGAA
> 
> Issue 2:
> 
> Your coordinates are given as 750 - 753 - I am guessing they are a 0 based half-closed interval - can you  mention that in the docs? It's not always obvious what you mean (eg some people may think they are 1-based like in the HGVS)
> 
>

**Comment by EmmaTudini** [comment]
@davmlaw Not sure how to test this? Is it bundled up in general variant normalisation testing? @TheMadBug Does the manual command need to be added to the prod deploy list?

**Comment by davmlaw** [comment]
The thig to look out for would be wrong ClinGen bases, ie check the c.HGVS for classifications matched via ClinGen instead of pyHGVS (They're probably really rare now though as we prefer PyHGVS)

**Comment by EmmaTudini** [comment]
@TheMadBug Is there any way to pull out variants that were matched using clingen allele registry?

**Comment by EmmaTudini** [comment]
To do - after prod deploy and upgrade (after re-matching) - verify that there are no hgvs mismatches between references bases on same genome build where clingen is used.

**Comment by EmmaTudini** [comment]
@TheMadBug Are you able to pull out variants that have been matched using ClinGen allele registry from prod?

**Comment by TheMadBug** [comment]
11,153 Variant Alleles have their origin set as ClinGen Allele Registry out of a total of
23,132 - basically nearly every leftover was done with it.

Here are the 63 variants that were lifted over with NCBI Remap
```
allele_id | variant_id | conversion_tool
11889 | 2966731 | NR
11835 | 3627481 | NR
11834 | 5066716 | NR
11808 | 5066715 | NR
11730 | 2965805 | NR
11532 | 4706440 | NR
11285 | 5066522 | NR
11286 | 4448744 | NR
11154 | 3583023 | NR
10613 | 5066241 | NR
10580 | 5066225 | NR
10360 | 5066151 | NR
10277 | 2966769 | NR
10276 | 5066133 | NR
10246 | 5066123 | NR
10155 | 3268967 | NR
9889 | 3611633 | NR
9717 | 3612509 | NR
9676 | 5065920 | NR
9530 | 3617269 | NR
9283 | 3361859 | NR
9214 | 5065766 | NR
9181 | 5065753 | NR
9084 | 5065718 | NR
9052 | 3600323 | NR
8909 | 3137695 | NR
8908 | 5065673 | NR
8846 | 2966319 | NR
8626 | 3635341 | NR
8273 | 5065511 | NR
7953 | 3749571 | NR
7940 | 3701121 | NR
7852 | 3601801 | NR
6413 | 3802017 | NR
6412 | 3801662 | NR
6518 | 2006383 | NR
6910 | 3800643 | NR
6599 | 2689359 | NR
6277 | 3799216 | NR
6276 | 3799214 | NR
6269 | 2451373 | NR
6192 | 3799046 | NR
6117 | 3497003 | NR
6116 | 3798874 | NR
6065 | 3798710 | NR
5970 | 3798499 | NR
5966 | 3798496 | NR
5758 | 3601843 | NR
5695 | 3296665 | NR
5576 | 3797566 | NR
5396 | 3797189 | NR
4180 | 3797047 | NR
3579 | 3797045 | NR
3275 | 3797043 | NR
3702 | 3797041 | NR
3670 | 2688467 | NR
3992 | 3797033 | NR
2366 | 3797035 | NR
5321 | 3497001 | NR
1726 | 3601863 | NR
5230 | 3796827 | NR
5231 | 3796826 | NR
5190 | 3722371 | NR
5145 | 3496995 | NR
5035 | 2385051 | NR
5020 | 2806175 | NR
4545 | 3795424 | NR
4431 | 2809269 | NR
4355 | 3794945 | NR
4296 | 3794797 | NR
1852 | 3793832 | NR
1268 | 3297003 | NR
3664 | 3793624 | NR
3344 | 2518017 | NR
2964 | 3792119 | NR
2755 | 3791677 | NR
2275 | 2808907 | NR
2112 | 3790108 | NR
1702 | 3722285 | NR
1446 | 3789021 | NR
1276 | 3722621 | NR
1652 | 3789019 | NR
1385 | 3789017 | NR
```

**Comment by EmmaTudini** [comment]
Sorry, I meant more matched by clingen allele registry over PyHGVS rather than lifted over using CAR

**Comment by TheMadBug** [comment]
Ahh, that's stored in the individual variant matching flag text, that'll be a bit of effort to extract.
