### ISSUE TITLE
ClinGen Allele Reference sequence is wrong

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#493]
I emailed a bug reports to ClinGen Allele Registry (brl-allele-reg@bcm.edu)

**transcriptAllele coordinate referenceAllele off by 1?**

> Hi, if you submit this HGVS:
> 
> NM_001276345.1:c.659_661delAGA
> 
> http://reg.clinicalgenome.org/allele/CA006429
> 
> as JSON contains a transcriptAllele entry:
> 
> ```
> {
>       "coordinates": [
>         {
>           "allele": "",
>           "end": 753,
>           "referenceAllele": "GAA",
>           "start": 750
>         }
>       ],
>       "gene": "http://reg.genome.network/gene/GN011949",
>       "geneNCBI_id": 7139,
>       "geneSymbol": "TNNT2",
>       "hgvs": [
>         "NM_001276345.1:c.659_661del"
>       ],
>       "proteinEffect": {
>         "hgvs": "NP_001263274.1:p.Lys220del",
>         "hgvsWellDefined": "NP_001263274.1:p.Lys220del"
>       },
>       "referenceSequence": "http://reg.genome.network/refseq/RS020876"
>     }
> ```
> 
> The RefSeq page https://www.ncbi.nlm.nih.gov/nuccore/NM_001276345.1 gives: CDS 93..989
> 
> If CDS starts at 93 that means there is a 92bp 5' UTR - so c.659_661 should be 1-based transcript coordinates of 92 + 659 to 92+661 = 751 to 753
> 
> Or, 0 based half closed interval of 750:753 - eg in Python I get the reference sequence of:
> 
> ```
> In [5]: nm_001276345_1_sequence[750:753]                                                                                                        
> Out[5]: 'AGA'
> ```
> 
> This matches what I submitted as the ref of my HGVS
> 
> 
> Issue 1 - referenceAllele is wrong, I think off by 1:
> 
> "referenceAllele": "GAA" - This is not the reference sequence. 
> 
> If I supply this as the ref eg I submit NM_001276345.1:c.659_661delGAA it errors:
> 
> http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/allele?hgvsOrDescriptor=NM_001276345.1%3Ac.659_661delGAA
> 
> Issue 2:
> 
> Your coordinates are given as 750 - 753 - I am guessing they are a 0 based half-closed interval - can you  mention that in the docs? It's not always obvious what you mean (eg some people may think they are 1-based like in the HGVS)
> 
>

**Comment by davmlaw** [comment]
Since I have the transcript sequence now, I can use the refseq coords to index it out easy

**Comment by davmlaw** [comment]
Coordinates in dups are bad too:

```
{"gene":"http://reg.genome.network/gene/GN026594",
"hgvs":["NM_173660.4:c.1124_1127dup"],
"geneSymbol":"DOK7",
"coordinates":[{"end":1197,
"start":1197,
"allele":"GCCT",
"referenceAllele":""}],
```

start and end are given as "end" basically so we could get it out (without having to know CDS start/end) via:

```
tvsi_NM_173660_4.sequence[1197 - len(allele):1197]
```

**Comment by davmlaw** [comment]
For testing, here are various indels etc that have the right bases:

NM_001276345.1:c.659_661delAGA
NM_000543.5:c.1497_1498delGTinsAC
NM_001304718.2:c.211-3dupT

**Comment by davmlaw** [comment]
We are going to have to give up adding bases to HGVS that include intron flanking sequences - the 

The spec says:

> NOTE: a coding DNA reference sequence does not contain intron or 5’ and 3’ gene flanking sequences and can therefore not be used as a reference to describe variants in these regions see Reference Sequences. Correct descriptions refer to a genomic reference sequence like LRG_199t1:c.357+1G>A,

But we can't really reject these. Thus, I think in this case we'll have to just not include the base as we can't get it properly

**Comment by EmmaTudini** [comment]
@davmlaw When you say the "wrong" bases, do you just mean that the coordinates haven't been right aligned and therefore the ref bases given for the chgvs are incorrect?

Using NM to denote an intronic variant has always been against the HGVS guidelines but ClinVar, Alissa, etc etc all use it so we need to be able to accept it and export it. 

Is there 100% no way to get the bases? We need the reference bases for import into Alissa or they will fail

**Comment by davmlaw** [comment]
The coordinates are correct, but I believe the reference sequence is off by one (see email I sent)

I re-matched as per code below, Variant Warnings went from 144 => 123

```
from classification.models import Classification
from classification.classification_import import reattempt_variant_matching
    
qs = Classification.objects.filter(flag_collection__flag__flagcomment__text__icontains='Significant change to the c.hgvs').distinct()
reattempt_variant_matching(admin_bot(), qs)
```

**Comment by EmmaTudini** [comment]
Bit difficult to test. Couldn't find a transcript that would fail both builds for us but pass Clingen. Found one where it failed for all versions in GRCh37 and that's how I tested this. @davmlaw Could you please make sure this test captures the change please?

Testing:
- Imported GRCh37  NM_001145026.1(PTPRQ):c.910+6_910+8del (in intron). Also imported GRCh37  NM_001145026.1(PTPRQ):c.724_726del (will need to be normalised)
- Both versions of this transcript do not work in GRCh37. 

Expected output: Both should be sent to Clingen allele registry for matching etc. Intronic variant should fail. Exonic variant should be right aligned as sequence can be checked.

Actual output: Passed

**Comment by davmlaw** [comment]
Those partially cover the change - would probably be worth testing the failure case, easiest there is a non-latest version of an Ensembl transcript

For all of these, the HGVS mutation type will need to be dup/del/delins, the change is to get the transcript sequence then use that to replace the bases instead of what ClinGen provides.

This can fails in 3 ways:

* It's an intron from a RefSeq transcript - should throw error of "A coding DNA reference sequence does not contain intron or 5' and 3' gene flanking sequences and can therefore not be used as a reference to describe variants in these regions"
* It's an LRG (don't have sequences from LRG)
* We can't get a transcript sequence via API (We can only get most recent version of a transcript from Ensembl)

**Comment by EmmaTudini** [comment]
Raise new issue about error message
