### ISSUE TITLE
Gene Symbol case sensitivity

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#496]
When I removed duplicate case insensitive gene symbols I just took the first I found. 

I need to go through and use the officially cased one, eg:

C19orf1

**Comment by EmmaTudini** [comment]
@davmlaw Was this changed with the upgrade to using HGNC for both builds?

**Comment by davmlaw** [comment]
Yes, should use HGNC for both builds, that caused inconsistent gene symbols between builds, was never given its own issue (was part of allele issues I think)

This one is about the case of gene symbols ie changing "C19orf1" or "C19ORF1"

**Comment by EmmaTudini** [comment]
@davmlaw in regards to using HGNC - it seems to for variant normalisation but the gene page still has it as different for this example - https://test.shariant.org.au/genes/view_gene/2538

**Comment by EmmaTudini** [comment]
Emma to raise a new issue

**Comment by TheMadBug** [comment]
Closed as new issue covers the remaining work
