### ISSUE TITLE
Pubmed search

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#5]
Click a button and open in new tab a pubMed search - given gene + variant (similar to Google search).

Could also include phenotype

SA Path decided that it's nice to have not must have for VEP upgrade (can still do manually)

**Comment by sksmi** [comment]
Not sure of scope here. Wondering if pubmed search necessary, given Mastermind/SETH/tmVar etc are options?

Have failed based on 2 issues:
1) doesn't include c.hgvs in search
2) doesn't identify related articles in pubmed

Test case -  https://app.qase.io/run/VG/dashboard/11

**Comment by davmlaw** [comment]
This feature was requested by K for SA Path VEP upgrade - I think it's part of SOP? It could be because they are unaware of the new features for finding publications... personally I'd prefer we change the SOP to use linked classifications via all the different means but this has not yet been validated

While usually I think it's a bad idea to invent scope during a test case, I was thinking the same thing while I was writing the code

**Comment by davmlaw** [comment]
@sksmi can you please provide a search term that would retrieve the results you want, so that I can generate it via code?

**Comment by sksmi** [comment]
Pubmed search is part of SOP, but the method is unspecified. Will f/u with K as not sure what's best here esp. given mastermind is VG3.0.

**Comment by sksmi** [comment]
Discussed with K. Ok to leave and wait for Mastermind in VG3.0. In interim we can use mastermind link via UCSC browser.

**Comment by davmlaw** [comment]
Should I remove the PubMed search link?

**Comment by sksmi** [comment]
Yep, safer that way.

**Comment by sksmi** [comment]
Checked 2 variants. Pubmed links removed. 
http://144.6.229.160/variantopedia/view_variant/242969475
http://144.6.229.160/variantopedia/view_allele_from_variant/241924500
