### ISSUE TITLE
Change gene symbols on view gene page to HGNC

### ISSUE THREAD

**Issue by EmmaTudini** [SACGF/variantgrid#509]
See example here -  https://test.shariant.org.au/genes/view_gene/2538
 HGNC is G6PC1 but shown as G6PC in GRCh37 and G6PC1 in GRCH38 on view gene page

**Comment by EmmaTudini** [comment]
See example here -  https://test.shariant.org.au/genes/view_gene/2538
 HGNC is G6PC1 but shown as G6PC in GRCh37 and G6PC1 in GRCH38 on view gene page

**Comment by davmlaw** [comment]
A gene can be assigned an HGNC as well as its own symbol by RefSeq/Ensembl. Not all genes are assigned an HGNC

I now display the HGNC (with link) and if different, also the symbol assigned by RefSeq/Ensembl. It's worth knowing the internal name as eg the HGNC symbol may have changed years after the last annotation was released for a genome build, ie there never was a time that anyone ever worked with GRCh37 data that called it the new HGNC symbol

**Comment by EmmaTudini** [comment]
Testing: 
- Logged into Shariant test as non-admin assigned to VCGS Unit 1 (emmatudini@gmail.com)
- Went to https://test.shariant.org.au/genes/view_gene/2538 (G6PC1)
- Went to https://test.shariant.org.au/genes/view_gene/7157 (Tp53)

Expected output: G6PC1 should specify G6PC for GRCh37 only.
TP53 should only appear as HGNC.

Actual output: Passed
@davmlaw - working but not sure why the GRCh37 version of G6PC1 is annotated as G6PC by Refseq. When I go into the Refseq website it only says G6PC1

**Comment by davmlaw** [comment]
The website show the latest information (build independent), while we show the latest for the genome build (GTF/GFF release)
