### ISSUE TITLE
HGVS generation error details not collected

### ISSUE THREAD

**Issue by EmmaTudini** [SACGF/variantgrid#511]
Testing:

Imported GRCh37 NM_001145026.1(PTPRQ):c.910+6_910+8del (in intron). Also imported GRCh37 NM_001145026.1(PTPRQ):c.724_726del (will need to be normalised)
Both versions of this transcript do not work in GRCh37.
Expected output: Both should be sent to Clingen allele registry for matching etc. Intronic variant should fail for GRCh37 only. Exonic variant should be right aligned as sequence can be checked. Error message should be -  A coding DNA reference sequence does not contain intron or 5' and 3' gene flanking sequences and can therefore not be used as a reference to describe variants in these regions

Actual output: **Failed** - error message is 
Error: Could not convert 12:80849266 GAAC>G to HGVS - tried: ClinGen Allele Registry (CA2499306831): NM_001145026.1 (PTPRQ/GRCh37), ClinGen Allele Registry (CA2499306831): NM_001145026.2 (PTPRQ/GRCh37) (GRCh37)

**Comment by davmlaw** [comment]
Variant matching is when you convert from HGVS -> Variant. We can do this ok with ClinGen for this variant

The failure occurs when we try and generate a HGVS for the variant via ClinGen (that's when we need to get the reference and can't as it's an intron)

We only report the methods attempted, not the errors each time. I can add this, but there will be a lot of redundancy - as it's a log (eg you might try pyhgvs with different versions, clingen with different versions and fail for different or the same reasons each time.)

**Comment by davmlaw** [comment]
Change is to give full details when we fail

I think this one made it into prod, apologies for not moving from coding to complete to Review/QA when I should have

**Comment by EmmaTudini** [comment]
Testing:
- Imported NM_001145026.1(PTPRQ):c.910+6_910+8del against GRCh37. 

Expected output: More information about ClinGen error. 

Actual output: Passed
Note: This is not retrospective, allele that have already failed will not have the message change unless another variant is imported against the same allele
