### ISSUE TITLE
Normalisation of variant outside of a transcript boundary

### ISSUE THREAD

**Issue by EmmaTudini** [SACGF/variantgrid#512]
Testing:

Logged in as non-admin assigned to lab
Imported NM_004360.5:c.4686del (in string of As at end of transcript)
Expected output: Should import without error and right align
Actual output: Passed
Finally found an example where it could right align off the transcript!

Imported NM_014381.3:c.7597dup (final base of transcript but there's another C off the transcript that it should be right aligned to). Also imported
GRCh37 NM_014381.3:c.7598dup and GRCh37 NM_014381.3(MLH3):c.*3308dupC - already off transcript but same variant as above

Actual output: The first variant that was in the transcript was right aligned to a base outside of the transcript but then the other variants that were already off the transcript generated errors. All of the variants above resolve to the same allele so it might be a bit risky erroring on the final two and not the first. Not sure what should be done?

Also tested searching for all three variants above and the first one worked, while the final two generated outside of the transcript errors

Discussed on a call whether all variants should be left aligned to determine whether it is on or off the transcript prior to normalisation. This would mean that the two variants above that currently fail due to being outside of a transcript boundary would left align to within the transcript boundary and match successfully

**Comment by davmlaw** [comment]
I believe we can close this as with BioCommons HGVS we now die if a variant is outside the transcript. This is similar to other tools. Testing:

NM_014381.3:c.7597dup:

Biocommons - can convert to variant coords ok, converting back gives "HGVSInvalidIntervalError: Position is beyond the bounds of transcript record"
Variant validator - Variant coordinate is out of the bound of CDS region (CDS length : 4290)


NM_014381.3:c.7598dup

Biocommons - dies with "HGVSInvalidIntervalError: c.7598 coordinate is out of bounds"
Variant validator - The given coordinate is outside the bounds of the reference sequence. (NM_014381.3)


NM_014381.3(MLH3):c.*3308dupC

Biocommons - dies with "HGVSInvalidIntervalError: c.*3308 coordinate is out of bounds"
Variant validator - Using a transcript reference sequence to specify a variant position that lies outside of the reference sequence is not HGVS-compliant: Instead re-submit NC_000014.8:g.75480478dup





See also - issue on [normalization of intron](https://github.com/SACGF/variantgrid_private/issues/3498)

**Comment by EmmaTudini** [comment]
Testing:
- As admin in HGVS resolution tool
1. NM_004360.5:c.4686del --> right aligns to end of transcript
2. NM_014381.3:c.7597dup -> initial base (before right alignment) is within the transcript, but it right aligns to be outside of transcript
3. NM_014381.3:c.7598dup --> is already outside of transcript

Expected/actual output: 
1. Should resolve as per pyhgvs - Passed
2. Saying above that it will error, which it does. But pyhgvs and mutalyzer were able to resolve it as the non-right aligned based was within the transcript. Also it doesn't really throw an error - @davmlaw **Failed** - need to at least show an error
3. Is outside bounds so should fail - Passed

**Comment by EmmaTudini** [comment]
Add error for option 2

**Comment by davmlaw** [comment]
The problem for (2) - NM_014381.3:c.7597dup is not during the resolution phase, but rather generating the HGVS again from the coordinate (as it's now not on the transcript)

I have made it show the correct error (about being off transcript) - you can see this now on resolution tool, but there may be places where errors generating HGVS are not shown

**Comment by davmlaw** [comment]
testing, ran "NM_014381.3:c.7597dup" through resolution tool - show error when generating again

**Comment by EmmaTudini** [comment]
Will create a test case later, but would like to discuss the meeting today.
Imported the following in GRCh37 and GRCh38 (see comments above):
NM_014381.3:c.7597dup
NM_014381.3(MLH3):c.*3307dupC
Resolved to this allele - https://test.shariant.org.au/variantopedia/view_allele/58607

- The issue here (as discussed above) is that the variant normalises 3' off the transcript. @davmlaw I think you generate an error somewhere, but it doesn't filter through completely so we're left with a weird kind of error, where a g.hgvs in GRCh37 and GRCh38 is still generated but no chgvs is generated. 
- The error only really shows on the imported allele page and not on the actual imported allele when clicking on it from the allele page. See below:
<img width="1463" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWN2Q3c9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2465cd1b094714c7c1cb8533d8ac96a44eba6b90/Screenshot%202025-08-27%20at%209.35.13%E2%80%AFAM.png" alt="Screenshot 2025-08-27 at 9.35.13 AM.png" />
- As the variant has g.hgvs it is marked as being ok to export (see above), however is not included in the vcf export. 

- Searching on this variant returns the following: 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUV2Q3c9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a927e2024cf63fc9018d21a0ae6d78c81e2cca6/Screenshot%202025-08-27%20at%209.20.16%E2%80%AFAM.png" alt="Screenshot 2025-08-27 at 9.20.16 AM.png" />

**Comment by EmmaTudini** [comment]
Test case: https://app.testiny.io/VG/testcases/tcf/81/tc/214/.
See results: https://docs.google.com/spreadsheets/d/17Ocg1LlOm0SmOnNQ8Tyune4aVwaRRCsQtuCEWBfXc9E/edit?gid=0#gid=0
Note: Testing performed in late August 2025 (delay in recording in Zenhub).

Status: **FAILED** - new issue raised to handle, and delayed to next build- see https://app.zenhub.com/workspaces/everything-space-5bb3158c4b5806bc2beae448/issues/gh/sacgf/variantgrid_shariant/212
