### ISSUE TITLE
Add warning on gene/transcript pages for pseudoautosomal (PAR) regions

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#519]
When a transcript can be resolved to multiple loci, show a warning on:

* Gene page
* Transcript
* Transcript version

**Comment by davmlaw** [comment]
Emma said in #506:

@davmlaw I'd appreciate if these were moved to review QA before the prod deploy so that they could be tested. 

Testing:
- Logged into prod as admin
- Searched for genes SHOX and CSF2RA
- Went to Refseq gene and affected transcript pages - NM_000451.3 and NM_006140.4

Expected output: 
- Transcript pages should show warning for it mapping to multiple places in the genome.

Actual output: Passed
Note: @davmlaw Think this is likely related as looking at the geneID pages for other genes that aren't in the PAR region works as expected, but for these genes, refseq gene page does not show genomic coordinates for both builds. One shows for one build, one doesn't show coordinates for either build. Does this have any downstream effects on search, etc? Or is it just a display?
![Screen Shot 2021-11-17 at 9.53.53 am.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/5872ef9b-8c3a-417d-bf5d-8f497caca176)
![Screen Shot 2021-11-17 at 9.56.20 am.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/aa3229f5-763a-4b59-b5e8-135e257c408b)

Also note that when I said to flag the allele, I meant to flag it on the allele page rather than the transcript page as the transcript page isn't viewed regularly by users.

@davmlaw Any thoughts on why the genomic coordinates are not being displayed on the geneID page?

**Comment by davmlaw** [comment]
> why the genomic coordinates are not being displayed on the geneID page?

We didn't handle the edge case of having multiple loci, it's a lot of work for not much gain, raised as #520 - GeneVersion handle multiple loci will do some time later

**Comment by EmmaTudini** [comment]
@davmlaw Has anything changed based on this issue since my last comment

**Comment by davmlaw** [comment]
Yes, I broke up the work into multiple issues from the issue you originally commented in. The scope is described in my comments

**Comment by EmmaTudini** [comment]
Ok in prod already and other issues exist so closing issue
