### ISSUE TITLE
Lab classification graphs - bootrap carousel indexes

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#525]
Bootstrap carousel uses an index to handle the links - the index won't properly line up with the graphs if we eg don't show a particular one due to lack of data or because it's admin only

I can't see an easy way to do carousel indexes by ID but maybe there is. If not, we should determine what is shows and the index in python then pass that in, so the index always lines up

**Comment by TheMadBug** [comment]
Any use of tab_builder can now have mode=`tabs|carousel|accordion` to switch between rendering modes.
Any format allows for a specific tab to be set active, or for the first tab to default as active.
Note that after that I've changed labs graphs page to be tabs as it's only really visited by admins.
Still want to make a new landing page to provide a lab status where a carousel of info would be more appropriate.
Closing as no longer applicable (even though it's now do-able in code)
