### ISSUE TITLE
Move JS files from CDN to local static

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#539]
There was some timing fingerprint attack so now most browsers don't cache CDNs between sites.

For intranet users, CDN is probably slower, and has the possibility of making the site break if one of the servers are down or slow (these are extremely fast + reliable but we rely on dozens)

You could make a template tag that takes both a local file and a CDN and can switch based on settings? Ie for variantgrid.com a CDN makes sense as it's on the web, but for an intranet yo don't want CDN. Adds a slight maintenance burden having to keep both so might not be worth it

https://csswizardry.com/2019/05/self-host-your-static-assets/

**Comment by TheMadBug** [comment]
So I think the biggest offender so far has been Font Awesome (had quite a few experiences where the icons turn to blocks, but haven't had an issue where jquerry etc have failed.)

Instructions on how to use a downloaded version of font awesome are here.
We'd just want the web font solution.

https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/hosting-font-awesome-yourself

**Comment by davmlaw** [comment]
* For font-awesome, I used the Django package, and locked the version to what was in the JS file we were using.
* For JQuery, were were already self-hosting 3.3.1 and also had externally hosted 3.5.1 (not sure why we had different versions going, assume it was an accident). Made it all use the same version self hosted one

**Comment by davmlaw** [comment]
Had a few issues w/Django font awesome - that were due to needing to add to CSS:

```
  font-family: 'Font Awesome 5 Free', 'FontAwesome';
  font-weight: 900;
```

**Comment by davmlaw** [comment]
Been using VG test and dev with this for a while, no issues came up (should be pretty obvious 404s and missing stuff)
