### ISSUE TITLE
Structural Variant - symbolic variants

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#54]
We would like to store very large CNVs in the system. We currently can't read symbolic alts from VCFs (ie ```<DEL>``` or ``<DUP>```)

We can convert HGVS indels into very large ref/alt sequences, which has a number of problems, including display issues, and #15 - large sequences crashing VEP

So this task is to:

* Support symbolic alts as the database representation (for >1kb size variants)
* Convert existing >1kb to symbolics
* Large CNVs appear ok on pages rather than dumping kilobytes of sequces on the page (find existing issue for this?)
* Parse symbolics from VCF
* Make sure all existing functionality eg HGVS still works

----------------

Further CNV issues have been split off:

* #824 CNV Callers and VCF processing
* #818 CNV Normalization and Representation
* #823 CNV Annotation - separate pipeline for large indels
* CNV Classification will do later

**Comment by EmmaTudini** [comment]
Also note that different guidelines have been suggested for CNVs - see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7313390/. May need to allow for a different classification schema for CNVs. Will need to ask the labs how they interpret CNVs first.

**Comment by EmmaTudini** [comment]
See https://app.zenhub.com/workspaces/everything-space-5bb3158c4b5806bc2beae448/issues/sacgf/variantgrid_private/2994 for more information

**Comment by davmlaw** [comment]
Need to integrate with systems for Shariant, collecting here: https://github.com/SACGF/shariant-admin/wiki/CNV-design

**Comment by davmlaw** [comment]
SA Path diagnostics use: decon, panelCNV (internal, written by Paul Wang), xhmm

All have their own formats.

Probably the best plan is to be able to load CNVs as:

* VCF
* Bed File
* Bed Graph (has chrom/start/end and float) - used as it displays nicely as a histogram in IGV

Then write (or ideally have others write) converters from the various tools into one of the above.

How you analyse it depends on whether you are looking at somatic or germline. Germlines typically small, somatics can be huge, eg cause LOH on entire chromosome or arm.

The other thing to think about is how it should be integrated with variants - ie Comp het could be a missense variant as a LOH in the same region?

Might be worth talking to people who are doing CNV anaylses, ie GA people - what are they currently doing?

Need to work this out before deciding eg to store as a kind of variant, or as something entirely different.

When annotating CNVs - probably want to have a slightly different annotation pipeline which avoids using base-level annotations such as conservation - VEP joins them using "&" which makes the annotation files massive - raised as issue for VEP https://github.com/Ensembl/ensembl-vep/issues/1023

**Comment by davmlaw** [comment]
Paul says consider using whatever format Manta uses

**Comment by davmlaw** [comment]
Hamish said gnomAD are doing CNVs - check them out

**Comment by EmmaTudini** [comment]
Riggs paper attached [https://app.zenhub.com/files/299486514/069a8eca-8996-4ea5-a51d-b84279c61853/download](https://app.zenhub.com/files/299486514/069a8eca-8996-4ea5-a51d-b84279c61853/download)

**Comment by EmmaTudini** [comment]
I think this part of the GA4GH VRS is related to CNVs - https://vrs.ga4gh.org/en/latest/terms_and_model.html#sequence-expression
Might be helpful as a pseudo allele ID? May also help with normalisation - https://vrs.ga4gh.org/en/latest/impl-guide/normalization.html#normalization

Then I think VRSATILE is an extension of this... https://vrsatile.readthedocs.io/en/latest/index.html

Would need to organise a meeting with the leads to understand further

**Comment by davmlaw** [comment]
**Annotations**

[VEP can do SVs](https://www.ensembl.info/2020/03/27/cool-stuff-the-ensembl-vep-can-do-annotating-structural-variants/) though may have issues with eg the bigwig per-base data. Has [StructuralVariantOverlap plugin](https://asia.ensembl.org/info/docs/tools/vep/script/vep_plugins.html#structuralvariantoverlap)

[AnnotSV](https://lbgi.fr/AnnotSV/annotations) -  [paper w/139 citations](https://academic.oup.com/bioinformatics/article/34/20/3572/4970516)

High citations, good webpage, examples looks good, it is written TCL(!?)

[CNVannotator](https://bioinfo.uth.edu/CNVannotator/) - [paper - 23 citations](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0080170)

**Comment by davmlaw** [comment]
Should same start/end but different alt (ie DEL/DUP) be the same? Is it annotated the same?

**VCFs*

I put 4 test VCFs in upload/test_data/vcf/cnv

Variant model - I think we should just add a start/end (which takes into account ref/alt for indels)

Then allow inserting N/<DUP> etc as Sequence will be ok?

Dragen CNV has "REF" - if alt is . - CN=2 why store it?

* Benchmark before (plus size of table) altering Variant model
* Add two null fields
* Write management command to populate existing variants
* Do manual migrations for previous management command
* Next migration fail if any are non-null, say to run manual migration
* Alter insert pipelines to add start/end
* Make start/end non-nullable

Alter code to allow insert of CNVs

**Cohort Genotype**

Dragen CNV format fields:

```
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=SM,Number=1,Type=Float,Description="Linear copy ratio of the segment mean">
##FORMAT=<ID=CN,Number=1,Type=Integer,Description="Estimated copy number">
##FORMAT=<ID=BC,Number=1,Type=Integer,Description="Number of bins in the region">
##FORMAT=<ID=PE,Number=2,Type=Integer,Description="Number of improperly paired end reads at start and stop breakpoints">
```

Looks like this uses "qual" - if only single sample we could use that and copy to samples_genotype_quality
CNV Kit format fields

```
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Float,Description="Genotype quality">
##FORMAT=<ID=CN,Number=1,Type=Integer,Description="Copy number genotype for imprecise events">
##FORMAT=<ID=CNQ,Number=1,Type=Float,Description="Copy number genotype quality for imprecise events">
```




**Annotation**

I think it would be best to stay with VEP for the meantime. It takes ages to run if you use the bigwig and repeats but is fast if you don't. I think we should break up the annotation into handling large and small indels / cnvs etc.

This is in a separate issue (link! or move this there) - most importantly we need to add a type (normal/large etc) to AnnotationRangeLock, altering unique together etc

In our VEP annotation - we strip out the genotype info - is this ok with CNVs?


**Other todo**

VEP and AnnoSV don't generate genomic HGVS - should be pretty trivial to do that at least for del/dup ones not multi

**Comment by davmlaw** [comment]
Benchmark on laptop. Full reload of Trio analysis on affected mother 2008 trio: http://localhost:8000/analysis/10743/

18.45, 19.62, 19.7, 17.99, 19.5

**Comment by davmlaw** [comment]
Perhaps VCF changes could have fixed #804

**Comment by davmlaw** [comment]
[ClinVar VCFs do not contain CNVs](https://www.ncbi.nlm.nih.gov/clinvar/docs/ftp_primer/)

> ClinVar’s VCF file includes variants that are simple alleles (not a haplotype or genotype) < 10 kb in length with precise endpoints mapped to the GRCh37 or GRCh38 human genome assemblies. Other variants are not in scope, including cytogenetic variants, copy number variants with inner and/or outer start and stop coordinates, and variants >10 kb.

Will have to get another file

**Comment by EmmaTudini** [comment]
@davmlaw I think the XML file should have them

**Comment by davmlaw** [comment]
I've been pulling in master frequently to reduce future merge conflicts.

If you want to get it all as 1 commit, you can create a new branch off master then merge/squash the ```feature/cnv``` branch into there, to see it as 1 big diff

```
git checkout master
git pull
git checkout -b feature/cnv_squash
git merge --squash feature/cnv
```

This code isn't really ready to go as I need to decide on how the END works and whether to normalize existing records in the database (#818)

I have decided to leave this branch, then work on a new feature branched from master #826 Switch out pyhgvs for BioCommons HGVS - first, as we need that for this code

There should only be a bit of conflict on genes/hgvs.py (mostly adding end to lots of variant tuple things)

**Comment by davmlaw** [comment]
**User testing (ie Shariant)**

From a user point of view - not much has changed.

There was a very big internal changes (75 files), which involves being able to load (from VCF) and store internally symbolic alleles eg ``<DEL>``` and ```<DUP>``` instead of explicitly storing huge ref/alt sequences.

So - need to check that you can resolve HGVS for del/dups, that they can be created, only 1 can be created, and they resolve etc etc.

I changed the "internal variant representation" which used to grow extremely large and now it looks like eg ```chr1:1000-2000 <DEL>```

**Comment by EmmaTudini** [comment]
@TheMadBug Could we do a big upload from ClinVar of dels/dups to test this?

**Comment by EmmaTudini** [comment]
Another example - NM_000441.2(SLC26A4):c.1246_2341ins23

**Comment by davmlaw** [comment]
I think this is because the VCF was written with an N:

```
##fileformat=VCFv4.1
##source=VariantGrid
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
7	107690221	.	N	<DEL>	.	.	SVLEN=25200;SVTYPE=DEL
```

The upload had a message: "Warning: Skipped 1 'non-standard bases in REF sequence' records"

**Comment by davmlaw** [comment]
Just needed to pass in genome build so that it would populate reference base if not there

**Comment by EmmaTudini** [comment]
Start of testing in this google doc - https://docs.google.com/document/d/1470Hqk81Myg-Fw3TkW190SyN5iJ0FFO856qVkBa06rQ/edit

**Comment by EmmaTudini** [comment]
Testing now recorded in private issue - https://app.zenhub.com/workspaces/everything-space-5bb3158c4b5806bc2beae448/issues/gh/sacgf/variantgrid_private/3645

**Comment by davmlaw** [comment]
This is one of the early SV issues - have been using/testing very thoroughly now onto very minor issues

tested eg NM_000441.2(SLC26A4):c.1246_2340dup works fine on VG test, loads with conservation now too in vep 112
