### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#549]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3559/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3559/)

```
Traceback (most recent call last):
  File "/data/variantgrid/sync/sync_runner.py", line 49, in run_sync
    return sync_shariant_download(sync_destination=sync_destination, full_sync=full_sync)
  File "/data/variantgrid/sync/shariant/shariant_download.py", line 130, in sync_shariant_download
    for batch in batch_iterator(records(), batch_size=50):
  File "/data/variantgrid/library/utils.py", line 327, in batch_iterator
    for record in iterable:
  File "/data/variantgrid/sync/shariant/shariant_download.py", line 123, in records
    mapped = shariant_download_to_upload(evidence_keys, record)
  File "/data/variantgrid/sync/shariant/shariant_download.py", line 74, in shariant_download_to_upload
    data = sanitize_data(known_keys, data, source_url)
  File "/data/variantgrid/sync/shariant/shariant_download.py", line 47, in sanitize_data
    for key, blob in data.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by davmlaw** [comment]
@TheMadBug  - while it could be straight forward to wrap it around a null check - is it right that it got back from the server data = None?

**Comment by davmlaw** [comment]
@TheMadBug I assume this is fixed?

**Comment by davmlaw** [comment]
This happened once, 136 days ago. Assuming it's fixed

**Comment by davmlaw** [comment]
The only reason this didn't error was because the sync destination had been disabled

**Comment by davmlaw** [comment]
I ran this manually and eventually got an IncompleteJSON error, as the server timed out in 60 minutes.

I think this caused ijson to start giving bad results for a while as it dealt with the cut off JSON - which crashed things out.

When doing an import, we do it "since" the last successful import. Because it failed here, it'll always use the same since and always die (eg has more and more classifications to do and times out)

**Comment by davmlaw** [comment]
James has made Shariant server side changes, yet to be deployed

SA Path request has streaming=True, we could remove that so that it guarantees it will be done in 60m request time

**Comment by davmlaw** [comment]
Patched prod and SA Path branch. Will deploy out of hours tonight and then start the download

**Comment by davmlaw** [comment]
I deployed stream=False to SA Path and manually ran a sync. It timed out after 1 hour server side, and died while I was inserting data (due to corrupted JSON)

**Comment by TheMadBug** [comment]
Damn, I'll have a look at the JSON generation shortly.

**Comment by davmlaw** [comment]
Closing issue - will handle server side issue in #637
