### ISSUE TITLE
Omim number (link) not showing in analysis

### ISSUE THREAD

**Issue by PeerArts** [SACGF/variantgrid#559]
The OMIM number used to be a link in on variantgrid.com as well as the diagnostic V3. Now the link isn't showing on VG.com anymore. 

It saves a lot of time if we (in analysis) can just click on the link. 
![Screen Shot 2022-01-13 at 10 05 48 am](https://user-images.githubusercontent.com/34562740/149240196-2f3cfe44-0c5f-429a-8717-b2b7ad248ba3.png)

Thanks

**Comment by davmlaw** [comment]
https://variantgrid.com/analysis/3181/

Should be:
LRBA - OMIM:614700
PGM3 - OMIM:615816 

This works on my machine, need to check on vg.com

```HGNC.objects.filter(gene_symbol='LRBA').values("omim_ids")```

**Comment by PeerArts** [comment]
Thanks, for me it's only missing on vg.com

**Comment by davmlaw** [comment]
PGM3 gene versions aren't linked to HGNC - even though description includes HGNC:8907

I think this needs to be solved via gene annotation import - will do in #556 - will re-test once that's done

**Comment by davmlaw** [comment]
Works for me in test, will double check in prod again once upgrade

**Comment by PeerArts** [comment]
Only have the issue in VG.com, not in any other version of VG.

**Comment by davmlaw** [comment]
@PeerArts this is fixed now
