### ISSUE TITLE
DataTables - add easy way to add "download as CSV"

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#571]
The tricky part is solving this:

https://datatables.net/faqs/index#buttons

> Q. How can I export the whole table when using serverSide and Buttons.
> A. Buttons is a client-side process, so it can only export the data available at the client-side. When server-side processing is enabled, the full data set is not held on the client-side, so only the visible data can be exported. You can either: 1. Use a server-side process to create the files to download (recommended) or 2. Disable server-side processing.

But you can use a workaround from here:  https://stackoverflow.com/a/44635032/295724

**Comment by davmlaw** [comment]
Copied how search_box_enabled works, so to add a CSV, use: 

```
self.download_csv_button_enabled = True
```

**Comment by davmlaw** [comment]
@TheMadBug  - you may want to review the commit above - 1st time really using DataTables

I had to add some more JS/CSS - while there I updated the libraries so they're all the latest given in the examples on datatables site, things still seem to work...

**Comment by TheMadBug** [comment]
I'll have a closer look later, but if you're using Datatable's inbuilt CSV download, just make sure it works for AJAX databases with pagination - but glancing at the code I think it probably handles that

**Comment by davmlaw** [comment]
Yep, worked when I tested downloading all 16 rows with only 10 shown on a page

**Comment by davmlaw** [comment]
Tested on variantgrid.com - worked ok
