### ISSUE TITLE
Classification fields mandatory for report but not for submit

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#573]
Regarding the classification report, is it possible to make certain fields mandatory only for "report" button? For instance, if "mode of inheritance" is not filled in, clicking "report" button will highlight this field and not proceed to generating report. At the meantime, it will not stop user submit this classcification (so no mandatory fields for submit/share).

Motivation:

For instance, if it is VUS, or Benigh, they may just want to keep a record, but no report is required. (That is my understanding from the discussion, not sure if that is precise). My interpretation is that: report is not always generated, but the classification form will always be filled/saved/submitted? So in the discussion, users wander if some fields required in the report could be made mandatory in case they forget to fill them in. However, missing those fields should not affect other operations except generating report.

**Comment by TheMadBug** [comment]
These are the evidence keys currently set to mandatory for SA Path:

At the global evidence key level (also shared by Shariant so we'd rather not change these)

- genome_build
- zygosity
- condition (under curation)
- clinical_significance

From lab level configuration:

- sex
- sample_id
- curated_by
- variant_qc
- curation_date
- affected_status
- assertion_method (but defaults to "acmg" anyway)
- curation_context (but defaults to "accredited" anyway)

"mode_of_inheritance" isn't mandatory, but I think it was given as an example of a field that isn't mandatory but that the report complains about.

Would be nice to know out of the above mandatory fields which ones they specifically don't want to be mandatory.

**Comment by davmlaw** [comment]
This was brought up in SA Path diagnostics meeting today. Keeps coming up...

**Comment by TheMadBug** [comment]
I'm 99% sure this can be done with things in the current state.
Just remove them from org and lab config where it says `{"field_name":{"mandatory":true}}`
The report is already pretty good at highlight fields it wants that are missing.

Just need to work out which of the fields currently set to mandatory you don't want.

**Comment by TheMadBug** [comment]
Also I'm not 100% sure but after changing the config you may need to restart VG for changes to take effect.
Give it a go on test.

**Comment by davmlaw** [comment]
I looked at VG3 upgrade (SA Path prod) and mode_of_inheritance is not included as mandatory. I think this has been fixed manually by someone already
