### ISSUE TITLE
Search for g.HGVS doesn't jump to variant page if isn't your default build

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#584]
Set your user settings default build to GRCh38 then search for a 37 g.HGVS eg "NC_000003.11:g.128200732G>T" this shows the results but doesn't jump to the page.

This is because of default build: https://github.com/SACGF/variantgrid_com/issues/53

**Comment by davmlaw** [comment]
I think things only jump if it's your desired build. We should decide on whether this is the right behavior

**Comment by davmlaw** [comment]
@TheMadBug - need to check this behavior is ok for Shariant, if not I can wrap in a setting

I made HGVS matcher return a "kind" ie "g" for HGVS
Search result now takes is_single_build parameter, which we set to True for g.HGVS
This can make a result in a non-preferred build a preferred result

See change 

https://github.com/SACGF/variantgrid/commit/20d677ae9870d9b05b30712196a3b79615dd68de

**Comment by TheMadBug** [comment]
@davmlaw there's already a setting called
PREFER_ALLELE_LINKS
so best to reuse that one.

It's mostly invoked by
view_allele_from_variant
which will take you to the allele or variant depending on it.

**Comment by TheMadBug** [comment]
After demonstration of this happy with how it works, in Shariant it still takes you to the Allele page when following the link.

**Comment by davmlaw** [comment]
**Shariant test:** Search for genomic HGVS where the contig is not in your default build (user settings) - it should now jump to the page

**Comment by EmmaTudini** [comment]
Testing:
- Logged in to Shariant test as non-admin assigned to VCGS Test (emmatudini@gmail.com)
- Genome build set to GRCh38. 
- Searched for NC_000015.9:g.48701198G>A in GRCh37
- Also searched for same variant in GRCh38 - NC_000015.10:g.48409001G>A

- Searched for NC_000010.10:g.89717667C>A (GRch37)

Expected output: Should go straight to appropriate allele page

Actual output: Passed
