### ISSUE TITLE
Error when adding tags on VG.com

### ISSUE THREAD

**Issue by PeerArts** [SACGF/variantgrid#596]
I'm getting this error when I try to tag a variant on vg.com. 

![image](https://user-images.githubusercontent.com/34562740/157162366-bab8d6f2-7bbd-4b38-850c-c7d8696cbb2a.png)

**Comment by davmlaw** [comment]
Thanks for reporting Peer will be able to fix tonight

**Comment by davmlaw** [comment]
Hi, I think I've fixed this issue.

Let me know if you see it again, thanks!

**Comment by davmlaw** [comment]
tested on vg test, no re-occurance in prod
