### ISSUE TITLE
UploadPipeline 11533 failed. Filename: Clinvar Error: null value in column "clinvar_allele_id" of relation "annotation_clinvar_version_9" violates not-null constraint

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#610]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3702/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3702/)

```
UploadPipeline 11533 failed. Filename: Clinvar Error: null value in column "clinvar_allele_id" of relation "annotation_clinvar_version_9" violates not-null constraint
DETAIL:  Failing row contains (3271897, 9095, null, null, null, null, 0, null, 0, 0, f, 1572247, 9, null, null).
CONTEXT:  COPY annotation_clinvar_version_9, line 1: "9	1572247	9095							0		0	0	False"

```

**Comment by TheMadBug** [comment]
@davmlaw if you could have a look at this when you get a chance, occurred after I tried importing the 3rd of March clinvar annotations into Shariant Test - guessing the ClinVar file had some blanks where we've previously always had values or something like that.

**Comment by davmlaw** [comment]
This was due to the gnomad VCF pre-processing change. I stripped VCF INFO fields going in. Usually we don't use them, but we do for ClinVar

I made it only strip genotype VCFs (not ClinVar)

**Comment by davmlaw** [comment]
ClinVar imports worked fine during vt test setup a few days ago
