### ISSUE TITLE
ClinVar Import Annotations Fails : NotNullViolation: null value in column "predictions_num_benign" of relation "annotation_varianttranscriptannotation_version_8" violates not-null constraintDETAIL:  Failing row contains (11102181, null, null, null, null, intergenic_variant, null, null, nu

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#614]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3734/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3734/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/variantgrid/annotation/tasks/annotate_variants.py", line 77, in annotate_variants
    import_vcf_annotations(annotation_run)
  File "/opt/variantgrid/annotation/vcf_files/import_vcf_annotations.py", line 36, in import_vcf_annotations
    bulk_inserter.finish()  # Any leftovers
  File "/opt/variantgrid/annotation/vcf_files/bulk_vep_vcf_annotation_inserter.py", line 430, in finish
    self.bulk_insert()
  File "/opt/variantgrid/annotation/vcf_files/bulk_vep_vcf_annotation_inserter.py", line 453, in bulk_insert
    sql_copy_csv(data_filename, partition_table, header, delimiter=DELIMITER)
  File "/opt/variantgrid/upload/vcf/sql_copy_files.py", line 44, in sql_copy_csv
    return sql_copy_csv_file(f, table_name, columns, delimiter, quote=quote)
  File "/opt/variantgrid/upload/vcf/sql_copy_files.py", line 73, in sql_copy_csv_file
    raise e
  File "/opt/variantgrid/upload/vcf/sql_copy_files.py", line 60, in sql_copy_csv_file
    value = cursor.copy_from(f,
NotNullViolation: null value in column "predictions_num_benign" of relation "annotation_varianttranscriptannotation_version_8" violates not-null constraint
DETAIL:  Failing row contains (11102181, null, null, null, null, intergenic_variant, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2910, null, null, null, 4167385, 8, null, null, null, null).
CONTEXT:  COPY annotation_varianttranscriptannotation_version_8, line 1: "8	2910	4167385									intergenic_variant											1														"

```

**Comment by TheMadBug** [comment]
Triggering command in Shariant Test
```
python3 manage.py clinvar_import /data/annotation/clinvar/38/clinvar_20220425.vcf.gz 
```
Pipeline: Annotation pipeline run 2910

**Comment by davmlaw** [comment]
I think this is due to running the migration of annotation 41 without merging in commit: 1011a312aba1d5db6218a0edcb72f35a375ca0e1 on 3/3/2022 which modified 41

Slack reference: https://variantgrid.slack.com/archives/DGBB86LH5/p1646267952426949

**Comment by EmmaTudini** [comment]
@davmlaw Any chance that this could be prioritised for next week please??

**Comment by davmlaw** [comment]
Well, according to Postgres that shouldn't have happened (even though it did)

https://www.postgresql.org/docs/current/ddl-inherit.html

> ALTER TABLE will propagate any changes in column data definitions and check constraints down the inheritance hierarchy

----------

I think the solution is to generate the SQL for the change, ie:

```python3 manage.py sqlmigrate annotation 0041```

Then copy/paste the alter table part and change it to each individual partition and run it. I'll do that on Shariant test and see how it goes

**Comment by davmlaw** [comment]
OK, I think this happened because we do table inheritance (which sets columns to be inherited ok) then future migrations are applied to all the columns and they are then marked as local, and thus the changes don't cascade down, ie:

https://stackoverflow.com/questions/56666552/postgres-broken-inheritance

```
SELECT attname, attnum, attislocal
FROM pg_attribute
WHERE attrelid = 'annotation_variantannotation_version_2'::regclass AND attnum > 0;
```

I will look into how to make them properly inherited again

**Comment by davmlaw** [comment]
Ran the following manually on Shariant test. Should make a database migration with this SQL in it:

```
DO $$
DECLARE
    tables CURSOR FOR
        SELECT tablename
        FROM pg_tables
        WHERE tablename LIKE 'annotation_variantannotation_version_%'
        ORDER BY tablename;
BEGIN
    FOR table_record IN tables LOOP
	EXECUTE format('ALTER TABLE %I 
	DROP COLUMN IF EXISTS "cadd_raw",
	DROP COLUMN IF EXISTS "fathmm_pred",
	DROP COLUMN IF EXISTS "gene_text",
	DROP COLUMN IF EXISTS "hgnc_id",
	DROP COLUMN IF EXISTS "mutation_assessor_pred",
	DROP COLUMN IF EXISTS "mutation_taster_pred",
	DROP COLUMN IF EXISTS "polyphen2_hvar_pred",
	DROP COLUMN IF EXISTS "swissprot",
	DROP COLUMN IF EXISTS "symbol_source",
	DROP COLUMN IF EXISTS "trembl",
	DROP COLUMN IF EXISTS "uniparc";', table_record.tablename);
    END LOOP;
END$$;


DO $$
DECLARE
    tables CURSOR FOR
        SELECT tablename
        FROM pg_tables
        WHERE tablename LIKE 'annotation_varianttranscriptannotation_version_%'
        ORDER BY tablename;
BEGIN
    FOR table_record IN tables LOOP
	EXECUTE format('ALTER TABLE %I 
	DROP COLUMN IF EXISTS "cadd_raw",
	DROP COLUMN IF EXISTS "dbsnp_rs_id",
	DROP COLUMN IF EXISTS "fathmm_pred",
	DROP COLUMN IF EXISTS "gene_text",
	DROP COLUMN IF EXISTS "hgnc_id",
	DROP COLUMN IF EXISTS "mutation_assessor_pred",
	DROP COLUMN IF EXISTS "mutation_taster_pred",
	DROP COLUMN IF EXISTS "phastcons_100_way_vertebrate",
	DROP COLUMN IF EXISTS "phastcons_30_way_mammalian",
	DROP COLUMN IF EXISTS "phastcons_46_way_mammalian",
	DROP COLUMN IF EXISTS "phylop_100_way_vertebrate",
	DROP COLUMN IF EXISTS "phylop_30_way_mammalian",
	DROP COLUMN IF EXISTS "phylop_46_way_mammalian",
	DROP COLUMN IF EXISTS "polyphen2_hvar_pred",
	DROP COLUMN IF EXISTS "pubmed",
	DROP COLUMN IF EXISTS "swissprot",
	DROP COLUMN IF EXISTS "symbol_source",
	DROP COLUMN IF EXISTS "trembl",
	DROP COLUMN IF EXISTS "uniparc",
	DROP COLUMN IF EXISTS "predictions_num_benign",
	DROP COLUMN IF EXISTS "predictions_num_pathogenic";', table_record.tablename);
    END LOOP;
END$$;
```

**Comment by davmlaw** [comment]
ok, I re-ran the annotation on Shariant test and it seemed to work that time. Have pushed migration with SQL above

**Comment by TheMadBug** [comment]
Believe this is all working fine now (there is a migration script for this, moving to review column.

**Comment by EmmaTudini** [comment]
Testing:
- Logged in as admin assigned to Test lab 1
- Imported NM_000020.2(ACVRL1):c.1346C>T (originally novel compared to clinvar compare but should now be discordant due to recent update in clinvar (2 months ago)
- Exported clinvar compare against GRCh37

Expected output: NM_000020.2(ACVRL1):c.1346C>T should be discordant (to show that the file was imported properly)
Actual output: Passed

Note: @themadbug THis allele https://test.shariant.org.au/variantopedia/view_allele/7884 is discordant according to the file - comparison is B vs Conflicting_interpretations_of_pathogenicity|_association?? Is that expected?

**Comment by TheMadBug** [comment]
Hmm, that would most likely be because it doesn't know what to do about `_association`, I'll exclude that as I'm guessing it doesn't have any special meaning for our context?

**Comment by EmmaTudini** [comment]
No idea what it means either, but since we know there's a reason for it, maybe leave it in.

**Comment by TheMadBug** [comment]
Does going to the ClinVar page provide any detail?
My change would be to treat "Conflicting_interpretations_of_pathogenicity|_association" the same as "Conflicting_interpretations_of_pathogenicity" which would then just result in the output saying "Unknown" instead of "Discordant"

**Comment by EmmaTudini** [comment]
Not really - https://www.ncbi.nlm.nih.gov/clinvar/variation/8178/?oq=%22NM_007272.3(CTRC):c.760C%3ET%22%5Bvarname%5D&m=NM_007272.3(CTRC):c.760C%3ET%20(p.Arg254Trp). Ok if it goes to unknown, that would probably make the most sense

**Comment by TheMadBug** [comment]
The second "Submitted interpretations and evidence" list on that page is
Pathogenic
**association** (from Invitae with no Condition)
Likely pathogenic
Benign
etc

Guessing "association" Is when you're feeling as wishy washy as possible.

**Comment by TheMadBug** [comment]
Okay clinvar values are split on both `,` and `|` now.
not_provided, association and other are ignored when it comes to comparing values.

But now we can get "Conflicting;R" as in both conflicting and Risk Factor etc
But conflicting will always take priority and mark as "Unknown" when it should probably be marked as "Overlap" but I think the comparison is good enough for now.

Interesting that LB;P gets turned into just "Conflicting" but Drug Response, Risk Factor etc still get to show up.

**Comment by EmmaTudini** [comment]
Might be worthwhile for you to look at this page? https://www.ncbi.nlm.nih.gov/clinvar/docs/clinsig/#clinsig_options_scv
There may be other options that pop up and would be good to account for them. Not sure about ignoring them, I'd almost lean towards putting them all in unknown...what happens if the overall classification is not_provided and Shariant has pathogenic, what will the status be? 

Also might be an idea to put everything other than B, LB, VUS, LP and P into unknown?

Have commented on #3264 regarding the meaning of "overlap"

**Comment by TheMadBug** [comment]
Okay re the linked file and your comments
https://ftp.ncbi.nlm.nih.gov/pub/GTR/standard_terms/Clinical_significance.txt

I now:
Divide statuses into regular (ones that can be mapped to our clinical sig values) and "unknown".
The regular statuses are:
"Benign": "B",
"Likely_benign": "LB",
"Uncertain_significance": "VUS",
"Likely_pathogenic": "LP",
"Pathogenic": "P",
"Pathogenic/Likely_pathogenic": ["P", "LP"],
"Benign/Likely_benign": ["B", "LB"],
"risk_factor": "R",
"drug_response": "D"

Overlaps have been renamed to "Intersection"
If there's a mix of regular and unknown statuses, you can still get an "intersection" e.g.
D vs  Conflicting;drug response will be "intersection" rather than "unknown"
Otherwise if there are unknown statuses and no intersection, the status will be "unknown".

Prior "not_provided" was ignored and would still be marked as "novel".
Not sure why people report to ClinVar without even a status, but that will now cause "unknown" (it's not very frequent so probably still best to highlight it).

Somewhat confusingly regular statuses will be translated when printed out, but unknown ones will be the exact provided text.

**Comment by TheMadBug** [comment]
So LP;P vs LP;P is still
LP agreement with LP, but not with P
P agreement with P, but not LP

So LP;P to LP;P is not complete agreement, it's half agreeing half slight disagreement to both.

**Comment by TheMadBug** [comment]
Note I have ended up splitting the ClinVar resolved statuses and ClinVar raw status into separate columns so
`Pathogenic/Likely_pathogenic|_risk_factor|_associated`
would render as
`P;LP;R;?` in "ClinVar Clinical Significances" and
`Pathogenic/Likely_pathogenic|_risk_factor|_associated` in "ClinVar Clinical Significances Raw"

**Comment by EmmaTudini** [comment]
I still don't think that intersection is going to make a whole lot of sense to the labs downloading this file. Overlap might actually be better? To me, examples like B vs B;LB would be better off under confidence to represent the least best match. It would also line up with calling it confidence for P vs LP;P (which is happening in test at the moment).

**Comment by TheMadBug** [comment]
Think this is best done over zoom, but I went with intersection other than the least best match as
B vs D;B;LB would be discordant as B is not Drug Response.

If anything Intersection should be renamed to "Agreement (partial)". Might be with discussing in a meeting along with any other outstanding issues.

**Comment by EmmaTudini** [comment]
Did a quick test by downloading from admin account - Passed
