### ISSUE TITLE
Notice on Clingen allele registry webpage - NOTICE - API Response Change: Users of the API please note that clingenPreferredTitle is now communityStandardTitle

### ISSUE THREAD

**Issue by EmmaTudini** [SACGF/variantgrid#626]
Not sure if we capture this field specifically 

NOTICE - API Response Change: Users of the API please note that clingenPreferredTitle is now communityStandardTitle

**Comment by TheMadBug** [comment]
clingenPreferredTitle doesn't appear in the source code, neither does preferred title, so I think we're safe.
Will leave it to @davmlaw to confirm though.
