### ISSUE TITLE
Annotation pipeline runs grid - filter by annotation version

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#633]
Need to be able to jump to a genome build variant annotation version quickly

Have a button per VEP version that works in combination with genome builds, so can easily select 37/38 and vep100/vep106

**Comment by davmlaw** [comment]
This was pretty unwieldy in shariant test/prod, I deleted some old variant annotation versions (vep 97 for Ensembl in 2019) which wasn't referenced by anything (checked in admin that it wouldn't cascade delete anything)

**Comment by EmmaTudini** [comment]
@TheMadBug How do I test this?

**Comment by TheMadBug** [comment]
It's the admin only page https://test.shariant.org.au/annotation/variant_annotation_runs?activeTab=GRCh38%3Atv9-100-refseq

I wouldn't worry about it too much as I think the page is only really used by Dave when something goes wrong with annotations.

**Comment by davmlaw** [comment]
I checked this works fine on Shariant
