### ISSUE TITLE
Suggestion: Improving 'Nearby Variants' Page

### ISSUE THREAD

**Issue by a1618617** [SACGF/variantgrid#641]
Hi guys,

I'm doing some re-classifications for the GAS cohort paper, and I quite liked Varsome's way of summarising Clinvar variants (Benign-Pathogenic) across "hotspots" (domains for regions with uniprot ID, or +/-25bp flanking regions for un-annotated protein regions):

Example: https://varsome.com/variant/hg19/6%3A31747470%20G%3EA?
![image](https://user-images.githubusercontent.com/16040469/174740902-34abde60-6e54-40a6-8557-f80971b8b6f3.png)

It'll be really cool to add that information to the variant page/nearby variants page. Example, on the variant page you have the number of clinvar variants within the exon/domain/50bp flanking, but in brackets if you could put the number of (n_Benign, n_LB, n_VUS, n_LP, n_P), that would be really useful for med scientists to quickly assess the PM1 criteria:
![image](https://user-images.githubusercontent.com/16040469/174742316-e64e7cd8-dc30-47f1-9466-495d858d461c.png)

Thanks.

**Comment by davmlaw** [comment]
I'd already made this change but forgot to actually use it by passing ```clinical_significance=True``` to the function (d'oh!). 

I've turned it on and also enabled it in SA Path

**Comment by a1618617** [comment]
Thanks Dave!

**Comment by davmlaw** [comment]
Had to undo change in SA Path as it had diverged a bit from prod, so didn't work right

**Comment by davmlaw** [comment]
Tested vg test

http://test.variantgrid.com/variantopedia/view_variant/959143

Shows:  ClinVar: (B: 1, LB: 1),
