### ISSUE TITLE
Add Faster g.HGVS method

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#643]
We should add a quick optimisation, where if a variant isn't an indel, we convert to g.HGVS via:

```f"{variant.locus.contig.refseq_accession}:g.{variant.locus.position}{variant.locus.ref}>{variant.alt}"```

Benchmarking, this is a bit over 100x faster than calling the HGVS methods

**Comment by davmlaw** [comment]
Bit over 10x as fast for 1k variants:

```
In [3]: %timeit g_hgvs = get_ghgvs(fast=False)  # Old way
807 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [4]: %timeit g_hgvs = get_ghgvs(fast=True)  # New way
77.4 ms ± 356 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by TheMadBug** [comment]
The g.hgvs doesn't even manifest itself anywhere I think, so all there is to test is does the variant description on the classification form show the right c.hgvs (it's generated at the same time as the g.hgvs)

**Comment by EmmaTudini** [comment]
Testing:
- Logged in to Shariant test as non-admin assigned to VCGS Test (emmatudini@gmail.com)
- Imported variant NM_000138.5(FBN1):c.*1989C>T g.hgvs NC_000015.10:g.48409001G>A against GRCh38 (same variant)
NM_000138.5(FBN1):c.*1989C>A g.hgvs NC_000015.10:g.48409001G>A against GRCh38
 (different change)

**Comment by EmmaTudini** [comment]
@davmlaw Also let me know if there are other things that I should be testing here

**Comment by davmlaw** [comment]
The optimisation cheats to generate the g.HGVS quickly, and failure would be using the cheat where you shouldn't (ie an indel) and thus generating an invalid HGVS

I will loop through classifications on test and prod, and make sure all the HGVSs are valid

**Comment by davmlaw** [comment]
Hmmm, testing this actually failed as it has errors with reference variants. We don't have many of those but occasionally we do as people classify something against an old genome build patch version

So need to fix this before the deploy

**Comment by davmlaw** [comment]
This was fixed, then made it into Shariant prod in september:

 https://github.com/SACGF/variantgrid/commits/shariant_prod_sep
