### ISSUE TITLE
pytz is being deprecated in Django 5

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#645]
https://docs.djangoproject.com/en/4.0/releases/4.0/#zoneinfo-default-timezone-implementation

There's only about 7 references to pytz left in Django, probably relatively easy to remove.
Always nice to remove a dependency.

**Comment by davmlaw** [comment]
zoneinfo is 3.9 only so I went with ```dateutil.tz```. Removed pytz from requirements.txt (and dev requirements)

I thought django.utils.timezone.now() was local time but it's UTC so I had to add the conversion to localtime() in a second checkin

**Comment by EmmaTudini** [comment]
Went to most pages under https://app.zenhub.com/workspaces/everything-space-5bb3158c4b5806bc2beae448/issues/sacgf/variantgrid_private/3257 and no explosions
