### ISSUE TITLE
OntologyVersion - gene_disease_relations returns multiple results

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#648]
So on the gene symbol page, the gene/disease relationship is duplicated and shows the HGNC instead of disease name.

```
OntologySnake.gene_disease_relations("RAD51C")
```

Internally this calls ```OntologySnake.terms_for_gene_symbol``` with desired_ontology=MONDO but it returns ontology in HGNC as well:

```
[<OntologyTermRelation: HGNC:9820 RAD51C -> (related) -> MONDO:0013253 breast-ovarian cancer, familial, susceptibility to, 3. Gene/Disease: Autosomal dominant (Strong: Genomics England PanelApp)>,
 <OntologyTermRelation: HGNC:9820 RAD51C -> (related) -> MONDO:0013248 Fanconi anemia complementation group O. Gene/Disease: Autosomal recessive (Strong: TGMI|G2P Moderate: Ambry Genetics)>,
 <OntologyTermRelation: HGNC:9820 RAD51C -> (related) -> MONDO:0016248 familial ovarian cancer. Gene/Disease: Autosomal dominant (Definitive: ClinGen)>,
 <OntologyTermRelation: MONDO:0013248 Fanconi anemia complementation group O -> (related) -> HGNC:9820 RAD51C. Gene/Disease: Autosomal recessive (Strong: TGMI|G2P Moderate: Ambry Genetics)>,
 <OntologyTermRelation: MONDO:0013253 breast-ovarian cancer, familial, susceptibility to, 3 -> (related) -> HGNC:9820 RAD51C. Gene/Disease: Autosomal dominant (Strong: Genomics England PanelApp)>,
 <OntologyTermRelation: MONDO:0016248 familial ovarian cancer -> (related) -> HGNC:9820 RAD51C. Gene/Disease: Autosomal dominant (Definitive: ClinGen)>]
```

**Cause**

For some imports, OntologyTermRelation is:

Older import - source_term=HGNC, dest_term = MONDO
Newer import - source_term=MONDO, dest_term = HGNC

I am not sure whether it's due to the ontology import having put things around the other way, or the fact that we used to delete all of the ontology term relationships before every import (now we keep old and use new version), so wouldn't have had this problem

**Potential fixes**

* We could sort source/dest term so that it's always inserted in a particular order?
* We could pick a particular ontology version and only use that (however I think that may still have the problem with the wrong order?)

**Comment by TheMadBug** [comment]
I can say that in Shariant Test no relationships have HGNC as the source.
and the following all occurred post upgrade:
mondo_file : 3 days ago
gencc_file : 3 days ago
and panelappau has done a lot of work lately.

**Comment by davmlaw** [comment]
Bug seems to only occur on my CCB west environment, which I did a table dump/restore on - perhaps I made a mistake there and this does not happen elsewhere.

Double check after deploying to VG.com and if no error there, can close this

**Comment by davmlaw** [comment]
Won'tfix - Dev environment only error

This was due to my dump and restore of the ontology table on desktop while I was doing dev and restore

I dumped out using select * (where dest_term was before source term) then restored back with explicit columns where I put source before dest

**Comment by davmlaw** [comment]
Well, the being backwards thing was due to dev. Still shows duplicates though, need to fix that

**Comment by davmlaw** [comment]
working in branch ontology_version

GeneAnnotationVersion now has ontology_version on it, and this must be the same as AnnotationVersion.ontology_version

so it's likely we'll have to do a manual migration to get people to run managment command ```gene_annotation --missing```

Am running on my HP desktop overnight

**Comment by davmlaw** [comment]
Confirm that no dupes show on 

http://test.variantgrid.com/genes/view_gene_symbol/RAD51C
