### ISSUE TITLE
HGVS - Switching out reference base for dups leads to different allele

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#659]
While fixing https://github.com/SACGF/variantgrid_shariant/issues/7 - that gives a warning if you switch the reference base on dups, I think the way it currently works is wrong.

A>AA means that we saw two "A"s in the patient but there was only a single A in the reference
At the moment if we switch reference on a dup, it makes it eg "C>CA" which means the allele is "CA" - different than the original "AA"

The patient genotype shouldn't change, only the reference base. So I think a dup should change to a delisn?

Eg compare searching for these two:

```
NM_004631.4(LRP8):c.2855T>TT' resolved to 1:53247055 C>AA # allele stays the same only ref swapped
NM_004631.4(LRP8):c.2855dupT' resolved to 1:53247054 T>TA
```

**Comment by EmmaTudini** [comment]
Some additional variants to use for testing
NM_007294.3(BRCA1):c.5097dupA goes to NM_007294.3(BRCA1):c.5098dupA. 
NM_007294.3(BRCA1):c.5097dupA goes to NM_007294.3(BRCA1):c.5097_5098insC (which I think makes more sense?).

**Comment by davmlaw** [comment]
NM_004631.4(LRP8):c.2855T>TT isn't a valid HGVS

As a HGVS uses a versioned reference, the ref should be the same everywhere

Genome build patch versions don't alter the main chromosomes (a fix-patch that did that would bump the contig version number) so we don't have to worry about it for genomic contigs

Because we are retrieving the transcript sequences from the genome, it's possible that provided refs and our refs are different.

It's important then to store this, or give a warning.



NM_007294.3(BRCA1):c.5097dup (implicit reference G)
NM_007294.3(BRCA1):c.5097dupG resolve to the same place

But specifying a different reference base, ie NM_007294.3(BRCA1):c.5097dupT

is handled differently in the different HGVS libraries.

biocommons = (VariantCoordinate(chrom='17', pos=43063928, ref='T', alt='TC')
pyhgvs = (VariantCoordinate(chrom='17', pos=43063928, ref='T', alt='TA')

and if given the VCF coordinates, biocommons will format it as:

NM_007294.3:c.5097_5098insT

There are some tests in genes.tests.test_hgvs.TestHGVS._test_reference_diff that are commented out

As pyhgvs swaps out the reference base, it can also normalize it to a different coordinate. This is easier to see with genomic variants.

This is the 

```
In [72]: matcher.get_variant_tuple("NC_000001.10:g.53712727dup")  # implicit
Out[72]: VariantCoordinate(chrom='1', pos=53712726, ref='T', alt='TC')

In [73]: matcher.get_variant_tuple("NC_000001.10:g.53712727dupC")  # explicit ref base
Out[73]: VariantCoordinate(chrom='1', pos=53712726, ref='T', alt='TC')
```

But when you supply different ref explicitly:

```
In [74]: matcher.get_variant_tuple("NC_000001.10:g.53712727dupG")
ERROR HGVS converters calling hgvs_to_variant_coords_and_reference_match(('NC_000001.10:g.53712727dupG', None)) returned different results! [
((VariantCoordinate(chrom='1', pos=53712727, ref='C', alt='CG'), self.provided_ref='G',self.calculated_ref='C'), 'BioCommons hgvs v0.1.dev1516+g2992037.d20230614'),
((VariantCoordinate(chrom='1', pos=53712726, ref='T', alt='TG'), self.provided_ref='G',self.calculated_ref='C'), 'pyhgvs v0.12.4')])
Out[74]: VariantCoordinate(chrom='1', pos=53712727, ref='C', alt='CG')
```

It looks like pyhgvs is normalizing against the provided genome sequence, while biocommons is normalizing against the retrieved one

**Comment by davmlaw** [comment]
I have fixed this in biocommons

NM_007294.3:c.5097dup has reference base G, so is equivalent of "NM_007294.3:c.5097dupG"

When you import the wrong base as a dup - NM_007294.3:c.5097dupC

Existing pyhgvs behavior is to import as NM_007294.3(BRCA1):c.5097_5098insC (ie forces insert of C at this pos)

New behavior is to replace reference base but not NM_007294.3(BRCA1):c.5097dupG

**Comment by davmlaw** [comment]
To test this you need to either have settings set to use biocommons for HGVS

Or you could use the hgvs resolution tool I guess

**Comment by EmmaTudini** [comment]
Testing:
- Logged in as admin to test via the HGVS resolution tool
1. NM_001009944.3(PKD1):c.*15dupG (correct base) vs NM_001009944.3(PKD1):c.*15dupC (incorrect base)
Expected output: Correct should normalise as expected. Incorrect should be changed to correct base and normalised
Actual output: Passed - both went to c.*19dupG

@davemlaw @TheMadBug how do we switch out to start using biocommons? Does this mean that if there are extra things that need to be implemented, that we can deploy other changes and just not switch over until all hgvs dev is done?

**Comment by TheMadBug** [comment]
Will have to wait to switching prod to biocommons for this to take effect in prod.
