### ISSUE TITLE
dbNSFP gene annotation Evidence Keys

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#667]
Should be able to just pull from variantgrid_column_id, eg previous config:

https://github.com/SACGF/variantgrid/commit/24819c484a1849212a0a7b92c821238e9c3271a0#diff-bedf613dbf1742e537e2c61f8eb4f63c2454955ffc9ffc6ee5c3cfe5f6ef4def

**Comment by davmlaw** [comment]
Probably won't include pathways etc, people can copy/paste into gene if they need

Many of the new fields are prediction - so can go in that section

But perhaps some are in functional, ie CRISPR screens?

https://www.sciencedirect.com/science/article/pii/S0092867415014956?via%3Dihub

May just leave those out for now

**Comment by davmlaw** [comment]
Actually, looking in "Gene" - there is "Gene constraint" which is "Based on z scores & pLI values calculated in gnomAD"

And also VAAST - which is "probabilistic search tool for identifying damaged genes"

So gene based probabilistic stuff can go in "gene"

Should move LoFTool there too I guess

**Comment by davmlaw** [comment]
**Shariant test:** Added new EKeys in Gene section if you want to review them

```
'gnomad_pli', 'gnomad_prec', 'gnomad_pnull', 'gene_damage_index_score', 'phi', 'ghis', 'prec', 'hipred_score', 'gene_indispensability_score', 'essential_gene_crispr', 'essential_gene_crispr2', 'essential_gene_gene_trap'
```

**Comment by EmmaTudini** [comment]
@davmlaw For the gnomad fields - just trying to work out if they overlap with existing fields. Where do you get the values from pli, prec and pnull from?

There are a few other edits that I'd like to make. Should I do that in the admin screen of Shariant test?

**Comment by davmlaw** [comment]
gnomAD document them here:

https://gnomad.broadinstitute.org/news/2018-10-gnomad-v2-1/#constraint

They recommend people use the o/e instead, but gnomAD still provide them, and people still use them (maybe for historical reasons)

**Comment by TheMadBug** [comment]
@EmmaTudini are your proposed changes to the description of evidence keys, or to which evidence keys are used in the first place?

The former will be simple enough, the later is a bit more complicated as these values are to be automatically populated in other environments.

**Comment by EmmaTudini** [comment]
Just the descriptions and labels (some labels are a bit long and could be shorter)

**Comment by TheMadBug** [comment]
Too easy. Probably easiest to just keep a list of what you changed then and we can apply it to Shariant Prod config after the upgrade.

Up to @davmlaw if he would want these applied to other VG environments.

**Comment by davmlaw** [comment]
@EmmaTudini - are you going to make any changes?

If not, can we close this?

If you have already done so please let me know what you altered

**Comment by davmlaw** [comment]
I checked EKeys in all environments in issue https://github.com/SACGF/variantgrid_private/issues/3443 and there wasn't any change to dbNSFP text, so going to close this
