### ISSUE TITLE
Gene / Variant page - tooltip help

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#668]
Have a little (?) icon using font awesome that appears next to field labels, then put the VariantGridColumn.description text in the tooltip

James mentioned we have "hover help" with data-toggle=tooltip which could be used for this

**Comment by TheMadBug** [comment]
data-toggle="tooltip" title="The help goes here"

or

data-toggle="popover" title="The title of help goes here" data-content="The content of help"
(this is more flexible, but clicking on a the field keeps the popover box on screen, which can cause issues)

and give the label class="hover-help"

I think we really should put support for this in the {% labelled %} tag.
Add a "help" attribute, then render it as appropriate.
(It looks like there's already some support for rendering tooltip in labelled, but only if "shorten_label" is True, and I think that's never set anymore. So remove support for shorten_label)

**Comment by davmlaw** [comment]
Added help to labelled, and took off shorten_label. It has data-html="true" so is ok with links. 

The popup has ```class="popover-hover-stay"``` which has some magic in global.js to make it stay when hovered over. Will see if it ends up with those permanent hang around popups... haven't seen any yet

Started on variant page, TODO:
* combo fields (maxent scan, splice AI) are missing help. Perhaps make them manually?
* Still need to check every field and maybe buff a few up
* Need to do gene page

**Comment by davmlaw** [comment]
This is not used by Shariant

**Comment by davmlaw** [comment]
works no issues with hanging around found so far
