### ISSUE TITLE
Evidence Key help text - condition under curation

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#669]
Need to update help to say MONDO preferred

HF to SAP

**Comment by davmlaw** [comment]
Just copy/paste into admin:

```
A condition with an association to the gene for which the variant was interpreted against.

Input MONDO, OMIM, HPO, Orphanet, DOID reference numbers and/or free text.
<em>If you require another ontology set, please contact the Shariant Team.</em>
This field is used for Condition Text Matching, where the resolved condition text is viewable
on classification listings and in the summary box on the classification form.

For the recording of phenotypes observed in the patient, see the "Patient phenotype" field.

See the Clinvar recommendations below for more detail
```

**Comment by TheMadBug** [comment]
Was already done, but doesn't hurt to do it again (I probably should have updated the Google Doc) or noticed this issue (I created my own).
<img width="1124" alt="CleanShot 2022-08-19 at 08 48 25@2x" src="https://user-images.githubusercontent.com/2100255/185508447-2b1fe400-fb81-426d-9340-d67749c9862f.png">

**Comment by davmlaw** [comment]
sorry I only for sure read things I'm tagged in, kind of skim read slack when it's super busy
