### ISSUE TITLE
Seqauto scans - make it possible for a group to run this (ie not superuser)

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#675]
Some diagnostic people want to be able to run this manually, but not be admins

Probably best to make a setting for a group with this special power, then add them to this

**Comment by TheMadBug** [comment]
We generally have:
admin power
user who has write access to data
user who has read access to data

But we've never really touched on making anything permission based other than admin or not.
Think this is something we should look at in the future for functions? (or would that need to be a bit of a refactor first?)

**Comment by davmlaw** [comment]
Yeah the 'magic group' was a hack....

Guardian permissions work on records, so you could perhaps make a record that defines actions

```
class UserAction(model.Model):
    app = models.TextField()
    action = models.TextField()

    class Meta:
        unique_together = ('app', 'action')
```

Then we insert them for actions that have restrictions, and they'll automatically be accessible to superusers

We could assign users/groups that way

The only trouble is - this requires a schema migration for SA Path and we don't want to do that. Maybe do the magic hack for patch back and do it properly going forward after upgrades etc

**Comment by TheMadBug** [comment]
I was thinking more of Django's built in permissions setup, as in we just make a permission called
"seqauto_scan_initiate" and assign it to users.

**Comment by davmlaw** [comment]
Ah, ok just tried and it'll work:

```
ct = ContentType.objects.get_or_create(app_label='seqauto', model='seqrun')[0]
perm = Permission.objects.create(codename='seqauto_scan_initiate', name='SeqAuto scan initiate', content_type=ct)

# Then can use 
user.has_perm(perm)
```

**Comment by davmlaw** [comment]
Tried assigning the permission to a non-admin and couldn't get it to work will try tomorrow

Also need to put to master, as well as the migration

**Comment by davmlaw** [comment]
OK, worked out how to do it:

```
user.has_perm('seqauto.seqauto_scan_initiate')
```

And there's also a way to do it nicely in templates:

```
        {% if perms.seqauto.seqauto_scan_initiate %}
            We can scan stuff!
        {% endif %}
```

**Comment by davmlaw** [comment]
Tested ok on SA Path, confirmed that non-admin test user could be given and revoked permissions to perform scan

**Comment by davmlaw** [comment]
Deployed to SAP

Need to write something up in the docs about this, and tell Song that AP has perm and is not superuser

We could also add a permission so users can see eg the server status?
