### ISSUE TITLE
HGVS resolved as off transcript (but is really an intron?)

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#682]
NM_001101.4(ACTB):c.-6-4G>T

This is resolved correctly in GRCh38 but for GRCh37 we get:

```
Invalid HGVS name "'NM_001101.4(ACTB):c.-6-4G>T' transcript position -5 is outside of NM_001101.4 (ACTB/GRCh37) range [1,1922]"
```

Mutalyzer gives an error:

```
Intronic position given for a non-genomic reference sequence. Tip: make use of a genomic reference sequence, e.g., NC_000007.14(NM_001101.4).
```

**Comment by davmlaw** [comment]
Comparing the JSON data, it's the same except the build coordinates, and end-length is the same.

The only difference is that GRCh38 provides cds_end and cds_start

```
In [55]: pt_37.get_cds_start_stop()
Out[55]: (5570340, 5566776)  # 3564 bases apart

In [56]: pt_38.get_cds_start_stop()
Out[56]: (5529657, 5527747) # 1910 bases apart
```

The data generated for pyHGVS is:

```
In [31]: t_37.pyhgvs_data
Out[31]: 
{'id': 'NM_001101.4',
 'chrom': 'NC_000007.13',
 'start': 5566776,
 'end': 5570340,
 'strand': '-',
 'cds_start': 5566776,
 'cds_end': 5570340,
 'gene_name': 'ACTB',
 'cdna_match': [[5566776, 5567522, 1177, 1922, None],
  [5567634, 5567816, 995, 1176, None],
  [5567911, 5568350, 556, 994, None],
  [5568791, 5569031, 316, 555, None],
  [5569165, 5569294, 187, 315, None],
  [5570154, 5570340, 1, 186, None]],
 'start_codon_transcript_pos': 192,
 'stop_codon_transcript_pos': 1320,
 'exons': [[5566776, 5567522, 1177, 1922, None],
  [5567634, 5567816, 995, 1176, None],
  [5567911, 5568350, 556, 994, None],
  [5568791, 5569031, 316, 555, None],
  [5569165, 5569294, 187, 315, None],
  [5570154, 5570340, 1, 186, None]]}

In [30]: t_38.pyhgvs_data
Out[30]: 
{'id': 'NM_001101.4',
 'chrom': 'NC_000007.14',
 'start': 5527145,
 'end': 5530709,
 'strand': '-',
 'cds_start': 5527747,
 'cds_end': 5529657,
 'gene_name': 'ACTB',
 'cdna_match': [[5527145, 5527891, 1177, 1922, None],
  [5528003, 5528185, 995, 1176, None],
  [5528280, 5528719, 556, 994, None],
  [5529160, 5529400, 316, 555, None],
  [5529534, 5529663, 187, 315, None],
  [5530523, 5530709, 1, 186, None]],
 'start_codon_transcript_pos': 192,
 'stop_codon_transcript_pos': 1320,
 'exons': [[5527145, 5527891, 1177, 1922, None],
  [5528003, 5528185, 995, 1176, None],
  [5528280, 5528719, 556, 994, None],
  [5529160, 5529400, 316, 555, None],
  [5529534, 5529663, 187, 315, None],
  [5530523, 5530709, 1, 186, None]]}
```

If I delete the provided cds_start/end from 38 then generate the pyhgvs it has the same cds_start/end (generated from start/stop codon)

```
 'cds_start': 5527747,
 'cds_end': 5529657,
```

**Comment by davmlaw** [comment]
In the UTA data, the CDS start and end are set to the full extent of the transcript (there are no UTRs)

OK, basically the problem is that cds_start and cds_end are not set in UTA data, only the start_codon_transcript_pos and stop_codon_transcript_pos

Then when converting from cdot JSON to pyhgvs JSON - if cds_start/cds_end is not provided, it is set to transcript start/end

**Comment by davmlaw** [comment]
Working on branch "uta_transcript_extents"

**Comment by davmlaw** [comment]
VG code calls get_pyhgvs_data which means that must be correct, rather than patching the transcript afterwards.

This means we need to fix the data 

I will make a UTA only release to upgrade VG data with

**Comment by davmlaw** [comment]
Testing: Try searching/importing HGVSs that are in introns, as well as before/after the transcripts

I don't think we need to import the cdot data, as the original error is fixed. We do so regularly and can wait for the next one

There were a few issues here:

* cdot issue about UTA cds_start/cds_end 
* The VG internal check about being on the transcript was wrong due to using "coding_length" which was calculated from the cds_start/end above. I changed this so that it used PyHGVS to calculate things in genomic coords, and then do the check there. This means that the check doesn't expose the 1st bug anymore, so we can resolve this without updating the cdot data (transcript.data via import gene annotation)

The only other thing that uses coding_length is protein length (displayed on variant details page) - but this won't happen as all of the VEP transcripts should be available somewhere else than UTA. On the transcript page, it may also say that proteins between genome builds different in length

**Comment by davmlaw** [comment]
Tested on Shariant test:

NM_001101.4:c.-6-4G>T

resolves to  CA201567 which has the above HGVS listed there

**Comment by EmmaTudini** [comment]
Tested imported NM_001101.4(ACTB):c.-6-7delC - Passed

**Comment by davmlaw** [comment]
Passed and has been deployed for a while now
