### ISSUE TITLE
Annotation page can show loading instructions to non-admin users

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#69]
The annotation page (when expanding some sections), will provide any user the server instructions required to load annotation data - though non-admin users wont be able to do anything with this.

In addition it links to https://github.com/SACGF/variantgrid/wiki/Transcripts-and-HGVS which is now defunct.

Lastly the page uses a combination of jQuery & Bootstrap show/hide toggle. Convert it all to Bootstrap.

**Comment by sksmi** [comment]
Tested using sking_gc account. Passed.
https://app.qase.io/run/VG/dashboard/12

Didn't test bootstrapping.
