### ISSUE TITLE
ACMG changes - population weighting (PM2), bayesian framework

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#691]
Need to think about (and maybe report back to SA Path) the difficulty of implementing 2 changes. Let James know and maybe he can have a quick think / discuss etc

SA Path do NOT want to switch to these yet, but are waiting for new ACMG guidelines update, word on the street is they will be released soon

* A paper came out saying that 52% of ExaC variants only occured in that patient and rare varants aren't that strong a case so PM2 should be changed to a supporting weight.

* At the moment we use a simple addition of scores, however there is the ACMG bayesian framework - how much work would it be to change to using this?

How would it be done and should you be able to toggle it on or off? Ie settings or lab/system wide config?

**Comment by TheMadBug** [comment]
Currently the ACMG calculation is just a bit of JavaScript made as a suggestion to the user.
Does the ACMG Bayesian framework still have all the same evidence keys? In which case that would be one of the smaller changes.

Re PM2 strength, it's almost as if the grid needs a rule engine. Interestingly enough that's what the report ended up doing - there's a lot of validation and warnings there. (Though again that's just JavaScript and doesn't have any influence on the data).

**Comment by davmlaw** [comment]
All you'd have to do with PM2 is change the weight, same calculation.

Then for the [Bayesian framework](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6336098/
), it's just using a different formula

They even provide a little spreadsheet you could copy the formula from:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6336098/bin/NIHMS915467-supplement-Supplemental_Table_S1.xlsx

**Comment by TheMadBug** [comment]
Surely for the PM2 change, the answer isn't to treat PM2 = moderate as supporting, but to actually change the values of PM2 = moderate to supporting?

Re the Bayesian framework, it looks like all the criteria are the same and the values for the criteria too (unless I'm missing something) - so most likely I'd actually just give the calculations based on both formulaes.

**Comment by EmmaTudini** [comment]
James has already implemented the points system (Bayesian model) in an export as that's what I ended up using for calculations in the paper. I specifically did an analysis of how many classifications would change if applying PM2 at a supporting weight instead of a moderate weight for all variants in Shariant. 

@davmlaw What is SA Path wanting here? An estimation of how many classifications will change or a code change to change every instance of PM2 to PM2_supporting?

**Comment by davmlaw** [comment]
We're speccing out how much the change would affect us, so both development time and changing classifications.

* Are you able to share the number of changes for PM2 supporting (via email - can forward to Karin)
* We're also interested in just a general "how hard is this" for development work to see if it's worth considering changing or not

**Comment by EmmaTudini** [comment]
Sent it to you. Just from the Shariant paper so not SA path specific but might give some guidance. It was also super easy to calculate. I just did it in excel.

**Comment by davmlaw** [comment]
Thanks a lot, this is enough for now I think - looks like we don't have to worry should be an easy change when / if we do it
