### ISSUE TITLE
Users can accidentally add empty comments to flags

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#71]
This appears to always have been an issue but hasn't come up in production environments of note.

A user can go to an editable flag, not change the status and not add a comment.
The user can then click "Save & Continue Editing"

and a blank comment with no status change is saved.

The user should have to change the status and/or add a comment for anything new to be saved.

**Comment by TheMadBug** [comment]
Users are still able to hit save on existing flags without changing the status or making a comment, but the server will ignore it and not create an empty FlagComment.

**Comment by EmmaTudini** [comment]
Testing:
- Logged into Shariant test as non-admin
- Went to suggestion flag for Test Lab 1 / vc7675 and clicked save without adding a comment. 
- Went to mismatched chgvs flag for allele 2456 and clicked save without adding a comment. 
- Also tested adding comments to both flags/ changing the status and clicking save.

Expected output:
- If no comment added, no comment will be saved or shown in the change logs. 
- If comment added, it would be shown in the change logs and saved against the flag.

Actual output: Passed

Note: Also tested using an admin login - Passed
