### ISSUE TITLE
Upload - when you initially visit page, it has no file types selected

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#717]
It should default to show all

Would also be good to add a select/deselect all option

**Comment by TheMadBug** [comment]
FYI, if you want some stuff to be remembered by user, but it's not important enough to save to the database, I've made it so you can have
```
<input type="checkbox" data-cookie="INSERT_COOKIE_NAME_OF_CHOICE_HERE" onclick="..." />
```
Right now it's coded assuming something isn't checked by default, so would need a few lines in global.js to better handle things that are checked by default.

**Comment by davmlaw** [comment]
Cool, yeah will keep in mind. For this though, users often use different computers (eg there's a "common room" of workstations, and some work from home) so I think this could be a bit confusing if their preferences change after setting them on 1 computer

**Comment by davmlaw** [comment]
VG test - Logged in as new user, confirmed page started with non internal file types (ie all except liftover/VCF variant only etc )
