### ISSUE TITLE
OMIM-Terms and Omim phenotype number not showing in analysis

### ISSUE THREAD

**Issue by PeerArts** [SACGF/variantgrid#729]
The OMIM terms and the number of variants associated with OMIM phenotypes (green node counts) recently disappeared from analyses. 

Did that get updated recently? 
For example in analysis https://variantgrid.com/analysis/3783 (and screenshot below), the OMIM terms list remains empty, and there are no green numbers. 

![image](https://user-images.githubusercontent.com/34562740/207477567-43d60153-d75b-40bf-bd08-34fea05521cb.png)

**Comment by davmlaw** [comment]
Investingating, the analysis has AnnotationVersion = 21
Ontoloy Version = 2

```
In [15]: av.ontology_version.terms_for_gene_symbol("GATA2", OntologyService.OMIM).leafs()
Out[15]: 
[<OntologyTerm: OMIM:601626 LEUKEMIA, ACUTE MYELOID; AML>,
 <OntologyTerm: OMIM:614038 LYMPHEDEMA, PRIMARY, WITH MYELODYSPLASIA>,
 <OntologyTerm: OMIM:614172 IMMUNODEFICIENCY 21; IMD21>,
 <OntologyTerm: OMIM:614286 MYELODYSPLASTIC SYNDROME; MDS>]

In [16]: av.gene_annotation_version
Out[16]: <GeneAnnotationVersion: v4. (30 November 2022)>

In [17]: av.gene_annotation_version.ontology_version
Out[17]: <OntologyVersion: v2. (30 November 2022)>
```

But all the GeneAnnotation is full of None:

```
In [22]: for v in av.gene_annotation_version.geneannotation_set.filter(gene__geneversion__gene_symbol='GATA2').distinct().values():
    ...:     print(v)

{'id': 73092, 'version_id': 4, 'gene_id': 'ENSG00000179348', 'dbnsfp_gene_id': None, 'hpo_terms': None, 'omim_terms': None, 'mondo_terms': None, 'gene_disease_moderate_or_above': None, 'gene_disease_supportive_or_below': None, 'gnomad_oe_lof': 0.061466}
```

It looks like the last 

```
python3 manage.py gene_annotation --missing
```

Something that seems immediately wrong is:

```
ga =av.gene_annotation_version.geneannotation_set.first()
In [34]: ga.gene_id
Out[34]: 'ENSG00000183044 (Ensembl)'
```

This is because we used ```str(gene)``` instead of ```str(gene.identity)``` somewhere.

Will make a fix and hopefully patch VG tonight (and data migration to look for any other instances on dev machines etc)

**Comment by davmlaw** [comment]
@PeerArts thanks for reporting - this should be fixed now
