### ISSUE TITLE
Somatic classification

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#75]
We need to work out how to manage somatic classifications.

Eg How is it different from current germline ACMG in terms of scoring and evidence keys?

Dumping out notes here:

### Comment 1 ###

Most commercial providers I have seen use COSMIC and that’s where it begins and ends. Pathogenicity on reports is often represented by how many times a variant has been seen in COSMIC in relevant tumour type.

In MO for variant ‘classification’ we use mycancer genome, oncoKB and cbioportal. They  have good curation with references and links to therapy. I have looked at CIVIC a few times but not found it that helpful, maybe not using it right or not used it enough? Too small at the moment maybe.

Most people don’t routinely classify somatic mutations according to a scale as yet that I have seen, probably because it’s too time consuming. Qiagen software does, can’t remember how they do it, but I’m sure we can find out.

### Comment 2 ###

I agree that a brainstorming session would be useful.

At this stage we are still in the discovery phase for CML in terms of clinical relevance of somatic mutations and the work has mostly been retrospective. Some mutations may have different clinical relevance depending on the disease phase of detection, diagnosis versus drug resistance/blast crisis.  

So far, I have used composite ideas to assign relevance and don’t rely solely on whether a variant has been reported in COSMIC. I haven’t used Civic

These are the criteria, which could evolve over time for CML but may be relevant for a broader range of cancers and many of these concepts are incorporated in the papers Anna sent.

Coding/splice site variants were retained for classification if CADD >=20, predicted to be damaging by at least 3 of 4 in silico prediction tools and met conservation criteria

Classified as clinically relevant if
* Known pathogenic germline mutations implicated in leukemia

* Variants in genes in the COSMIC Cancer Gene Census if listed as either directly causally implicated in hematologic malignancy or if somatic mutations occur in the gene in more than 1% of hematopoietic tissue samples, providing they met one of the following criteria:

* The variant was recurrent in COSMIC, such as IDH1 R132H, ASXL1 E635fs*15 or U2AF1 Q157R 

* Novel variants occurring in the same domains as known variants, such as RUNX1 Runt domain missense variants or GATA2 zinc finger variants 

* Truncating variants (nonsense, frameshift indels and essential splice site variants)

* Fusions involving known fusion partners such as MLL, RUNX1 and MECOM 

* Deletions involving genes where deletion is a pathogenic mechanism, such as IKZF1, PAX5 and CDKN2A, or occurring in genes associated with hematologic malignancy, such as RUNX1

Possibly relevant variants were essentially variants in genes where the same type of somatic variants occurred in 2 or more patients in our dataset with the same phenotype – such as frameshift/stop mutations in patients with blast crisis.

All other retained variants were classified as unknown significance.

Still a work in progress but there may be some disease specific criteria used for classification in the future, eg, ASXL1 mutations at diagnosis of CML may not have the same prognostic significance compared with their detection at blast crisis or if detected in a patient with AML at diagnosis.

## Databases ##

Write a brief overview of these:

* CIVIC
* COSMIC
* mycancer genome
* oncoKB
* cbioportal

**Comment by davmlaw** [comment]
@TheMadBug - This is a very old issue - is it now obsolete? Can you link to the new one sand close as dupe?

**Comment by TheMadBug** [comment]
Covered in SACGF/variantgrid_private#3568 and SACGF/variantgrid_private#3531 and a host of others.
Note that I've added no special support for the databases you list, for the most part they're in quick links but that's about it.

Happy to have this issue closed if you are. Can always make a new issue if there's more support needed from creating classifications from samples in a more variantgrid (less Shariant) use case.
