### ISSUE TITLE
IncompleteJSONError: parse error: premature EOF
                                       
                     (right here) ------^


### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#750]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3874/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3874/)

```
Traceback (most recent call last):
  File "/data/variantgrid/sync/sync_runner.py", line 49, in run_sync
    return sync_shariant_download(sync_destination=sync_destination, full_sync=full_sync)
  File "/data/variantgrid/sync/shariant/shariant_download.py", line 129, in sync_shariant_download
    for batch in batch_iterator(records(), batch_size=50):
  File "/data/variantgrid/library/utils.py", line 327, in batch_iterator
    for record in iterable:
  File "/data/variantgrid/sync/shariant/shariant_download.py", line 120, in records
    for record in ijson.items(response.content, 'records.item'):
IncompleteJSONError: parse error: premature EOF
                                       
                     (right here) ------^

```

**Comment by davmlaw** [comment]
James says:

Re the JSON Issue, looking at the code, I don’t think it errors if the server errors..

```
response = requests.get(shariant.url('classification/api/classifications/export'),
                                auth=shariant.auth(),
                                params=params,
                                stream=False,
                                timeout=MINUTE_SECS)

        last_modified = response.headers.get('Last-Modified')
...
        def records():
            nonlocal skipped
            for record in ijson.items(response.content, 'records.item'):
                make_json_safe_in_place(record)
```

It’s missing a

```
response.raise_for_status()
```
right after the request has been made.
Might be worth patching that one line back to SA Path

**Comment by TheMadBug** [comment]
When discussing this hotfix it's worth communicating that this will only improve our logging as to what's going wrong - another fix *might* be required once we have more information.

**Comment by davmlaw** [comment]
I emailed about the HF, but connected to the system to have a look what's going on.

At the start of the sync it looks when the last successful one was, and this is what we currently return:

```
In [20]: SyncRun.objects.filter(destination=sync_destination, status=SyncStatus.SUCCESS).order_by('-created').first()                      
Out[20]: <SyncRun: shariant_download 2022-08-02 05:54:32.530344+00:00>
```

I then looked at when there was ANY SyncRun:

```
In [23]: SyncRun.objects.filter(destination=sync_destination).order_by("-created").first()                                                 
Out[23]: <SyncRun: shariant_download 2022-08-02 05:54:32.530344+00:00>
```

This is because the shariant_download SyncDestination is False

So - I suspect the error is actually with the variantgrid download - we just got confused because it says shariant sync

@TheMadBug - did you want me to enable Shariant download? Can you remember why it was disabled?

**Comment by TheMadBug** [comment]
SA Path download of Shariant data was disabled because at the time, SA Path VM couldn't even download a few kb at a time of it.
When I saw this error I thought you must have got it up and running again, I should have thought a bit harder.

The download would be pretty big from Shariant by now, unless the download speed from the SA Path VM has significantly improved we might have to do the downloading from a file solution again.

**Comment by davmlaw** [comment]
Ah yeah - I have an issue to try and make a new VM

https://github.com/SACGF/variantgrid_sapath/issues/249

**Comment by davmlaw** [comment]
This is a server side error on the VariantGrid.com side

```
https://variantgrid.com/classification/api/classifications/export?share_level=public&type=json&build=GRCh37&since=1675383947.0
```

response:

```
In [57]: response.content                                                                                                                                                          
Out[57]: b'{"records":[\n'
```

Also tested in web browser.

variantgrid.com details:

Git Modified Date: 14 days ago
Git Hash: 9ac47f869f76cf39da2635d5ebbf52df4b4bded9

So if this is the old code - no point fixing? Perhaps we should just keep it disabled, wait a bit while new code is tested, then upgrade variantgrid.com to the new code and re-enable SA Path's SyncDestination?

**Comment by davmlaw** [comment]
James said:

Looks like the code tries to find a Discordance Report if the Clinical Context is marked as Discordant.
But unless Discordance functionality has been enabled, there wont be one, I’ll write a fix for that.

So .. the export from variantgrid.com should now fix itself after the next deploy from master. Though if you can wait for Shariant Test to go through some more testing next week for everything else next week first, that would be optimal

**Comment by davmlaw** [comment]
* Upgraded variantgrid.com on the weekend
* Manually running variantgrid_com_download sync on VG3 upgrade - new classifications being made seems good
* Have set admin to enabled so next sync nightly sync should run as well

Will close this off in a few hours after checking back that manual sync worked ok
