### ISSUE TITLE
TypeError: citation.id is undefined

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#763]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/4205/](https://rollbar.com/jimmy.andrews/VariantGrid/items/4205/)

```

TypeError: citation.id is undefined
  File "http://test.variantgrid.com/static/CACHE/js/output.25d4e775ec60.js", line 164, in renderData
  File "http://test.variantgrid.com/static/CACHE/js/output.25d4e775ec60.js", line 157, in populate/<
```

**Comment by davmlaw** [comment]
I accidentally removed the citations from the variant details page a few months ago (when I moved pubmed from VariantTranscriptAnnotation to VariantAnnotation), put them back recently, which is probably why this is only showing up now

**Comment by TheMadBug** [comment]
The way to load citations on HTML now is just
```
<div data-citation-id="{{ citation_id }}">...</div>
```
I'm not working most of the day so I wont have a chance to look at this properly unitl next week.

**Comment by davmlaw** [comment]
Yeah error is that it looks like:

```<div data-citation-id="PMID:None" class="citation" data-p="1"></div>```

**Comment by davmlaw** [comment]
tested vg test - passed
