### ISSUE TITLE
Support LRG  (Locus Reference Genomic)

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#77]
### Overview

A [Locus Reference Genomic](http://www.lrg-sequence.org) (LRG) is a manually curated record that contains stable and thus, un-versioned reference sequences designed specifically for reporting sequence variants with clinical implications.

Any change LRGs do not have version numbers, the whole ID changes.

----------

LRG contains a stable “fixed” section and a regularly updated “updatable” section. The fixed section contains stable genomic DNA sequence for the region of interest, transcripts and proteins deemed essential for reporting variants, and an LRG-specific exon numbering system. The updatable section contains mapping information, annotation of all transcripts and overlapping genes in the regions, and other relevant information submitted by the community (e.g legacy exon numbering).

LRG loosely maps to a “gene” - ie can contain multiple transcripts. Thus 
t1, t2 - transcript 1, 2. P1,p2 => protein 1,2 etc

In HGVS, using c. LRGs need to include transcript ie: 'LRG_199**t1**:c.11T>G'

Example is here:  [web view](http://ftp.ebi.ac.uk/pub/databases/lrgex/LRG_377.xml) [raw XML](ftp://ftp.ebi.ac.uk/pub/databases/lrgex/LRG_377.xml)

-----------------

### Mapping / Conversion

These LRG annotation files contain mappings to other systems:

```
      <mapping coord_system="NM_001377273.1" other_name="NM_001377273.1" other_id="NM_001377273.1" other_start="1" other_end="8728" type="transcript">
        <mapping_span lrg_start="269" lrg_end="495" other_start="1" other_end="227" strand="1" />
        <mapping_span lrg_start="870" lrg_end="985" other_start="228" other_end="343" strand="1" />
        <mapping_span lrg_start="3618" lrg_end="3677" other_start="344" other_end="403" strand="1" />
        <mapping_span lrg_start="5001" lrg_end="5162" other_start="404" other_end="565" strand="1" />
        <mapping_span lrg_start="7772" lrg_end="7913" other_start="566" other_end="707" strand="1" />
        <mapping_span lrg_start="15632" lrg_end="15753" other_start="708" other_end="829" strand="1" />
        <mapping_span lrg_start="24592" lrg_end="24758" other_start="830" other_end="996" strand="1" />
        <mapping_span lrg_start="25785" lrg_end="26027" other_start="997" other_end="1239" strand="1" />
        <mapping_span lrg_start="28629" lrg_end="28823" other_start="1240" other_end="1434" strand="1" />
        <mapping_span lrg_start="30717" lrg_end="30869" other_start="1435" other_end="1587" strand="1" />
        <mapping_span lrg_start="31383" lrg_end="31538" other_start="1588" other_end="1743" strand="1">
          <diff type="mismatch" lrg_start="31514" lrg_end="31514" other_start="1719" other_end="1719" lrg_sequence="T" other_sequence="C" />
        </mapping_span>
```

I don't like the idea of having to do conversions across different exons and handling mismatches etc so perhaps it’s better to use a web service (eg NCBI liftover etc)

### Web services

VEP supports LRG input formats, though it only works online (ie needs to send over the internet and can't use local cache like we normally do)

NCBI ReMap (which we already use for liftover) has some info on [LRG](https://www.ncbi.nlm.nih.gov/refseq/rsg/lrg/)

I did a test run of LRGs from [HGVS page](https://varnomen.hgvs.org/bg-material/refseq/):

LRG_199t1:c.11T>G lifted over to NC_000023.10:g.33229419_33229419A>C
LRG_199t1:c.357+1G>A lifted over to NC_000023.10:g.32841412_32841412-1C>T

Notice they both have the same position doubled. This fails with our current HGVS parser. If I change it to just the 1 position (not sure if this is right??) eg NC_000023.10:g.33229419A>C this can resolve, but uses our reference base of C and thus is a ref variant

**Comment by EmmaTudini** [comment]
@davmlaw @TheMadBug can we bump this up the list please?

**Comment by davmlaw** [comment]
ClinGen Allele registry works ok with this, eg searching for LRG_199t1:c.357+1G>A will get CA412674406 which has HGVSs of: ```["NM_004006.2:c.357+1G>A", "LRG_199t1:c.357+1G>A"]```

There is also mapping to RefSeq - see https://www.ncbi.nlm.nih.gov/refseq/rsg/lrg/

File: ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/RefSeqGene/LRG_RefSeqGene

```
$ grep NM_004006 LRG_RefSeqGene 
9606	1756	DMD	NG_012232.1	LRG_199	NM_004006.3		NP_003997.2		aligned: Selected
9606	1756	DMD	NG_012232.1	LRG_199	NM_004006.2	t1	NP_003997.1	p1	reference standard
```

The t1/t2/... identifier(s) is/are provided as a cross-reference to each RefSeq cDNA.

So, we could probably do this via:

* HGVSName with LRG sets the LRG to gene not transcript. Need to handle that in first few lines of get_variant_tuple
* TranscriptVersion could return RefSeq using that lookup in ```filter_best_transcripts_by_accession```
* Need to test the case where no refseq mapping (or mapping to alignment gap) so will call ClinGen allele registry
* Need to handle going back the other way
* Make sure whole process works with a classification import

**Comment by davmlaw** [comment]
Tested classification import with "LRG_199t1:c.357+1G>A" and it works and links to variant however issues are:

* It auto-populates RefSeq Transcript ID with "LRG_199T1" then gives a warning about missing version ID - we should populate it with the real refseq transcript ID we look up from LRGRefSeqGene or maybe make a new EKey about LRG
* It raises a 37/38 against the allele as the cHGVS doesn't work (haven't done code the other way yet)

**Comment by EmmaTudini** [comment]
Need to determine what can be accepted by Alissa Interpet. Think my account has been disabled so will need to email Stan

**Comment by EmmaTudini** [comment]
Also currently LRG does not populate gene symbol in chgvs. @TheMadBug If no gene symbol is populated, what does that affect downstream? Remember populating it for a reason

**Comment by EmmaTudini** [comment]
@TheMadBug Just raising a comment to ask about the previous comment...

**Comment by EmmaTudini** [comment]
Also see note in - https://app.zenhub.com/workspaces/everything-space-5bb3158c4b5806bc2beae448/issues/sacgf/shariant-admin/126 about ALissa not supporting LRGs

**Comment by davmlaw** [comment]
For Alissa LRG support see https://github.com/SACGF/shariant-admin/issues/126

Next deploy, LRG will now include gene symbol

**Comment by EmmaTudini** [comment]
Testing:
- Logged in as non-admin assigned to VCGS Unit 1
- Imported LRG_321t6:c.1A>G against GRCh37, NM_000546.5:c.397A>G against GRCh38  and LRG_321t3(TP53):c.397T>G (wrong reference base)
Expected output: Should resolve to the same allele and result in a discordance. LRG should be matched to NM_001126116.1 and NM_001126114.2 (equivalent transcripts) repectively. LRG should be in specific field in classification record. Gene symbols should be populated for all.  LRG_321t3 record should have variant matching flag as incorrect reference base.

Actual output: Passed

**Comment by EmmaTudini** [comment]
@TheMadBug These are still being exported into the MVL and I'm guessing Clinvar as well. As we don't have any labs submitting to us in LRG at the moment, maybe we should turn off LRG until the next deploy?

**Comment by TheMadBug** [comment]
I coded a solution for this on Friday but did not commit it or deploy it (as in just exclude it from the MVL and from ClinVar Exports).
To re-test after rematching finishes.

**Comment by TheMadBug** [comment]
Can confirm that the default refseq only now excludes LRG.
The download with all transcripts supported is 11 rows longer than the one without.

The wording on the page should change (as it says refseq only or refseq and Ensembl) where it should say refseq or ALL - will raise a task for this, not important enough to fix now as that functionality is pretty useless outside of test anyway.

**Comment by EmmaTudini** [comment]
Testing:
- Logged into non-admin assigned to VCGS Unit 1
- Exported MVL including and excluding ensembl (and now LRG)

Expected output: Export with Ensembl should include LRG
Export without Ensembl shouldn't include LRG

Actual output: Passed

**Comment by EmmaTudini** [comment]
Testing:
- To try to generate a clinvar export had to include gene symbol in LRG expression
- Imported LRG_321t3(TP53):c.397del

Expected output: Should match and use gene symbol to populate
Actual output: **Failed** - https://test.shariant.org.au/classification/classification/44763
Error message - Attempted to match GRCh37 LRG_321t3(TP53):c.397del, error = Error attempting to parse variant coordinate (Could not convert LRG_321t3(TP53):c.397del - tried: ClinGen Allele Registry as 'LRG_321t3.1(TP53):c.397del')

**Comment by EmmaTudini** [comment]
^ This needs to be fixed before prod I think?

**Comment by EmmaTudini** [comment]
Disable LRG for now. Patch next prod deploy

**Comment by davmlaw** [comment]
PyHGVS didn't detect LRG as transcript by itself properly ie:
```
"LRG_321t3:c.397del" # HGVSName.transcript = None, gene=LRG_321t3
"LRG_321t3(TP53):c.397del" # HGVSName.transcript = LRG_321t3, gene=TP53
```

* Fixed this in PyHGVS (Need to update pyHGVS library)
* Enabled LRG_ transcript type in Shariant

**Comment by davmlaw** [comment]
I turned LRG_ back off in Shariant as we need to handle exports, see: https://github.com/SACGF/shariant-admin/issues/126

**Comment by EmmaTudini** [comment]
@TheMadBug Any idea where this should go?

**Comment by TheMadBug** [comment]
So this is an interesting one:
* LRG resolution most likely works but we need some more testing of it.
* Even when LRG does work, we can't export it to Alissa without extra work - though if we don't resolve LRG, we're not going to export them to Alissa either.
* We don't have any LRGs in prod.

My suggestion would be to close this task until someone wants to send us a LRG, then we re-evaluate the state of everything.

**Comment by EmmaTudini** [comment]
Closing until LRGs go into Shariant
