### ISSUE TITLE
AlleleOverlap.c_hgvses should be a property not a method

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#785]
Linter picked this up:

```
classification/models/allele_overlaps.py:278:4: W0236: Method 'c_hgvses' was expected to be 'property', found it instead as 'method' (invalid-overridden-method)
```

**Comment by TheMadBug** [comment]
Code got away with it by all references to c_hgvses being in a django template (which treats a no arg method and property the same). Will still fix for next build as easy enough to do.

**Comment by TheMadBug** [comment]
To test, just make sure the overlaps page still functions

**Comment by EmmaTudini** [comment]
Check if can load and filter on it - will explode otherwise

**Comment by GracePendlebury** [comment]
Tested
Logged in as Grace.Pendlebury@qimrberghofer.edu.au (admin)
Outcome:
Passed. Loads and filters without exploding.
