### ISSUE TITLE
Search HGVS missing dot fails

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#798]
NM_007194.3(CHEK2):c591del

I thought we fixed that but apparently not

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3568/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3568/)

```
Search Error
```

**Comment by davmlaw** [comment]
The previous fix only worked for HGVS without the gene symbol in brackets. Added support for fixing that as well

Needs testing in Shariant

@TheMadBug - needs to be patched to Shariant prod

**Comment by EmmaTudini** [comment]
Testing
- Logged in as non-admin tester
Searched for 
1. NM_000441.1 (SLC26A4) : c-3-2A>G
2. NM_007194.3(CHEK2):c591del
3. NM_007294.3:c672_4096dup (should already be working)

Actual output:
1. **Failed** - showed no results.
2. **Failed** - showed no results.
3. Passed 

I think this actually shows a bigger issue. The warnings that appear in prod regarding the search not being as expected/supported no longer appears. Instead it just shows "no result". This is risky as a user then doesn't know that they've input the wrong search. You can see users responding to these warnings in prod and correcting their search, so we shouldn't get rid of these warnings

**Comment by davmlaw** [comment]
This wasn't patched to Shariant prod, and was in "coding complete" so shouldn't have been tested

**Comment by EmmaTudini** [comment]
@davmlaw My bad. There is an outstanding issue RE lack of warning to say that this isn't a valid input though. I'll put together a set of inputs and expected outputs and send them through

**Comment by davmlaw** [comment]
The issue with "NM_000441.1 (SLC26A4) : c-3-2A>G" is not new, so shouldn't be against this issue. Please start a new issue for new requirements

The trouble is, for speed and to not spam users with unrelated error messages - we can't throw an HGVS error for everything, so need a certain minimum HGVS-likeness to be able to determine it's a HGVS. 

It's possible that we should strip HGVS-like things of all spaces, and then perhaps it might be able to salvage the above. But it has like 4 or 5 things wrong with it to be valid HGVS

**Comment by EmmaTudini** [comment]
@davmlaw I'll raise a new issue about the warnings, but it is a blocker for this deploy so needs to be looked at. 

In prod it does through a warning for NM_000441.1 (SLC26A4) : c-3-2A>G without the ".".

**Comment by davmlaw** [comment]
Ah, sorry yeah the above is only a bit away from a HGVS (strip whitespace and add a dot) - the two negative numbers threw me off, but yeah I think the issue was it didn't remove the "." if the next character was a dash (ie negative coordinate)

A simpler test case, ie: NM_000350.2(ABCA4):c-52delC still fails - will fix that up

**Comment by davmlaw** [comment]
@TheMadBug 

Need to cherry pick 2472294637381f9f74d2f6f095ad632e67627095 into Shariant prod please

**Comment by davmlaw** [comment]
This has been put in Shariant prod branch and deployed

**Comment by EmmaTudini** [comment]
Tested under https://app.zenhub.com/workspaces/everything-space-5bb3158c4b5806bc2beae448/issues/gh/sacgf/variantgrid_private/3458
