### ISSUE TITLE
HGVS - Reference genomic coordinate span ie "89623915_89623920=" fails

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#799]
"NC_000010.10:g.89623915_89623920=" works fine on variant validator.

We should fix this up but only if easy. Maybe the last one we do as we should seriously think of switching HGVS libraries

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3498/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3498/)

```
Search Error
```

**Comment by davmlaw** [comment]
@TheMadBug - needs cherry pick into Shariant branch (or you could just upgrade the pyhgvs library for a quick and dirty way)

**Comment by TheMadBug** [comment]
Deployed and active in Shariant Test

**Comment by EmmaTudini** [comment]
@davmlaw How do I test this?

**Comment by davmlaw** [comment]
Search for "NC_000010.10:g.89623915_89623920=" or another coordinate span that has "=" at the end

**Comment by EmmaTudini** [comment]
Testing
- Searched for the above - NC_000010.10:g.89623915_89623920= - don't think there should be any results. - Passed
Searched for NC_000010.11:g.87863696T= - should go to allele page - Passed

@davmlaw Importing NC_000010.10:g.89623915_89623920= errors out. Did you expect that to be fixed with this change?

**Comment by davmlaw** [comment]
It fails in 38 because it's explicitly referring to the GRCh37 contig version (we don't bump contig versions)

**Comment by davmlaw** [comment]
@EmmaTudini - can you close this if ok?

NC_000010.10:g.89623915_89623920= is a GRCh37 contig, so works if imported as GRCh37
It fails when importing as GRCh38 - because the contig is not in 38
