### ISSUE TITLE
Download VCF/CSV on samples grid and samples page

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#8]
*Originally reported by* **David Lawrence (Bitbucket: [davmlaw](https://bitbucket.org/davmlaw), GitHub: [davmlaw](https://github.com/davmlaw))**

----------------------------------------

Some people may just want to download annotated stuff quickly, make it easy for them

----------------------------------------
- Bitbucket: https://bitbucket.org/sacgf/variantgrid/issue/456

**Comment by davmlaw** [comment]
Bump everyone keeps using this

**Comment by davmlaw** [comment]
TODO: Should do this for sample as well

Drive this from sample tab auto analysis.

Should change sample node "All variants":

```
zygosity_ref=True
zygosity_unk=True
output_node=True
```

Then use that

**Comment by davmlaw** [comment]
Once this is deployed, tell John/Frank to simplify their workflows

**Comment by davmlaw** [comment]
tested on variantgrid test - leaving open as need to validate on vg.com once deployed

Found + fixed issue where analysis JSON had hardcoded cohort ID which caused node to not appear - set to NULL, verified things work now.

Found another problem - but raised as separate issue:

#1015 - VCF export - symbolic alt records don't include SVLEN

**Comment by davmlaw** [comment]
verified works on vg.com
