### ISSUE TITLE
Search - top level warnings for no results

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#802]
In issue #731 Emma asked for:

> This shows "no results" which is ok as the only variant is against the non-MANE transcript, but as this could be a false negative, it would be good if you could add in "no results. Warning: only searched for transcript xx."

> I think this is critical as we don't want labs thinking that the variant doesn't exist when it only searched for the mane transcript

I couldn't do this as we have top level errors, and warnings on results, but we don't have top level warnings.

I added it as a warning message to a "no result" SearchResult but that caused the "No results" to disappear.

This caused the gene HGVS search to be disabled in Shariant

**Comment by davmlaw** [comment]
I made a ```SearchWarning``` exception which you can throw that renders the message as a warning instead of an error. This allows you to return "no results" and a message. 

So this is what happens if you search for a gene HGVS and have SEARCH_HGVS_GENE_SYMBOL_USE_MANE = False

![Screenshot from 2023-04-17 16-28-05.png](https://images.zenhubusercontent.com/5bb45cdce135e46293defe80/659bf336-72d4-4fd9-94b5-e3e31b14786a)

This is what happens with no results if you have SEARCH_HGVS_GENE_SYMBOL_USE_MANE = True

![Screenshot from 2023-04-17 16-28-26.png](https://images.zenhubusercontent.com/5bb45cdce135e46293defe80/f806f96f-f87e-4b87-9a72-ab0b07a82250)

**Comment by TheMadBug** [comment]
SearchMessageOverall has been made as part of this task (which can specifically yielded from a search, or generated from a search raising an Exception)

search currently does a pretty good job of showing overall errors for variants now

**Comment by TheMadBug** [comment]
The messages are now formatted under the "No Results" message, which has been in place for a while as part of the search rewrite, e.g.
![CleanShot 2023-06-27 at 14.55.22.png](https://images.zenhubusercontent.com/5b9734f72df36e0aa911d89d/d8ab96c5-2671-454b-b1ae-16db0393f964)

**Comment by GracePendlebury** [comment]
Tested as part of #3462. **Passed**
