### ISSUE TITLE
rename settings.VARIANT_CLASSIFICATION to CLASSIFICATION

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#805]
We renamed the package but forgot the settings

**Comment by davmlaw** [comment]
Now that developer settings are no longer available - we should put a warning there if any left. Maybe even die?

```
from django.conf import settings
settings.__dict__
for x in dir(settings):
    if x.startswith("VARIANT_CLASSIFICATION"):
        print(x)
```

**Comment by EmmaTudini** [comment]
@davmlaw Does anything need to be tested on the Shariant end for this?

**Comment by davmlaw** [comment]
Everything should stay the same if this change was successful. This was a find/replace of variables and I looked pretty hard to make sure I didn't miss anything, so you could just keep an eye out for classification behaviour not working as per normal.

Bad changes to pages would break with an exception, so we'd find them easily enough. A bug that would occur without loud errors if I missed anything would be Shariant behaviour would revert to defaults, so you could go through and validate them. The Shariant settings affected by this change were:

```
CLASSIFICATION_REDCAP_EXPORT = False

CLASSIFICATION_GRID_MULTI_LAB_FILTER = False
CLASSIFICATION_NEW_GROUPING = True
CLASSIFICATION_ALLOW_DELETE = False
CLASSIFICATION_NON_ACMG_ASSERTION_METHOD = [
    re.compile(r'.*VCGS.*', flags=re.IGNORECASE),
    re.compile(r'.*Sherloc.*', flags=re.IGNORECASE)
]

CLASSIFICATION_OMNI_IMPORTER_APP_DIR = "/opt/shariant_omni_importer"
CLASSIFICATION_OMNI_IMPORTER_PUBLISH_LEVEL = "logged_in_users"
CLASSIFICATION_OMNI_IMPORTER_INCLUDE_SOURCE = False

CLASSIFICATION_SUPPORTED_TRANSCRIPTS = {"NM", "NR", "ENST", "XR"}
CLASSIFICATION_REQUIRE_OVERWRITE_NOTE = False
CLASSIFICATION_AUTOFUZZ_AGE = True
CLASSIFICATION_GRID_SHOW_USERNAME = False  # In Shariant - this may be a lab's API user so hide it
CLASSIFICATION_STATS_USE_SHARED = True  # False=Use visible to user. True = Shared
CLASSIFICATION_WEB_FORM_CREATE_INITIALLY_REQUIRE_SAMPLE = False
CLASSIFICATION_WEB_FORM_CREATE_BY_NON_ADMIN = False
CLASSIFICATION_GRID_SHOW_ORIGIN = False
CLASSIFICATION_GRID_SHOW_PHGVS = False  # would be nice to show but isn't populated consistently
CLASSIFICATION_GRID_SHOW_SAMPLE = False
CLASSIFICATION_FILE_ATTACHMENTS = False
CLASSIFICATION_ID_FILTER = False
CLASSIFICATION_SHOW_SPECIMEN_ID = False

CLASSIFICATION_MAX_REFERENCE_LENGTH = 1000000  # Try to generate large values for sake of MVL

CLASSIFICATION_ID_OVERRIDE_PREFIX = True
```

So, example testing:

Verify CLASSIFICATION_REDCAP_EXPORT = False

* Go to [classifications grid](https://test.shariant.org.au/classification/classifications)
* Verify redcap export is missing from bottom of grid - PASSED

Verify CLASSIFICATION_GRID_MULTI_LAB_FILTER = False

* Go to [classifications grid](https://test.shariant.org.au/classification/classifications)
* Verify you can only select 1 lab at a time in dropdown

Verify CLASSIFICATION_ALLOW_DELETE = False

* View classification as admin or owner
* Ensure there is no delete button

**Comment by TheMadBug** [comment]
I've checked the related functionality quite a bit, and also checked for any remaining references to VARIANT_CLASSIFICATION in the code.
(The only remaining references were in my personal settings files that weren't in source control so that was expected).

Moving this to pending release.

**Comment by TheMadBug** [comment]
Can see at a glance that many of the settings are correct in prod, classifications are grouped on allele/gene symbol page, the right columns show on the table etc.
