### ISSUE TITLE
Switch out pyhgvs for BioCommons HGVS

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#826]
While working with structural variants, the existing PyHGVS problems have become too great, specifically things like [#2655 HGVS Indel issue - dup converted to ins](https://github.com/SACGF/variantgrid_private/issues/2655)

### Plan

Going to do this in master, as CNV/structural variant code is not ready to go yet

Working in ```features/biocommons_hgvs```

It's possible we can turn off CNV via feature flags, otherwise will have to merge existing changes back (both touch hgvs.py)

* Write a HGVS DataProvider that pulls cdot data out of transcript records
* Hook in new code, perhaps even leaving old one in place so we can compare?
* Write export CSV checker code (see below)
* Look back through HGVS issues, perhaps some can be closed now?

Discuss with Shariant folk re their upgrade plans

### Existing HGVS validation

Usually we validate by ```running classification_matching_check``` management command.

James suggested that we instead modify it to use a classification export, that way we can easily test all the HGVS that have been sent to us in various environments

**Comment by davmlaw** [comment]
We could potentially move all the conversion to biocommons Babel

Can add a lot of test cases as well (maybe using a subset of cdot)

**Comment by davmlaw** [comment]
Currently having issues building the HGVS from VCF style coords.

```
GRCh37 variant coord - 1:235611672 A>ACAATTCAAAAGGTGAAGGGATTGCTGTCACGTCTTCTCAAAGTTCCTGTGTCAGACCTTCTGTTGTCCTATGAAAGTCCCAAAGTAAGTTGCCCAGCAAAATACAAAGTCAAAGTCAAGCTTAGTCCTCGTATTATGACATTAAACTGTCTCTAGATAGCAACAGTTTGATTCTAAATGGAGACCATGGGTCTGTTTGTTTGATTTTAAGGGTAAGCTACTGCCTGGGGACGGGGTGGGGGAAGAGTATGTGTAGCATGCTTTATCGGATCTGTCTTAATCACATCCTTCCCCACCTTCGTTCTAATTTTAGAAGCCGGG
```

If we can get this going through normalize - it would norm to a dup:

```NC_000001.10:g.235611773_235611774insTACAAAGTCAAAGTCAAGCTTAGTCCTCGTATTATGACATTAAACTGTCTCTAGATAGCAACAGTTTGATTCTAAATGGAGACCATGGGTCTGTTTGTTTGATTTTAAGGGTAAGCTACTGCCTGGGGACGGGGTGGGGGAAGAGTATGTGTAGCATGCTTTATCGGATCTGTCTTAATCACATCCTTCCCCACCTTCGTTCTAATTTTAGAAGCCGGGCAATTCAAAAGGTGAAGGGATTGCTGTCACGTCTTCTCAAAGTTCCTGTGTCAGACCTTCTGTTGTCCTATGAAAGTCCCAAAGTAAGTTGCCCAGCAAAA```

I think the normalize code is wrong here, got 3 and 5 mixed up?

```
                if self.shuffle_direction == 3:
                    adj_seq = self._fetch_bounded_seq(var, start - alt_len - 1, end - 1, 0, boundary)
                else:
                    adj_seq = self._fetch_bounded_seq(var, start - 1, start + alt_len - 1, 0, boundary)
```

**Comment by davmlaw** [comment]
ok, need to run parallel implementation so that we can double check everything...

Also need to bump version of our fork of pyhgvs, and add manual migration to upgrade

**Comment by davmlaw** [comment]
There are still a few remaining differences, however when I've looked, they have all been the same variant, but BioCommons normalized correctly while PyHGVS didn't:

BioCommons - NC_000003.12:g.128481185dup	ClinGen =  CA2499216425 - NC_000003.12:g.128481185dup (Correct)
PyHGVS     - NC_000003.12:g.128481183dup	ClinGen =  CA2499216425 - NC_000003.12:g.128481185dup (Was not normalized)

BioCommons - NM_006015.6(ARID1A):c.495_500del    ClinGen =  CA2517060205 - NM_139135.4:c.495_500del  (Correct)
PyHGVS     - NM_006015.6:c.492_497del   	 ClinGen =  CA2517060205 - NM_139135.4:c.495_500del  (was not normalized)

VariantCoordinate(chrom='13', pos=32912886, ref='AATTAC', alt='A')
BioCommons - NM_000059.3(BRCA2):c.4398_4402del - ClinGen = CA020088 - NM_000059.3:c.4398_4402del (Correct)
PyHGVS     - NM_000059.3(BRCA2):c.4397_4401del - ClinGen = CA020088 - NM_000059.3:c.4398_4402del (Was not normalized)

VariantCoordinate(chrom='13', pos=32907382, ref='GTTTA', alt='G')
BioCommons - NM_000059.3:c.1773_1776del - ClinGen = CA013167 - NM_000059.3:c.1773_1776del (Correct)
PyHGVS     - NM_000059.3:c.1770_1773del - ClinGen = CA013167 - NM_000059.3:c.1773_1776del (Was not normalized)

VariantCoordinate(chrom='13', pos=32333245, ref='GTTTA', alt='G')

BioCommons - NC_000013.11:g.32333251_32333254del -  CA013167 - NC_000013.11:g.32333251_32333254del (correct)
PyHGVS     - NC_000013.11:g.32333248_32333251del -  CA013167 - NC_000013.11:g.32333251_32333254del (was not normalized)

**Comment by davmlaw** [comment]
TODO: 

* Remove all instances of HGVSName from everywhere but PyHGVS specific code
* Make a common exception for InvalidHGVSName - each various API should catch and re-throw

**Comment by davmlaw** [comment]
There is still a difference in searching for "DMD:c.5234G>A" - get_transcript_accession returns "DMD" for biocommons, we should move looks_like_transcript out of HGVSMatcher so it can return '' if not a transcript

**Comment by davmlaw** [comment]
1 last one left. I think genes.hgvs.biocommons_hgvs.babelfish.Babelfish.hgvs_to_vcf is adjusting all dels should only do when length is 1, see: https://github.com/biocommons/hgvs/blob/main/src/hgvs/extras/babelfish.py

```
ERROR HGVS converters calling variant_coords_to_g_hgvs((
VariantCoordinate(chrom='1', pos=53712726, ref='T', alt='TC')
returned different results! [
(NC_000001.10:g.53712726del, 'BioCommons hgvs v1.5.3'),
(NC_000001.10:g.53712727dup, 'pyhgvs v0.12.4')])
```

**Comment by EmmaTudini** [comment]
@davmlaw Could you explain how to test the comment from June 8th above?

**Comment by EmmaTudini** [comment]
@davmlaw Could you explain how to test the comment from June 8th above?

**Comment by EmmaTudini** [comment]
Should be done
