### ISSUE TITLE
Search for TranscriptVersion doesn't auto-jump properly

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#828]
Search for a transcript that is in both builds, eg: "NM_000441.1"

TranscriptVersion is only unique per build, so there can be multiple with the same transcript/version

The code that pulls it out:

```TranscriptVersion.objects.filter(transcript=transcript, version=version).first()```

Will take whatever build the DB returns, this may (depending on luck ) be from a non-preferred build and thus not auto-jump properly.

**Comment by TheMadBug** [comment]
Good catch.

Now searching on transcript version now tries each genome build individually, e.g.
https://test.shariant.org.au/variantopedia/search?search=NM_000441.1&mode=preview

So it should now always be able to auto-jump if the version does exist in the genome build.

**Comment by TheMadBug** [comment]
Now tweaked it so if a transcript version exists in both builds, only 1 search result (with both builds attributed to it) is returned. This is because the transcript version search result links to the same page regardless of genome build - assuming the transcript version exists.

**Comment by GracePendlebury** [comment]
**Tested**
Logged in as: Grace.Pendlebury@qimrberghofer.edu.au (admin)

Searched for:
NM_058216.1 (37)
NM_058216.2 (37 & 38)

Expected output:
For the versions to tie to the correct build and only one search result to show, linked to both 37 & 38 for NM_058216.2.

Actual output:
Passed
