### ISSUE TITLE
rebase repos

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#83]
TODO:

* shariant

DONE

* dml hp desktop 
* dml laptop
* james macbook
* shariant test
* vg.com
* vg test
* runx1

**Comment by davmlaw** [comment]
@TheMadBug did you do this for Shariant?

**Comment by TheMadBug** [comment]
I've updated Shariant prod a few times since, think I've had to "git pull --rebase" each time (sorry not 100% sure).

Doesn't need to be own issue if I need to do a proper reset of Shariant git during next upgrade if it keeps complaining about unrelated origins.
