### ISSUE TITLE
Search HGVS using gene symbol issues

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#830]
Hi just dumping this as I need to go home...

Search for "DMD:c.5234G>A" with ```SEARCH_HGVS_GENE_SYMBOL_USE_MANE = True```

**issue 1**

```_search_hgvs_using_gene_symbol``` Is returning a SearchResult with annotation_consortia = None

I made a wrapper around it ```if r.annotation_consortia is not None:```  but I think it's better to actually better to set it.

In Variant search line 351 it says ```# TODO: do we need to set the annotation_consortia on the result?```

**Issue 2**

At the end of ```_search_hgvs_using_gene_symbol``` - near the ```list(unique_messages.keys())```

```
    	yield SearchResult(preview=record.preview, messages=[SearchMessage(m) for m in messages])
```

was dying as ```SearchMessage.__post_init__``` was checking that message was always a string, however we built a search message out of a search message we got from somewhere else and it died

I made the code do a loop and only converted if it wasn't already converted - but I think it might be neater to go back and work out whether we want a string/SearchMessage etc or maybe do something else

**Issue 3**

When the search warnings are shown - they are no longer proper HTML links - I think it needs to be set to "safe" in a template somewhere

**Comment by davmlaw** [comment]
1 - I handled this at the TODO and also added annotation_consortia to TranscriptVersion results
2 - just kept everything in unique_messages as a SearchResult object
3 - This was due to the way search results are displayed - the whole thing is a big clickable, so there's no way to click it, even if I rendered the html safe.

**Comment by EmmaTudini** [comment]
Cannot test in Shariant test as disabled.

**Comment by davmlaw** [comment]
I've changed settings to enable in Shariant test - should appear next deploy

**Comment by davmlaw** [comment]
For real life examples searched for - see private issue https://github.com/SACGF/shariant-admin/issues/144

**Comment by GracePendlebury** [comment]
**See testing document**
Overall it is functional, but there are differences between admin and non-admin and the errors need work.

[Searching without transcript #830.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakdMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--da27a0fc9c24c9801548b57296a274e007f7ebb5/Searching%20without%20transcript%20%23830.docx)

**Comment by GracePendlebury** [comment]
Updated document attached with a few extra searches

[Searching without transcript #830.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmVMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--efca9ed5a8b03c3733272c471a84f1e5edb9668b/Searching%20without%20transcript%20%23830.docx)

**Comment by davmlaw** [comment]
Still working on this, but fixed these 2:

GNE:c.1132G>T - It used to search for the 1st MANE it found, now I search for both MANE select / clinical, it now finds it
FANCN:c.3549C>G - Changed so that we can now search on aliases as well

--------

Quite a lot of these are the same problem - basically when it does the gene search, if it's invalid or can't find anything, then it throws the original parse error about needing a transcript.

I have made it so that if it was a valid gene symbol HGVS, but has no results, it now just shows no results.

Q. Would you like it to show that it did use all of the MANE transcripts etc but had no results? 

CLDN5:c.-647G>T - "couldn’t locate NM_001130861.1(CLDN5):c.-647G>T" - The MANE transcript for CLDN5 is NM_001363066.2, when you search for NM_001363066.2(CLDN5):c.-647G>T you get "cdna_start -647 resolves outside of transcript" (then as it didn't retreive anything it shows parse error as per top of this comment) - I guess I should change it so that it shows it used MANE and then throws the out of bounds message instead of parse error?

BRCA1:c.53T>C - "Did not locate same variant as non-admin even though it states resolved to the same genomic coordinates" I don't understand what's wrong here, can you please provide more detail?

**Comment by GracePendlebury** [comment]
I think my main issue with the original parse error is that it misrepresents the search. To a user, I think it would just look like it is not even accepting the search without transcript, rather than accepting that input but finding nothing, which is why I marked them as failed.

RE your Q, I think it would be a good idea to be transparent about what is going on in the background in these cases, the same way you can see in admin (but tidied up to be less overwhelming as per the comments on the last page of the doc). So, showing that it checked against all the available MANE transcripts etc, or if no MANE transcript is stored to search against.

For the CLDN5 variant, it would have been good to know what it was doing. i.e. a warning about having searched against the MANE transcript and it resolving outside. I don’t believe that the parse error is sufficient, it isn’t descriptive enough to actually be helpful IMO…

**Comment by GracePendlebury** [comment]
For the BRCA1 variant the comment about coordinates was me noting that it was trying to search for the same thing: 
Admin:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHlpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1d29108721884dbb8587fb5a178cd9d55a6471bd/image.png)
Non-admin:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDJpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--570283ac39f5d7da460665aeecd4d1806ed1cbd7/image.png)

But the main problem is that it does not suggest the other alt for BRCA1:c.53T>G when searching in admin, while it does in non-admin and this is an inconsistency.

This is another situation again where all the errors that pop up are overwhelming and make it hard to work out what’s happening. For example, the ones crossed out below are redundant to start with:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDZpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4a15b27c81f1d40b341b0b7bd58f1e1cba6e1b1a/image.png)

Ideally, I think it would be good for all searches recognised as gene symbol and c.HGVS to have a separate info banner similar to the one in the below screenshot, that has some standard messages such as:
A gene symbol and c.HGVS search has been recognised
Please note that we only support this against MANE Plus Clinical, MANE Select & RefSeq transcripts blah blah
Some of the other warnings could be pulled up into there too, like 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcCtpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--99e69936d4cf1716c6ef2be45620a3d2e58fb674/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUNpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cde8440564b34afde1fc751639afdb57a23fb7ad/image.png)

**Comment by TheMadBug** [comment]
@davmlaw 
Note I've fixed an issue where the gene symbol search would duplicate the SearchMessages (didn't stop them from being generated but I did suppress them from being displayed).

Also I commented out the line `result.messages.append(SearchMessage(str(alias)))` in `variant_search.py` as that was resulting in the "None"s, and even if there was an alias, I'm not sure that SearchMessage would be useful.

**Comment by TheMadBug** [comment]
@GracePendlebury I've turned off all c.HGVS searching without a transcript. It's something we can easily turn back on once there are fixes for any outstanding problems with it.

See https://test.shariant.org.au/variantopedia/search?search=GNE%3Ac.1132G%3ET&mode=None for details.
If you could just run through a few other variant search scenarios to make sure they're still in good order. I've tried a few and it looks like my fix only affected this.

**Comment by GracePendlebury** [comment]
As far as I can see there are no problems with the other searches from turning this off. I tested a few.

**Comment by EmmaTudini** [comment]
@TheMadBug Could we turn this back on in test to have a look?

**Comment by TheMadBug** [comment]
https://test.shariant.org.au/variantopedia/search?search=DMD%3Ac.5234G%3EA&mode=None

Before
![image](https://github.com/SACGF/variantgrid/assets/2100255/4f6b6fc3-03b4-4562-aae9-9c5da2dea5df)

After
![CleanShot 2024-05-16 at 12 11 47@2x](https://github.com/SACGF/variantgrid/assets/2100255/173bcfcd-5c4a-4c2d-b739-ad9d1f91d038)

**Comment by TheMadBug** [comment]
@davmlaw searching for `DMD:c.5234G>A` before and after enabling this setting caused no difference
https://test.shariant.org.au/variantopedia/search?search=DMD%3Ac.5234G%3EA&mode=None

Doesn't appear to approve of the gene symbol being in brackets e.g. `(EGFR):c.2573T>G`, but I'm not sure people search on it like that if no transcript has been provided

**Comment by GracePendlebury** [comment]
**Testing**

Logged in as:
Grace.Pendlebury@qimrberghofer.edu.au (admin) & g.pendlebury1@outlook.com (non-admin)

Performed:
See testing doc: [Searching without transcript #830 NEW 2024.06.05.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzQ1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46babbcf4f6da5e58670c7cce9b44eeb430dcca1/Searching%20without%20transcript%20%23830%20NEW%202024.06.05.docx)


Expected outcome:
Successful searching without transcript (only for MANE) with cleaning and consistency between admin and non-admin. Resolution of issues from previous testing rounds.

Actual outcome:
**Failed** - Still cleaning issues and warning improvements (detailed in testing doc).

**Comments:**
The errors are looking much better overall. I don’t think we need the first part of this warning banner “HGVS requires transcript, given symbol GNE”. Given this functionality is to allow searching without transcript, it makes it sounds like the feature doesn't work.
<img width="843" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2M1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--294f4e9fabd1df7ac36a15af2bcf462ca4ad050d/image.png" alt="image.png" />

Could also consider changing the second half to “Warning: **Searching without transcript is only supported for coordinates resolved against MANE transcripts.** [GNE] has non-MANE transcripts that may resolve to different coordinates. You may wish to **add a transcript or** search for the gene symbol to view all results”

**Comment by davmlaw** [comment]
Rework see test document

**Comment by davmlaw** [comment]
CLDN5:c.-647G>T - "out of bounds" MANE message - fixed

NM_003545.4(HIST1H4E):c.34G>A - gene symbol alias - raised as [new issue](https://github.com/SACGF/variantgrid_private/issues/3634) as this is a new feature not in original scope

Cleaning badly formed gene based HGVS eg GNEc.1225G>T, GNE :C.1225G>T, GNE:C.1225C>T, (GNE):c.1225G>T - raised as [new issue](https://github.com/SACGF/variantgrid_private/issues/3635) - separate code area, not part of original scope of issue

**Comment by GracePendlebury** [comment]
With the other things split out into separate issues, I think for this task we still need to resolve the warning message text. 

I would suggest the following:
“Warning: Searching without transcript is only supported for coordinates resolved against MANE transcripts. [GNE] has non-MANE transcripts that may resolve to different coordinates. You may wish to add a transcript or search for the gene symbol to view all results”

**Comment by davmlaw** [comment]
Rework to change message

**Comment by davmlaw** [comment]
@GracePendlebury at the moment the functionality is:

If we're given a non-compliant HGVS with a gene symbol, give the warning:

> HGVS requires transcript, given symbol GNE

Then, if we find out there are transcripts that are not in MANE, we add:

> Warning: GNE has non-MANE transcripts that may resolve to different coordinates. You may wish to search for the gene symbol to view all results 

So, can you clarify:

Q) Should we give any warning if a gene symbol HGVS is given, and all the transcripts are MANE (ie there are no non-MANE transcripts)?

**Comment by GracePendlebury** [comment]
@davmlaw can I check what you mean by non-compliant HGVS?

**Comment by davmlaw** [comment]
"HGVS requires a transcript" is supposed to warn people it's a [non-compliant HGVS](https://hgvs-nomenclature.org/stable/background/refseq/)

> A sequence variant is defined in the context of a reference sequence which must be referred to by means of a unique sequence identifier ... reference sequences must come from data sources that provide stable and permanent identifier ... *Gene symbols should not be used as specification.*

**Comment by davmlaw** [comment]
@GracePendlebury I should have used "non-conforming" - meaning it doesn't follow the spec

"HGVS requires a transcript" is supposed to warn people it's a [non-conforming to the HGVS standard](https://hgvs-nomenclature.org/stable/background/refseq/)

> A sequence variant is defined in the context of a reference sequence which must be referred to by means of a unique sequence identifier ... reference sequences must come from data sources that provide stable and permanent identifier ... **Gene symbols should not be used as specification.**

**Comment by GracePendlebury** [comment]
Okay thanks. Then I would probably suggest -

**Comment by EmmaTudini** [comment]
Testing (of new warnings):
-	- Logged in as non-admin
-	- Searched for: 
1. GNE:c.1225G>T (Mane Plus Clinical c.HGVS)
-	Expected output: Should search and show results, but with a warning of "Warning: Searching without transcript is only supported for coordinates resolved against MANE transcripts." and "GNE has non-MANE transcripts that may resolve to different coordinates. You may wish to add a transcript or search for the gene symbol to view all results”
-	Actual output: Passed
-	
2. CLDN5:c.-647G>T (out of bounds)
-	Expected output: Should show warning about MANE resolution and out of bounds error
-	Actual output: Passed
-	
3. UAE1:c.1225G>T (aliased gene symbol)
-	Expected output: Should search and show results, but with a warning of "Warning: Searching without transcript is only supported for coordinates resolved against MANE transcripts.", matched against an alias,  and "GNE has non-MANE transcripts that may resolve to different coordinates. You may wish to add a transcript or search for the gene symbol to view all results”
-	Actual output: Passed - but @davmlaw, @TheMadBug super picky, but could a full stop be added after the alias sentence - Matched to MANE gene symbol 'GNE' via alias UAE1 (HGNC)**.**
-	
4. GNE:c.802G>T (chgvs in non mane transcript)
-	Expected output: Should search and show warning as per test 1. 

-	Actual output: **Failed** - Another error appears that doesn’t make sense. See below. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGkyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b981ab66cdbf0bfaa3b91fafc4695938718a1155/Screenshot%202024-07-05%20at%201.55.55%20pm.png" alt="Screenshot 2024-07-05 at 1.55.55 pm.png" />

-	Subbing in ENST00000642385.2:c.802G>T – then results in the below (same error as above), which doesn’t make sense
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG0yQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70cb8a1eabed0567ce84eb9ca178a0c25ee02e5c/Screenshot%202024-07-05%20at%202.08.56%20pm.png" alt="Screenshot 2024-07-05 at 2.08.56 pm.png" />

5. TP53:c.337G>A (c.hgvs in non mane transcript)
Expected output: Should search and show warning as per test 1. 
Actual output: Passed

6. SP2-DT:c.1G>T (no Mane transcripts)
Expected output: Should only show “Searching without transcript is only supported for coordinates resolved against MANE transcripts.” And [Gene] has no MANE transcripts. 
Actual output: Passed – could a full stop be added at the end of SP2-DT (or any aliases) have no MANE transcripts**.**

**Comment by davmlaw** [comment]
Moved back for rework

**Comment by davmlaw** [comment]
3. Added full stop

4. GNE:c.802G>T and "ENST00000642385.2:c.802G>T" - this was wrongly matching Ensembl as a gene symbol and sent down that path, and we badly pulled out the symbol. Should be fixed now

**Comment by GracePendlebury** [comment]
@davmlaw tried testing GNE:c.802G>T and it looks like this functionality is not working now?
<img width="1175" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk84QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--316fd80a1cefd48ff412db7fc239bff5d0a0ff7a/image.png" alt="image.png" />

**Comment by davmlaw** [comment]
Yeah, that broke when I was handling aliases. It's been fixed now

I will do a deploy and move things from coding to complete to ready for testing

**Comment by davmlaw** [comment]
ok good to go

**Comment by GracePendlebury** [comment]
**Re-testing 10/07**

GNE:c.1225G>T
CLDN5:c.-647G>T
UAE1:c.1225G>T
GNE:c.802G>T
TP53:c.337G>A
SP2-DT:c.1G>T

Now passed on all of the above, see comment in #3634 about formatting of the error message now displayed for GNE:c.802G>T.

**Comment by davmlaw** [comment]
For the error message - do you think the user gains from knowing we attempted ClinGenAllele registry and the transcripts we tried or would they be better off with a simpler message ie "Cannot resolve HGVS"?

**Comment by GracePendlebury** [comment]
I much prefer the simpler message of "Cannot resolve HGVS"

**Comment by davmlaw** [comment]
Rework to change error to be more user friendly in search (if admins care about real error, they can use HGVS tool now)

**Comment by davmlaw** [comment]
As we've passed testing and doing a fork / deploy - span search simplification message into own issue #1113

**Comment by davmlaw** [comment]
@GracePendlebury - since it's been split to new issue, ok to move this to pending?
