### ISSUE TITLE
Search - searching for IGV style coordinate always produces "create manual variant" option

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#838]
Search for IGV style coordinate "chr20:58909349 G>A" or "20:58909349 G>A" always returns the create manual variant option, even if it exists

![image.png](https://images.zenhubusercontent.com/5bb45cdce135e46293defe80/9bf6065d-5b6e-402f-bd9c-13c38ef5cb87)

This is probably a quick fix I will look into it more now...

**Comment by davmlaw** [comment]
Was always just yielding create manual variant. Added a has_results = True flag

to test:

Search for IGV variant coordinates that don't exist - should come back with 2 create manual variants
Create for 1 build, re-search, should come back with 1 for build it exists in, 1 for create
Create for other build, re-search, should come back with result for each build, and 0 create manual variants

**Comment by GracePendlebury** [comment]
### **Testing**
Logged in as: Grace.Pendlebury@qimrberghofer.edu.au (admin)
Performed/Searched for:
1.	Variant in both builds:
NM_000038.5(APC):c.3920T>A
37 - 5:112175211 T>A
38 - 5:112839514 T>A
Was imported in both builds

2.	Variant only imported in 38:
16:2109052 G>A

3.	Variant only imported in 37:
NM_001009944.3(PKD1):c.*15G>A in 37, should have coordinates of 16:2139713 C>T

4.	Variant that doesn’t exist in either build:
NM_001009944.3(PKD1):c.12905G>A
16:2139735 C>T

Expected output:
Searching by IGV style variant coordinates should only give an option to create and annotate a variant if it does not already exist in the database for either/both GRCh38 or GRCh37. 

Actual output:
**1.** Variant in both builds
Result – **Failed**? I think this should say matched on both GRCh38 and GRCh37 regardless of which coordinate you search as the same variant has been imported against both builds and does exist in the system. Still gives you option to create and annotate for 37.
Prod/Original search:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXQxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--288c813afd2dd1f7f3c056c091d33281cd6085db/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXgxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a790a7a408d94bac4ff14d12f8c490b9d2b95ac0/image.png)
Test:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTExIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f23727db49ddc98a49f898e03f731de7b481df34/image.png)

**2.** Variant only imported in 38
Result – **Passed**. Only suggests to create new variant for 37.
Prod/Original:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTUxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3528fb9d15f72c46fe05ffe2959a605141f7e783/image.png)
Test:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTkxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4e52e5cb9ef0bf14b00475a2aa775f969ac67b3e/image.png)


**3.** Variant only imported in 37
Result – **Passed**
Prod/Original:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkIxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--206e8b4f8bf208b4ebaa469a1344d5a1022824c9/image.png)
Test:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkYxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d36ff82cee379b3e15a6ff81711b543dc99645b2/image.png)


**4.** Variant that doesn’t exist in either build
Result – **Failed**. Should have come back with two create variants options, one for each build.
Prod/Original: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkoxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1023b5020258673d222dd552863a9738003871bf/image.png)
Test:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbk4xIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3cb273d66b7d5eaf50b73e6bb4a4544678aec393/image.png)

**Comment by davmlaw** [comment]
1. 

> Search for "5:112175211 T>A" - I think this should say matched on both GRCh38 and GRCh37 regardless of which coordinate you search as the same variant has been imported against both builds and does exist in the system. Still gives you option to create and annotate for 37.

Two completely different variants from different builds can have the same IGV representation, eg here are some from ChrX that match IGV coordinates between 38/39 on variant test - note, I didn't create these, they were there when I looked:

```
 'X:153579982 G>A',
 'X:153579999 C>T',
 'X:153592508 G>A',
 'X:153592515 C>T',
 'X:153592745 C>T',
 'X:153592746 G>A',
 'X:18954256 G>A',
 'X:31496962 C>T',
 'X:41334255 G>A',
 'X:49067430 C>T',
 'X:49074913 C>T',
 'X:53432318 C>T'
```

If you don't allow creating the different variant, just because a completely unrelated variant just happens to have the same IGV style variant - you would have in effect have prohibited the creation of these

4. ```16:2139735 C>T``` - the variant already exists in test in GRCh37 - which is why there is no option to create it there. I suggest you use a different variant eg change the alt to ``` 16:2139735 C>G```

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0twIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e687fe891bd124f3d6294b25d3ebfd619381b6c9/image.png)

**Comment by GracePendlebury** [comment]
1. That's fair, passed.
4. Ah I see, so the variant record exists but there are no classifications for it currently in the system. Would this variant just have been annotated previously? Tested this with 16:2139735 C>G instead - passed.

**Comment by TheMadBug** [comment]
Confirmed a few searched in prod
