### ISSUE TITLE
Unable to access own analysis (from template)

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#84]
**Describe the bug**
Relates only to user abrown: Can make new analysis from template. It shows up in the analysis list, but am forbidden from opening analysis: PermissionDenied: You do not have READ permission to view 1931

**To Reproduce**
1. Go to https://variantgrid.com/snpdb/view_sample/7748
2. Create new analysis from template (e.g. Somatic singleton analysis)
3. Returns 'Forbidden' error, however, analysis still created in analysis list

**Expected behavior**
Be able to open own analyses.

**Other**
- SKS: appears that user group settings not applied to new analyses (all boxes unticked). Have manually added access to analyses as temp workaround. 
- current user default group settings: 
![image](https://user-images.githubusercontent.com/8601717/96225469-a9241980-0fd8-11eb-91f1-d074359130b1.png)

**Comment by davmlaw** [comment]
This should be fixed, and has been deployed to vg.com

**Comment by sksmi** [comment]
@davmlaw not sure how to test this. Have flagged for meeting.

**Comment by davmlaw** [comment]
To test, it was a permission error, so need to use a non-admin user to perform original steps.

**Comment by sksmi** [comment]
Tested using: sking_test.
Generated analysis from template: http://144.6.229.160/analysis/1721/
Passed.
