### ISSUE TITLE
Classification action buttons extremely large in Safari

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#85]
On Safari Version 14.0 (15610.1.28.1.9, 15610)
![image.png](https://images.zenhubusercontent.com/5b9734f72df36e0aa911d89d/0d3cdded-9fee-427f-944b-cabe48286cc9)

**Comment by TheMadBug** [comment]
Likewise for view_allele, it would be anywhere where css sets height to 100% and hopes that a parent div is limiting the height (* would be a little bit more specific than that, work out does and doesn't restrict it)

![image.png](https://images.zenhubusercontent.com/5b9734f72df36e0aa911d89d/d9156c3e-f643-4c4b-8645-a49e96f08f09)

**Comment by TheMadBug** [comment]
Unlike in Chrome, tooltips don't dissapear when a dialog opens, e.g.
![image.png](https://images.zenhubusercontent.com/5b9734f72df36e0aa911d89d/75d9aaff-56cd-49b1-b46a-646718cd99a0)

**Comment by EmmaTudini** [comment]
@TheMadBug Think this might be a change after I had done my original testing on bootstrap. Had looked at safari and this wasn't the case then.

**Comment by EmmaTudini** [comment]
Tooltip not disappearing (new screenshot to get rid of lab specific references)
<img width="913" alt="Screen Shot 2020-10-20 at 9 23 30 am" src="https://user-images.githubusercontent.com/43164432/96522116-10321e80-12b6-11eb-888d-ef8c60717acb.png">

**Comment by TheMadBug** [comment]
Buttons and card sizes fixed in Safari (also quickly tested the same pages in Chrome and Firefox).

I have not address the tooltip issue as part of this task, as in certain circumstances it can cause problems across all browsers.

**Comment by EmmaTudini** [comment]
Testing:
- Logged into Shariant test as non-admin assigned to VCGS (emmatudini@gmail.com)
- Using Safari Version 13.1.1 (15609.2.9.1.2) and Safari Version 14.0 (15610.1.28.1.9, 15610)
- Git Hash
60523306b32b5f99e160e5f50e8f8aa22eb8466e
- Went to VCGS Unit 1 record - https://test.shariant.org.au/classification/classification/7745
- Went to allele for record above - https://test.shariant.org.au/variantopedia/view_allele/2445

Expected output:
Submit, share and withdraw would all be "normal" sizes. 
Boxes with genome builds on allele page would have a decreased height.

Actual output: Passed
