### ISSUE TITLE
Detect build by contigs

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#86]
When testing SA Path GRCh38 VCF, we found that it couldn't detect the genome via contigs. This is because GRCh38 has an absurd number of contigs. We should only use the core ones to do the genome build detection

**Comment by davmlaw** [comment]
When you upload a VCF and it requires manual input, it's obvious if you go to the VCF page, but it's completely non-obvious what to do on the upload page (which is the bigger link).

**Comment by sksmi** [comment]
@davmlaw might need a bit of help on this one. Have flagged for meeting.

**Comment by davmlaw** [comment]
JuJu will test this next time he uploads a VCF again to SA Path test, and it'll be easy to see if it works or not - will re-open if it fails
