### ISSUE TITLE
variant to hgvs no longer using ClinGen Allele registry

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#866]
We used to create HGVS for alleles via ```HGVSMatcher.variant_to_hgvs``` but after refactoring we run through ```variant_to_c_hgvs_variant```

This only converts using our internal transcripts - ie doesn't call clingen (I also re-wrote new path it to support LRG when it already supported it in old path)

TODO:

* Separate out variant_to_hgvs to work with variant coordinate
* Make other paths be internal ie _variant_to_c_hgvs_variant and add docs to 
* Modify set_variant_and_save to use variant_to_hgvs

**Comment by EmmaTudini** [comment]
@davmlaw Is this the reason that we have the following variants failing? I thought it was discussed and this was due to issues with clingen not connecting, but I think it seems like it might be this instead?
NM_012309.5(SHANK2):c.790G>A
NM_012309.5(SHANK2):c.722C>T
NM_001372044.2(SHANK3):c.112A>C

**Comment by davmlaw** [comment]
@EmmaTudini I moved your comment to a private issue. 

This was fixed in August 23, so before then, the re-import test using biocommons would have just failed without trying ClinGen (no mention of clingen in errors etc)
After August 23, the pipeline will have attempted to go to ClinGen, and if there was an error, there will be a clingen error listed

**Comment by EmmaTudini** [comment]
@davmlaw I think there may be a discrepancy between what is in the file as having changed and what actually seems to happen when you look via the HGVS resolution tool. All variants listed in the other issue seem to resolve normally according to that tool

**Comment by davmlaw** [comment]
The spreadsheet was run on September 7th, so had this fix applied.

In the spreadsheet, for the variants you listed, it says it tried ClinGen and failed. That shows that it did try clingen and this issue is resolved.

The failure at that time, while it works now, is probably due to a temporary error on their end

**Comment by EmmaTudini** [comment]
@davmlaw James also re-ran the spreadsheet today, so I'd assumed that it would have corrected itself?

**Comment by davmlaw** [comment]
If it did, that would prove it was a temp ClinGen error at the time

Before this fix, it never called ClinGen at all.

But yeah we should collect the actual error codes and put them in the spreadsheet so we could know why it failed (us sending them bad data or them just dying for their own reasons)
