### ISSUE TITLE
Lab gene classification counts

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#87]
For a fun experiment, I'd like to see how the lab classifications overlap.

Doing this as a table of everything would blow out the size of it very quickly. I think use GeneGrid as that handles being able to dynamically add columns and genes.

Quick specs:

* Lab names, icons
* Display counts nicely
* Clean up gene grid etc to only show what we need (hide color coverage)
* Link from gene stats page?

**Comment by davmlaw** [comment]
@EmmaTudini have a go at this, I thought it would be fun to find the overlaps at a gene level - gives us a heads up on where we should expect overlaps at a variant level:

https://test.shariant.org.au/classification/lab_gene_classification_counts

This currently uses the gene symbol used in the submission, not using all the aliases we use (which are extremely complicated)

**Comment by TheMadBug** [comment]
^ should be pointed out there's no way to navigate to this page normally, so it's just for our sake for now.

**Comment by TheMadBug** [comment]
![Screen Shot 2020-10-22 at 2.07.40 pm.png](https://images.zenhubusercontent.com/5b9734f72df36e0aa911d89d/7fa70bbb-6da0-4fb9-a605-65603679b10d)
(Attached screenshot for reference)

**Comment by EmmaTudini** [comment]
Testing:
- Logged into Shariant test as non-admin assigned to VCGS (emmatudini@gmail.com)
- Git Hash
60523306b32b5f99e160e5f50e8f8aa22eb8466e
- Note this is just a general test for functionality
- Went to https://test.shariant.org.au/classification/lab_gene_classification_counts

Some initial thoughts - 
- What's the intent for the data columns vs gene lists tabs? Think it would be best to collapse into one tab. Maybe for panelapp panel, have an option for panelapp all and then add a tick box for clingen?
- Clingen lookup currently not working. Results in slack notifications. 
- Need addition of help. Currently not obvious what is being done. I.e. selecting another panel adds extras to the list on the left
- If you select classification summary in the data columns tab, and then select a lab. The summary is not turned on. Need to go back to  the tab and de-select and re-select classification summary for it to be shown. Also if another lab is added, it then has the original lab with the summary and new lab without the summary. Need to do as above for the new lab to also show a breakdown of classifications.
- Filtering on gene already in the list doesn't work. 
![Screen Shot 2020-11-15 at 7.14.14 pm.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/a3edb460-3575-4a4f-9ae1-72cfdc68f2a4)
- Filtering on gene not in the list, adds it to the list. This doesn't seem right to me as it's a filter?
- Can copy and add or remove genes from gene list. This is likely encroaching into panelapp territory so might be best to turn off for Shariant? 
- Also if it were to stay on and you could add/delete genes, not obvious where that saved list goes (figured out that you needed to click on the icon). When going to https://test.shariant.org.au/genes/view_gene_list/3 - view/edit in gene grid results in internal error. 
- Would suggest adding in panelapp Aus

**Comment by TheMadBug** [comment]
This is a page with the main purpose is to manage gene lists within SA Pathology that Dave has added some quick functionality to be more classification focused with plenty of functionality that has no application to Shariant.

I would suggest we never enable this outside of admin use for a curious glance at what genes are being looked at by which labs.

**Comment by davmlaw** [comment]
>> Think it would be best to collapse into one tab.

This wasn't original functionality - happened after bootstrapping 

>> Filtering on gene not in the list, adds it to the list. This doesn't seem right to me as it's a filter?

Need to change "Gene Symbol" to "Add gene symbol"

>> Would suggest adding in panelapp Aus

This is already covered in another issue

**Comment by davmlaw** [comment]
ClinGen issues that cause exceptions Emma is talking about only occurs on Shariant test (not prod or my dev machine)

Eg contain MONDO:

http://localhost:8000/annotation/api/disease_validity/CDH1
https://shariant.org.au/annotation/api/disease_validity/CDH1

Does not contain MONDO:

https://test.shariant.org.au/annotation/api/disease_validity/CDH1

**Comment by davmlaw** [comment]
I think MONDO had been deleted and reloaded on Shariant depoyments, as ClinGenDiseaseValidity had all the MONDO nulled out.

I reloaded ClinGenDiseaseValidity via the "Update from web" button and they're ok now (need to use a cache buster)

I modified GeneGrid gene symbol button to "Add Gene Symbol" to make it clear it's not a filter - but since this is internal and don't want to spend more time on this, am closing it
