### ISSUE TITLE
Create manual variant entry from text broken with indels

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#892]
Enter indel into search eg: NC_000001.10:g.7682001_7685000del

Our default representation for indels is now SPDI - but we don't have a way of loading them in create manual variant entry.

So either read it correctly or just send the HGVS?

**Comment by davmlaw** [comment]
I changed the internal representation of variant to be eg ```chr1:1000-2000 <DEL>``` for indels - this is what is now used to create this when you search/create

To test basically just create a few deletions and duplications, make sure they are created ok

**Comment by TheMadBug** [comment]
Not that we even manually create variants in Shariant, but can confirm the link exists for admins after doing that search.
