### ISSUE TITLE
Requirements - use Biocommons HGVS main branch

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#895]
All of my changes have now been merged into Biocommons HGVS
Change requirements.txt and dev, pick latest commit and use that

Verify that all fixes I did are in there / things work

**Comment by davmlaw** [comment]
Tested on [latest commit](https://github.com/biocommons/hgvs/commit/4efed793dad6b230feb39ff0e28f1ba16b8843ac)  locked into requirements.

* Parser can be imported, and instantiation time is quick
* gene symbol dash - ```NR_135480(SP2-DT):c.1G>T``` and  ```SP2-DT:c.1G>T```
* HGVS to VCF coordinate works

**Comment by davmlaw** [comment]
No testing required - this is a code/deployment only change. Verified deploy on test:

```
ubuntu@sharianttest:~$ python3 -m pip freeze | grep hgvs
hgvs @ git+https://github.com/biocommons/hgvs@4efed793dad6b230feb39ff0e28f1ba16b8843ac
```

Will keep this around so we know to do the same on prod during deploy

**Comment by TheMadBug** [comment]
I can confirm even that prod isn't using biocommons for variant resolution currently, it's currently using the same version as test "v1.5.5.dev60+g4efed79"
