### ISSUE TITLE
Search - support variant range regex

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#896]
I introduced a new  format for the symbolic variants, a range format like: ```chr1:1000-2000 <DEL>``` - hook this up to work in search

**Comment by GracePendlebury** [comment]
@davmlaw do you have any advice for testing this? I tried Chr17:43074319-43080000 del as a test but it looks exactly the same in test and prod atm, so not sure if I should import a variant first or if the current system would even let me do that?

**Comment by TheMadBug** [comment]
I tried it and I got a the following, maybe somewhat confusing, error message
https://test.shariant.org.au/variantopedia/search?search=Chr17%3A43074319-43080000+%3CDEL%3E&mode=None

![CleanShot 2023-10-13 at 15 24 17@2x](https://github.com/SACGF/variantgrid/assets/2100255/87424600-3a54-40a0-b723-2805d8f9820e)

I'm not too worried about that error message as nobody is going to search for that, but obviously that's not the desired output.

**Comment by GracePendlebury** [comment]
Hmm okay, well Chr17 is definitely in GRCh37!
I guess the <> is necessary around the event to trigger the search.

**Comment by TheMadBug** [comment]
I'm guessing it's confusing Chr17 for a transcript not a chromosome.

**Comment by davmlaw** [comment]
```chr17:43077419-43080000 <DEL>``` works, it just fails with the upper case "C" - that's a legit bug easy fix

**Comment by TheMadBug** [comment]
Can confirm this works in prod now and the CHR is case insensitive
