### ISSUE TITLE
Variant preview / summary

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#898]
If you search for a variant, if (and only if) it contains a classification - it will show the HGVS:

![hgvs_search_variant](https://github.com/SACGF/variantgrid/assets/763201/20c32e1a-3239-4d8c-a22a-7edf97364b92)

I would like to change:

* No point showing genome build again (it is already on the left)
* It should always show the c. HGVS if available (regadless of classiifed or not)
* If no c. HGVS available - show something like "2kb upstream of gene"

**Comment by davmlaw** [comment]
ok, we use the classification c.HGVS if available, then:
fall back on get_canonical_c_hgvs, then if "distance" - a message like upstream/downstream Xbp of GENE, then failing that, "intergenic"

Testing:

NC_000001.11:g.1019833T>C - comes up as "287bp upstream of AGRN"

**Comment by EmmaTudini** [comment]
@davmlaw testing for this? You might need to walk me through it

**Comment by davmlaw** [comment]
To see this, you need to have a variant search result turn up (ie not auto jump) so

* Click "Go" on empty search to go to search screen
* Untick "auto jump"

Search for a variant that has a HGVS, eg: ```NC_000007.13:g.117199563G>T``` or ```7:117199563G>T``` - verify that c.HGVS 

Search for a variant that doesn't have c.HGVS, ie that is intergenic like ```NC_000001.11:g.1019833T>C``` - verify that it says something like X upstream of the nearest gene

**Comment by GracePendlebury** [comment]
**Testing**
Logged in as:
Grace.Pendlebury@qimrberghofer.edu.au (admin)

1. Variant that has a classification and HGVS, NC_000003.11:g.10183836C>T
Passed

2. Variant that has a classification but doesn't have c.HGVS
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0lrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f88491bad62b2462897737bd1c7abc0926e61495/image.png)
Failed – I think I picked a correct upstream variant for testing this but it doesn’t display the “X upstream of the nearest gene”.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL01rQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a0231f175b74c871ca3b98c8e7788b762b0a97a/image.png)
Is there a reason that this search term doesn’t locate the variant?

**Comment by TheMadBug** [comment]
Re the second search, I tried searching for "NR_104091.1(LINC00970):n.-4245C>T" and according to Rollbar it produced the error

InvalidHGVSName Invalid HGVS allele "n.-4245C>T": Non-coding transcript cannot contain negative (5'UTR) coordinates

But that error message never made its way to the user.

**Comment by TheMadBug** [comment]
Note, I've fixed the issue where `NR_104091.1(LINC00970):n.-4245C>T` returns a blank error message.
See commit #8a1a55c32ad0dd2157cb2920dc31df5771073a8e

I'll leave fixing/discussing the search result of  NC_000003.11:g.10183836C>T to save.

**Comment by TheMadBug** [comment]
I still always end up showing the genome build next to the c.HGVS in the search result as that's part of preview that can be used outside of search, and sometimes even in search it's ambiguous e.g.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0pBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8eb7c1a888ceeea23b380b40787ae03f21f180c/CleanShot%202023-10-17%20at%2015.18.52.png)

But at least the genome build is less emphasised now in an allele preview.
