### ISSUE TITLE
Tissue Node broken

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#9]
*Originally reported by* **David Lawrence (Bitbucket: [davmlaw](https://bitbucket.org/davmlaw), GitHub: [davmlaw](https://github.com/davmlaw))**

----------------------------------------

* Check whether HPA importer work on zipped file? If not modify and document
* Show expression level in HPA genes grid

----------------------------------------
- Bitbucket: https://bitbucket.org/sacgf/variantgrid/issue/617

**Comment by davmlaw** [comment]
tested in vg test
