### ISSUE TITLE
GeneGrid tooltips need bootstrappin'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#90]
Recreate:

* Add panel app panel
* Hover over green/red/orange square

Expected: a tooltip popup appears with lots of info in it

-------

Bootstrap example is classifications page, hover over classification HGVS

James give example of:

```
<div title="heading" data-toggle="popover" data-content="I am some HTML<ul><li>dot one</li></lidot two</li></ul>">regular content</div>
```

https://getbootstrap.com/docs/4.5/components/popovers/

**Comment by sksmi** [comment]
Tested gene symbol page, 
Tested gene grid page.

Popup works well on both .
