### ISSUE TITLE
Improve wiki/documentation

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#909]
Notes from Y reading "read the docs" for the first time:

Please review the [changes](https://github.com/SACGF/variantgrid_docs/compare/6d03ad1a311c07737a2751dad5a5726255110142..b08979c)

### Somatic Data:

https://variantgrid.readthedocs.io/en/latest/data/somatic_allele_frequency.html

> Make it clear how "all" and "any" behave for all the tools, eg whether it is all samples in cohort or all filters applied

https://github.com/SACGF/variantgrid_docs/compare/6d03ad1a311c07737a2751dad5a5726255110142..8381d2de2d7909dfd7597b867d0155f3c6d59e20#diff-227c2f5c832c065dc8925f924fb14ee2ecfdd2270012f81e4ec02167cd0f9d2bR11

### Ancestry:

> More info about graphs

https://github.com/SACGF/variantgrid_docs/compare/6d03ad1a311c07737a2751dad5a5726255110142..8381d2de2d7909dfd7597b867d0155f3c6d59e20#diff-b30540dccb7a248ee91f9d60a666e3e66ac57c3e38a841ea9fa416daeaad2439R3

### Cohort

> Need to explain how AND/OR etc work for cohort eg across samples  
> Allele Frequency - need to mention slider is a percentage (or just add "%" to label)
> Need to explain how AND/OR works

https://github.com/SACGF/variantgrid_docs/compare/6d03ad1a311c07737a2751dad5a5726255110142..8381d2de2d7909dfd7597b867d0155f3c6d59e20#diff-227c2f5c832c065dc8925f924fb14ee2ecfdd2270012f81e4ec02167cd0f9d2bR11

* **Counts**:

Go into detail how "any zygosity" works - eg say that it can't be unknown

Are ref/het/hom etc applied in an AND or OR?

Mention why a sample would have no zygosity call (eg not covered during sequencing)

Added images and expanded text

https://github.com/SACGF/variantgrid_docs/compare/6d03ad1a311c07737a2751dad5a5726255110142..8381d2de2d7909dfd7597b867d0155f3c6d59e20#diff-b5a0a8e836a78d034bd80d267a776dab8bc549939af2870f18503b1866d09160R30

### Trio:

> For the zygosity filtering, lets say we select "recessive". Does it display variants where the proband is recessive AND the parents are heterozygous for the variant? (I am asking this in case we have instances where the proband is recessive but for example we are missing info from the parents).

Moved bit about "require zygosity" right above table - https://github.com/SACGF/variantgrid_docs/compare/6d03ad1a311c07737a2751dad5a5726255110142..8381d2de2d7909dfd7597b867d0155f3c6d59e20#diff-b5a0a8e836a78d034bd80d267a776dab8bc549939af2870f18503b1866d09160R87

### Population

* I do not understand this section much to be honest.

https://github.com/SACGF/variantgrid_docs/compare/6d03ad1a311c07737a2751dad5a5726255110142..8381d2de2d7909dfd7597b867d0155f3c6d59e20#diff-b5a0a8e836a78d034bd80d267a776dab8bc549939af2870f18503b1866d09160R310

### Zygosity

> "Multiple hit filters to >=2 hits in a gene, regardless of zygosity." Please explain this more.

https://github.com/SACGF/variantgrid_docs/compare/6d03ad1a311c07737a2751dad5a5726255110142..8381d2de2d7909dfd7597b867d0155f3c6d59e20#diff-b5a0a8e836a78d034bd80d267a776dab8bc549939af2870f18503b1866d09160R346

## Karyomapping:

https://variantgrid.readthedocs.io/en/latest/analysis/karyomapping.html

> I am guessing "out of phase" with affected child means the 2 alleles of the parent are different from the child. Please confirm
> "Proband phase shows the child's marker percentage from each parent". I am confused by what this means. Please clarify.

https://github.com/SACGF/variantgrid_docs/compare/6d03ad1a311c07737a2751dad5a5726255110142..8381d2de2d7909dfd7597b867d0155f3c6d59e20#diff-61427d7b07572295b702021268402afffbca02cbbb03841c81efde705f23ccc6R7

# Annotation

## Annotation Details

https://variantgrid.readthedocs.io/en/latest/annotation/annotation_details.html

> "To see the VEP fields used, check the “Show Ensembl Variant Effect Predictor source fields” checkbox on the annotation descriptions ([annotation] -> [descriptions]) page".  I did not see an option for this

This is now shown by default, so:

* remove from read the docs
* add column headers mentioning VEP fields etc - http://test.variantgrid.com/annotation/view_annotation_descriptions

# Genes

## Gene Coverage

> "Boxplots of sample coverage for genes are on the gene symbol page". I did not see this box plot

Edit read the docs - say it's only on systems that have uploaded coverage files

> Also "canonical" is mispelled in the canonical transcript page 

*genes* -> *canonical transcripts*

Misspelled: "Canoical"

# Pathology tests:

> How do I navigate to the above?

Mention in read the docs that this is only enabled on some systems

# Patients

### Create from a larger cohort

> * Also, where can we view the plots below?
> Read the docs say "There are some other analyses you can perform from the cohort/VCF page, eg:" but it is unclear how to do this - need links/directions

Explicitly listed links for each graph

>  * (Also, is the number in the matrix supposed to be how many of that type of variation inside that gene for each sample)?

https://github.com/SACGF/variantgrid_docs/commit/b08979c78e0f2bbacc0e7143d63eef9b2418c5a3

## Pedigree

https://variantgrid.readthedocs.io/en/latest/patients/pedigree.html

>  needs more info

expanded pedigree page, pedigree node

# Sequencing Run

https://variantgrid.readthedocs.io/en/latest/sequencing/sequencing_runs.html

> Unless I need special admin privedges, where can I see the sequencing info/setup page?

Mentioned it doesn't appear on all systems

> How does the enrichment kit tie into this anyway (I do not understand the purpose of why it is included in this website).

Added quick summary of enrichment kit and linked to admin read the docs

# Settings

### IGV Configuration:

> I amanged to find the IGV port number in [username] -> [user settings] and not [username] -> [igv integration]

Update read the docs

**Comment by davmlaw** [comment]
@YasirKusay - can you please send me the URL of the page where it says go to ```[username] -> [igv integration]``` for the IGV port number?

**Comment by YasirKusay** [comment]
Hi @davmlaw, do you mean in variant grid? If so it is a link like this https://variantgrid.com/snpdb/settings/user

**Comment by davmlaw** [comment]
In this list of documentation changes you said:

> I think the documentation is quite outdated. I amanged to find the IGV port number in [username] -> [user settings] and not [username] -> [igv integration]

Where does it say to go to that page?

Because on [read the docs](https://variantgrid.readthedocs.io/en/latest/settings/igv_integration.html#variantgrid-configuration) it says:

> If the value of the IGV port is different from 60151 (default), you need to change the IGV Port option in your User Settings page.

Maybe I will make that a link to the user settings documentaiton, which I just looked at an is completely empty

**Comment by YasirKusay** [comment]
I think I may have made a mistake reading the documentation, I may have misread it and thought that it was in the IGV integration page.

**Comment by YasirKusay** [comment]
I am just going through the doc again now, will add uncertainties as I go through it:

https://variantgrid.readthedocs.io/en/latest/analysis/nodes.html - Underneath `Zygosity Counts`: 
For example lets use a cohort with 3 samples. If you put values into more than one item like 0-3 for `ANY`, 1-2 for `REF`, 1-2 for `HET`, I initially assumed that these individual items get treated like an "OR" statement (i.e. get me variants where 0-3 samples have `ANY` zygosity `OR` ......). 
The description **These counts are applied simultaneously, so be careful the ref/het/hom alt minimums don’t add up to more than the number of samples in the cohort** proves otherwise but I am still not sure what it means. Using our example above, our filter must get variants where 1-2 samples are `HET` for that variant AND 1-2 samples are `REF` for that variant (i.e. identical to reference). This is partially impossible as we cannot have a situation where 2 different samples are REF and 2 different samples are HET. Please provide more clarity,

**(I tried to play around with this with many different combinations but I kept on breaking it and I am not sure why, I initially assumed that only one of each can be applied).**

**Comment by YasirKusay** [comment]
https://variantgrid.readthedocs.io/en/latest/analysis/nodes.html - Underneath *Population*: Does PopMax mean pick the subpopulation that has the highest frequency for a given variant? Allele Frequency appears to make sense, it means average occurrence of a variant across all different populations.

**Comment by davmlaw** [comment]
OK, [updated page](https://variantgrid.readthedocs.io/en/latest/analysis/nodes.html)

[commit](https://github.com/SACGF/variantgrid_docs/commit/035046a53375effc782e31aaa0df77dddd7c09eb)

**Comment by YasirKusay** [comment]
Thanks, it is now much clearer now
