### ISSUE TITLE
Test framework for Datatables

### ISSUE THREAD

**Issue by YasirKusay** [SACGF/variantgrid#914]
There needs to be a way to test datatables, similar to the `_test_grid_list_urls` method that is part of the `URLTestCase` class inside `library.django_utils_unittest_utils`. 

In addition, once we convert all JQGrid tables to Datatables, we should remove the `_test_grid_list_urls` method.

**Comment by davmlaw** [comment]
I've started on this. You can just hit the URLs pretty easily, which will at least give it some coverage.

I've done this for "seqauto" and "classification" tables, see test_urls.py in relative projects

Started on ```_test_datatables_grid_list_urls``` - which I will finish off soon, get it to test permissions etc

Then when done, I will raise an issue for the remaining datatables to be tested and assign that to Yasir

**Comment by davmlaw** [comment]
Documented here: https://github.com/SACGF/variantgrid/wiki/Unit-testing---DataTable-grids

Will go and raise issues for remaining data grid apps

**Comment by davmlaw** [comment]
Unit tests - not user testable
