### ISSUE TITLE
Unit test datatables

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#923]
I've [documented how to do this here](https://github.com/SACGF/variantgrid/wiki/Unit-testing---DataTable-grids)

Here is an example - that I have already done - see [commit](https://github.com/SACGF/variantgrid/commit/e2bb8cdff5f460b9c4e9600d25b525d2963ee372)

### Genes

urls.py DatabaseTableView entries:

Test view:

* gene_wiki_datatable
* gene_lists_datatable
* canonical_transcript_collections_datatable
* canonical_transcript_datatable

Permission test:

* gene_lists_datatable

Remember if you want to run the unit test, it's much quicker to explicitly list it, so it doesn't run all of them:

```
# Run just genes test_urls
python3 manage.py test --keepdb genes.tests.test_urls
```

----------
Everything above this point has already been done as an example. Please do everything below this point
----------------------

TODO:

### Annotation

Test view:

* variant_annotation_version_datatable
* annotation_run_datatable

Test Permissions:

n/a

------

### EventLog

Test view:

* event_log_datatable

Test Permissions:

n/a

------

### Manual

Test view:

* manual_migrations_datatable

Test Permissions:

n/a

### snpdb

Test view:

* tag_color_collections_datatable
* custom_columns_collections_datatable

Test Permissions:

* tag_color_collections_datatable
* custom_columns_collections_datatable

### Variantopedia

Test view:

* variant_wiki_datatable
* variant_tag_counts_datatable
* variant_tag_detail_datatable

Test Permissions:

n/a

**Comment by YasirKusay** [comment]
Hi, I have just started work for this. I have committed some beginner lines (with some comments) as I do want more clarification on how to use the testing framework.

**Comment by YasirKusay** [comment]
Will commit something else in a bit

**Comment by davmlaw** [comment]
```_test_datatables_grid_list_urls``` is really "rename to something like check grid for object" - I will modify after you have done your changes

names_obj - this is a list of tuples of (name, kwargs, obj)

obj can be either a object (that has a pk that is checked for)

or it can be a tuple of (object, "key in row JSON to retrieve the primary key ID")

The reason for this is we need to pull out the primary key from a javascript object (the row) to check it matches the object (and thus we can tell the grid contains the object) - By default this is "id"

There is a example:

```            ("gene_lists_datatable", {}, ("text", cls.gene_list)),  # id uses view_primary_key - renders it as "text"```
            
            
This is because GeneListColumns has:

```
            RichColumn('id',
                       renderer=self.view_primary_key,
                       client_renderer='TableFormat.linkUrl'),
```                       

                       
This is rendered for an object with primary key of 11 as JSON like: ```{"text": 11, "data": "xxx"}```

This is so the client renderer (javascript) can make a nice link

**Comment by YasirKusay** [comment]
Currently just punching through this list, where can I find the pages for manual and variantopedia inside the variantgrid site?

**Comment by YasirKusay** [comment]
Nevermind found it

**Comment by YasirKusay** [comment]
I have finished adding tests to all the things but I still have an issue with the above. In addition, I added tests for Variantopedia but they are all failing.

**Comment by davmlaw** [comment]
There is no security on that grid, so it is not necessary to test it for security by seeing if a user can or can't see something.

If you look at how I broke it down above, I said:

Manual - Test Permissions: n/a - which means you don't need to test it. So just leave that one.



But assuming you ran into this problem somewhere else, remember that you can look at the JSON in the browser using inspect, eg here is the manual migrations data table:

```
{
	"0": {
		"task": "python3 manage.py one_off_calc_variant_end",
		"source_version": "9e02f3673eccbdbf83645d7503194ac237349670",
		"note": null,
		"created": 1694584315.545454
	}
}
```

You can see there is no "id" field

I looked at the page - http://test.variantgrid.com/manual/manual/migrations and it looks like the ID field is not present at all on the grid.

So, we are unable to test that the primary key is on that grid at present. The way to be able to test it would be to add it but make it invisible, so it won't appear but you could inspect the JSON
