### ISSUE TITLE
Variant details - styling for no ClinVar/Classifications

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#93]
Need variant details turned on (ie not Shariant)

* Go to a variant that has no clinvar or classifications
* The ClinVar/Classification sections are not aligned or styled like the rest of the page

**Comment by TheMadBug** [comment]
Do you have an example of a URL from variantgrid.com for variant with ClinVar section handy?

**Comment by davmlaw** [comment]
Classifications + ClinVar: https://variantgrid.com/variantopedia/view_variant/139660
Neither: https://variantgrid.com/variantopedia/view_variant/28260398

To find them - search for a random gene, eg "GATA2" then on the variant grid, ones with red squares have ClinVar, purple squares have internal classifications and blank ones have neither.

**Comment by davmlaw** [comment]
If you haven't done this yet, what do you think about having "Classifications" as the header and then internal grid and clinvar as 2 separate cards inside?  would save a bit of vertical space (and remove redundancy of ClinVar/ClinVar Variation ID )

**Comment by TheMadBug** [comment]
So the bigger problem is there's two sizings:

* One for most everything, where it's typically form data.
* One for tables that get too wide to fit in the spacing that's good enough for almost everything else.

If we solve that issue, everything will line up and things like this will be less of a problem.
I'm guessing the solution will be a merging of columns on some tables (especially the classification table as it pops up in a few different places), as well as overriding "max-width" on .container to be a bit larger.

I've generally avoided putting tables in cards when possible, as I treat the cards as something that wraps label/value data, whereas tables are tabular data.

For the more immediate problem I would suggest:
Removing the heading of "ClinVar" and renaming the card header from "ClinVar Variation ID" to "ClinVar"
If there are no Clinvar records, still have the card, but have its contents just be "No ClinVar Record"
and leave it at that.
(Then we can look at shrinking Classifications as a separate task)

**Comment by davmlaw** [comment]
This was unreasonably annoying to me so I made some quick changes:

* Removed redundant headers for "classification", "clinvar" and "nearby" - they have them on the card - can see more now in same vertical space 
* Made tables look nicer when no Classifications or ClinVar
* ClinVar now shows what version nothing was found in, and a link to search ClinVar website with g.HGVS (just thought that would be easy to do)
* Added g.HGVS to page (at the top)

**Comment by sksmi** [comment]
**PASS**

This is fantastic - also been driving me insane!

Viewed +/- ClinVar +/- Classification combos. All worked & look good. 
ClinVar g.HGVS link works (tested ~2x variants)
g.HGVS matches expectations (tested ~4x variants)
