### ISSUE TITLE
UploadPipeline 7932 failed. Filename: Clinvar Error: UploadedFile has no uploadedclinvarversion.

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#930]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4630](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4630)

```
UploadPipeline 7933 failed. Filename: Clinvar Error: UploadedFile has no uploadedclinvarversion.
```

**Comment by TheMadBug** [comment]
Importing the same GRCh38 ClinVar annotations VCF twice caused this error and resulted in the ClinVar annotations not being recognised within VariantGrid.
Subsequent imports just resulted in the same error.

To solve I had to manually delete the latest UploadedClinVarVersion and then the next run worked fine.

**Comment by davmlaw** [comment]
I made it so you can upload the same clinvar file twice

**Comment by davmlaw** [comment]
I made it so you can upload the same clinvar file twice

**Comment by davmlaw** [comment]
No further issues reported, closing as fixed
