### ISSUE TITLE
Tooltips have a bad habbit of sticking around

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#94]
Bootstrap's popover library has a bad habit of sticking around.
Normally this is when the tooltip is up due to hover, and clicking on the underlining item removes or changes the element in the DOM.

StackOverflow has an article on this
https://stackoverflow.com/questions/33584392/bootstraps-tooltip-doesnt-disappear-after-button-click-mouseleave

Keep in mind we use a combination of normal invoking of tooltips as well as registering a dom mutation listener, so the solution to close tooltips on click would need to be applied in both instances.
(I did try something like this originally, I think it didn't work in a few cases due to the order of events, e.g. if a click listener was already removing the item from the dom and this hide tooltip happens after that it might be too late, but worth another try. Maybe the issue was something else or regardless it might still make things better in 90% of cases)

**Comment by TheMadBug** [comment]
Think this effectively got tested under other tooltip related tasks.

**Comment by EmmaTudini** [comment]
Close this issue and raise again if becomes bad
