### ISSUE TITLE
Search - help - ClinVar Export icon broken

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#967]
Click "go" on the search bar

In the help, ClinVar Export is "fa-file-medical mr-2" which shows to me as "broken unicode code" on Firefox and blank on Chromium

<img width="631" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem1VQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3a08a12642ad57361fec4cda8b111398befa036/Screenshot%20from%202024-01-03%2017-20-51.png" alt="Screenshot from 2024-01-03 17-20-51.png" />

**Comment by TheMadBug** [comment]
It's missing a `fa-solid` will fix.

**Comment by TheMadBug** [comment]
I switched it to an upload icon (to make it easier to distinguish from the concept of a clinvar record that we've downloaded)

**Comment by TheMadBug** [comment]
Can see the fix here <img width="764" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTNaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68485334d5e1742ba2434834e3c86c6c4d2d438f/CleanShot%202024-05-14%20at%2016.27.02.png" alt="CleanShot 2024-05-14 at 16.27.02.png" />

**Comment by GracePendlebury** [comment]
Verified in the course of testing SCV search - Passed
