### ISSUE TITLE
Analysis broken due to UI Layout Initialization error

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#977]
The commit just before Somatic change is ok, now broken.

Load an analysis, eg http://test.variantgrid.com/analysis/44/

This now dies with:

```
 / UI Layout Initialization Error
The center-pane element does not exist.
The center-pane is a required element.
```

**Comment by davmlaw** [comment]
The failing line is:

```
    $('div.main-content').layout();
```

It looks like this was due to putting ```div#main-content-body``` between ```.main-content``` and the django template content in base.html, will try and fix

**Comment by davmlaw** [comment]
I will spend a few mins trying to get different libraries than JQuery layout to handle draggable panels

**Comment by TheMadBug** [comment]
I remember I tried years ago, and almost got there (and ultimately failed) but would be great to get rid of the need of JQuery layout as bootstrap can do everything we need except for the split panes.

**Comment by davmlaw** [comment]
I remember having a go myself then quitting and feeling bad.  https://split.js.org looks promising

**Comment by davmlaw** [comment]
I have resolved this with a quick hack fix, and deployed + verified in vg test

I think it will take a non-trivial amount of work replace JQuery layout so have moved into own task  - #978
