### ISSUE TITLE
Replace JQuery layout

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#978]
James agrees it would be very good to see this gone

I have tried https://split.js.org but I think it will take a day to deal with all the intricacies, so have split this into own issue

**Comment by davmlaw** [comment]
testing vg test:

Failed - need to set overflow properly, at the moment the whole screen scrolls down past the split pane

**Comment by davmlaw** [comment]
@TheMadBug - I've removed jquery layout (very minor issue found in testing)

I vaguely remember analysis.html was stopping us from removing some legacy code? Do you remember what?

I thought it might be global CSS and analysis.html imported global_legacy.css which we can now remove but it looks like now that uicore base includes both global_legacy.css and global_bs.css ?

**Comment by TheMadBug** [comment]
@davmlaw I took the css output of layout.scss, global_bs.scss and global_legacy.scss, put it into a css -> scss optimiser, divided that up into sections in global.scss - pulled out the stuff that was my styling attempts from pre-bootstrap and put that in global_deprecated.scss

I ran the web tests before and after the change (and except for a small time where the font was broken) there were no changes on the Shariant page.
(Analysis, patients etc are not covered by these tests).

I moved global_bs.scss, global_legacy.scss and layout.scss to unused. If you find things still look okay please remove these files.

Going forward we still want to rework html that relies on styles in global_deprecated.scss - as stated earlier this file is full of my pre-bootstrap solutions.

**Comment by davmlaw** [comment]
Tested vg test - been using this for a while, no noted issues
