### ISSUE TITLE
UploadPipeline 67 failed. Filename: VCF - Insert variants only (no samples etc) Error: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#984]
To recreate, create an "indel identity" NC_000006.12:g.49949407_49949408=

View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4831](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4831)

```
UploadPipeline 67 failed. Filename: VCF - Insert variants only (no samples etc) Error: '<' not supported between instances of 'NoneType' and 'str'
```

**Comment by davmlaw** [comment]
This is due to identity indels (ie len(ref) > 1 and ref == alt) having entire common prefix stripped away and then you do a comparison vs None

Raised issue + pull request on Biocommons HGVS - https://github.com/biocommons/hgvs/issues/722

In the meantime, need to update from my repo:

```
python3 -m pip install --upgrade git+https://github.com/davmlaw/hgvs@variantgrid#egg=hgvs
```

**Comment by davmlaw** [comment]
@TheMadBug - we constantly have to upgrade eg HGVS and cdot libraries to get around bugs...

What do you think about running something like a unit test on startup that quickly tries to identify the version (or recreate bugfixes if it's a patch to my forked repo) then dies with an error message?

**Comment by TheMadBug** [comment]
Dying with an error message is a little too extreme (I don't want prod refusing to boot up after a hot fix for example) - but something that reports an exception would be great.

**Comment by davmlaw** [comment]
I made some checks (takes 0.04 secs on my machine) - to ensure library is updated

This runs in apps, decided to move all checks in there (including python version check out of managment command)

This is automated so no user testing required
