### ISSUE TITLE
Variant.end and svlen

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#990]
There are a few problems with the current implementation of Variant.end

It is being used as both start/end for overlaps, and to store "svlen" 

This is fine for a deletion, as the (absolute length) corresponds to the end of the genomic position, however for an insertion - the end should be start+1 as the new sequence was inserted, it's wrong to calculate overlaps for the length of the new sequence

So we need to have separate end and svlen, and we need to:

* Introduce a nullable svlen for symbolic variants
* re-calculate end

**Comment by davmlaw** [comment]
Doing this at the same time as #894 - in feature/issue_894_symbolic_inv

**Comment by davmlaw** [comment]
As I explained to James:

I had to modify how Variant works for symbolic variants...
I originally thought hey, lets use start/end and then pack the length of the change into "end" - this means we can save an int and use it for overlap queries as well as storing symbolic variants

But an insertion inserts sequence without changing anything, so it actually has an overlap of length 0  with the reference
So I was storing the size of it ok, but it was screwing up the overlaps so I had to introduce svlen (which is what they use in VCF) - and have it separate from end
so now Variant/VariantCoordinate  use (chrom, position, ref, alt, svlen) instead of (chrom, start, end, ref, alt)
I changed it back to position, I changed it from postition to start as I had end, now I don't so figure have it match VCF is better

**Comment by davmlaw** [comment]
I still need to work out what to do with variant end - we don't really use it at the moment so no urgency

I think I need to modify the existing one_off calculate variant end, maybe to do nothing except symbolic

Then have a second one run to do it properly

**Comment by EmmaTudini** [comment]
@davmlaw What can I test here? SVLEN isn't in the VCF export currently

**Comment by davmlaw** [comment]
Hi - yes, I raised an issue about that - #1065 

"end" is only used for overlap calculations in VariantGrid, so I don't think you need to test anything for Shariant against this issue

will move this to "vg test"
